irontec/ivozprovider

web/admin/application/configs/klear/model/CallCsvSchedulers.yaml
web/admin/application/library/IvozProvider/Klear/Filter/CallCsvSchedulerEndpointType.php

Fixed endpoint listbox filtering to avoid displaying Fax when client has no Fax feature enabled or Friend when no Friend feature is enabled.

Fix Call CSV Scheduler endpoint field filtering

---

web/portal/brand/package.json
web/portal/brand/src/entities/Company/genericCompanyForeignKeyResolver.ts
web/portal/brand/src/entities/Ddi/ForeignKeyResolver.tsx
web/portal/brand/yarn.lock

portal/brand: Fix links to nowhere

---

library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php
library/Ivoz/Provider/Application/Service/Carrier/CarrierDtoAssembler.php
library/Ivoz/Provider/Application/Service/CarrierServer/CarrierServerDtoAssembler.php
library/Ivoz/Provider/Application/Service/CarrierServer/GetStatusFromLcrGatewayInfo.php
library/Ivoz/Provider/Domain/Model/Carrier/CarrierDto.php
library/Ivoz/Provider/Domain/Model/Carrier/CarrierStatus.php
library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerDto.php
library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CarrierServerDoctrineRepository.php
schema/tests/Provider/CarrierServer/CarrierServerRepositoryTest.php
web/rest/brand/features/provider/carrier/getCarrier.feature
web/rest/brand/features/provider/carrierServer/getCarrierServer.feature
web/rest/brand/features/provider/carrierServer/getCarrierServerStatus.feature

Added status Icon attributes to Carrier and CarrierServer entities.

Expose status in get carrier servers and get carriers

---

library/Ivoz/Provider/Domain/Model/DestinationRate/DestinationRateDto.php
web/portal/brand/src/entities/DestinationRate/DestinationRate.tsx
web/rest/brand/features/provider/destinationRate/getDestinationRate.feature

Added new property currencySymbol in Detailed response when DestinationRate object is requested.

Added currencySymbol in detailed response

---

web/rest/brand/config/packages/security.yaml
web/rest/brand/features/auth.feature
web/rest/brand/features/provider/notificationTemplate/postNotificationTemplate.feature
web/rest/client/config/packages/security.yaml
web/rest/client/features/auth.feature
web/rest/platform/config/packages/security.yaml
web/rest/platform/features/auth.feature
web/rest/user/config/packages/security.yaml
web/rest/user/features/auth.feature

This issue avoid users to send requests without authorization headers to custom endpoints.

Review custom endpoint security.

---

web/portal/brand/src/App.tsx
web/portal/brand/src/index.tsx
web/portal/brand/src/router/AppRouteContentWrapper/AppRouteContentWrapper.tsx
web/portal/brand/src/translations/languages.ts

feat: Added language selector

---

asterisk/agi/src/Agi/Action/ServiceAction.php
asterisk/agi/src/Agi/Action/VoiceMailAction.php
asterisk/agi/src/Agi/Wrapper.php
asterisk/config/dialplan/default.conf

In order to improve performance, Voicemail app invocations are better placed outside AGI php code.

Move Voicemail app calls to dialplan contexts

---

web/portal/brand/src/entities/Company/Form.tsx
web/portal/brand/src/entities/Feature/SelectOptions/SelectOptions.ts
web/portal/package.json
web/portal/yarn.lock

Toggle fields based on selected features

Company feture multiselect visual toggles

---

web/portal/brand/src/entities/BillableCall/BillableCall.tsx

Reviewed Brand section from Klear and adapted new portals to ensure that it serves at least the same data.

Review brand api default collections order

---

library/DataFixtures/ORM/ProviderInvoiceTemplate.php
library/composer.json
library/composer.lock
web/rest/brand/config/routes.yaml
web/rest/brand/config/services.yaml
web/rest/brand/features/provider/invoiceTemplate/getInvoiceTemplatePreview.feature
web/rest/brand/src/Controller/Provider/InvoiceTemplatePreviewAction.php
web/rest/brand/src/Service/InvoiceTemplate/InvoiceTemplateGenerator.php

This feature creates a new endpoint for invoice template preview, giving us an HTML response as a template.

New brand portal invoice templates preview

---

web/portal/brand/src/entities/Destination/Destination.tsx
web/portal/brand/src/entities/DestinationRateGroup/DestinationRateGroup.tsx
web/portal/brand/src/entities/RatingPlanGroup/RatingPlanGroup.tsx
web/portal/brand/src/entities/RoutingPattern/ForeignKeyResolver.tsx
web/portal/brand/src/entities/RoutingPattern/RoutingPattern.tsx
web/portal/brand/src/entities/TransformationRuleSet/TransformationRuleSet.tsx
web/portal/package.json
web/portal/yarn.lock

feat: multilang support lists

---

library/Ivoz/Provider/Domain/Model/Queue/QueueAbstract.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Queue.QueueAbstract.orm.xml
schema/DoctrineMigrations/Version20221123120153.php

Fix Queue table Announce field name formats to be camelcase.

Queue Announce Position field naming fix

---

web/portal/brand/src/App.tsx
web/portal/brand/src/router/AppRouteContentWrapper/AppRouteContentWrapper.tsx
web/portal/brand/src/router/AppRoutes.tsx
web/portal/brand/src/translations/languages.ts
web/portal/package.json
web/portal/yarn.lock

web/portal: set languages from store

---

web/portal/client/src/entities/CallForwardSetting/Form.tsx
web/portal/client/src/entities/Ddi/Form.tsx

Fixed CFS and DDI edition crash

portal/client: fixed router regression

---

.gitignore
kamailio/trunks/config/apiban.cfg.in
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/apiban.cfg.in
kamailio/users/config/kamailio.cfg

Add APIBAN support in both Kamailio proxies. Needs copying a .in file with apiban api key to work.
No functional change until it is enabled.

kam: add APIBAN optional support

---

library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointAbstract.php
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointDtoAbstract.php
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointInterface.php
library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/PsEndpoint.PsEndpointAbstract.orm.xml
schema/DoctrineMigrations/Version20230125165233.php
schema/tests/Provider/ResidentialDevice/ResidentialDeviceLifeCycleTest.php

Add RTP timeout fields to asterisk endpoints table

---

web/admin/application/library/IvozProvider/Klear/Filter/CallCsvSchedulerEndpointType.php

It was throwing an error when no company is emulated

call CSV scheduler filter issues

---

library/Ivoz/Provider/Application/Service/Company/CompanyDtoAssembler.php
library/Ivoz/Provider/Domain/Model/Company/CompanyDto.php
web/rest/brand/features/provider/company/getCompanies.feature
web/rest/client/features/provider/company/getCompany.feature

Upport from PROVIDER-485-show-domain-in-client-collection-api-responses

Upport show domain in client collection api responses

---

library/Ivoz/Provider/Domain/Service/Contact/UpdateByExtension.php
library/Ivoz/Provider/Domain/Service/Extension/ExtensionLifecycleServiceCollection.php

Contacts generated from user store their extension in otherPhone field. This field was not being updated if the extension number is changed from Extension edit screen.

Add service to update contact phone by extension

---

library/Ivoz/Provider/Domain/Model/Contact/ContactDto.php
web/rest/client/features/provider/contact/getContact.feature

This makes the api spec for Contacts the same in artemis and halliday

Expose user field in rest API collection responses

---

library/DataFixtures/ORM/CgrTpDestination.php
library/DataFixtures/ORM/CgrTpRatingPlan.php
library/DataFixtures/ORM/ProviderDestination.php
library/DataFixtures/ORM/ProviderRatingPlanGroups.php
library/DataFixtures/Stub/Cgr/TpDestinationStub.php
library/DataFixtures/Stub/Cgr/TpRatingPlanStub.php
library/Ivoz/Cgr/Domain/Model/TpRatingProfile/SimulatedCall.php
library/Ivoz/Cgr/Infrastructure/Cgrates/Service/BillingService.php
library/Ivoz/Provider/Application/Service/RatingPlanGroup/SimulateCallByRatingPlanGroup.php
library/Ivoz/Provider/Domain/Model/RatingPlanGroup/TarificationInfo.php
library/bin/composer-require
schema/tests/Provider/Destination/DestinationLifeCycleTest.php
schema/tests/Provider/RatingPlan/RatingPlanLifeCycleTest.php
web/rest/brand/config/api/raw/provider.yml
web/rest/brand/config/routes.yaml
web/rest/brand/config/services.yaml
web/rest/brand/features/provider/destination/getDestination.feature
web/rest/brand/features/provider/destination/postDestination.feature
web/rest/brand/features/provider/destinationRateGroup/postDestinationRateGroup.feature
web/rest/brand/features/provider/ratingPlanGroup/getRatingPlanGroup.feature
web/rest/brand/features/provider/ratingPlanGroup/postRatingPlanGroup.feature
web/rest/brand/features/provider/ratingPlanGroup/postRatingPlanGroupSimulateCall.feature
web/rest/brand/src/Controller/Provider/SimulateCallAction.php

Simulate Call functionality over Rating Plan Groups.

Simulate call rating plan group

---

web/portal/brand/src/entities/Destination/Form.tsx
web/portal/brand/src/entities/Destination/SelectOptions.ts

It was throwing an error on brand portal

Fixed destination form error

---

web/portal/platform/src/entities/WebPortal/Form.tsx
web/portal/platform/src/entities/WebPortal/SelectOptions.ts
web/portal/platform/src/entities/WebPortal/WebPortal.tsx
web/portal/platform/src/entities/WebPortal/WebPortalProperties.ts
web/portal/platform/src/router/EntityMap.ts

Added WebPortal entity into platform portal.

Add Web Portals to platform portal

---

library/Ivoz/Provider/Domain/Model/Company/CompanyRepository.php
library/Ivoz/Provider/Domain/Service/Company/CompanyLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/Company/SanitizeBillingMethod.php
library/Ivoz/Provider/Domain/Service/FeaturesRelBrand/AvoidBillingRemoval.php
library/Ivoz/Provider/Domain/Service/FeaturesRelBrand/FeaturesRelBrandLifecycleServiceCollection.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CompanyDoctrineRepository.php
library/psalm-baseline.xml

- Validate Company billing method field when Brand has no Billing enable
- Ensure all Companies has billing method none if Brand Feature is being disabled

Company Billing method validation services

---

.gitignore
library/Ivoz/Cgr/Infrastructure/Cgrates/Service/BillingService.php
library/Ivoz/Provider/Application/Service/RatingProfile/SimulateCallByRatingProfile.php
library/Ivoz/Provider/Domain/Service/RatingProfile/BillingServiceInterface.php
library/phpstan-baseline.neon
web/admin/application/controllers/KlearCustomTarificatorController.php
web/rest/brand/config/api/raw/provider.yml
web/rest/brand/config/routes.yaml
web/rest/brand/features/provider/ratingProfile/postRatingProfileSimulateCall.feature
web/rest/brand/src/Controller/Provider/SimulateCall/SimulateCallRatingPlanGroupAction.php
web/rest/brand/src/Controller/Provider/SimulateCall/SimulateCallRatingProfileAction.php

This feature adds a new endpoint for call simulation through rating Profiles.

Simulate call rating profile

---

web/portal/client/src/App.tsx
web/portal/client/src/translations/languages.ts

Client portal languages

---

debian/ivozprovider-web-portals.install
debian/rules
profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf

Added apache site and build rules for packaging new platform portal.

Add configuration and build for platform portal site

---

library/DataFixtures/ORM/ProviderVoicemail.php
library/Ivoz/Provider/Domain/Model/Voicemail/VoicemailDto.php
web/portal/client/src/entities/Voicemail/Form.tsx
web/portal/client/src/router/EntityMap.ts
web/portal/client/src/router/useAclFilteredEntityMap.tsx
web/rest/client/config/api/raw/provider.yml
web/rest/client/features/provider/voicemail/getVoicemail.feature
web/rest/client/features/provider/voicemail/postVoicemail.feature
web/rest/client/features/provider/voicemail/putVoicemail.feature
web/rest/client/features/provider/voicemail/removeVoicemail.feature
web/rest/client/features/provider/voicemailMessage/getVoicemailMessage.feature
web/rest/client/features/provider/voicemailMessage/removeVoicemailMessage.feature
web/rest/user/features/my/company_voicemails/getCompanyVoicemails.feature

Residential admins cannot create voicemails, just edit them.

Voicemail security enhancement

---

web/portal/package.json
web/portal/platform/src/entities/BannedAddress/BannedAddress.tsx
web/portal/platform/src/entities/BannedAddress/BannedAddressProperties.ts
web/portal/platform/src/router/EntityMap.ts
web/portal/yarn.lock

Added Banned Address entity to platform portal

web/portal: Added Banned Address to platform portal

---

web/portal/platform/src/entities/TerminalManufacturer/Form.tsx
web/portal/platform/src/entities/TerminalManufacturer/SelectOptions.ts
web/portal/platform/src/entities/TerminalManufacturer/TerminalManufacturer.tsx
web/portal/platform/src/entities/TerminalManufacturer/TerminalManufacturerProperties.ts
web/portal/platform/src/entities/TerminalModel/Form.tsx
web/portal/platform/src/entities/TerminalModel/SelectOptions.ts
web/portal/platform/src/entities/TerminalModel/TerminalModel.tsx
web/portal/platform/src/entities/TerminalModel/TerminalModelProperties.ts
web/portal/platform/src/router/EntityMap.ts

Added Teminal Manufacturer entity to platform portal

web/portal: Added Teminal Manufacturer to platform portal

---

web/portal/package.json
web/portal/platform/src/entities/Service/Form.tsx
web/portal/platform/src/entities/Service/SelectOptions/SelectOptions.ts
web/portal/platform/src/entities/Service/SelectOptions/UnassignedServiceSelectOptions.ts
web/portal/platform/src/entities/Service/SelectOptions/index.ts
web/portal/platform/src/entities/Service/Service.tsx
web/portal/platform/src/entities/Service/ServiceProperties.ts
web/portal/platform/src/router/EntityMap.ts
web/portal/yarn.lock

Added Service entity to platform portal

web/portal: Added Service entity to platform portal

---

library/DataFixtures/ORM/ProviderDdi.php
library/Ivoz/Provider/Domain/Model/Ddi/Ddi.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiAbstract.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiDtoAbstract.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Ddi.DdiAbstract.orm.xml
library/phpstan-baseline.neon
library/spec/Ivoz/Provider/Domain/Model/Ddi/DdiSpec.php
schema/DoctrineMigrations/Version20230203101227.php
web/rest/client/features/provider/ddi/postDdi.feature
web/rest/client/features/provider/ddi/putDdi.feature

Remove DDI.billInboundCalls

---

library/Ivoz/Cgr/Infrastructure/Cgrates/Service/ProcessExternalCdr.php
library/Ivoz/Provider/Domain/Service/BillableCall/UpdateByTpCdr.php
library/spec/Ivoz/Cgr/Infrastructure/Cgrates/Service/ProcessExternalCdrSpec.php
library/spec/Ivoz/Provider/Domain/Service/BillableCall/UpdateByTpCdrSpec.php

Check company billing method instead of carrier.externallyRated in rate process

Rate based on company billing method

---

web/rest/brand/config/api/raw/provider.yml

MOH files were pointing to a unexisting model

Fixed MOH files spec

---

library/Ivoz/Provider/Domain/Model/InvoiceTemplate/InvoiceTemplate.php
web/rest/brand/features/provider/invoiceTemplate/putInvoiceTemplate.feature
web/rest/brand/features/provider/invoiceTemplate/removeInvoiceTemplate.feature

Added scenarios to check Global InvoiceTemplates can not be removed or edited from brand API.

Update InvoiceTemplate rest API tests with extra scenarios

---

web/portal/brand/src/entities/Ddi/DdiProperties.ts
web/portal/brand/src/entities/Ddi/Form.tsx
web/portal/brand/src/router/EntityMap.ts

DDIS must be editable for brand admin

Editable DDIs in brand portal

---

web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/currency/getCurrency.feature
web/rest/platform/features/provider/currency/postCurrency.feature
web/rest/platform/features/provider/currency/putCurrency.feature
web/rest/platform/features/provider/currency/removeCurrency.feature

These changes permit CRUD operations for Currency entity.

Add divisas crud to platform api

---

web/portal/brand/src/App.tsx
web/portal/brand/src/components/Login.tsx
web/portal/brand/src/entities/Company/Action/Impersonate.tsx
web/portal/brand/src/entities/Company/Action/index.ts
web/portal/brand/src/entities/Company/Company.tsx
web/portal/brand/src/router/EntityMap.ts
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json
web/portal/client/src/components/Login.tsx
web/portal/yarn.lock

Allow to jump to a lower level portal with requesting credentials

New portal impersonation system

---

web/portal/platform/src/entities/Domain/Domain.tsx
web/portal/platform/src/entities/Domain/DomainProperties.ts
web/portal/platform/src/router/EntityMap.ts

Added Domain entity to portal platform

web/portal: Added Domain to portal platform

---

web/portal/package.json
web/portal/platform/src/entities/InvoiceTemplate/Form.tsx
web/portal/platform/src/entities/InvoiceTemplate/InvoiceTemplate.tsx
web/portal/platform/src/entities/InvoiceTemplate/InvoiceTemplateProperties.ts
web/portal/platform/src/entities/InvoiceTemplate/SelectOptions.ts
web/portal/platform/src/router/EntityMap.ts
web/portal/yarn.lock

Added Invoice Template entity to portal platform

web/portal: Added Invoice Template to portal platform

---

web/portal/platform/.hygen.js
web/portal/platform/src/entities/Currency/Currency.tsx
web/portal/platform/src/entities/Currency/CurrencyProperties.ts
web/portal/platform/src/entities/Currency/Form.tsx
web/portal/platform/src/router/EntityMap.ts

This issue adds a new entity to the platform portal.

Added currency entity to platform portal

---

web/portal/platform/src/entities/Country/Country.tsx
web/portal/platform/src/entities/Country/CountryNameSelectOptions.ts
web/portal/platform/src/entities/Country/CountryProperties.tsx
web/portal/platform/src/entities/Country/SelectOptions.ts
web/portal/platform/src/entities/SpecialNumber/ForeignKeyResolver.tsx
web/portal/platform/src/entities/SpecialNumber/Form.tsx
web/portal/platform/src/entities/SpecialNumber/SelectOptions.ts
web/portal/platform/src/entities/SpecialNumber/SpecialNumber.tsx
web/portal/platform/src/entities/SpecialNumber/SpecialNumberProperties.ts
web/portal/platform/src/router/EntityMap.ts

Added Special Number entity to portal platform

web/portal: Added Special Number entity to portal platform

---

library/DataFixtures/ORM/ProviderTransformationRuleSet.php
library/Ivoz/Provider/Domain/Model/TransformationRuleSet/TransformationRuleSet.php
library/bin/test-codestyle-gherkin
web/rest/brand/features/provider/carrier/getCarrier.feature
web/rest/brand/features/provider/carrier/postCarrier.feature
web/rest/brand/features/provider/company/getCompanies.feature
web/rest/brand/features/provider/company/postCompanies.feature
web/rest/brand/features/provider/ddiProvider/getDdiProvider.feature
web/rest/brand/features/provider/ddiProvider/postDdiProvider.feature
web/rest/brand/features/provider/transformationRule/getTransformationRule.feature
web/rest/brand/features/provider/transformationRule/postTransformationRule.feature
web/rest/brand/features/provider/transformationRuleSet/getTransformationRuleSet.feature
web/rest/brand/features/provider/transformationRuleSet/postTransformationRuleSet.feature
web/rest/brand/features/provider/transformationRuleSet/putTransformationRuleSet.feature
web/rest/brand/features/provider/transformationRuleSet/removeTransformationRuleSet.feature
web/rest/client/features/provider/company/getCompany.feature
web/rest/client/features/provider/transformationRuleSet/getTransformationRuleSet.feature
web/rest/client/features/provider/user/getUser.feature
web/rest/client/features/provider/user/postUser.feature

- Added sanitize to check brandId field has not changed
- Reviewed data fixtures to add extra items
- Added extra API tests to check forbidden requests

Review Tranformation Rule Sets access tests

---

web/portal/platform/src/components/ActiveCalls/ActiveCalls.tsx
web/portal/platform/src/components/ActiveCalls/ActiveCallsTable.tsx
web/portal/platform/src/components/ActiveCalls/index.ts
web/portal/platform/src/components/ActiveCalls/types.ts
web/portal/platform/src/components/ActiveCalls/useRealtimeCalls.tsx
web/portal/platform/src/components/ActiveCalls/useWsClient.ts
web/portal/platform/src/entities/ActiveCalls/ActiveCalls.tsx
web/portal/platform/src/entities/ActiveCalls/ActiveCallsProperties.tsx
web/portal/platform/src/router/EntityMap.ts
web/portal/platform/src/router/addCustomRoutes.ts

Added Active calls entity to platfom portal

web/portal: Added Active calls to platfom portal

---

schema/DoctrineMigrations/Version20220929101012.php
schema/DoctrineMigrations/Version20221007090801.php
schema/DoctrineMigrations/Version20221103163102.php
schema/DoctrineMigrations/Version20221108082529.php
schema/DoctrineMigrations/Version20221123120153.php
schema/DoctrineMigrations/Version20230124094754.php
schema/DoctrineMigrations/Version20230125165233.php
schema/bin/test-schema

Update migrations to extend from LoggableMigration

---

library/DataFixtures/ORM/ProviderTransformationRule.php
library/Ivoz/Provider/Domain/Model/TransformationRule/TransformationRule.php
web/rest/brand/features/provider/transformationRule/getTransformationRule.feature
web/rest/brand/features/provider/transformationRule/postTransformationRule.feature
web/rest/brand/features/provider/transformationRule/putTransformationRule.feature
web/rest/brand/features/provider/transformationRule/removeTransformationRule.feature

- Added an extra sanitize to ensure transformationRuleSet field is never updated
- Added extra Rest API tests

Tranformation rules ACL review

---

library/Ivoz/Provider/Domain/Model/MatchListPattern/MatchListPattern.php
web/portal/client/src/entities/MatchListPattern/MatchListPattern.tsx
web/rest/client/features/provider/matchListPattern/putMatchListPattern.feature
web/rest/client/features/provider/matchListPattern/removeMatchListPattern.feature

- Added an extra sanitize to ensure matchListId field is never updated
- Removed edit and delete actions from client portal
- Added extra Rest API tests

Match list patterns ACL review

---

web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/notificationTemplateContent/getNotificationTemplateContent.feature
web/rest/platform/features/provider/notificationTemplateContent/postNotificationTemplateContent.feature
web/rest/platform/features/provider/notificationTemplateContent/putNotificationTemplateContent.feature
web/rest/platform/features/provider/notificationTemplateContent/removeNotificationTemplateContent.feature

Register new entity Notification Templates Content

Register notification template contents entity into platform api rest

---

web/portal/platform/src/entities/BillableCall/BillableCall.tsx
web/portal/platform/src/entities/BillableCall/BillableCallProperties.ts
web/portal/platform/src/router/EntityMap.ts

Added Billable call entity to platform portal

web/portal: Added Billable call to platform portal

---

web/portal/platform/src/entities/ProxyUser/Form.tsx
web/portal/platform/src/entities/ProxyUser/ProxyUser.tsx
web/portal/platform/src/entities/ProxyUser/ProxyUserProperties.ts
web/portal/platform/src/entities/ProxyUser/SelectOptions.ts
web/portal/platform/src/router/EntityMap.ts

Added ProxyUser entity to platform portal

web/portal: Added ProxyUser to platform portal

---

web/portal/platform/src/entities/MediaRelaySet/Form.tsx
web/portal/platform/src/entities/MediaRelaySet/MediaRelaySet.tsx
web/portal/platform/src/entities/MediaRelaySet/MediaRelaySetProperties.ts
web/portal/platform/src/entities/MediaRelaySet/SelectOptions.ts
web/portal/platform/src/router/EntityMap.ts

Added Media relay set entity to platform portal

web/portal: Added Media relay set to platform portal

---

web/portal/platform/src/entities/ApplicationServer/ApplicationServer.tsx
web/portal/platform/src/entities/ApplicationServer/ApplicationServerProperties.ts
web/portal/platform/src/entities/ApplicationServer/Form.tsx
web/portal/platform/src/entities/ApplicationServer/SelectOptions.ts
web/portal/platform/src/router/EntityMap.ts

Added Application server entity to platform portal

web/portal: Added Application server to platform portal

---

web/portal/brand/src/translations/languages.ts
web/portal/client/src/translations/languages.ts
web/portal/platform/src/translations/languages.ts

Reorder languages to multilang inputs

web/portal: Reorder languages to multilang inputs

---

web/portal/platform/src/entities/ProxyTrunk/Form.tsx
web/portal/platform/src/entities/ProxyTrunk/ProxyTrunk.tsx
web/portal/platform/src/entities/ProxyTrunk/SelectOptions.ts
web/portal/platform/src/router/EntityMap.ts

portal/platform: Added Porxy Trunks entity

---

web/admin/application/configs/klear/model/CallCsvSchedulers.yaml
web/admin/application/library/IvozProvider/Klear/Filter/CallCsvSchedulerEndpointType.php

Upport call csv scheduler filter issues

Upport call csv scheduler filter issues

---

web/portal/brand/index.html
web/portal/brand/src/index.tsx
web/portal/client/index.html
web/portal/client/src/index.tsx
web/portal/platform/index.html
web/portal/platform/src/index.tsx
web/portal/user/index.html
web/portal/user/src/index.tsx

Easier to know what portal are you working with.

Update new portals colors and titles

---

web/portal/platform/src/entities/Language/Form.tsx
web/portal/platform/src/entities/Language/Language.tsx
web/portal/platform/src/entities/Language/SelectOptions.ts
web/portal/platform/src/entities/NotificationTemplate/Form.tsx
web/portal/platform/src/entities/NotificationTemplate/NotificationTemplate.tsx
web/portal/platform/src/entities/NotificationTemplate/NotificationTemplateProperties.ts
web/portal/platform/src/entities/NotificationTemplateContent/Form.tsx
web/portal/platform/src/entities/NotificationTemplateContent/NotificationTemplateContent.tsx
web/portal/platform/src/entities/NotificationTemplateContent/NotificationTemplateContentProperties.ts
web/portal/platform/src/entities/NotificationTemplateContent/SelectOptions.ts
web/portal/platform/src/router/EntityMap.ts

Added Notification Template Entity to platform portal

Added Notification Templates entity

---

ChangeLog
asterisk/config/pjsip.conf
debian/changelog
doc/sphinx/conf.py
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
web/rest/client/CHANGELOG.md

Added Feature and API Changelogs, all versions bumped to 2.23.0

Release 2.23.0 changelog

---

ChangeLog
README.md

Update changelog and iso links for 2.23.0

---

web/portal/brand/src/router/EntityMap.ts
web/portal/brand/src/router/useAclFilteredEntityMap.tsx

Hide entities you have no access to

Filter entities based on brand features

---

web/rest/brand/features/my/profile/getProfile.feature
web/rest/brand/src/Service/Behat/FeatureContext.php
web/rest/platform/behat.yml.dist
web/rest/platform/config/packages/test/behat.yaml
web/rest/platform/features/my/profile/getProfile.feature
web/rest/platform/psalm-baseline.xml
web/rest/platform/src/Service/Behat/FeatureContext.php

This issue adds new tests for my/profile endpoints.

My profile api tests

---

web/portal/platform/src/router/EntityMap.ts

Added impersonate button to brand list

portal/platform: Added impersonate button to brand list

---

web/portal/client/src/entities/CallCsvScheduler/CallCsvScheduler.tsx

Email attribute not required in CallCsvSchedulers form.

Portal client csv schedulers email field cannot be required

---

web/rest/brand/phpstan-baseline.neon
web/rest/brand/psalm-baseline.xml
web/rest/brand/src/Controller/Auth/TokenExchangeAction.php
web/rest/brand/src/Controller/My/ActiveCallsAction.php
web/rest/brand/src/Controller/My/RegistrationSummaryAction.php
web/rest/brand/src/Controller/Provider/PostUsersMassImportAction.php
web/rest/brand/src/Controller/Provider/PutBillableCallRatingAction.php
web/rest/brand/src/Controller/Provider/ServicesUnassignedAction.php
web/rest/client/src/Controller/Auth/TokenExchangeAction.php
web/rest/client/src/Controller/Provider/ExtensionsUnassignedAction.php
web/rest/client/src/Controller/Provider/HuntGroupUsersAvailableAction.php
web/rest/client/src/Controller/Provider/RatingPlanPricesAction.php
web/rest/client/src/Controller/Provider/ServicesUnassignedAction.php
web/rest/client/src/Controller/Provider/TerminalsUnassignedAction.php
web/rest/platform/phpstan-baseline.neon
web/rest/platform/src/Controller/My/ActiveCallsAction.php
web/rest/platform/src/Controller/Provider/PutBillableCallRatingAction.php
web/rest/user/phpstan-baseline.neon
web/rest/user/psalm-baseline.xml
web/rest/user/src/Controller/My/PostCallForwardSettingsAction.php
web/rest/user/src/Controller/My/PutProfileAction.php
web/rest/user/src/Controller/My/WebThemeAction.php

This issue replace every RequestStack Calls on controllers by Request package belonging to Symfony Framework.

Replace request stack in controllers

---

web/portal/brand/src/entities/CallCsvScheduler/Form.tsx
web/portal/brand/src/entities/Company/Form.tsx
web/portal/client/src/App.tsx
web/portal/client/src/entities/HuntGroupMember/Form.tsx
web/portal/package.json
web/portal/platform/src/entities/Language/Form.tsx
web/portal/yarn.lock

Enhanced multilang and embeddable fields

---

asterisk/agi/composer.lock
library/composer.lock
microservices/balances/composer.lock
microservices/provision/composer.lock
microservices/realtime/composer.lock
microservices/recordings/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/user/composer.lock

Includes https://github.com/irontec/ivoz-core/commit/5954470e105faad5f8318b2dee991ca63651e19e

core: updated ivoz-core

---

web/portal/user/.hygen.js
web/portal/user/bin/generate-entity
web/portal/user/src/entities/CallForwardSetting/CallForwardSetting.tsx
web/portal/user/src/entities/CallForwardSetting/ForeignKeyResolver.tsx
web/portal/user/src/entities/CallForwardSetting/Form.tsx
web/portal/user/src/entities/CallForwardSetting/SelectOptions.ts
web/portal/user/src/entities/Extension/Extension.tsx
web/portal/user/src/entities/Extension/ExtensionProperties.ts

Fixed Call Forward Settings extension resolution in list screen

CFS extension issues

---

library/Ivoz/Provider/Domain/Model/Company/Company.php
web/portal/brand/src/router/EntityMap.ts
web/portal/package.json
web/portal/yarn.lock

Create company issues

---

web/portal/client/src/entities/QueueMember/foreignKeyResolver.tsx

fix user-update link from QueueMember

portal/client: fix user link from QueueMember

---

web/portal/client/src/entities/Queue/Queue.tsx

Add null value to Queue locutions

potal/client: Add null value to Queue locutions

---

web/portal/package.json
web/portal/yarn.lock

It was imposible to create a new holiday date on new portals

Holiday date

---

web/portal/brand/src/entities/CompanyBalances/CompanyBalances.tsx

remove create, delete & update actons from CompanyBalance

portal/brand: remove create, delete & update actons from CompanyBalance

---

web/portal/client/src/entities/IvrEntry/Form.tsx

portal/client: fix IvrEntry create form

---

web/portal/brand/src/entities/BalanceMovement/BalanceMovement.tsx

remove create action from BalanceMovement

portal/brand: remove create action from BalanceMovement

---

web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/proxyTrunk/postProxyTrunk.feature

Added post operation over Proxy Trunks entity located in Platform API.

Post endpoint in proxy trunk under platform api

---

web/portal/client/src/entities/Friend/Friend.tsx

Description not required under Friends web entity

---

web/portal/client/src/entities/HuntGroupMember/Form.tsx

hide timeoutTime if strategy is ringAll

portal/client: hide timeoutTime if strategy is ringAll

---

web/portal/brand/src/entities/DdiProvider/DdiProvider.tsx

DDI Provider description field cannot be null

---

web/portal/client/src/entities/Country/Country.tsx
web/portal/client/src/entities/Ddi/foreignKeyResolver.tsx

fix holidayNumberCountry in ExternalCallFilter

portal/client: fix holidayNumberCountry in ExternalCallFilter

---

library/Ivoz/Provider/Domain/Model/RoutingPattern/RoutingPatternDto.php
web/portal/brand/src/entities/RoutingPattern/RoutingPattern.tsx
web/rest/brand/features/provider/routingPattern/getRoutingPattern.feature

Serve description in Routing pattern collections and fixed regexp

Routing pattern issues

---

web/portal/brand/src/entities/Administrator/Administrator.tsx

Administrator > email not required.

---

web/portal/brand/src/entities/DdiProviderRegistration/DdiProviderRegistration.tsx

Fixed required fields in DdiProviderRegistration

---

web/portal/brand/src/entities/BalanceNotification/BalanceNotification.tsx
web/portal/brand/src/entities/BalanceNotification/Form.tsx

Required fields, Balance Notifications

---

web/portal/brand/src/entities/DestinationRate/SelectOptions.ts
web/portal/brand/src/entities/DestinationRateGroup/SelectOptions.ts
web/portal/brand/src/entities/RatingPlan/Form.tsx
web/portal/brand/src/entities/RatingPlan/SelectOptions.ts
web/portal/brand/src/entities/RatingPlanGroup/Form.tsx

Fixed RatingPlanGroup & RatingPlan form issues

---

web/rest/brand/config/api/raw/provider.yml
web/rest/brand/features/provider/balanceMovement/postBalanceMovement.feature

Portal brand carrier balance movements cannot have edit option

---

library/Ivoz/Provider/Domain/Model/HuntGroupMember/HuntGroupMember.php
web/portal/client/src/entities/Country/SelectOptions.ts
web/portal/client/src/entities/HuntGroupMember/HuntGroupMember.tsx

Country and  number must be required

Review HuntGroupMember required fields

---

web/portal/brand/src/entities/CompanyCurrentDayUsage/CompanyCurrentDayUsage.tsx

We'll get it back once it's exposed in the API

Hide current day usage status

---

Jenkinsfile
tests/docker/bin/prepare-composer-deps
tests/docker/bin/prepare-fixtures
tests/docker/bin/prepare-node-modules

Build stages based on PR commit messages
Build all stages in bleeding and halliday branches

ci: add changelog patterns to stage build conditions

---

web/portal/brand/src/entities/User/ForeignKeyResolver.tsx
web/portal/brand/src/entities/User/User.tsx

portal/brand: fix company name in User

---

library/Ivoz/Provider/Domain/Model/Brand/BrandDto.php
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/brand/getBrands.feature
web/rest/platform/features/provider/brand/postBrands.feature
web/rest/platform/features/provider/brand/putBrands.feature

Added accepted detailed context to Proxy trunk contexts

---

web/portal/brand/src/router/EntityMap.ts
web/portal/brand/src/router/useAclFilteredEntityMap.tsx
web/rest/brand/config/api/raw/provider.yml
web/rest/brand/src/Controller/Provider/Carrier/ModifyCarrierBalanceAction.php
web/rest/brand/src/Controller/Provider/Company/ModifyCompanyBalanceAction.php

Front & Back acces control for carrier children entities based on billing brand feature

Carrier subscreen access control

---

library/Ivoz/Provider/Domain/Model/RoutingPatternGroup/RoutingPatternGroup.php
library/Ivoz/Provider/Domain/Model/RoutingPatternGroup/RoutingPatternGroupInterface.php
library/psalm-baseline.xml
web/portal/brand/src/entities/RoutingPatternGroup/RoutingPatternGroup.tsx

Added required property to name in RoutingPatternGroups.

---

web/rest/client/src/Controller/My/ProfileAction.php

Check brand features ir order to resolve it properly

Fixed client admin profile showBillingInfo value

---

Jenkinsfile

Added 3 new labels to force Pipeline tests if required
- ci-force-tests: force all tests
- ci-force-test-back: only force backend tests
- ci-force-test-front: only force front tests

Force back and front tests from GitHub labels

---

web/portal/package.json
web/portal/yarn.lock

It was imposible to edit a brand without logo

Empty file issues

---

web/portal/platform/src/router/EntityMap.ts

There were some missing filterBys in platform EntityMap

Fixed EntityMap filterBy properties

---

library/Ivoz/Provider/Domain/Assembler/Brand/BrandDtoAssembler.php
library/Ivoz/Provider/Domain/Model/Brand/BrandDto.php
library/spec/Ivoz/Provider/Domain/Assembler/Brand/BrandDtoAssemblerSpec.php
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/brand/putBrands.feature

Fixed brand.proxyTrunks form handling

Fixed brand edition

---

web/portal/brand/src/entities/CallCsvScheduler/Form.tsx
web/portal/client/src/entities/CallCsvScheduler/Form.tsx

Call CSV scheduler hide fields by feature

---

web/portal/platform/src/entities/TerminalModel/TerminalModel.tsx

move prefix to helpText in forms

portal/platform: move prefix to helpText in forms

---

web/portal/brand/src/entities/Invoice/Invoice.tsx
web/portal/brand/src/entities/OutgoingRouting/Field/Operator.tsx
web/portal/client/src/entities/HuntGroupMember/Field/Target.tsx

added numberSequence-visualToggle in Invoice form

Added numberSequence-visualToggle in Invoice form

---

web/portal/brand/src/entities/Carrier/Carrier.tsx

portal/brand: fix Carrier ChildDecorator

---

web/admin/application/configs/klear/ExtensionsList.yaml

web/admin: remove voicemail column from Extensions list

---

microservices/workers/src/Worker/AsteriskDialplan.php
microservices/workers/src/Worker/AsteriskHintUpdater.php
microservices/workers/src/Worker/Cgrates.php
microservices/workers/src/Worker/Invoices.php
microservices/workers/src/Worker/Multimedia.php
microservices/workers/src/Worker/Rates.php

This PR does the same as #2024 for all existing workers.

microservices: properly check blPop return value

---

library/Ivoz/Provider/Domain/Model/Brand/BrandDto.php
web/rest/platform/features/provider/brand/postBrands.feature
web/rest/platform/features/provider/brand/putBrands.feature

It was imposible to upload a brand logo

Brand file upload issues

---

library/DataFixtures/ORM/ProviderInvoiceScheduler.php
library/Ivoz/Provider/Domain/Model/Invoice/Invoice.php
library/psalm-baseline.xml
library/spec/Ivoz/Provider/Domain/Model/Invoice/InvoiceSpec.php
schema/tests/Provider/BillableCall/BillableCallRepositoryTest.php
schema/tests/Provider/Invoice/CreateBySchedulerServiceTest.php
web/portal/brand/src/entities/Invoice/Form.tsx
web/portal/brand/src/entities/Invoice/Invoice.tsx
web/rest/brand/features/provider/fixedCostsRelInvoiceScheduler/getFixedCostsRelInvoiceScheduler.feature
web/rest/brand/features/provider/fixedCostsRelInvoiceScheduler/postFixedCostsRelInvoiceScheduler.feature
web/rest/brand/features/provider/invoiceScheduler/getInvoiceScheduler.feature

portal/brand: Fixed required attributes

---

library/Ivoz/Provider/Domain/Model/FixedCost/FixedCost.php
library/psalm-baseline.xml
web/portal/brand/src/entities/FixedCost/FixedCost.tsx

Ensure that cost property is a required attribute

Portal brand cost field should be required

---

web/portal/client/src/entities/HuntGroup/HuntGroup.tsx

noAnswerLocution null value in HuntGroup

portal/client: noAnswerLocution null value in HuntGroup

---

web/portal/client/src/entities/Ivr/Ivr.tsx

portal/client: added null value to Ivr locutions

---

web/portal/brand/src/entities/Company/Form.tsx
web/portal/brand/src/entities/Retail/Form.tsx
web/portal/brand/src/entities/Wholesale/Form.tsx

Check invoices and billing feature properly

Fixed retail and wholesale feature based filter issues

---

web/rest/platform/features/provider/invoiceTemplate/getInvoiceTemplate.feature
web/rest/platform/features/provider/invoiceTemplate/postInvoiceTemplate.feature
web/rest/platform/features/provider/invoiceTemplate/putInvoiceTemplate.feature
web/rest/platform/features/provider/invoiceTemplate/removeInvoiceTemplate.feature

Add missing platform invoice templates api test

---

web/portal/brand/src/entities/Company/Form.tsx
web/portal/brand/src/entities/Retail/Form.tsx
web/portal/brand/src/entities/Wholesale/Form.tsx

…eature
invoiceNotificationTemplate filtered by hasInvoicesFeatures

InvoiceNotificationTemplate filtered by invoices feature

---

web/portal/brand/src/entities/Carrier/Carrier.tsx

Description field cannot be required in Carrier relation

Description field cannot be required in Carrier

---

library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServer.php
library/psalm-baseline.xml
library/spec/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerSpec.php
web/portal/brand/src/entities/CarrierServer/CarrierServer.tsx

Portal brand carrier server sip proxy field should be required

---

web/portal/brand/src/entities/DdiProviderAddress/DdiProviderAddress.tsx

Ip property should be required in DdiProviderAddress

Ip property should be required

---

web/portal/package.json
web/portal/yarn.lock

Upgrade ivoz-ui

---

library/Ivoz/Provider/Domain/Model/Invoice/InvoiceDto.php
web/portal/platform/bin/generate-entity
web/portal/platform/src/entities/Brand/ForeignKeyResolver.tsx
web/portal/platform/src/entities/Carrier/Carrier.tsx
web/portal/platform/src/entities/Carrier/CarrierProperties.ts
web/portal/platform/src/entities/Company/Company.tsx
web/portal/platform/src/entities/Company/CompanyProperties.ts
web/portal/platform/src/entities/Ddi/Ddi.tsx
web/portal/platform/src/entities/Ddi/DdiProperties.ts
web/portal/platform/src/entities/DdiProvider/DdiProvider.tsx
web/portal/platform/src/entities/DdiProvider/DdiProviderProperties.ts
web/portal/platform/src/entities/Invoice/Invoice.tsx
web/portal/platform/src/entities/Invoice/InvoiceProperties.ts
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/invoice/getInvoices.feature
web/rest/platform/features/provider/invoice/postInvoices.feature
web/rest/platform/features/provider/invoice/putInvoices.feature
web/rest/platform/features/provider/invoice/removeInvoices.feature

Add BillableCall foreign key entities so that list & form values are rendered properly

Platform billable call issues

---

web/portal/client/src/entities/User/User.tsx
web/portal/package.json
web/portal/yarn.lock

API masks some sensitive values like password. Handle it so that they are not post/put back to the API

Fixed password issues

---

web/portal/brand/src/entities/Carrier/Carrier.tsx
web/portal/brand/src/entities/CarrierServer/CarrierServer.tsx
web/portal/brand/src/entities/CarrierServer/Field/StatusIcon.tsx

Added carrier and carrier server status custom component

Fixed carrier status issues

---

web/portal/client/src/entities/User/User.tsx

added null value to callAcl in User

portal/client: added null value to callAcl in User

---

web/portal/platform/src/entities/Administrator/Administrator.tsx

fix email administrator to not required

portal/platform: fix email administrator to not required

---

web/portal/brand/src/entities/DdiProviderRegistration/DdiProviderRegistration.tsx

remove password pattern & added authProxy pattern

portal/brand: remove password pattern & added authProxy pattern

---

web/portal/client/src/entities/ResidentialDevice/ResidentialDevice.tsx

fix description to not required in ResidentialDevice

portal/client: fix description to not required in ResidentialDevice

---

library/composer.lock
microservices/realtime/composer.lock
web/portal/brand/src/router/EntityMap.ts
web/portal/package.json
web/portal/yarn.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/user/composer.lock

Fixed prepaid balances filter issues

---

library/composer.lock
microservices/realtime/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/user/composer.lock

Handle "CURRENT_TIMESTAMP" datetime values

---

web/portal/package.json
web/portal/yarn.lock

Fixed search filters

---

web/portal/brand/src/entities/ResidentialDevice/Form.tsx
web/portal/brand/src/entities/ResidentialDevice/ResidentialDevice.tsx
web/portal/brand/src/entities/ResidentialDevice/SelectOptions/SelectOptions.ts
web/portal/brand/src/router/EntityMap.ts

added create action to ResidentialDevice

portal/brand: added create action to ResidentialDevice

---

web/portal/brand/src/entities/RetailAccount/Form.tsx
web/portal/brand/src/entities/RetailAccount/RetailAccount.tsx
web/portal/brand/src/entities/RetailAccount/SelectOptions/SelectOptions.ts
web/portal/brand/src/router/EntityMap.ts

added create action to RetailAccount

portal/brand: added create action to RetailAccount

---

web/portal/user/src/entities/CallForwardSetting/CallForwardSetting.tsx
web/portal/user/src/entities/CallForwardSetting/Form.tsx

added visualToggle to targetType

portal/user: added visualToggle to targetType

---

library/Ivoz/Provider/Application/Service/HolidayDate/CreateHolidayDateRange.php
library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDateRange.php
web/rest/client/config/api/raw/provider.yml
web/rest/client/config/routes.yaml
web/rest/client/features/provider/holidayDate/postHolidayDateRange.feature
web/rest/client/psalm-baseline.xml
web/rest/client/src/Controller/Provider/CreateHolidayDatesAction.php

Added massive creation of Holiday Dates.

Holiday dates intervals

---

debian/ivozprovider-profile-common.postinst

Add date and time to bash history entries

---

web/portal/client/src/entities/HuntGroupMember/HuntGroupMember.tsx

portal/clien: fix HuntGroupMember columns

---

web/portal/client/src/entities/HuntGroupMember/HuntGroupMember.tsx

timeoutTime & priority required

portal/client: timeoutTime & priority required

---

web/portal/platform/src/entities/MediaRelaySet/MediaRelaySet.tsx

default media relay set no edit & no delete

portal/platform: default media relay set no edit & no delete

---

web/rest/brand/features/provider/brand/putBrands.feature
web/rest/brand/features/provider/webPortal/putWebPortal.feature
web/rest/platform/features/provider/webPortal/putWebPortal.feature

File download test

---

web/portal/brand/src/entities/Company/Company.tsx

Remove required fields from Client entity

---

web/portal/package.json
web/portal/yarn.lock

Includes https://github.com/irontec/ivoz-ui/commit/2874f511662bc9165e9ae808b81f35deb3ab39ef
This fixes links to nowhere (entities without route) in lists

upgrade to ivoz-ui 0.14.5

---

web/portal/platform/src/router/EntityMap.ts

Added web portals child to brand entity

portal/platform: Added web portals child to brand entity

---

library/DataFixtures/ORM/ProviderProxyTrunk.php
web/portal/platform/src/entities/ProxyTrunk/Form.tsx
web/portal/platform/src/entities/ProxyTrunk/ProxyTrunk.tsx
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/proxyTrunk/getProxyTrunk.feature
web/rest/platform/features/provider/proxyTrunk/postProxyTrunk.feature
web/rest/platform/features/provider/proxyTrunk/removeProxyTrunk.feature

Portal platform proxy trunk name field should be editable with ids different to 1

---

library/Ivoz/Provider/Domain/Model/Ddi/Ddi.php
web/portal/brand/src/entities/Ddi/Form.tsx

Do not allow ddi.client update in order to avoid inconsistencies

Destination rate issues

---

web/portal/client/src/entities/Ddi/Form.tsx

It was not loading foreign keys in the form

Include DDI.externalCallFilter for residential clients

---

library/DataFixtures/ORM/ProviderRecording.php
library/DataFixtures/Stub/Provider/RecordingStub.php
library/Ivoz/Provider/Application/Service/Recording/ZipRecordingFiles.php
library/Ivoz/Provider/Domain/Assembler/Recording/RecordingDtoAssembler.php
web/portal/brand/src/entities/RetailAccount/ForeignKeyGetter.tsx
web/portal/brand/src/entities/RetailAccount/Form.tsx
web/portal/brand/src/entities/RetailAccount/RetailAccount.tsx
web/rest/client/config/api/raw/provider.yml
web/rest/client/config/routes.yaml
web/rest/client/config/services.yaml
web/rest/client/features/provider/recording/getRecordingZipFiles.feature
web/rest/client/src/Controller/Provider/RecordedFilesZipAction.php
web/rest/client/src/Service/Behat/FeatureContext.php

Added recordings/recorded_files_zip API endpoint

Recordings multidownload

---

web/portal/brand/src/entities/Residential/Residential.tsx
web/portal/brand/src/entities/Retail/Form.tsx
web/portal/brand/src/entities/Wholesale/Form.tsx

Removed domainUsers from form

---

ChangeLog
README.md

Added changelog entries for 3.1.0 release

Release 3.1.0 changelog

---

web/rest/client/config/api/raw/provider.yml

Fixed Tag attribute for holiday dates range

Fixed Tag attribute for holiday dates range

---

web/portal/brand/src/entities/Company/Action/Impersonate.tsx
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json

Added translation for impersonation through brand portal

Added translation for impersonation through brand portal

---

web/portal/platform/src/components/ActiveCalls/ActiveCallsTable.tsx
web/portal/platform/src/components/ActiveCalls/types.ts
web/portal/platform/src/components/ActiveCalls/useRealtimeCalls.tsx

Added missing columns and fixed some hints

Fixed some minor platform active call issues

---

web/portal/yarn.lock

This PR fixes some issues in user portal when switching from an edit form to another edit form diurectly

Upgrade to ivoz-ui 0.14.6

---

web/portal/platform/src/entities/PublicEntity/PublicEntity.tsx
web/portal/platform/src/entities/PublicEntity/PublicEntityProperties.ts
web/portal/platform/src/entities/PublicEntity/SelectOptions.ts

ACLs of Platform's Operators does not load

ACLs of Platform's Operators does not load

---

web/portal/brand/src/entities/PublicEntity/PublicEntity.tsx
web/portal/brand/src/entities/PublicEntity/SelectOptions.ts

portal/brand: Fixed lint problems

---

web/portal/brand/src/entities/InvoiceScheduler/Form.tsx

Cannot show on edit next and last execution date

Cannot show on edit next and last execution date

---

asterisk/config/dialplan/click2dial.conf
asterisk/config/modules.conf
kamailio/users/config/kamailio.cfg

Fix caller/callee in click2dial calls

kamusers: fix caller/callee in click2dial calls

---

doc/sphinx/administration_portal/brand/clients/virtual_pbx.rst
doc/sphinx/administration_portal/brand/settings/corporations.rst
doc/sphinx/administration_portal/brand/settings/index.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends/internal_friends.rst
web/admin/application/configs/klear/CompaniesList.yaml
web/admin/application/configs/klear/CorporationsList.yaml
web/admin/application/configs/klear/FriendsList.yaml
web/admin/application/configs/klear/conf.d/mapperList.yaml
web/admin/application/configs/klear/klear.yaml
web/admin/application/configs/klear/model/Companies.yaml
web/admin/application/configs/klear/model/Corporations.yaml
web/admin/application/languages/ca_ES/ca_ES.po
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/languages/it_IT/it_IT.po
web/admin/application/library/IvozProvider/Klear/Filter/FriendInterCompany.php

Added screens to Klear portals with new entity Corporations.

Add corporations klear screens and documentation

---

web/portal/client/src/router/EntityMap.ts

Moved Invoice to General section.

Moved Invoice to General section.

---

web/portal/brand/vite.config.ts
web/portal/client/vite.config.ts
web/portal/package.json
web/portal/platform/vite.config.ts
web/portal/user/vite.config.ts
web/portal/yarn.lock

Fix new portals prod build

---

web/portal/brand/src/entities/CallCsvScheduler/Form.tsx
web/portal/brand/src/entities/Company/ClientFeatures.ts
web/portal/brand/src/entities/Company/Field/TypeIcon.tsx
web/portal/brand/src/entities/Company/ForeignKeyGetter.tsx
web/portal/brand/src/entities/Company/Form.tsx
web/portal/brand/src/entities/Company/genericCompanyForeignKeyResolver.ts
web/portal/brand/src/entities/Ddi/Field/RouteType.tsx
web/portal/brand/src/entities/Feature/SelectOptions/ResidentialSelectOptions.ts
web/portal/brand/src/entities/Feature/SelectOptions/RetailFeatureSelectOptions.ts
web/portal/brand/src/entities/Feature/SelectOptions/SelectOptions.ts
web/portal/brand/src/entities/Retail/Form.tsx
web/portal/brand/src/router/EntityMap.ts
web/portal/platform/src/entities/Brand/Brand.tsx

Redistribute brand list columns sizes

Web portal refactoring

---

web/portal/client/src/entities/BillableCall/BillableCall.tsx
web/portal/client/src/store/index.ts
web/portal/package.json
web/portal/yarn.lock

Show conditionally based on client settings

Billable call price column

---

web/portal/brand/src/entities/Company/Form.tsx
web/portal/brand/src/router/EntityMap.ts

Hide company fields by billing feature

---

web/portal/brand/src/components/Login.tsx
web/portal/brand/src/router/AppRoutesGuard.tsx
web/portal/brand/src/store/clientSession/aboutMe.ts
web/portal/client/src/components/Login.tsx
web/portal/client/src/router/AppRoutesGuard.tsx
web/portal/platform/src/components/Login.tsx

Broken since web migrated to ivoz ui 1.0

Fixed impersonate regression

---

library/DataFixtures/ORM/ProviderCarrier.php
library/Ivoz/Provider/Domain/Model/Carrier/Carrier.php
web/portal/brand/src/entities/Carrier/Form.tsx

Carriers without billing feature must have calculate cost equal to false

Carrier calculate cost

---

library/Ivoz/Provider/Domain/Model/Company/CompanyRepository.php
library/Ivoz/Provider/Domain/Model/FeaturesRelCompany/FeaturesRelCompanyRepository.php
library/Ivoz/Provider/Domain/Service/FeaturesRelBrand/AvoidFeaturesInUseRemoval.php
library/Ivoz/Provider/Domain/Service/FeaturesRelBrand/FeaturesRelBrandLifecycleServiceCollection.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/FeaturesRelCompanyDoctrineRepository.php
schema/tests/Provider/Company/CompanyRepositoryTest.php
schema/tests/Provider/FeaturesRelCompany/FeaturesRelCompanyRepositoryTest.php
web/rest/platform/features/provider/featuresRelBrand/removeFeaturesRelBrand.feature

Added lifecycle for avoiding nested feature removal.

Added lifecycle for avoiding nested features removal.

---

web/portal/client/src/entities/Friend/Form.tsx
web/portal/client/src/entities/Friend/Friend.tsx

Added fields restrictions to Friend web entity.

---

web/portal/brand/src/entities/Company/Company.tsx
web/portal/platform/src/entities/Brand/Brand.tsx

Secured confirmation dialog on client and brand deletion

Delete double check

---

web/portal/brand/src/entities/BannedAddressBruteForce/Action/Unban.tsx
web/portal/brand/src/entities/BannedAddressBruteForce/Action/index.ts
web/portal/brand/src/entities/BannedAddressBruteForce/BannedAddressBruteForce.tsx
web/portal/brand/src/router/EntityMap.ts
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json

Added unban brute force attack button into brand portal

Unban brute force attack IP

---

web/portal/brand/src/entities/BillableCall/Action/Export.tsx
web/portal/brand/src/entities/BillableCall/Action/index.ts
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json
web/portal/client/src/entities/BillableCall/Action/Export.tsx
web/portal/client/src/entities/BillableCall/Action/index.ts
web/portal/client/src/entities/BillableCall/BillableCall.tsx
web/portal/client/src/router/EntityMap.ts
web/portal/package.json
web/portal/platform/src/entities/BillableCall/Action/Export.tsx
web/portal/platform/src/entities/BillableCall/Action/index.ts
web/portal/platform/src/entities/BillableCall/BillableCall.tsx
web/portal/platform/src/entities/Company/Company.tsx
web/portal/platform/src/entities/Company/SelectOptions.ts
web/portal/platform/src/router/EntityMap.ts
web/portal/yarn.lock

Added export to CSV button in billable calls

Billable Calls exporters

---

web/portal/brand/src/entities/Corporation/Corporation.tsx
web/portal/brand/src/entities/Corporation/Form.tsx

Upgrade basecode to ivoz-ui 1.x

Fixed corporation form

---

library/Ivoz/Provider/Domain/Model/MediaRelaySet/MediaRelaySetAbstract.php
library/Ivoz/Provider/Domain/Model/MediaRelaySet/MediaRelaySetDtoAbstract.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/MediaRelaySet.MediaRelaySetAbstract.orm.xml
schema/DoctrineMigrations/Version20230621151043.php

Web platform media relays 0 as default value in name attribute when you create a media relay set

---

web/portal/brand/src/entities/Residential/Residential.tsx

Hidded some non required columns

Hidded some non required columns

---

library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccountDto.php
web/portal/client/src/entities/RetailAccount/Form.tsx
web/portal/client/src/entities/RetailAccount/RetailAccount.tsx
web/portal/client/src/router/EntityMap.ts

Web client retail account missing multiple fields

Web client retail account missing multiple fields

---

web/portal/client/src/entities/ExternalCallFilter/ExternalCallFilter.tsx
web/portal/client/src/entities/ExternalCallFilter/Form.tsx

Inject outOfScheduleTargetType = 'number' value (hidden in the form)

Fixed residential external call filters

---

web/portal/platform/src/router/EntityMap.ts
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/webPortal/getWebPortal.feature
web/rest/platform/features/provider/webPortal/postWebPortal.feature
web/rest/platform/features/provider/webPortal/putWebPortal.feature
web/rest/platform/features/provider/webPortal/removeWebPortal.feature

Filter in the API and fix front values

Filter web portal list

---

web/portal/client/src/entities/RetailAccount/RetailAccount.tsx

Added to string into RetailAccount entity

Added to string into RetailAccount entity

---

web/portal/client/src/components/ActiveCalls/ActiveCalls.tsx

Fixed unused title and loading translation

Fixed unused title

---

web/portal/client/src/entities/FaxesInOut/FaxesInOut.tsx
web/portal/client/src/entities/FaxesInOut/FaxesInOutProperties.tsx
web/portal/client/src/entities/FaxesOut/FaxesOut.tsx
web/portal/client/src/translations/ca.json
web/portal/client/src/translations/en.json
web/portal/client/src/translations/es.json
web/portal/client/src/translations/it.json

Modified columns in Faxes Out entity.

Modified columns in Faxes Out entity.

---

library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CallForwardSettingDoctrineRepository.php
web/portal/package.json
web/portal/user/src/components/Header/Avatar/Avatar.tsx
web/portal/user/src/components/Header/MenuItems/MenuItems.tsx
web/portal/user/src/components/Header/useTerminalStatus.ts
web/portal/yarn.lock
web/rest/user/config/api/raw/provider.yml
web/rest/user/phpstan-baseline.neon
web/rest/user/psalm-baseline.xml
web/rest/user/psalm.xml
web/rest/user/src/Controller/My/CallForwardSettingsAction.php
web/rest/user/src/Controller/My/CallHistoryAction.php
web/rest/user/src/Controller/My/FilterCollectionTrait.php

There were no filters on /my/call_forward_settings API endpoint

User CFS filter issues

---

web/portal/brand/src/entities/BillableCall/Action/index.ts
web/portal/brand/src/entities/Company/Action/Impersonate.tsx
web/portal/brand/src/router/EntityMap.ts
web/portal/package.json
web/portal/platform/src/entities/Brand/Action/Impersonate.tsx
web/portal/platform/src/router/EntityMap.ts
web/portal/yarn.lock

- Changed icon
- set impersonate as first row action
- Impersonate in a new tab

Impersonate enhancements

---

web/admin/application/configs/klear/ExternalCallFiltersResidentialList.yaml
web/admin/application/configs/klear/model/CalendarPeriods.yaml
web/admin/application/configs/klear/model/ExternalCallFilters.yaml
web/admin/application/configs/klear/model/ExternalCallFiltersResidential.yaml
web/admin/application/configs/klear/model/HolidayDates.yaml
web/admin/application/configs/klear/model/HolidayDatesRange.yaml

Send outOfScheduleTargetType value in web/admin

Fixed residential external call filter issues

---

web/portal/brand/src/router/EntityMap.ts
web/portal/client/src/router/EntityMap.ts

Sort and regroup some menu items

Menu rearrange

---

web/portal/package.json
web/portal/yarn.lock

Avoid browser freeze when navigating from a custom edit route to another

Fixed user portal hangs

---

web/portal/package.json
web/portal/yarn.lock

Under some circumstances, canceling a request may lead to an infinite loop in foreign key loaders

Fixed random page hangs on reload

---

library/Ivoz/Provider/Domain/Model/Ddi/Ddi.php
web/portal/client/src/entities/Ddi/Ddi.tsx

In Ddis If assigned an external call filter it cannot be unlinked afterwards

In Ddis If assigned an external call filter it cannot be unlinked afterwards

---

web/portal/client/src/router/EntityMap.ts

CallForwardSettings visible outside three dots of options

---

web/portal/client/src/entities/Fax/Fax.tsx

Email should be required if sendByEnail is activated

Email should be required if sendByEmail is activated

---

asterisk/agi/composer.lock
library/composer.lock
microservices/balances/composer.lock
microservices/provision/composer.lock
microservices/realtime/composer.lock
microservices/recordings/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/platform/features/querystringFilters.feature
web/rest/user/composer.lock

Fixed filter regression and added tests to avoid them in the future

API querystring filter issues

---

library/composer.lock
microservices/realtime/composer.lock
web/portal/platform/src/entities/Administrator/Administrator.tsx
web/portal/platform/src/router/EntityMap.ts
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/administrator/getAdministrators.feature
web/rest/platform/features/provider/administratorRelPublicEntities/getAdministratorRelPublicEntities.feature
web/rest/platform/features/querystringFilters.feature
web/rest/user/composer.lock

Filter brand  admins properly in platform portal

Brand admin issues

---

web/portal/brand/src/translations/index.js
web/portal/client/src/translations/index.js
web/portal/package.json
web/portal/platform/src/translations/index.js
web/portal/user/src/translations/index.js
web/portal/yarn.lock

Inherit translations from ivoz-ui

Include ivoz UI translations

---

web/portal/brand/src/entities/Destination/Destination.tsx
web/portal/brand/src/entities/Destination/Form.tsx
web/portal/package.json
web/portal/yarn.lock

Required name fields and read only prefix on edit

Fixed destination issues

---

web/portal/brand/src/entities/Destination/SelectOptions.ts
web/portal/brand/src/entities/DestinationRate/DestinationRate.tsx
web/portal/brand/src/entities/DestinationRate/Field/ConnectionFee.tsx
web/portal/brand/src/entities/DestinationRate/Field/Cost.tsx

Fixed cost and connectionFee fields at the form component and destination prefixes inside parenthesis

Fixed cost and connectionFee fields at the form component and destination prefixes inside parenthesis

---

web/portal/client/src/entities/CallCsvScheduler/Form.tsx

Adapt call scheduler form to each type of client

portal/client: fixed call scheduler form issues

---

library/DataFixtures/ORM/ProviderTerminalModel.php
library/Ivoz/Provider/Domain/Model/TerminalModel/TerminalModelDto.php
web/rest/client/features/provider/terminalModel/getTerminalModel.feature
web/rest/platform/features/provider/terminalModel/getTerminalModel.feature

Portal platform terminal models url generic value nor specific is being shown on the list

Portal platform terminal models url generic value nor specific is being shown on the list

---

web/portal/brand/src/entities/DestinationRate/DestinationRate.tsx

Portal brand destination rate rate delete currency column

Portal brand destination rate rate delete currency column

---

web/portal/client/src/entities/ExternalCallFilter/ExternalCallFilter.tsx

Added required columns in External Call Filters

Added required columns in External Call Filters

---

library/composer.lock
microservices/realtime/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/platform/features/querystringFilters.feature
web/rest/user/composer.lock

Some filters were throwing an error with array values

Fixed array filter issues

---

web/portal/brand/src/entities/Company/Form.tsx

Fixed client forms

---

web/portal/brand/src/entities/Carrier/Action/BalanceOperations.tsx
web/portal/brand/src/entities/Carrier/Carrier.tsx
web/portal/brand/src/router/EntityMap.ts
web/portal/brand/src/router/useAclFilteredEntityMap.tsx
web/portal/brand/src/store/clientSession/aboutMe.ts

Show disabled children as gray text instead of empty row

Empty carrier menu items

---

library/Ivoz/Provider/Application/Service/WebPortal/WebThemeFactory.php
web/portal/brand/src/App.tsx
web/portal/client/src/App.tsx
web/portal/package.json
web/portal/platform/src/App.tsx
web/portal/user/src/App.tsx
web/portal/yarn.lock
web/rest/brand/features/my/theme/getWebTheme.feature
web/rest/client/features/my/theme/getWebTheme.feature
web/rest/platform/features/my/theme/getWebTheme.feature
web/rest/user/features/my/theme/getWebTheme.feature

Show portal logo based on WebPortals entity

Logo by url

---

library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerDto.php
web/portal/.gitignore

Portal brand error on create fixed cost of ddi type at invoice scheduler

Portal brand error on create fixed cost of ddi type at invoice scheduler

---

web/portal/client/src/entities/Friend/Form.tsx
web/rest/client/config/api/raw/provider.yml
web/rest/client/tests/DataAccessControl/Provider/FriendTest.php

Fixed security rules & show name in new portal form

Friend form issues

---

web/portal/brand/src/entities/Carrier/Action/BalanceOperations.tsx
web/portal/brand/src/router/EntityMap.ts

Apply on carrier balance operations same rules we apply to it's siblings

Carrier balance operation issues

---

web/portal/brand/src/entities/Invoice/Field/Total.tsx
web/portal/brand/src/entities/Invoice/Field/TotalWithTax.tsx
web/portal/brand/src/entities/Invoice/Invoice.tsx

- Fixed list row order
- Fixed custom field styles
- Fixed datetime to date conversion for inDate and outDate fields

Fixed invoice issues

---

library/Ivoz/Provider/Infrastructure/Api/Jwt/AdminTokenAuthenticator.php

Set admin.onBehalfOf value so that it's properly rendered in Commandlog

core: fixed changelog impersonation chain

---

web/portal/platform/src/router/EntityMap.ts

Update Brand webportals section documentation link

portal/platform: update Brand Webportals documentation link

---

web/rest/brand/CHANGELOG.md
web/rest/client/CHANGELOG.md
web/rest/platform/CHANGELOG.md
web/rest/user/CHANGELOG.md

doc: updated API changelog

---

ChangeLog
README.md

Updated changelog to new upcoming release

doc: update ChangeLog for 3.2.0 release

---

web/portal/package.json
web/portal/yarn.lock

Update to latest ivoz-ui version

web/portal: update ivoz-ui

---

web/portal/brand/bin/build
web/portal/client/bin/build
web/portal/platform/bin/build
web/portal/user/bin/build

It was empty and it's required to invalidate api spec cache

web/portal: fixed build version

---

library/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/platform/features/my/dashboard/getDashboard.feature
web/rest/user/composer.lock

Update to latest ivoz-api and use it's new behat json context "shold be like" matchers

Api test matchers

---

web/portal/package.json
web/portal/yarn.lock

Fixed baseUrl related breadcrumb issues on mobile devices

portal: upgrade ivoz-ui

---

web/portal/brand/src/router/AppRoutes.tsx
web/portal/client/src/router/AppRoutes.tsx
web/portal/platform/src/router/AppRoutes.tsx
web/portal/user/src/router/AppRoutes.tsx

Avoid warnings while routes are being parsed

Fixed router warnings on page first load

---

web/portal/client/src/entities/MatchListPattern/MatchListPattern.tsx
web/portal/package.json
web/portal/yarn.lock

- Remove add button on inherited matchlists
- Simplified ACL settings

Matchlist pattern ACL issues

---

web/portal/brand/src/router/useAclFilteredEntityMap.tsx
web/portal/client/src/router/useAclFilteredEntityMap.tsx
web/portal/platform/src/router/useAclFilteredEntityMap.tsx

Avoid distinct implementations as much as possible

Unify useAclFilteredEntityMap hook

---

microservices/balances/bin/reset-daily-usage-counter
microservices/balances/bin/sync
microservices/balances/config/routes.yaml
microservices/recordings/bin/recordings-encoder
microservices/scheduler/bin/run-billable-calls
microservices/scheduler/bin/run-billable-calls-historic
microservices/scheduler/bin/run-call-csv-to-email
microservices/scheduler/bin/run-invoice-scheduler
microservices/scheduler/bin/run-voicemail-messages
microservices/workers/bin/asterisk-dialplan-reload
microservices/workers/bin/asterisk-hint-update
microservices/workers/bin/cgrates-reloader
microservices/workers/bin/invoicer
microservices/workers/bin/kam-rpc-delayed
microservices/workers/bin/kam-rpc-request
microservices/workers/bin/multimedia-encoder
microservices/workers/bin/rates-import

- Fixed route path
- script exit code 1= 0 if error

Reset daily usage counter issues

---

library/DataFixtures/Stub/Ast/PsEndpointStub.php
library/DataFixtures/Stub/Ast/VoicemailStub.php
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByResidentialDevice.php
library/Ivoz/Provider/Domain/Model/Carrier/Carrier.php
library/Ivoz/Provider/Domain/Model/Feature/Feature.php
library/Ivoz/Provider/Domain/Model/Feature/FeatureInterface.php
library/Ivoz/Provider/Domain/Traits/RoutableTrait.php
microservices/workers/src/Worker/Invoices.php
schema/tests/Provider/Company/CompanyLifeCycleTest.php
web/rest/brand/src/Controller/Provider/Carrier/ModifyCarrierBalanceAction.php
web/rest/brand/src/Controller/Provider/Company/ModifyCompanyBalanceAction.php
web/rest/client/src/Controller/My/ProfileAction.php

Adapted code to reuse Feature Iden constants.

Feature iden constants

---

library/composer.lock
web/rest/platform/features/querystringFilters.feature

Fixed API array filters and updated tests

Fixed api array filters

---

web/portal/package.json
web/portal/yarn.lock

Updated to latest ivoz-ui that implements fast search on foreign keys

Fast search on foreign keys

---

web/portal/brand/src/entities/Language/Language.tsx
web/portal/brand/src/entities/Service/Service.tsx

- fixed language.toString
- fixed service.toString

Fixed translation issues

---

schema/DoctrineMigrations/Version20230817114147.php

Persist PublicEntities and AdministratorRelPublicEntities in PublicEntities db table

Updated public entities

---

library/Ivoz/Provider/Application/Service/RatingPlanGroup/SimulateCallByRatingPlanGroup.php
web/portal/brand/src/entities/RatingPlanGroup/Action/SimulateCall.tsx
web/portal/brand/src/entities/RatingPlanGroup/Action/index.ts
web/portal/brand/src/entities/RatingPlanGroup/RatingPlanGroup.tsx
web/portal/brand/src/router/EntityMap.ts

Added simulate call action button on rating plan groups

Rating plan group simulate call

---

web/portal/client/src/entities/Voicemail/Voicemail.tsx

Added childDecorator as argument of Voicemails

Added childDecorator as argument of Voicemails

---

web/portal/client/src/router/EntityMap.ts
web/portal/client/src/translations/ca.json
web/portal/client/src/translations/en.json
web/portal/client/src/translations/es.json
web/portal/client/src/translations/it.json

[show address book instead of contacts in the menu and breadcrumbs](https://github.com/irontec/ivozprovider/commit/1c9c1716fb396568d89c419db1725ba4547db5a0)

Contact menu rename

---

microservices/recordings/src/Recording/Encoder.php

Properly catch conversion command Exceptions to gracefuly handle errors.

Recordings conversion error handling

---

microservices/recordings/src/Service/Encoder.php

microservices: properly handle recordings conversion errors

---

library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalAbstract.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalDtoAbstract.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/WebPortal.WebPortalAbstract.orm.xml
schema/DoctrineMigrations/Version20230918140953.php
web/rest/brand/features/provider/webPortal/getWebPortal.feature
web/rest/brand/features/provider/webPortal/postWebPortal.feature
web/rest/brand/features/provider/webPortal/putWebPortal.feature
web/rest/platform/features/provider/webPortal/getWebPortal.feature
web/rest/platform/features/provider/webPortal/postWebPortal.feature

Make newUI default value in WebPortals

---

web/portal/brand/src/components/Dashboard/Dashboard.styles.tsx
web/portal/client/src/components/Dashboard/Dashboard.styles.tsx
web/portal/platform/src/components/Dashboard/Dashboard.styles.tsx
web/portal/user/src/components/Dashboard/Dashboard.styles.tsx

Fixed dashboard styles in small devices

---

library/Ivoz/Provider/Domain/Service/InvoiceTemplate/InvoiceTemplatePreviewGenerator.php
tests/docker/Dockerfile
web/rest/brand/config/api/raw/provider.yml
web/rest/brand/config/routes.yaml
web/rest/brand/features/provider/invoiceTemplate/getInvoiceTemplatePreview.feature
web/rest/brand/src/Controller/Provider/InvoiceTemplatePreviewAction.php
web/rest/platform/composer.json
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/config/routes.yaml
web/rest/platform/features/provider/invoiceTemplate/getInvoiceTemplatePreview.feature
web/rest/platform/src/Controller/Provider/InvoiceTemplatePreviewAction.php

- Fixed API endpoints (return a pdf instead of html)
- Add them to swagger

Invoice template preview backend issues

---

library/DataFixtures/ORM/ProviderWebPortal.php
library/Ivoz/Provider/Application/Service/WebPortal/WebThemeFactory.php
web/rest/brand/features/provider/webPortal/postWebPortal.feature
web/rest/platform/features/my/theme/getWebTheme.feature
web/rest/platform/features/provider/webPortal/getWebPortal.feature
web/rest/platform/features/provider/webPortal/postWebPortal.feature
web/rest/platform/psalm-baseline.xml
web/rest/platform/src/Service/Behat/FeatureContext.php

Serve default ivozprovider logo if webportal doesn't include one

Webportal logo fallback

---

web/portal/brand/src/components/Dashboard/Dashboard.styles.tsx
web/portal/brand/src/components/Dashboard/Dashboard.tsx
web/portal/client/src/components/Dashboard/Dashboard.styles.tsx
web/portal/client/src/components/Dashboard/Dashboard.tsx
web/portal/package.json
web/portal/platform/src/components/Dashboard/Dashboard.styles.tsx
web/portal/platform/src/components/Dashboard/Dashboard.tsx
web/portal/user/src/components/Dashboard/Dashboard.styles.tsx
web/portal/user/src/components/Dashboard/Dashboard.tsx
web/portal/yarn.lock

Update portals circle chart

---

library/Ivoz/Provider/Application/Service/Extension/SyncFromCsv.php
library/Ivoz/Provider/Domain/Service/Extension/ExtensionFactory.php
library/phpstan-baseline.neon
library/spec/Ivoz/Provider/Application/Service/User/SyncFromCsvSpec.php
library/spec/Ivoz/Provider/Domain/Service/Extension/ExtensionFactorySpec.php
web/rest/client/config/api/resources.yml
web/rest/client/config/routes.yaml
web/rest/client/features/provider/extension/postExtensionMassImport.feature
web/rest/client/src/Controller/Provider/PostExtensionsMassImportAction.php
web/rest/client/src/Model/ExtensionsMassImport.php

Back extensions section alias import

---

web/portal/client/src/entities/Extension/Action/Import.tsx
web/portal/client/src/entities/Extension/Action/index.ts
web/portal/client/src/entities/Extension/Extension.tsx
web/portal/client/src/translations/ca.json
web/portal/client/src/translations/en.json
web/portal/client/src/translations/es.json
web/portal/client/src/translations/it.json

Web client extensions section import aliases

Web client extensions section import aliases

---

web/admin/application/controllers/KlearCustomAclController.php
web/admin/application/controllers/KlearCustomBruteForceUnbanController.php
web/admin/application/controllers/KlearCustomDownloadFileController.php
web/admin/application/controllers/KlearCustomDownloadRatingPlanController.php
web/admin/application/controllers/KlearCustomForwardFaxController.php
web/admin/application/controllers/KlearCustomIncrementBalanceController.php
web/admin/application/controllers/KlearCustomRestoreBackupController.php
web/admin/application/controllers/KlearCustomRestoreDefaultController.php
web/admin/application/controllers/KlearCustomRtController.php
web/admin/application/controllers/KlearCustomRunCodeController.php
web/admin/application/controllers/KlearCustomTarificatorController.php
web/admin/application/controllers/KlearCustomUploadFileController.php

Fixes a regression introduced in https://github.com/irontec/ivozprovider/pull/2383

fixed klear custom script paths

---

web/portal/brand/src/entities/BannedAddressBruteForce/Action/Unban.tsx
web/portal/brand/src/entities/BillableCall/Action/Export.tsx
web/portal/brand/src/entities/BillableCall/Action/Rerate.tsx
web/portal/brand/src/entities/InvoiceTemplate/Action/Preview.tsx
web/portal/brand/src/entities/RatingPlanGroup/Action/SimulateCall.tsx
web/portal/brand/src/entities/RatingProfile/Action/SimulateCall.tsx
web/portal/client/src/entities/BillableCall/Action/Export.tsx
web/portal/client/src/entities/RatingProfile/Action/SimulateCall.tsx
web/portal/client/src/entities/UsersCdr/Action/Export.tsx
web/portal/package.json
web/portal/platform/src/entities/BillableCall/Action/Export.tsx
web/portal/platform/src/entities/InvoiceTemplate/Action/Preview.tsx
web/portal/yarn.lock

Custom components refactoring replace with components done in ivoz UI

Custom components refactoring replace with components done in ivoz UI

---

web/portal/brand/src/entities/CompanyBalances/Action/BalanceOperations.tsx

Fixed post values in BalanceOperation action

Fixed operations prepaid balances front

---

library/bin/cache-clear
library/bin/cache-rm
library/bin/composer-install
library/bin/composer-remove
library/bin/composer-require
library/bin/composer-update
library/bin/test-app-console
library/bin/test-phplint
library/bin/test-phpstan
library/bin/test-psalm
library/bin/vendor-rm
microservices/router/psalm-baseline.xml

core: update scripts with automatic app discovery loops

---

asterisk/agi/src/Agi/Action/ConferenceRoomAction.php
library/Ivoz/Provider/Domain/Model/ConferenceRoom/ConferenceRoomAbstract.php
library/Ivoz/Provider/Domain/Model/ConferenceRoom/ConferenceRoomDto.php
library/Ivoz/Provider/Domain/Model/ConferenceRoom/ConferenceRoomDtoAbstract.php
library/Ivoz/Provider/Domain/Model/ConferenceRoom/ConferenceRoomInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ConferenceRoom.ConferenceRoomAbstract.orm.yml
schema/DoctrineMigrations/Version20231108092228.php
web/admin/application/configs/klear/ConferenceRoomsList.yaml
web/admin/application/configs/klear/model/ConferenceRooms.yaml
web/admin/application/languages/ca_ES/ca_ES.po
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/languages/it_IT/it_IT.po
web/rest/client/features/provider/conferenceRoom/getConferenceRoom.feature
web/rest/client/features/provider/conferenceRoom/postConferenceRoom.feature

Configurable setting to announce how many participants are already present when joining a conference room.
Also change the default sound for join and leave to beep.

Conference Announce user count

---

library/Ivoz/Provider/Domain/Model/Voicemail/VoicemailRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/VoicemailDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/VoicemailMessageDoctrineRepository.php
web/rest/client/features/my/dashboard/getDashboard.feature
web/rest/client/src/Service/Domain/Dashboard/GetResidentialInfo.php

Modified Dashboard to obtain Voicemail messages, actually it was retrieving only voice mails.

Fix clients residential dashboard

---

web/portal/package.json
web/portal/yarn.lock

Fixed new portal background image

---

library/Ivoz/Provider/Domain/Model/Feature/Feature.php
library/Ivoz/Provider/Domain/Service/FeaturesRelCompany/CheckValidity.php
library/Ivoz/Provider/Domain/Service/FeaturesRelCompany/FeaturesRelCompanyLifecycleServiceCollection.php
schema/DoctrineMigrations/Version20231115173418.php
web/portal/brand/src/entities/Company/ClientFeatures.ts
web/portal/brand/src/entities/Feature/SelectOptions/ResidentialFeatureSelectOptions.ts
web/portal/brand/src/entities/Feature/SelectOptions/RetailFeatureSelectOptions.ts

Operator panel feature

---

library/Ivoz/Provider/Application/Service/ActiveCall/RegistrationChannelResolver.php
library/Ivoz/Provider/Domain/Model/Administrator/Administrator.php
library/Ivoz/Provider/Domain/Service/ActiveCall/AssertAccessGranted.php
web/rest/brand/config/api/resources.yml
web/rest/brand/config/routes.yaml
web/rest/brand/features/my/activeCalls/getActiveCallsFilters.feature
web/rest/brand/src/Controller/My/ActiveCallsRealtimeFilterAction.php
web/rest/client/config/api/resources.yml
web/rest/client/config/routes.yaml
web/rest/client/features/my/activeCalls/getActiveCallsFilters.feature
web/rest/client/src/Controller/My/ActiveCallsRealtimeFilterAction.php
web/rest/platform/config/api/resources.yml
web/rest/platform/config/routes.yaml
web/rest/platform/features/my/activeCalls/getActiveCallsFilters.feature
web/rest/platform/src/Controller/My/ActiveCallsRealtimeFilterAction.php

Created four new endpoints to retrieve filter actions for future use in Redis

Endpoints to retrieve realtime filter actions

---

asterisk/agi/src/Agi/Action/ServiceAction.php
asterisk/agi/src/Agi/Wrapper.php
library/Ivoz/Ast/Domain/Model/QueueMember/QueueMemberRepository.php
library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/QueueMemberDoctrineRepository.php
library/Ivoz/Provider/Domain/Model/Service/Service.php
schema/DoctrineMigrations/Version20231127093825.php
schema/tests/Ast/QueueMember/QueueMemberRepositoryTest.php

Added two new services codes to pause or unpause a queue member in all its queues

Queue pause and unpause services

---

microservices/realtime/pkg/services/feeder/users_calls.go
microservices/realtime/pkg/services/redis_helper.go

Fixed realtime bug in party type

Fixed realtime bug in party type

---

microservices/realtime/configs/config.yml
microservices/realtime/go.mod
microservices/realtime/go.sum
microservices/realtime/pkg/config/viper.go
microservices/realtime/pkg/services/http.go
microservices/realtime/pkg/services/redis_helper.go
microservices/realtime/pkg/websocket/websocket_server.go

Added logger functionality to realtime

---

microservices/realtime/cmd/server/main.go
microservices/realtime/pkg/log/logrus.go
microservices/realtime/pkg/services/http.go
microservices/realtime/pkg/services/redis_helper.go
microservices/realtime/pkg/websocket/websocket_server.go

Created logger package to wrap logrus initialization

Wrapped Logger initialization

---

web/portal/platform/src/translations/es.json

Fix translation typo

---

web/portal/brand/src/entities/Company/Form.tsx

Fixed recording form fields when client is retail

---

library/Ivoz/Provider/Domain/Model/Carrier/CarrierRepository.php
library/Ivoz/Provider/Domain/Model/Company/CompanyRepository.php
library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderRepository.php
library/Ivoz/Provider/Domain/Service/ActiveCall/AssertAccessGranted.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CarrierDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CompanyDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/DdiProviderDoctrineRepository.php
library/phpstan-baseline.neon
library/psalm-baseline.xml

Prevent strict comparison issues in ActiveCall/AssertAccessGranted

---

web/portal/brand/src/entities/Company/Form.tsx

Form fields disposition

---

web/rest/platform/config/api/raw/provider.yml

Documented api response codes for platform

---

ChangeLog

v3.4 ChangeLog

---

web/portal/brand/src/entities/Country/CountryProperties.tsx
web/portal/brand/src/entities/Ddi/Form.tsx
web/portal/brand/src/entities/Ddi/hooks/useDefaultCountryId.tsx

Set ddi country value based on selected client

DDI country default value by client

---

web/portal/client/src/entities/CalendarPeriod/Form.tsx
web/portal/client/src/entities/CallForwardSetting/Form.tsx
web/portal/client/src/entities/ConditionalRoute/Form.tsx
web/portal/client/src/entities/ConditionalRoutesCondition/Form.tsx
web/portal/client/src/entities/Contact/Form.tsx
web/portal/client/src/entities/Extension/Form.tsx
web/portal/client/src/entities/ExternalCallFilter/Form.tsx
web/portal/client/src/entities/FaxesOut/Form.tsx
web/portal/client/src/entities/HolidayDate/Form.tsx
web/portal/client/src/entities/HuntGroupMember/Form.tsx
web/portal/client/src/entities/Ivr/Form.tsx
web/portal/client/src/entities/IvrEntry/Form.tsx
web/portal/client/src/entities/MatchListPattern/Form.tsx
web/portal/client/src/entities/Queue/Form.tsx
web/portal/client/src/store/clientSession/aboutMe.ts
web/rest/client/features/my/profile/getProfile.feature
web/rest/client/src/Controller/My/ProfileAction.php
web/rest/client/src/Model/Profile.php

Apply client's default country in new entity forms

Default country value in new entity forms

---

microservices/realtime/pkg/services/http.go
microservices/realtime/pkg/utils/jwt.go
microservices/realtime/pkg/websocket/websocket_server.go

microservices/realtime: Added call filters

---

web/portal/brand/src/entities/Carrier/Action/BalanceOperations.tsx

Fixed balance operations in Carrier entity

---

web/portal/brand/src/entities/Carrier/Action/BalanceOperations.tsx

protal/brand: linted code

---

Jenkinsfile
library/bin/test-app-dependencies

New pipeline test to validate all applications have their composer.lock files up-to-date

ci: new test to validate application composer dependencies

---

library/Ivoz/Provider/Domain/Model/NotificationTemplate/NotificationTemplateAbstract.php
library/Ivoz/Provider/Domain/Model/NotificationTemplate/NotificationTemplateInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/NotificationTemplate.NotificationTemplateAbstract.orm.xml
schema/DoctrineMigrations/Version20231218161807.php
web/portal/platform/src/entities/NotificationTemplate/NotificationTemplate.tsx
web/portal/platform/src/translations/ca.json
web/portal/platform/src/translations/en.json
web/portal/platform/src/translations/es.json
web/portal/platform/src/translations/it.json

Added schema migrations for new accesCredentials enum into Notification templates

Access credentials notification templates

---

library/Ivoz/Provider/Application/Service/WebPortal/WebThemeFactory.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalAbstract.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalDtoAbstract.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalInterface.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebTheme.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/WebPortal.WebPortalAbstract.orm.xml
schema/DoctrineMigrations/Version20231214112518.php
web/rest/brand/features/my/theme/getWebTheme.feature
web/rest/brand/features/provider/webPortal/postWebPortal.feature
web/rest/brand/features/provider/webPortal/putWebPortal.feature
web/rest/client/features/my/theme/getWebTheme.feature
web/rest/platform/features/my/theme/getWebTheme.feature
web/rest/platform/features/provider/webPortal/getWebPortal.feature
web/rest/platform/features/provider/webPortal/postWebPortal.feature
web/rest/platform/features/provider/webPortal/putWebPortal.feature
web/rest/user/features/my/theme/getWebTheme.feature

Added new color attributes for WebPortals, this element will be dynamically established in migrations using four different colors for each of the web portals configured previously.

Backend portal themes

---

Jenkinsfile

Add new functional stage to Jenkins pipeline to avoid merging a PR that has Functional review pending in Irontec Jira

Add Jenkins pipeline functional stage checks

---

web/portal/platform/src/entities/Brand/Form.tsx
web/portal/platform/src/entities/Feature/SelectOptions.ts

Used iden to display sip domain

---

web/portal/brand/src/App.tsx
web/portal/brand/src/Theme.tsx
web/portal/brand/src/index.tsx
web/portal/client/src/App.tsx
web/portal/client/src/Theme.tsx
web/portal/client/src/index.tsx
web/portal/platform/src/Theme.tsx
web/portal/platform/src/index.tsx
web/portal/user/src/App.tsx
web/portal/user/src/Theme.tsx
web/portal/user/src/index.tsx

- Added Administration portal primary color picker
- Apply selected color

Apply custom web portal color

---

library/Ivoz/Provider/Domain/Model/Voicemail/VoicemailDto.php
web/portal/client/src/entities/Voicemail/Form.tsx
web/portal/client/src/entities/Voicemail/Voicemail.tsx
web/portal/client/src/router/EntityMap.ts
web/rest/client/features/provider/voicemail/getVoicemail.feature

Show email, attachSound when email notification enabled

---

library/DataFixtures/Stub/Provider/UsersCdrStub.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrRepository.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrAbstract.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrDtoAbstract.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrInterface.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrRepository.php
library/Ivoz/Kam/Domain/Service/UsersCdr/SetParsed.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.xml
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/UsersCdrDoctrineRepository.php
library/Ivoz/Provider/Application/Service/BillableCall/MigrateFromUnparsedTrunksCdr.php
library/Ivoz/Provider/Application/Service/UsersCdr/MigrateFromUnparsedKamUsersCdr.php
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrAbstract.php
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrInterface.php
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrRepository.php
library/Ivoz/Provider/Domain/Service/UsersCdr/MigrateFromKamUsersCdr.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.xml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/UsersCdrDoctrineRepository.php
library/phpstan-baseline.neon
library/psalm-baseline.xml
library/spec/Ivoz/Provider/Application/Service/BillableCall/MigrateFromUnparsedTrunksCdrSpec.php
microservices/scheduler/bin/run-users-cdrs
microservices/scheduler/config/routes.yaml
microservices/scheduler/config/services.yaml
microservices/scheduler/src/BillableCallController.php
microservices/scheduler/src/UsersCdrController.php
schema/DoctrineMigrations/Version20231127151351.php
schema/DoctrineMigrations/Version20240115165305.php
schema/tests/Kam/UsersCdr/UsersCdrRepositoryTest.php
schema/tests/Provider/UsersCdr/UsersCdrRepositoryTest.php

Users proxy cdr migration service

User cdr mixer

---

debian/ivozprovider-scheduler.install
debian/ivozprovider-scheduler.ivozprovider-users-cdrs.service
debian/ivozprovider.postinst
debian/rules
debian/systemd/ivozprovider-users-cdrs.service
debian/systemd/ivozprovider-users-cdrs.timer

Added systemd timer and services for users cdrs mixer

Add systemd timer and service for users cdrs mixer

---

web/admin/application/library/IvozProvider/Klear/Auth/User.php

This is required to silence PHP8.2 deprecation warnings related to dynamic class properties
This is required to silence PHP8.2 deprecation warnings related to dynamic class properties

web/admin: add missing properties in IvozProvider\Klear\Auth\User

---

web/portal/client/src/entities/UsersCdr/UsersCdr.tsx

They were always disabled so... just remove them

Remove users cdr action buttons

---

web/portal/platform/src/entities/Brand/Form.tsx
web/portal/platform/src/entities/Feature/SelectOptions.ts

portal/platform: used iden to display sip domain

---

library/Ivoz/Provider/Domain/Model/Domain/DomainDto.php
schema/DoctrineMigrations/Version20240122174421.php
web/portal/client/src/entities/Domain/Domain.tsx
web/portal/client/src/entities/Domain/DomainProperties.ts
web/portal/client/src/entities/Friend/Friend.tsx
web/portal/client/src/entities/UsersCdr/UsersCdr.tsx
web/rest/client/config/api/raw/provider.yml
web/rest/client/features/provider/domain/getDomains.feature

Resolve domain column properly in collection page

Friends list issues

---

asterisk/agi/composer.lock
library/composer.json
library/composer.lock
microservices/balances/composer.lock
microservices/provision/composer.lock
microservices/recordings/composer.lock
microservices/router/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/user/composer.lock

Updated ivoz-dev-tools

---

library/Ivoz/Provider/Domain/Model/Voicemail/VoicemailDto.php
web/portal/client/src/entities/Voicemail/Form.tsx
web/portal/client/src/entities/Voicemail/Voicemail.tsx
web/portal/client/src/router/EntityMap.ts
web/rest/client/features/provider/voicemail/getVoicemail.feature

Residential voicemails should show email and attach sound

---

schema/initial.sql

Alice and Bob should have users.ivozprovider.local as outbound proxy.

schema: add outbound-proxy to alice and bob

---

schema/DoctrineMigrations/Version20230210074653.php
schema/DoctrineMigrations/Version20230626081909.php
schema/DoctrineMigrations/Version20230817071407.php
schema/DoctrineMigrations/Version20230817093032.php
schema/DoctrineMigrations/Version20230817114147.php
schema/DoctrineMigrations/Version20231108092228.php
schema/DoctrineMigrations/Version20231127093825.php
schema/DoctrineMigrations/Version20231127151351.php
schema/bin/test-schema

The test was actually checking that all migrations extends from this class but it was not raising error when not.

Update test-schema to ensure all migrations extends from LoggableMigration

---

library/Ivoz/Provider/Domain/Model/Carrier/CarrierDto.php
library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderDto.php
web/portal/brand/src/components/ActiveCalls/hooks/useRealtimeCalls.tsx
web/portal/platform/src/components/ActiveCalls/ActiveCalls.helpers.tsx
web/portal/platform/src/components/ActiveCalls/ActiveCalls.styles.tsx
web/portal/platform/src/components/ActiveCalls/ActiveCalls.tsx
web/portal/platform/src/components/ActiveCalls/FilterComponent.tsx
web/portal/platform/src/components/ActiveCalls/hooks/useCriteriaChangeListener.tsx
web/portal/platform/src/components/ActiveCalls/hooks/useRealtimeCalls.tsx
web/portal/platform/src/components/ActiveCalls/hooks/useWsClient.ts
web/portal/platform/src/components/ActiveCalls/types.ts
web/portal/platform/src/entities/ActiveCalls/ActiveCalls.tsx
web/portal/platform/src/entities/ActiveCalls/ActiveCallsProperties.tsx
web/portal/platform/src/entities/Carrier/Carrier.tsx
web/portal/platform/src/entities/Carrier/SelectOptions.ts
web/portal/platform/src/entities/DdiProvider/DdiProvider.tsx
web/portal/platform/src/entities/DdiProvider/SelectOptions.ts
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/carrier/getCarrier.feature
web/rest/platform/features/provider/carrier/postCarrier.feature
web/rest/platform/features/provider/carrier/putCarrier.feature
web/rest/platform/features/provider/carrier/removeCarrier.feature
web/rest/platform/features/provider/ddiProvider/getDdiProvider.feature
web/rest/platform/features/provider/ddiProvider/postDdiProvider.feature
web/rest/platform/features/provider/ddiProvider/putDdiProvider.feature
web/rest/platform/features/provider/ddiProvider/removeDdiProvider.feature

Web platforms active calls filters

---

library/DataFixtures/ORM/ProviderProxyUser.php
library/Ivoz/Provider/Domain/Model/ProxyUser/ProxyUser.php
library/Ivoz/Provider/Domain/Model/ProxyUser/ProxyUserAbstract.php
library/Ivoz/Provider/Domain/Model/ProxyUser/ProxyUserDto.php
library/Ivoz/Provider/Domain/Model/ProxyUser/ProxyUserDtoAbstract.php
library/Ivoz/Provider/Domain/Model/ProxyUser/ProxyUserInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ProxyUser.ProxyUserAbstract.orm.xml
library/psalm-baseline.xml
library/psalm.xml
schema/DoctrineMigrations/Version20240126103408.php
web/portal/platform/src/entities/ProxyUser/Form.tsx
web/portal/platform/src/entities/ProxyUser/ProxyUser.tsx
web/portal/platform/src/entities/ProxyUser/ProxyUserProperties.ts
web/portal/platform/src/translations/ca.json
web/portal/platform/src/translations/en.json
web/portal/platform/src/translations/es.json
web/portal/platform/src/translations/it.json
web/rest/platform/features/provider/proxyUser/getProxyUser.feature
web/rest/platform/features/provider/proxyUser/putProxyUser.feature

Added advertised address attribute into ProxyUsers

Proxy users advertised address

---

library/DataFixtures/ORM/ProviderProxyTrunk.php
library/Ivoz/Provider/Domain/Model/ProxyTrunk/ProxyTrunk.php
library/Ivoz/Provider/Domain/Model/ProxyTrunk/ProxyTrunkAbstract.php
library/Ivoz/Provider/Domain/Model/ProxyTrunk/ProxyTrunkDto.php
library/Ivoz/Provider/Domain/Model/ProxyTrunk/ProxyTrunkDtoAbstract.php
library/Ivoz/Provider/Domain/Model/ProxyTrunk/ProxyTrunkInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ProxyTrunk.ProxyTrunkAbstract.orm.xml
schema/DoctrineMigrations/Version20240126121409.php
web/portal/platform/src/entities/ProxyTrunk/Form.tsx
web/portal/platform/src/entities/ProxyTrunk/ProxyTrunk.tsx
web/portal/platform/src/entities/ProxyTrunk/ProxyTrunkProperties.ts
web/rest/brand/features/provider/proxyTrunk/getProxyTrunk.feature
web/rest/platform/features/provider/proxyTrunk/getProxyTrunk.feature
web/rest/platform/features/provider/proxyTrunk/postProxyTrunk.feature
web/rest/platform/features/provider/proxyTrunk/putProxyTrunk.feature
web/rest/platform/features/provider/proxyTrunkRelBrand/getProxyTrunkRelBrand.feature
web/rest/platform/features/provider/proxyTrunkRelBrand/postProxyTrunkRelBrand.feature

Add advertised address attribute into ProxyTrunks

Proxy trunks advertised address

---

web/admin/application/configs/klear/FriendsList.yaml
web/admin/application/configs/klear/ResidentialDevicesList.yaml
web/admin/application/configs/klear/RetailAccountsList.yaml
web/admin/application/configs/klear/TerminalsList.yaml

Load custom scripts properly. Some sections like Friends were broken because os this.

Fixed custom scripts paths

---

library/DataFixtures/ORM/ProviderProxyUser.php
web/portal/platform/src/entities/ProxyTrunk/ProxyTrunk.tsx
web/portal/platform/src/entities/ProxyUser/Form.tsx
web/portal/platform/src/entities/ProxyUser/ProxyUser.tsx
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/proxyUser/getProxyUser.feature
web/rest/platform/features/provider/proxyUser/postProxyUser.feature
web/rest/platform/features/provider/proxyUser/putProxyUser.feature
web/rest/platform/features/provider/proxyUser/removeProxyUser.feature

Allow to add multiple proxy users in the UI

Many proxy users

---

web/portal/brand/src/entities/RatingPlanGroup/RatingPlanGroup.tsx
web/portal/package.json
web/portal/yarn.lock

Make rating plan group description not nullable

---

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CompanyDoctrineRepository.php

Removed exceptions thrown by a repository method used in friend write access control checks

Create friend issues [backport]

---

asterisk/agi/composer.lock
library/composer.json
library/composer.lock
microservices/balances/composer.lock
microservices/provision/composer.lock
microservices/recordings/composer.lock
microservices/router/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/user/composer.lock

Upgrade vulnerable dependencies

---

web/portal/user/src/components/Dashboard/ChatBubbleIcon.tsx
web/portal/user/src/components/Dashboard/Dashboard.tsx
web/portal/user/src/components/Dashboard/PhoneForwardedIcon.tsx

Fixed dashboard style issues

---

web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/proxyTrunk/putProxyTrunk.feature

Added some missing backend validation rules that were only being applied in the frontend

enhanced proxy trunks API access control

---

debian/ivozprovider-profile-proxy.postinst

The replace commands in package postinstall use / as separator, that can be a valid character in rtpengine interface settings

Fix configuration replacements in ivozprovider-profile-proxy package

---

library/Ivoz/Kam/Domain/Service/TrunksUacreg/SyncValuesByDdiProvider.php
library/Ivoz/Kam/Domain/Service/TrunksUacreg/UpdateByDdiProvider.php
library/Ivoz/Kam/Domain/Service/TrunksUacreg/UpdateByProxyTrunk.php
library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderRepository.php
library/Ivoz/Provider/Domain/Service/DdiProvider/DdiProviderLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/ProxyTrunk/ProxyTrunkLifecycleServiceCollection.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/DdiProviderDoctrineRepository.php
library/phpstan-baseline.neon
library/spec/Ivoz/Provider/Domain/Service/ProxyTrunk/DeleteProtectionSpec.php

- Fixed kam_trunks_uacreg lifecycles update when modifying proxy trunks
- Fixed minor hints in repository methods

Fix update kam trunks uac reg lifecycle

---

library/Ivoz/Provider/Application/Service/ActiveCall/RegistrationChannelResolver.php
library/Ivoz/Provider/Domain/Service/ActiveCall/AssertAccessGranted.php
web/rest/brand/features/my/activeCalls/getActiveCallsFilters.feature
web/rest/platform/features/my/activeCalls/getActiveCallsFilters.feature

Fixed RegistrationChannelResolver when clients send, ambiguous filtering

Fixed registration channel filters

---

web/portal/brand/src/entities/Carrier/Action/BalanceOperations.tsx

Backport fixing Carrier Balance operations to halliday

Fix carriers balance operations

---

library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrDto.php
web/rest/client/features/provider/usersCdr/getUsersCdr.feature

Ensure brand and company are not exposed in APIs that should not be aware of those fields.

Review UsersCdrs API exposed fields

---

web/rest/brand/CHANGELOG.md
web/rest/client/CHANGELOG.md
web/rest/platform/CHANGELOG.md
web/rest/user/CHANGELOG.md

Update API Changelog for 4.0.0

---

ChangeLog
README.md
asterisk/config/pjsip.conf
doc/sphinx/conf.py
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Changelog with main changes in the first release of 4.x branch

Changelog for 4.0.0 release

---

web/portal/client/src/components/Dashboard/TitleDescription.tsx

Fixed broken link in dashboard

---

debian/rules

Fix ivozprovider-users-cdrs systemd service

---

web/portal/client/src/entities/ExternalCallFilter/ExternalCallFilter.tsx

Removed conflicting visual toggle rules

portal/client: fixed external call filter visualToggle issues

---

web/portal/client/src/entities/ExternalCallFilter/ExternalCallFilter.tsx
web/portal/client/src/entities/ExternalCallFilter/Field/OutOfScheduleEnabled.tsx

portal/client: fixed field name on residential external call filters

---

library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOutDto.php
web/portal/client/src/entities/FaxesInOut/FaxesInOut.tsx
web/portal/client/src/entities/FaxesOut/FaxesOut.tsx
web/rest/client/features/provider/faxesInOut/getFaxesInOut.feature

Add Fax PDF file column to Incoming and Outgoing Faxes

---

web/portal/brand/src/entities/OutgoingRouting/Form.tsx

Fixed carrier value not populated in form

---

ChangeLog
README.md
debian/changelog
web/rest/brand/CHANGELOG.md
web/rest/client/CHANGELOG.md

Update ChangeLog for 4.0.1 release

---

debian/control
debian/ivozprovider-provision.install
debian/ivozprovider-provision.postinst
debian/ivozprovider-provision.preinst

Add new package with provision microservice contents

Add new package ivozprovider-provision

---

doc/sphinx/administration_portal/brand/settings/notification_templates.rst
doc/sphinx/administration_portal/client/residential/index.rst
doc/sphinx/administration_portal/client/residential/residential_devices.rst
doc/sphinx/administration_portal/client/vpbx/ddis.rst
doc/sphinx/administration_portal/client/vpbx/extensions.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/conference_rooms.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/hunt_groups.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/ivrs.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/queues.rst
doc/sphinx/administration_portal/client/vpbx/routing_tools/calendars.rst
doc/sphinx/administration_portal/client/vpbx/routing_tools/external_call_filters.rst
doc/sphinx/administration_portal/client/vpbx/terminals.rst
doc/sphinx/administration_portal/client/vpbx/users.rst
doc/sphinx/administration_portal/client/vpbx/voicemails.rst

Documentation review

---

web/portal/brand/src/i18n.js
web/portal/client/src/i18n.js
web/portal/package.json
web/portal/platform/src/i18n.js
web/portal/user/src/i18n.js
web/portal/yarn.lock

Some translation issues have been reported recently. We suspect it's related to the browser language. This PR aims to address that issue.
This upgrades ivoz-ui to the latest version: https://github.com/irontec/ivoz-ui/pull/103

Translation issues

---

web/portal/brand/src/entities/Invoice/Invoice.tsx

Remove Total and Taxes column in invoice list

Remove Total and Taxes column in invoice list

---

web/portal/brand/src/translations/es.json
web/portal/client/src/translations/es.json
web/portal/platform/src/translations/es.json

Modified Spanish text on portal

---

schema/DoctrineMigrations/Version20240308080459.php
web/portal/client/src/entities/UsersCdr/UsersCdr.tsx

Restricted admin for call register only

---

web/portal/brand/src/components/Dashboard/Dashboard.tsx
web/portal/client/src/components/Dashboard/Dashboard.tsx
web/portal/platform/src/components/Dashboard/Dashboard.tsx
web/portal/user/src/components/Dashboard/Dashboard.tsx

PROVIDER-1687-Chart-colors

---

library/Ivoz/Provider/Domain/Service/Invoice/Generator.php
library/psalm-baseline.xml
web/rest/brand/config/api/raw/provider.yml

Some data like postalAddress was not available in the invoice since that field was moved to Company\Invoicing value object

Invoice data issues

---

web/portal/brand/src/entities/RatingProfile/RatingProfile.tsx

Require RatingProfile.activationTime
showing current date and time in component

portal/brand: showing current date and time in component

---

library/Ivoz/Provider/Domain/Assembler/ResidentialDevice/ResidentialDeviceDtoAssembler.php
library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceDto.php
web/rest/brand/features/provider/residentialDevice/getResidentialDevice.feature
web/rest/client/features/provider/residentialDevices/getResidentialDevice.feature

Serve residential device status in detail API responses so that we can show it properly in the frontend

Residential device issues

---

library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerDto.php
web/portal/brand/src/entities/InvoiceScheduler/Field/LastExecution.tsx
web/portal/brand/src/entities/InvoiceScheduler/InvoiceScheduler.tsx
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json
web/rest/brand/features/provider/invoiceScheduler/getInvoiceScheduler.feature

Show whether the invoice scheduler has succeeded in the list view

Invoice scheduler success feedback

---

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/UserDoctrineRepository.php

Get only 5 user data in dashboard

Get only 5 user data in dashboard

---

web/portal/brand/src/components/Dashboard/Dashboard.tsx
web/portal/client/src/components/Dashboard/Dashboard.tsx
web/portal/platform/src/components/Dashboard/Dashboard.tsx
web/portal/user/src/components/Dashboard/Dashboard.tsx

PROVIDER-1720-Fix-doughnut-colors-dashboard

---

web/portal/brand/src/router/EntityMap.ts
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json

portal/brand: text translation into Spanish in billing block

---

library/Ivoz/Provider/Application/Service/WebPortal/WebThemeFactory.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebTheme.php
web/portal/brand/index.html
web/portal/brand/src/Theme.tsx
web/portal/client/index.html
web/portal/client/src/Theme.tsx
web/portal/platform/index.html
web/portal/platform/src/App.tsx
web/portal/platform/src/Theme.tsx
web/portal/user/src/Theme.tsx
web/rest/brand/features/my/theme/getWebTheme.feature
web/rest/client/features/my/theme/getWebTheme.feature
web/rest/platform/features/my/theme/getWebTheme.feature
web/rest/user/features/my/theme/getWebTheme.feature

Use the page title defined in the theme

Theme based web titles

---

web/portal/brand/src/components/Dashboard/Dashboard.styles.tsx
web/portal/client/src/components/Dashboard/Dashboard.styles.tsx
web/portal/platform/src/components/Dashboard/Dashboard.styles.tsx
web/portal/user/src/components/Dashboard/Dashboard.styles.tsx

Fixed bashboard img position

---

library/Ivoz/Provider/Domain/Model/Voicemail/VoicemailDto.php
library/Ivoz/Provider/Domain/Model/Voicemail/VoicemailRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/VoicemailDoctrineRepository.php
web/rest/user/config/api/raw/provider.yml
web/rest/user/config/routes.yaml
web/rest/user/config/services.yaml
web/rest/user/features/my/voicemail/getVoicemails.feature
web/rest/user/features/provider/voicemail/getVoiceMail.feature
web/rest/user/features/provider/voicemail/putVoiceMail.feature
web/rest/user/features/provider/voicemail_message/deleteVoicemailMessage.feature
web/rest/user/features/provider/voicemail_message/getVoicemailMessage.feature
web/rest/user/phpstan-baseline.neon
web/rest/user/src/Controller/My/VoicemailsAction.php

Add user voicemail and voicemailmessages endpoints

---

web/portal/brand/src/entities/InvoiceNumberSequence/InvoiceNumberSequence.tsx

Invoice Number Sequence - Prefix field should be optional

Invoice Number Sequence - Prefix field should be optional

---

web/portal/platform/src/entities/TerminalModel/Field/GenericTemplate/RunTemplate.tsx
web/portal/platform/src/entities/TerminalModel/Field/SpecificTemplate/RunTemplate.tsx

show buttons correctly in generi and specific template

show buttons correctly in generi and specific template

---

web/portal/brand/src/entities/InvoiceScheduler/InvoiceScheduler.tsx

form data optional mail and mandatory numbering.

Form data optional mail and mandatory numbering

---

web/portal/brand/src/components/ActiveCalls/ActiveCallsTable.tsx
web/portal/client/src/components/ActiveCalls/ActiveCallsTable.tsx
web/portal/platform/src/components/ActiveCalls/ActiveCallsTable.tsx

Change inbound/outbund icon call on table calls

---

web/portal/brand/src/entities/Domain/Domain.tsx
web/portal/brand/src/entities/Domain/DomainSelectOptions.ts
web/portal/client/src/entities/Domain/Domain.tsx
web/portal/client/src/entities/Domain/DomainSelectOptions.ts

Showing data to filter by domain

---

web/portal/brand/src/entities/InvoiceTemplate/InvoiceTemplate.tsx

Show buttons and set them to disabled in invoices template portal/brand

Show buttons and set them to disabled in invoices template

---

web/portal/brand/src/entities/ProxyTrunk/ProxyTrunk.tsx
web/portal/brand/src/entities/ProxyTrunk/ProxyTrunkProperties.ts
web/portal/brand/src/entities/ProxyTrunk/SelectOptions.ts
web/portal/platform/src/entities/ProxyTrunk/ProxyTrunk.tsx
web/portal/platform/src/entities/ProxyTrunk/SelectOptions.ts

Show advertised address instead of IP if present

Proxy trunk advertised address issues

---

ChangeLog
README.md
debian/changelog
web/rest/brand/CHANGELOG.md
web/rest/user/CHANGELOG.md

Main relevant changes in 4.0.3 release

Update ChangeLog for 4.0.3 release

---

library/DataFixtures/ORM/ProviderFaxesInOut.php
web/rest/client/config/api/raw/provider.yml
web/rest/client/config/routes.yaml
web/rest/client/features/provider/faxesInOut/getFaxesInOut.feature
web/rest/client/features/provider/faxesInOut/postFaxesInOut.feature
web/rest/client/features/provider/faxesInOut/postFaxesInOutResend.feature
web/rest/client/src/Controller/Provider/PostFaxResendAction.php
web/rest/client/src/Service/Domain/FaxesInOut/ResendFax.php

Added API endpoint to resend fax with error status

Faxes resend on error option

---

web/portal/brand/src/entities/Carrier/Carrier.tsx
web/portal/package.json
web/portal/yarn.lock

Balance column does not have to be shown if the brand does not have Pricing feature

Hide balance if the brand does not have Pricing feature

---

web/portal/brand/src/entities/Ddi/Ddi.tsx
web/portal/client/src/entities/Ddi/Ddi.tsx

Show DDIE164 as the first column of the listings so that the quick finder is useful

Enhanced DDI columns in portals

---

library/composer.json
library/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.json
web/rest/platform/composer.lock
web/rest/user/composer.lock

Fixes small issue with downloaded file names

Updated ivoz-api-bundle

---

web/rest/brand/features/provider/domain/postDomains.feature
web/rest/brand/features/provider/domain/putDomains.feature
web/rest/brand/features/provider/domain/removeDomains.feature
web/rest/client/features/provider/domain/postDomains.feature
web/rest/client/features/provider/domain/putDomains.feature
web/rest/client/features/provider/domain/removeDomains.feature
web/rest/platform/features/provider/domain/postDomains.feature
web/rest/platform/features/provider/domain/putDomains.feature
web/rest/platform/features/provider/domain/removeDomains.feature

Added API tests for POST, PUT and DELETE

Complete test for domains

---

web/portal/client/src/entities/HolidayDate/Action/AddHolidayDateRange.tsx

Hide Add Holiday date range option if user does not have permissions

---

web/portal/client/src/entities/FaxesOut/Action/Resend.tsx
web/portal/client/src/entities/FaxesOut/Action/index.ts
web/portal/client/src/entities/FaxesOut/FaxesOut.tsx
web/portal/client/src/router/EntityMap.ts
web/portal/client/src/translations/ca.json
web/portal/client/src/translations/en.json
web/portal/client/src/translations/es.json
web/portal/client/src/translations/it.json

Add option to resend fax

---

web/portal/client/src/entities/CallAclRelMatchList/CallAclRelMatchList.tsx

Error when redirecting to call acl rel match lists

---

web/portal/brand/src/entities/DestinationRateGroup/Form.tsx

- [] Small bug fix
configuration to download the imported file

Configuration to download the imported file

---

web/portal/brand/src/entities/TransformationRuleSet/TransformationRuleSet.tsx

Disable edit button instead of hiding it

---

web/portal/platform/src/entities/TerminalModel/Field/SpecificTemplate/RunTemplate.tsx

Show correct content in specific template

---

web/portal/brand/src/entities/Ddi/hooks/useDefaultCountryId.tsx

Fetch country infinite request loop

---

ChangeLog
README.md
debian/changelog
web/rest/client/CHANGELOG.md
web/rest/user/CHANGELOG.md

Main relevant changes in 4.0.4 release

Update ChangeLog for 4.0.4 release

---

web/portal/brand/src/entities/BannedAddress/BannedAddress.tsx
web/rest/brand/config/api/raw/provider.yml

Ordered banned IPs by date (DESC)

Banned address order

---

web/portal/package.json
web/portal/yarn.lock

Search by "+34633" in DDIs for example

Fixed search by special characters

---

web/portal/client/src/entities/Terminal/ForeignKeyResolver.tsx

Avoid SIP domain from getting stalled at loading state

Fixed terminals foreign key resolver race condition

---

library/Ivoz/Provider/Domain/Assembler/Domain/DomainDtoAssembler.php
web/rest/platform/features/provider/domain/getDomains.feature

Brand not shown on sip domains

---

web/portal/brand/src/entities/Currency/Currency.tsx
web/portal/brand/src/entities/Destination/Destination.tsx
web/portal/brand/src/entities/DestinationRateGroup/DestinationRateGroup.tsx
web/portal/brand/src/entities/Feature/Feature.tsx
web/portal/brand/src/entities/PublicEntity/PublicEntity.tsx
web/portal/brand/src/entities/RatingPlanGroup/RatingPlanGroup.tsx
web/portal/brand/src/entities/RoutingPattern/RoutingPattern.tsx

portal/brand: fixed multilanguage issues

---

web/portal/brand/src/entities/OutgoingRouting/Form.tsx
web/portal/brand/src/entities/OutgoingRouting/OutgoingRouting.tsx

Outgoing routing form rework

---

library/DataFixtures/ORM/ProviderCompany.php
library/Ivoz/Provider/Domain/Model/Company/CompanyRepository.php
library/Ivoz/Provider/Domain/Service/ApplicationServer/ApplicationServerLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/ApplicationServer/DeleteProtection.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CompanyDoctrineRepository.php
schema/tests/Provider/ApplicationServer/ApplicationServerLifeCycleTest.php
schema/tests/Provider/Company/CompanyRepositoryTest.php
web/rest/platform/features/provider/applicationServer/removeApplicationServer.feature

Prevented deletion of an application server if it is used by any Company.

Avoid delete referenced application server

---

asterisk/config/sorcery.conf

asterisk: enable sorcery caches for endpoints, aors and identifies

---

asterisk/config/dialplan/click2dial.conf
asterisk/config/dialplan/default.conf
asterisk/config/extensions.conf
debian/ivozprovider-profile-as.postinst
debian/ivozprovider-profile-as.templates

Add new global variable to configure default Dial application options

Asterisk default Dial options

---

library/Ivoz/Provider/Domain/Model/Recording/Recording.php
library/Ivoz/Provider/Domain/Model/Recording/RecordingInterface.php

Ignore Recordings in Changelog

---

Jenkinsfile

ci: improve functional review requirement integration

---

library/Ivoz/Provider/Domain/Model/Voicemail/VoicemailDto.php
library/Ivoz/Provider/Domain/Model/VoicemailRelUser/VoicemailRelUser.php
library/Ivoz/Provider/Domain/Model/VoicemailRelUser/VoicemailRelUserInterface.php
library/Ivoz/Provider/Domain/Model/VoicemailRelUser/VoicemailRelUserRepository.php
library/Ivoz/Provider/Domain/Service/VoicemailRelUser/CheckGenericVoicemail.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/VoicemailRelUserDoctrineRepository.php
web/portal/user/src/entities/Voicemail/Voicemail.tsx
web/rest/user/config/api/raw/provider.yml
web/rest/user/config/services.yaml
web/rest/user/features/my/company_voicemails/getCompanyVoicemails.feature
web/rest/user/features/my/voicemail/getVoicemails.feature
web/rest/user/features/provider/voicemail/getVoiceMail.feature
web/rest/user/features/provider/voicemail/putVoiceMail.feature
web/rest/user/src/Controller/My/VoicemailsAction.php

Show user related voicemails

---

library/Ivoz/Ast/Domain/Model/QueueMember/QueueMemberAbstract.php
library/Ivoz/Ast/Domain/Model/QueueMember/QueueMemberDtoAbstract.php
library/Ivoz/Ast/Domain/Model/QueueMember/QueueMemberInterface.php
library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/QueueMember.QueueMemberAbstract.orm.xml
schema/DoctrineMigrations/Version20240520100114.php

Add reason_paused field to ast_queue_members table to silence a warning in asterisk startup

Add queue members reason pause field

---

asterisk/config/features.conf

asterisk: replace transfer feature codes to avoid collisions

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Make acc module cdr inserts to database in async mode.
[db_insert_mode modparam of ACC module](https://kamailio.org/docs/modules/5.7.x/modules/acc.html#acc.p.db_insert_mode) to 2.

kam: make acc cdr inserts async

---

web/portal/brand/src/entities/ResidentialDevice/ResidentialDevice.tsx
web/portal/brand/src/entities/RetailAccount/RetailAccount.tsx

Fixed breadcumb on client configurations

---

library/DataFixtures/Stub/Provider/VoicemailMessageStub.php
library/Ivoz/Provider/Domain/Model/Voicemail/VoicemailRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/VoicemailDoctrineRepository.php
web/portal/client/src/entities/Voicemail/Voicemail.tsx
web/rest/client/config/api/raw/provider.yml
web/rest/client/config/services.yaml
web/rest/client/features/provider/voicemailMessage/getVoicemailMessage.feature
web/rest/client/features/provider/voicemailMessage/removeVoicemailMessage.feature
web/rest/user/features/provider/voicemail_message/getVoicemailMessage.feature

Client administration access to a user's voicemail messages has been banned.

Limit access to user voicemails in client

---

debian/ivozprovider-web-rest.postinst

Regenerate web/rest caches after upgrade

---

web/portal/package.json
web/portal/yarn.lock

Use datetime-local for date input in the search form

Datetime search UI helper

---

asterisk/agi/src/Dialplan/FaxDial.php
asterisk/agi/src/Dialplan/Friends.php
asterisk/agi/src/Dialplan/Residentials.php
asterisk/agi/src/Dialplan/Retails.php
asterisk/agi/src/Dialplan/Trunks.php
asterisk/agi/src/Dialplan/Users.php
asterisk/config/dialplan/default.conf
asterisk/config/modules.conf
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointAbstract.php
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointDtoAbstract.php
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointInterface.php
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByExtension.php
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByUser.php
library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/PsEndpoint.PsEndpointAbstract.orm.xml
library/spec/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByExtensionSpec.php
schema/DoctrineMigrations/Version20240527071749.php
schema/tests/Provider/Extension/ExtensionLifeCycleTest.php

This is part of a new set of enhancements to optimize call process for high load environments.
This agi was being called for each outbound call and some scenarios, like ringall Huntgroups, can generate a lot of calls at the same time, spawning a PHP for each of them.

Replace Headers AGI with diaplan functions

---

asterisk/agi/src/Agi/Action/HuntGroupAction.php
asterisk/agi/src/Agi/Action/HuntGroupStatusAction.php
asterisk/config/dialplan/default.conf
library/Ivoz/Provider/Domain/Model/HuntGroup/HuntGroup.php
library/Ivoz/Provider/Domain/Model/HuntGroup/HuntGroupInterface.php
tests/bbs/2405-test-huntgroup-all-complex.yaml
tests/bbs/2415-test-huntgroup-rr-complex.yaml
tests/bbs/dataset.json

Add vPBX logics to handle simple huntgroups without using Local channels

Simple Hunt Groups support

---

library/DataFixtures/ORM/ProviderFriend.php
library/Ivoz/Provider/Domain/Model/Friend/Friend.php
library/Ivoz/Provider/Domain/Model/Friend/FriendAbstract.php
library/Ivoz/Provider/Domain/Model/Friend/FriendDto.php
library/Ivoz/Provider/Domain/Model/Friend/FriendDtoAbstract.php
library/Ivoz/Provider/Domain/Model/Friend/FriendInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Friend.Friend.orm.xml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Friend.FriendAbstract.orm.xml
library/psalm-baseline.xml
library/spec/Ivoz/Provider/Domain/Model/Friend/FriendSpec.php
schema/DoctrineMigrations/Version20240527074431.php
schema/tests/Provider/Friend/FriendLifeCycleTest.php
web/portal/brand/src/entities/Friend/Form.tsx
web/portal/brand/src/entities/Friend/Friend.tsx
web/portal/brand/src/entities/Friend/FriendProperties.ts
web/rest/brand/features/provider/friend/getFriend.feature
web/rest/brand/features/provider/friend/postFriend.feature
web/rest/brand/features/provider/friend/putFriend.feature

Added proxyUser field to Friends in Brand portal.

Direct connectivity friends must have proxy user

---

debian/Dockerfile
debian/control

Update Debian packaging dockerfile with a version that auto-resolves dependencies based on debian/control using pbuilder scripts

pkg: update debian packaging Dockerfile

---

web/portal/user/.eslintrc.js
web/portal/user/src/App.tsx
web/portal/user/src/components/Header/useTerminalStatus.ts
web/portal/user/src/router/EntityMap.tsx
web/portal/user/src/router/addCustomRoutes.ts
web/portal/user/src/router/useEntityMap.ts
web/portal/user/src/router/useFeatureFilteredEntityMap.tsx
web/portal/user/src/store/index.ts
web/portal/user/src/store/userStatus/index.ts
web/portal/user/src/store/userStatus/status.ts
web/rest/user/features/my/status/getStatus.feature
web/rest/user/src/Controller/My/StatusAction.php
web/rest/user/src/Model/UserStatus.php

Hide faxes section when unavailable

---

Jenkinsfile

ci: add packaging testing stage to pipeline

---

library/composer.json
library/composer.lock
web/rest/platform/features/querystringFilters.feature

Handle timezone conversion of partial date time strings

---

debian/control

Add missing dependency on  ivozprovider-web-rest that was being pulled only by ivozprovider-web-admin (removed in #2670)

pkg: add missing dependency on ivozprovider-web-rest

---

web/portal/client/src/entities/Ddi/Form.tsx

Unskipped faxes from residential and vpbx clients

Unskipped faxes from residential and vpbx clients

---

microservices/scheduler/bin/run-billable-calls-historic

microservice scheduler-historic-calls fails on start up

---

web/portal/client/src/entities/HolidayDate/Field/Target.tsx

Fixed target value when is of type number

Fixed target value when is of type number

---

web/portal/client/src/entities/HolidayDate/Action/Import.tsx

Hide import holidays from rows

Hide Import CSV from Holiday rows

---

web/portal/brand/src/entities/TransformationRule/TransformationRule.tsx
web/portal/brand/src/entities/TransformationRuleSet/TransformationRuleSet.tsx
web/portal/package.json
web/portal/yarn.lock

Removed extra edition icon

---

ChangeLog
README.md
asterisk/config/pjsip.conf
debian/changelog
doc/sphinx/conf.py
extra/simple-cdd/package.list
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
web/rest/brand/CHANGELOG.md
web/rest/client/CHANGELOG.md
web/rest/platform/CHANGELOG.md
web/rest/user/CHANGELOG.md

doc: update ChangeLog for 4.1.0

---

library/Ivoz/Provider/Domain/Model/WebPortal/WebPortal.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalAbstract.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalDtoAbstract.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/WebPortal.WebPortalAbstract.orm.xml
library/psalm-baseline.xml
schema/DoctrineMigrations/Version20240627075829.php
web/portal/brand/src/entities/CallCsvScheduler/Form.tsx
web/portal/brand/src/entities/WebPortal/ForeignKeyGetter.tsx
web/portal/brand/src/entities/WebPortal/Form.tsx
web/portal/brand/src/entities/WebPortal/WebPortal.tsx
web/portal/brand/src/entities/WebPortal/WebPortalProperties.ts
web/portal/brand/src/entities/WebPortal/hooks/useCompany.tsx
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json
web/rest/brand/features/provider/webPortal/postWebPortal.feature
web/rest/brand/features/provider/webPortal/putWebPortal.feature
web/rest/platform/features/provider/webPortal/postWebPortal.feature
web/rest/platform/features/provider/webPortal/putWebPortal.feature

Binding portals to one client

---

Jenkinsfile
tests/docker/Dockerfile
tests/docker/bin/prepare-and-run
tests/docker/bin/prepare-node-modules

Decrease image size by grouping run commands to minize layers

ci: optimize testing Dockerfile commands

---

library/bin/test-commit-tags

Update commit tags test to only allow exact documented tags

---

web/portal/brand/cypress/e2e/Language/Language.cy.js
web/portal/brand/src/i18n.js
web/portal/client/cypress/e2e/Language/Language.cy.js
web/portal/client/src/i18n.js
web/portal/platform/cypress/e2e/Language/Language.cy.js
web/portal/platform/src/i18n.js

- Removed a bug that only allows English language
- Introduce new cypress tests to ensure language switching

Fix portal default languages

---

library/DataFixtures/Stub/Provider/RecordingStub.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiDtoAbstract.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiInterface.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiTrait.php
library/Ivoz/Provider/Domain/Model/Recording/RecordingAbstract.php
library/Ivoz/Provider/Domain/Model/Recording/RecordingDtoAbstract.php
library/Ivoz/Provider/Domain/Model/Recording/RecordingInterface.php
library/Ivoz/Provider/Domain/Model/User/UserDtoAbstract.php
library/Ivoz/Provider/Domain/Model/User/UserInterface.php
library/Ivoz/Provider/Domain/Model/User/UserTrait.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Ddi.Ddi.orm.xml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Recording.RecordingAbstract.orm.xml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/User.User.orm.xml
library/psalm-baseline.xml
schema/DoctrineMigrations/Version20240726184847.php
schema/tests/Provider/Company/CompanySoftDeleteTest.php
web/rest/client/features/provider/recording/getRecording.feature

Add fields to recordings

---

library/DataFixtures/ORM/ProviderWebPortal.php
library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalDto.php
schema/tests/Provider/Brand/BrandSoftDeleteTest.php
web/portal/brand/cypress/fixtures/apiSpec.json
web/portal/brand/src/entities/WebPortal/WebPortal.tsx
web/rest/brand/features/provider/webPortal/getWebPortal.feature
web/rest/brand/features/provider/webPortal/postWebPortal.feature
web/rest/platform/features/provider/webPortal/postWebPortal.feature

Show company on user list

---

microservices/recordings/src/Service/Encoder.php

Added logic in recordings microservice for setting user or ddi for new records.
- [x ] New feature or enhancement

Store ddi or user in recordings

---

Jenkinsfile

Small typo was preventing Backend tests to run on microservices/* commits

Run backend tests on microservices commits

---

Jenkinsfile

Cypress tests depend on API spec, so they should be run when API have changes

Force frontend tests when API rest has been updated

---

asterisk/config/dialplan/faxes.conf

asterisk: fix add headers gosub for outgoing faxes

---

web/rest/client/config/api/raw/provider.yml

rest/client: Fixed order in the recordings

---

web/portal/client/cypress/e2e/Recording/Recording.cy.js
web/portal/client/cypress/fixtures/Recording/getCollection.json
web/portal/client/cypress/fixtures/Recording/getItem.json
web/portal/client/cypress/pacts/client-provider-Recording-client-consumer-Recording.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js
web/portal/client/src/entities/Ddi/Ddi.tsx
web/portal/client/src/entities/Recording/View.tsx
web/portal/client/src/router/EntityMap.ts

Add records to ddi client section

---

library/DataFixtures/ORM/ProviderAdministrator.php
library/DataFixtures/ORM/ProviderCompany.php
library/Ivoz/Provider/Domain/Service/Administrator/AdminLoginChecker.php
library/Ivoz/Provider/Domain/Service/Administrator/AssertWebPortalAccessible.php
library/Ivoz/Provider/Domain/Service/HostnameGetter.php
library/Ivoz/Provider/Domain/Service/User/AssertWebPortalAccessible.php
library/Ivoz/Provider/Domain/Service/User/UserLoginChecker.php
library/Ivoz/Provider/Infrastructure/Hostname/GetHostname.php
library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/services/infraestructure/rest.yml
library/composer-packages/irontec/ivoz-provider-bundle/composer.json
library/composer.lock
schema/tests/Provider/Brand/BrandSoftDeleteTest.php
schema/tests/Provider/Company/CompanyRepositoryTest.php
schema/tests/Provider/Company/CompanySoftDeleteTest.php
web/rest/brand/features/my/activeCalls/getActiveCalls.feature
web/rest/brand/features/my/dashboard/getDashboard.feature
web/rest/brand/features/provider/administrator/getAdministrators.feature
web/rest/brand/features/provider/company/getCompanies.feature
web/rest/brand/features/provider/company/postCompanies.feature
web/rest/brand/features/provider/webPortal/putWebPortal.feature
web/rest/platform/features/provider/company/getCompany.feature

Implemented login checks to restrict access using the WebPortal URL assigned to a company or brand, ensuring it is relevant to the user or admin.

Check access permissions to WebPortals host

---

web/portal/client/src/entities/Recording/Recording.tsx

Hide column on ddis/recordings

---

web/portal/client/cypress/e2e/Ddi/BillableCalls/BillableCalls.cy.js
web/portal/client/cypress/e2e/HuntGroup/HuntGroupMember/HuntGroupMember.cy.js
web/portal/client/cypress/e2e/User/HuntGroups/HuntGroups.cy.js
web/portal/client/cypress/fixtures/BillableCall/getCollection.json
web/portal/client/cypress/fixtures/BillableCall/getItem.json
web/portal/client/cypress/fixtures/Users/getHuntGroupMemebersCollection.json
web/portal/client/cypress/fixtures/Users/getItem.json
web/portal/client/cypress/pacts/client-provider-Ddi-client-consumer-Ddi.json
web/portal/client/cypress/pacts/client-provider-User-HuntGroup-client-consumer-User-HuntGroup.json
web/portal/client/cypress/pacts/client-provider-User-client-consumer-User.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js

Add cypress tests to users terminals extensions ddis

---

web/portal/user/cypress/e2e/Recording/Recording.cy.ts
web/portal/user/cypress/fixtures/Recording/getCollection.json
web/portal/user/cypress/fixtures/Recording/getItem.json
web/portal/user/cypress/fixtures/apiSpec.json
web/portal/user/cypress/pacts/user-provider-User-Recording-user-consumer-User-Recording.json
web/portal/user/cypress/support/commands/prepareGenericPactInterceptors.ts
web/portal/user/src/entities/Recording/Recording.tsx
web/portal/user/src/entities/Recording/RecordingProperties.tsx
web/portal/user/src/entities/Recording/View.tsx
web/portal/user/src/router/EntityMap.tsx
web/portal/user/src/translations/ca.json
web/portal/user/src/translations/en.json
web/portal/user/src/translations/es.json
web/portal/user/src/translations/it.json
web/rest/user/config/api/raw/provider.yml
web/rest/user/config/routes.yaml
web/rest/user/config/services.yaml
web/rest/user/features/provider/recording/getRecording.feature
web/rest/user/features/provider/recording/getRecordingZipFiles.feature
web/rest/user/features/provider/recording/removeRecording.feature
web/rest/user/src/Controller/Provider/RecordedFilesZipAction.php

Recordings in user portal

---

library/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateByTrunksCdr.php
library/Ivoz/Provider/Domain/Service/UsersCdr/MigrateFromKamUsersCdr.php
library/phpstan-baseline.neon
microservices/recordings/src/Service/Encoder.php

Duration with excesive precission

---

web/portal/brand/cypress/e2e/Clients/Residential/Residentials.cy.js
web/portal/brand/cypress/e2e/Clients/Residential/Residentials.tests.js
web/portal/brand/cypress/e2e/Clients/Retails/Retails.cy.js
web/portal/brand/cypress/e2e/Clients/Retails/Retails.tests.js
web/portal/brand/cypress/e2e/Clients/VirtualPbxs/VirtualPbxs.cy.js
web/portal/brand/cypress/e2e/Clients/VirtualPbxs/VirtualPbxs.tests.js
web/portal/brand/cypress/e2e/WebPortals/WebPortals.cy.js
web/portal/brand/cypress/e2e/WebPortals/WebPortals.tests.js
web/portal/brand/cypress/fixtures/Provider/WebPortals/getCollection.json
web/portal/brand/cypress/fixtures/Provider/WebPortals/getItem.json
web/portal/brand/cypress/fixtures/Provider/WebPortals/post.json
web/portal/brand/cypress/fixtures/Provider/WebPortals/put.json
web/portal/brand/cypress/pacts/brand-provider-WebPortals-brand-consumer-WebPortals.json
web/portal/brand/cypress/support/commands/prepareGenericPactInterceptors.js
web/portal/brand/src/entities/WebPortal/Form.tsx
web/portal/brand/src/router/EntityMap.ts

Added WebPortal children to each client type

---

web/portal/client/cypress/e2e/Calendar/HolidayDate/HolidayDate.cy.js
web/portal/client/cypress/e2e/Calendar/HolidayDateRange/HolidayDateRange.cy.js
web/portal/client/cypress/e2e/MatchList/MatchListPattern/MatchListPattern.cy.js
web/portal/client/cypress/fixtures/HolidayDate/getCollection.json
web/portal/client/cypress/fixtures/HolidayDate/getItem.json
web/portal/client/cypress/fixtures/HolidayDate/massImport.csv
web/portal/client/cypress/fixtures/HolidayDate/post.json
web/portal/client/cypress/fixtures/HolidayDate/postHolidayDateRange.json
web/portal/client/cypress/fixtures/HolidayDate/put.json
web/portal/client/cypress/fixtures/MatchList/post.json
web/portal/client/cypress/fixtures/MatchListPattern/getCollection.json
web/portal/client/cypress/fixtures/MatchListPattern/getItem.json
web/portal/client/cypress/fixtures/MatchListPattern/post.json
web/portal/client/cypress/fixtures/MatchListPattern/put.json
web/portal/client/cypress/pacts/client-provider-MatchList-client-consumer-MatchList.json
web/portal/client/cypress/pacts/client-provider-RoutingTools-HolidayDate-client-consumer-RoutingTools-HolidayDate.json
web/portal/client/cypress/pacts/client-provider-RoutingTools-HolidayDateRange-client-consumer-RoutingTools-HolidayDateRange.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js
web/portal/client/cypress/support/commands/uploadFile.js
web/portal/client/cypress/support/e2e.js

add Cypress Testing for Routing Tools

portal/client: add Cypress Testing for Routing Tools

---

web/portal/brand/src/entities/Invoice/Invoice.tsx
web/portal/package.json
web/portal/yarn.lock

Download the PDF file from the list

Download the PDF file from the list

---

web/portal/client/cypress/e2e/Dashboard/Dashboard.cy.js
web/portal/client/cypress/fixtures/My/Dashboard/getDashboard.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js

Updated cypress tests fro client dashboard

---

web/portal/client/cypress/fixtures/apiSpec.json
web/rest/client/config/api/resources.yml

Fixed documentation for /my/active_calls/realtime_filter client endpoint

Bug apispec client

---

web/portal/client/cypress/e2e/CallAcl/CallAclRelMatchList/CallAclRelMatchList.cy.js
web/portal/client/cypress/e2e/OutgoingDdiRule/OutgoingDdiRulePatterns/OutgoingDdiRulePatterns.cy.js
web/portal/client/cypress/fixtures/CallAclRelMatchList/getCollection.json
web/portal/client/cypress/fixtures/CallAclRelMatchList/getItem.json
web/portal/client/cypress/fixtures/CallAclRelMatchList/post.json
web/portal/client/cypress/fixtures/CallAclRelMatchList/put.json
web/portal/client/cypress/fixtures/OutgoingDdiRulePatterns/getCollection.json
web/portal/client/cypress/fixtures/OutgoingDdiRulePatterns/getItem.json
web/portal/client/cypress/fixtures/OutgoingDdiRulePatterns/post.json
web/portal/client/cypress/fixtures/OutgoingDdiRulePatterns/put.json
web/portal/client/cypress/pacts/client-provider-CallAcl-CallAclRelMatchList-client-consumer-CallAcl-CallAclRelMatchList.json
web/portal/client/cypress/pacts/client-provider-OutgoingDdiRule-OutgoingDdiRulePatterns-client-consumer-OutgoingDdiRule-OutgoingDdiRulePatterns.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js

Added cypress tests for User configuration section

User configuration block e2e tests

---

web/portal/brand/cypress/e2e/NotificationTemplate/NotificationTemplateWithoutBilling.cy.js
web/portal/brand/cypress/e2e/NotificationTemplate/NotificationTemplateWithoutInvoice.cy.js
web/portal/brand/cypress/e2e/NotificationTemplate/NotificationTemplateWithoutVpbxAndResidential.cy.js
web/portal/brand/cypress/fixtures/Provider/NotificationTemplates/getItem.json
web/portal/brand/cypress/fixtures/Provider/NotificationTemplates/post.json
web/portal/brand/cypress/fixtures/Provider/NotificationTemplates/put.json
web/portal/brand/cypress/support/commands/prepareGenericPactInterceptors.js
web/portal/brand/src/entities/NotificationTemplate/Form.tsx

Filter notification types based on enabled features

Portal brand notification templates filter notification types based on enabled features

---

web/portal/brand/src/entities/SpecialNumber/SpecialNumber.tsx

Disabled edit and delete buttons

---

web/portal/brand/src/entities/Invoice/Form.tsx

Order invoice creation form

---

web/portal/client/src/entities/Fax/Fax.tsx

Change the default email option to no

Change the default email option to no

---

web/portal/brand/src/entities/CallCsvScheduler/CallCsvScheduler.tsx
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json

Fix various issues in Csv Scheduler

---

library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallAbstract.php
library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallDtoAbstract.php
library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallInterface.php
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrAbstract.php
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrDtoAbstract.php
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.xml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.xml
library/phpstan-baseline.neon
library/psalm-baseline.xml
library/spec/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateByTrunksCdrSpec.php
library/spec/Ivoz/Provider/Domain/Service/BillableCall/UpdateByTpCdrSpec.php
library/spec/Ivoz/Provider/Domain/Service/BillableCall/UpdateDtoByDefaultRunTpCdrSpec.php
schema/DoctrineMigrations/Version20240826105439.php
web/portal/brand/cypress/fixtures/apiSpec.json
web/portal/client/cypress/fixtures/apiSpec.json
web/portal/platform/cypress/fixtures/apiSpec.json
web/portal/user/cypress/fixtures/apiSpec.json

alter schema start time userscdr billablecalls

---

library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallRepository.php
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/UsersCdrDoctrineRepository.php
microservices/recordings/phpstan-baseline.neon
microservices/recordings/psalm-baseline.xml
microservices/recordings/src/Service/Encoder.php

Replaced use of TrunksCrd with BillableCalls

Use provider entities on recordings microservice

---

web/portal/brand/cypress/e2e/Administrator/Administrator.tests.js
web/portal/client/cypress/e2e/Ddi/Ddi.cy.js
web/portal/client/cypress/e2e/Fax/Fax.cy.js
web/portal/client/cypress/e2e/Fax/FaxIn/FaxIn.cy.js
web/portal/client/cypress/e2e/Friend/CallForwardSettings/CallForwardSettings.cy.js
web/portal/client/cypress/e2e/Friend/Friend.cy.js
web/portal/client/cypress/e2e/Recording/Recording.cy.js
web/portal/client/cypress/e2e/User/HuntGroups/HuntGroups.cy.js
web/portal/client/cypress/e2e/User/User.cy.js
web/portal/client/cypress/fixtures/Company/getCollection.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js
web/portal/package.json
web/portal/yarn.lock

Upgraded ivoz-ui to version 1.4.6 fixing an issue with action icons

Fixed action icons per row

---

web/portal/package.json
web/portal/yarn.lock

portal: update ivoz-ui

---

doc/dev/AcceptedCommitTagsList.txt
docker-compose.yml
docker/backend/060-ivozprovider-api.conf
docker/backend/Dockerfile
docker/backend/start.sh
docker/backend/xdebug.ini
docker/mariadb/Dockerfile
docker/mariadb/initial.sql
docker/portal/Dockerfile
docker/portal/start.sh
docker/redis/Dockerfile
docker/redis/redis.conf
docker/redis/sentinel.conf
docker/redis/supervisord.conf
web/portal/brand/vite.config.ts
web/portal/client/vite.config.ts
web/portal/platform/vite.config.ts
web/portal/user/vite.config.ts

This PR includes requires files to generate containers for mysql, redis, rest APIs and web portals using a docker-compose file.

Initial docker-compose support for development containers

---

web/portal/client/cypress/e2e/Calendar/HolidayDate/HolidayDate.cy.js
web/portal/scripts/test-pact

Fix Holidays Date import cypress test

---

web/portal/client/cypress/e2e/Calls/ActiveCalls.cy.js
web/portal/client/cypress/e2e/Calls/BillableCalls.cy.js
web/portal/client/cypress/e2e/Calls/Recordings.cy.js
web/portal/client/cypress/e2e/Calls/UsersCdrs.cy.js
web/portal/client/cypress/fixtures/UsersCdrs/getCollection.json
web/portal/client/cypress/pacts/client-provider-UsersCdrs-client-consumer-UsersCdrs.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js

cypress client calls block

---

web/portal/client/cypress/e2e/Dashboard/RetailDashboard.cy.js
web/portal/client/cypress/fixtures/My/Profile/getRetailProfile.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js

Added e2e testing for retail accounts at the client portal

Updated dashboard tests for retail account

---

web/portal/brand/vite.config.ts
web/portal/client/vite.config.ts
web/portal/platform/vite.config.ts
web/portal/user/vite.config.ts

Fix vite configuration

---

web/portal/client/cypress/e2e/RetailAccount/CallForwardSetting/CallForwardSetting.cy.js
web/portal/client/cypress/e2e/RetailAccount/Ddi/Ddi.cy.js
web/portal/client/cypress/e2e/RetailAccount/RetailAccount.cy.js
web/portal/client/cypress/fixtures/My/Profile/getProfileRetail.json
web/portal/client/cypress/fixtures/RetailAccount/getItem.json
web/portal/client/cypress/fixtures/RetailAccount/post.json
web/portal/client/cypress/fixtures/RetailAccount/put.json
web/portal/client/cypress/pacts/client-provider-Retail-Accounts-CallForwardSetting-client-consumer-Retail-Accounts-CallForwardSetting.json
web/portal/client/cypress/pacts/client-provider-Retail-Accounts-Ddi-client-consumer-Retail-Accounts-Ddi.json
web/portal/client/cypress/pacts/client-provider-Retail-Accounts-client-consumer-Retail-Accounts.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js

Retail Accounts and DDI

---

library/Ivoz/Provider/Domain/Model/Voicemail/VoicemailRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/VoicemailDoctrineRepository.php
web/portal/client/src/entities/Voicemail/Voicemail.tsx
web/portal/user/cypress/fixtures/apiSpec.json
web/portal/user/src/entities/Voicemail/Voicemail.tsx
web/rest/user/config/api/raw/provider.yml
web/rest/user/src/Controller/My/VoicemailsAction.php

Sort list in the Voicemail section in the Vpbx client

---

web/portal/brand/cypress/e2e/Clients/Residential/Administrator/Administrator.cy.js
web/portal/brand/cypress/e2e/Clients/Retails/Administrator/Administrator.cy.js
web/portal/brand/cypress/e2e/Clients/VirtualPbxs/Administrator/Administrator.cy.js
web/portal/brand/cypress/e2e/Clients/VirtualPbxs/VirtualPbxs.cy.js
web/portal/brand/cypress/pacts/brand-provider-residential-client-administrator-brand-consumer-residential-client-administrator.json
web/portal/brand/cypress/pacts/brand-provider-retail-client-administrator-brand-consumer-retail-client-administrator.json
web/portal/brand/src/entities/Administrator/Action/Impersonate.tsx
web/portal/brand/src/entities/Company/Action/Impersonate.tsx
web/portal/platform/src/entities/Administrator/Action/Impersonate.tsx
web/portal/platform/src/entities/Brand/Action/Impersonate.tsx

Enable or disable the Impersonate feature

---

web/portal/package.json
web/portal/yarn.lock

Upgraded ivoz-ui dependencies

---

web/portal/user/cypress/e2e/Fax/Fax.cy.js
web/portal/user/cypress/e2e/Fax/FaxIn/FaxIn.cy.js
web/portal/user/cypress/e2e/Fax/FaxOut/FaxOut.cy.js
web/portal/user/cypress/e2e/Voicemail/Voicemail.cy.js
web/portal/user/cypress/e2e/Voicemail/VoicemailMessage/VoicemailMessage.cy.js
web/portal/user/cypress/fixtures/Fax/getCollection.json
web/portal/user/cypress/fixtures/Fax/getItem.json
web/portal/user/cypress/fixtures/Fax/post.json
web/portal/user/cypress/fixtures/Fax/put.json
web/portal/user/cypress/fixtures/FaxInOut/getCollection.json
web/portal/user/cypress/fixtures/FaxInOut/getItem.json
web/portal/user/cypress/fixtures/FaxInOut/post.json
web/portal/user/cypress/fixtures/FaxInOut/put.json
web/portal/user/cypress/fixtures/VoicemailMessage/getCollection.json
web/portal/user/cypress/pacts/user-provider-Fax-Incomingfaxfiles-user-consumer-Fax-Incomingfaxfiles.json
web/portal/user/cypress/pacts/user-provider-Fax-OutgoingFaxfiles-user-consumer-Fax-OutgoingFaxfiles.json
web/portal/user/cypress/pacts/user-provider-Voicemail-VoicemailMessage-user-consumer-Voicemail-VoicemailMessage.json
web/portal/user/cypress/pacts/user-provider-Voicemail-user-consumer-Voicemail.json
web/portal/user/cypress/support/commands/prepareGenericPactInterceptors.ts

Testing section voicemail and fax

---

web/portal/user/cypress/e2e/Calls/Calls.cy.ts
web/portal/user/cypress/pacts/user-provider-User-Calls-user-consumer-User-Calls.json

portal/user: call test section

---

web/portal/brand/src/entities/Company/List.tsx

Hide brand price profiles

---

web/portal/brand/cypress/e2e/Dashboard/Dashboard.cy.js
web/portal/brand/cypress/fixtures/My/Dashboard/getDashboard.json
web/portal/brand/cypress/fixtures/Provider/ProxyTrunks/getCollection.json
web/portal/brand/cypress/support/commands/prepareGenericPactInterceptors.js

Added Dashboard cy tests

---

web/portal/.gitignore
web/portal/client/.gitignore
web/portal/client/cypress/e2e/Recording/Recording.cy.js
web/portal/client/src/entities/Recording/Action/Download.tsx
web/portal/client/src/entities/Recording/Action/index.ts
web/portal/client/src/entities/Recording/Recording.tsx
web/portal/client/src/translations/ca.json
web/portal/client/src/translations/en.json
web/portal/client/src/translations/es.json
web/portal/client/src/translations/it.json
web/portal/user/cypress/e2e/Recording/Recording.cy.ts
web/portal/user/src/entities/FaxesOut/Form.tsx
web/portal/user/src/entities/Recording/Action/Download.tsx
web/portal/user/src/entities/Recording/Action/index.ts
web/portal/user/src/entities/Recording/Recording.tsx
web/portal/user/src/translations/ca.json
web/portal/user/src/translations/en.json
web/portal/user/src/translations/es.json
web/portal/user/src/translations/it.json

Multiple recording file download for portal user and client

Download multiple recording files

---

web/portal/platform/src/entities/MediaRelaySet/MediaRelaySet.tsx

Show disabled buttons for media relay set

---

library/Ivoz/Provider/Domain/Service/MediaRelaySet/DeleteProtection.php
library/Ivoz/Provider/Domain/Service/MediaRelaySet/MediaRelaySetEventHandlerInterface.php
library/Ivoz/Provider/Domain/Service/MediaRelaySet/MediaRelaySetLifecycleServiceCollection.php
library/psalm-baseline.xml
schema/tests/Provider/MediaRelaySet/MediaRelaySetRepositoryTest.php
web/rest/platform/features/provider/mediaRelaySet/removeMediaRelaySet.feature

Avoid deleting default media relay set

---

web/portal/client/cypress/e2e/Dashboard/ResidentialDashboard.cy.js
web/portal/client/cypress/fixtures/My/Dashboard/getResidentialDashboard.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js

Updated cypress tests

---

web/portal/client/cypress/e2e/Dashboard/ResidentialDashboard.cy.js
web/portal/client/cypress/e2e/Dashboard/RetailDashboard.cy.js
web/portal/client/cypress/e2e/Dashboard/WholesaleDashboard.cy.js
web/portal/client/cypress/fixtures/My/Dashboard/getWholesaleDashboard.json
web/portal/client/cypress/fixtures/My/Profile/getWholesaleProfile.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js

Added wholesale dashboard cypress support

---

library/Ivoz/Provider/Domain/Model/Terminal/TerminalDto.php
web/portal/client/src/entities/RetailAccount/Field/Status.tsx
web/rest/brand/features/provider/terminal/getTerminalStatus.feature
web/rest/client/features/provider/terminal/getTerminal.feature
web/rest/client/features/provider/terminal/getTerminalStatus.feature

- Updated TerminalDto to resolve publicContact
-  Fixed regex in Status Icon

Hint sip alg terminales broken

---

web/portal/client/cypress/e2e/Ddi/ResidentialDdi/BillableCalls/BillableCalls.cy.js
web/portal/client/cypress/e2e/Ddi/ResidentialDdi/Ddi.cy.js
web/portal/client/cypress/e2e/ExternalCallFilter/ExternalCallFilterResidential/ExternalCallFilter.cy.js
web/portal/client/cypress/e2e/MatchList/ResidentialMatchList/MatchList.cy.js
web/portal/client/cypress/fixtures/Ddi/getItemResidential.json
web/portal/client/cypress/fixtures/Ddi/getResidentialCollection.json
web/portal/client/cypress/fixtures/Ddi/putResidential.json
web/portal/client/cypress/pacts/client-provider-Ddi-Residential-client-consumer-Ddi-Residential.json
web/portal/client/cypress/pacts/client-provider-ExternalCallFilter-Residential-client-consumer-ExternalCallFilter-Residential.json
web/portal/client/cypress/pacts/client-provider-MatchList-Residential-client-consumer-MatchList-Residential.json

Residential Client Testing 

---

web/portal/client/cypress/e2e/Invoice/Invoice.cy.js
web/portal/client/cypress/e2e/RatingProfile/RatingProfile.cy.js
web/portal/client/cypress/e2e/RatingProfile/SimulateCall/SimulateCall.cy.js
web/portal/client/cypress/fixtures/Invoices/getCollection.json
web/portal/client/cypress/fixtures/RatingPlanGroup/getCollection.json
web/portal/client/cypress/fixtures/RatingProfiles/getCollection.json
web/portal/client/cypress/fixtures/RoutingTag/getCollection.json
web/portal/client/cypress/pacts/client-provider-RatingProfiles-client-consumer-RatingProfiles.json
web/portal/client/cypress/support/commands/prepareGenericPactInterceptors.js

Add cypress tests for billing section

---

microservices/balances/src/Controller/Sync.php

Added daily usage sync to microservices/balance

---

web/portal/brand/src/entities/CallCsvScheduler/CallCsvScheduler.tsx

CSV call scheduler must enforce to select one specific endpoint (user/fax/friend/residentialDevice) once Endpoint Type has been chosen.

portal/brand: enforce CSV call scheduler specific endpoint

---

scripts/update-package-version.sh
scripts/update-version.sh

Added an script to update debian/changelog taking into consideration the format X.X~Y.Y.Y with ivozprovider and software version.

Add scripts for updating Debian package version

---

web/portal/client/src/entities/Contact/Form.tsx

Disabled edit button for contacts with non-null userId

---

Jenkinsfile

Moved where Jira custom fields are populated to a new stage

Populate Jira branch custom field from pipeline

---

library/Ivoz/Provider/Domain/Service/MediaRelaySet/DeleteProtection.php
library/Ivoz/Provider/Domain/Service/MediaRelaySet/MediaRelaySetLifecycleEventHandlerInterface.php
library/Ivoz/Provider/Domain/Service/MediaRelaySet/MediaRelaySetLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/MediaRelaySet/SendTrunksRtpengineReloadRequest.php
library/Ivoz/Provider/Domain/Service/MediaRelaySet/SendUsersRtpengineReloadRequest.php
library/spec/Ivoz/Provider/Domain/Service/MediaRelaySet/SendTrunksRtpengineReloadRequestSpec.php
library/spec/Ivoz/Provider/Domain/Service/MediaRelaySet/SendUsersRtpengineReloadRequestSpec.php
schema/tests/Provider/MediaRelaySet/MediaRelaySetLifecycleTest.php

Reload rtpengine after media relay set delete

---

Jenkinsfile
doc/dev/AcceptedCommitTagsList.txt

Pipeline mergeability tests

---

web/portal/brand/cypress/fixtures/apiSpec.json

portal/brand: Updated apiSpec

---

web/portal/user/src/entities/UsersCdr/UsersCdr.tsx

portal/user: Hide owner column in call log

---

library/Ivoz/Provider/Domain/Model/Carrier/CarrierAbstract.php
library/Ivoz/Provider/Domain/Model/Carrier/CarrierInterface.php
library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderAbstract.php
library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderDto.php
library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Carrier.CarrierAbstract.orm.xml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/DdiProvider.DdiProviderAbstract.orm.xml
library/psalm-baseline.xml
schema/DoctrineMigrations/Version20241219145458.php
web/portal/brand/cypress/fixtures/apiSpec.json
web/portal/brand/src/entities/Carrier/Carrier.tsx
web/portal/brand/src/entities/DdiProvider/DdiProvider.tsx
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json
web/rest/brand/config/api/raw/provider.yml
web/rest/brand/features/provider/carrier/postCarrier.feature
web/rest/brand/features/provider/ddiProvider/postDdiProvider.feature

Use company's mediaRelaySets in Carrier and DdiProvider

---

library/Ivoz/Kam/Domain/Service/Dispatcher/UpdateByApplicationServerSetRelApplicationServer.php
library/Ivoz/Provider/Domain/Assembler/ApplicationServerSet/ApplicationServerSetDtoAssembler.php
library/Ivoz/Provider/Domain/Model/ApplicationServerSetRelApplicationServer/ApplicationServerSetRelApplicationServerAbstract.php
library/Ivoz/Provider/Domain/Model/ApplicationServerSetRelApplicationServer/ApplicationServerSetRelApplicationServerInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ApplicationServerSetRelApplicationServer.ApplicationServerSetRelApplicationServerAbstract.orm.xml
library/psalm-baseline.xml
schema/DoctrineMigrations/Version20241219160857.php

Modified FK fields to be not nullable

Fixed table application server set rel application server

---

Jenkinsfile
web/portal/platform/cypress/fixtures/apiSpec.json

Add API spec sync tests to pipeline backend stage

---

web/portal/brand/src/components/Login.tsx
web/portal/client/src/components/Login.tsx
web/portal/user/src/components/Login.tsx

Impersonation extra slashes in url

---

web/portal/client/cypress/e2e/Invoice/Invoice.cy.js
web/portal/client/cypress/fixtures/apiSpec.json
web/portal/client/src/entities/Invoice/Invoice.tsx
web/rest/client/config/api/raw/provider.yml

Clients cannot download their invoices

---

web/portal/client/src/entities/Locution/Field/RecordingExtension.tsx
web/portal/client/src/store/clientSession/recordLocutionService.ts

Use company locution service code instead of global service code

---

web/portal/package.json
web/portal/yarn.lock

Fix filter operators when search field changes

---

doc/sphinx/administration_portal/platform/infrastructure/application_server_sets.rst
web/portal/platform/src/entities/ApplicationServerSet/ApplicationServerSet.tsx

Application Server Set documentation link

---

library/DataFixtures/ORM/ProviderCompany.php
library/Ivoz/Provider/Domain/Model/Company/Company.php
web/portal/brand/cypress/e2e/Clients/utils/PbxsValidator.ts
web/portal/brand/cypress/pacts/brand-provider-wholesale-brand-consumer-wholesale.json
web/portal/brand/src/entities/Company/Company.tsx
web/portal/brand/src/entities/Company/Form.tsx
web/rest/brand/features/provider/company/getCompanies.feature

Hide application server set selector for wholesale client

---

web/portal/platform/cypress/e2e/Administrator/AdministratorRelPublicEntities/AdministratorRelPublicEntities.cy.js
web/portal/platform/cypress/e2e/Administrator/AdministratorRelPublicEntities/AdministratorRelPublicEntities.tests.js
web/portal/platform/cypress/e2e/webPortal/WebPortal.cy.js
web/portal/platform/cypress/e2e/webPortal/WebPortal.tests.js
web/portal/platform/cypress/fixtures/AdministratorRelPublicEntities/getCollection.json
web/portal/platform/cypress/fixtures/AdministratorRelPublicEntities/getItem.json
web/portal/platform/cypress/fixtures/AdministratorRelPublicEntities/put.json
web/portal/platform/cypress/fixtures/PublicEntities/getCollection.json
web/portal/platform/cypress/fixtures/PublicEntities/getItem.json
web/portal/platform/cypress/fixtures/PublicEntities/post.json
web/portal/platform/cypress/fixtures/PublicEntities/put.json
web/portal/platform/cypress/fixtures/WebPortal/getItem.json
web/portal/platform/cypress/fixtures/WebPortal/post.json
web/portal/platform/cypress/fixtures/WebPortal/put.json
web/portal/platform/cypress/pacts/platform-provider-Administrator-relPublic-entities-platform-consumer-Administrator-relPublic-entities.json
web/portal/platform/cypress/pacts/platform-provider-Web-portals-platform-consumer-Web-portals.json
web/portal/platform/cypress/support/commands/prepareGenericPactInterceptors.js

Testing Platform section portals and platform operators 

---

Jenkinsfile

Update Jira custom field ids in pipelines

---

asterisk/agi/config/routes.yaml
asterisk/agi/config/services.yaml
asterisk/agi/src/Agi/Action/IvrAction.php
asterisk/agi/src/Agi/Wrapper.php
asterisk/agi/src/Dialplan/IvrStatus.php
asterisk/config/dialplan/default.conf

Moved READ function from AGI to diaplan to reduce the lifetime of AGI and resource consumption

IVR: Request digits in dialplan instead of inside the AGI

---

microservices/recordings/config/services.yaml
microservices/recordings/src/Model/RawRecordingInfo.php
microservices/recordings/src/Service/Encoder.php
microservices/recordings/src/Service/RawRecordingInfoFactory.php
microservices/recordings/src/Service/RecordingEndedChecker.php
microservices/recordings/tests/Service/EncoderTest.php
microservices/recordings/tests/Service/RecordingEndedCheckerTest.php

Check rtpengine recording has ended using lsof

---

asterisk/config/voicemail.conf

This requires upgrading asterisk to 20.11.0 and removing the custom patch with the same purpose.

asterisk: configure voicemail audio files to store on disk

---

web/portal/platform/cypress/e2e/Calls/Externalcalls/ExternalCalls.cy.js
web/portal/platform/cypress/fixtures/ExternalCalls/billableCallsExport.json
web/portal/platform/cypress/fixtures/ExternalCalls/getCollection.json
web/portal/platform/cypress/pacts/platform-provider-invoice-billable_calls-platform-consumer-invoice-billable_calls.json
web/portal/platform/cypress/support/commands/prepareGenericPactInterceptors.js

Testing platform session billable calls

---

web/portal/brand/cypress/e2e/Calls/CallCsvSchedulers/CallCsvReport/CallCsvReport.cy.js
web/portal/brand/cypress/e2e/Calls/CallCsvSchedulers/CallCsvScheduler.cy.js
web/portal/brand/cypress/e2e/Calls/CallCsvSchedulers/CallCsvSchedulers.tests.js
web/portal/brand/cypress/e2e/Calls/Externalcalls/ExternalCalls.cy.js
web/portal/brand/cypress/fixtures/Provider/BillableCalls/billableCallsExport.json
web/portal/brand/cypress/fixtures/Provider/BillableCalls/getCollection.json
web/portal/brand/cypress/fixtures/Provider/CallCsvReport/getCollection.json
web/portal/brand/cypress/fixtures/Provider/CallCsvReport/getItem.json
web/portal/brand/cypress/fixtures/Provider/CallCsvScheduler/getCollection.json
web/portal/brand/cypress/fixtures/Provider/CallCsvScheduler/getItem.json
web/portal/brand/cypress/fixtures/Provider/CallCsvScheduler/post.json
web/portal/brand/cypress/fixtures/Provider/CallCsvScheduler/put.json
web/portal/brand/cypress/pacts/brand-provider-Call-Csv-Report-brand-consumer-Call-Csv-Report.json
web/portal/brand/cypress/pacts/brand-provider-Call-Csv-Scheduler-brand-consumer-Call-Csv-Scheduler.json
web/portal/brand/cypress/pacts/brand-provider-External-calls-brand-consumer-External-calls.json
web/portal/brand/cypress/support/commands/prepareGenericPactInterceptors.js

Testing Brand session calls

---

library/bin/test-commit-tags

tests: ignore merge commits while validating commit tags

---

web/portal/brand/cypress/e2e/Settings/NumericTransformations/CallerInTransformations/CallerInTransformations.cy.js
web/portal/brand/cypress/pacts/brand-provider-Caller-in-transformations-brand-consumer-Caller-in-transformations.json
web/portal/brand/src/entities/TransformationRule/TransformationRule.tsx

Disable Edit and Delete buttons in transformation rule sets

---

kamailio/users/config/kamailio.cfg
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointAbstract.php
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointDtoAbstract.php
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointInterface.php
library/Ivoz/Ast/Domain/Model/VoicemailMessage/VoicemailMessage.php
library/Ivoz/Ast/Domain/Model/VoicemailMessage/VoicemailMessageInterface.php
library/Ivoz/Ast/Domain/Service/VoicemailMessage/SendVoicemailRefresh.php
library/Ivoz/Ast/Domain/Service/VoicemailMessage/VoicemailMessageLifecycleEventHandlerInterface.php
library/Ivoz/Ast/Domain/Service/VoicemailMessage/VoicemailMessageLifecycleServiceCollection.php
library/Ivoz/Ast/Infrastructure/Asterisk/AMI/AMIConnector.php
library/Ivoz/Ast/Infrastructure/Asterisk/AMI/FakeAMIConnector.php
library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/PsEndpoint.PsEndpointAbstract.orm.xml
library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/parameters.yml
library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/services/infraestructure/asterisk.yml
library/composer-packages/irontec/ivoz-provider-bundle/composer.json
library/composer.json
library/composer.lock
library/psalm-baseline.xml
schema/DoctrineMigrations/Version20250204100801.php
schema/tests/Provider/ResidentialDevice/ResidentialDeviceLifeCycleTest.php

Add MWI subscription support

---

.github/dependabot.yml
doc/dev/AcceptedCommitTagsList.txt

Limit dependabot scans to library/composer.lock and web/portal/yarn.lock to avoid duplicated security reports

Configure dependabot scan files

---

Jenkinsfile

ci: add support for stages cached pipeline results

---

web/portal/client/src/translations/ca.json
web/portal/client/src/translations/es.json

Proofreading in translations

---

web/portal/client/src/entities/ConditionalRoutesCondition/ConditionalRoutesCondition.tsx
web/portal/client/src/entities/HuntGroupMember/HuntGroupMember.tsx
web/portal/client/src/entities/IvrEntry/IvrEntry.tsx

Fix the default sorting in some entities

---

library/Ivoz/Provider/Domain/Service/TerminalModel/TemplateRenderer.php

Delete empty temporary files

---

library/Ivoz/Provider/Domain/Assembler/Location/LocationDtoAssembler.php
library/Ivoz/Provider/Domain/Model/Location/Location.php
library/Ivoz/Provider/Domain/Model/Location/LocationDto.php
library/Ivoz/Provider/Domain/Model/Location/LocationInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Location.Location.orm.xml
web/portal/client/cypress/e2e/Location/Location.cy.js
web/portal/client/cypress/fixtures/Location/getItem.json
web/portal/client/cypress/fixtures/Location/post.json
web/portal/client/cypress/fixtures/Location/put.json
web/portal/client/cypress/fixtures/apiSpec.json
web/portal/client/cypress/pacts/client-provider-Location-client-consumer-Location.json
web/portal/client/src/entities/Location/ForeignKeyResolver.tsx
web/portal/client/src/entities/Location/Form.tsx
web/portal/client/src/entities/Location/Location.tsx
web/portal/client/src/entities/Location/LocationProperties.tsx
web/portal/client/src/translations/ca.json
web/portal/client/src/translations/en.json
web/portal/client/src/translations/es.json
web/portal/client/src/translations/it.json
web/rest/client/features/provider/location/getLocation.feature
web/rest/client/features/provider/location/postLocation.feature
web/rest/client/features/provider/location/putLocation.feature

Manage users by location

---

microservices/workers/psalm-baseline.xml
microservices/workers/src/Worker/Rates.php

fix rates importer ignore column

---

schema/DoctrineMigrations/Version20250307085857.php

Fix wrong fqdn in PublicEntities

---

Jenkinsfile

[PROVIDER-2223] Update pull request title with jira ticket

---

library/Ivoz/Provider/Domain/Service/Terminal/Provision/ProvisionSpecific.php

[PROVIDER-2212] Update the last provision date when the specified provision is met

---

web/portal/client/src/entities/User/Action/Impersonate.tsx

[PROVIDER-2220] Fix impersonation for usernames with plus sign

---

doc/sphinx/administration_portal/brand/settings/notification_templates.rst
doc/sphinx/locale/es/LC_MESSAGES/administration_portal/brand/settings/notification_templates.po
web/portal/brand/src/entities/NotificationTemplateContent/NotificationTemplateContent.tsx
web/portal/brand/src/entities/NotificationTemplateContent/NotificationTemplateContentProperties.ts
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json
web/portal/platform/src/entities/NotificationTemplateContent/NotificationTemplateContent.tsx

[PROVIDER-2235] Add Notification templates content documentation

---

web/portal/user/cypress/e2e/Fax/Fax.cy.js
web/portal/user/cypress/fixtures/Fax/getCollection.json
web/portal/user/cypress/support/commands/prepareGenericPactInterceptors.ts
web/portal/user/src/entities/Fax/Fax.tsx
web/rest/user/config/api/raw/provider.yml
web/rest/user/features/provider/faxes/getFaxes.feature
web/rest/user/public/apiSpec.json

[PROVIDER-2234] Fix rename endpoint from my faxes to faxes

---

web/portal/client/src/entities/Locution/Locution.tsx
web/portal/client/src/entities/Locution/LocutionProperties.tsx
web/portal/client/src/entities/MusicOnHold/Form.tsx
web/portal/client/src/entities/MusicOnHold/MusicOnHold.tsx
web/portal/client/src/entities/MusicOnHold/MusicOnHoldProperties.tsx
web/portal/client/src/translations/ca.json
web/portal/client/src/translations/en.json
web/portal/client/src/translations/es.json
web/portal/client/src/translations/it.json

[PROVIDER-2219] Display the encoded file field in Locution and MusicOnHold details

---

docker-compose.yml
docker/backend/start.sh
web/portal/brand/vite.config.ts
web/portal/client/vite.config.ts
web/portal/platform/vite.config.ts
web/portal/user/vite.config.ts

[PROVIDER-2247] Improve docker containers

---

web/portal/client/src/entities/RetailAccount/Form.tsx

[PROVIDER-2238] portal/client: Show the multiContact option in advanced settings

---

tests/run-pipeline

[PROVIDER-2252] tests: add test-phpstan-update-baseline to local pipeline runner

---

web/portal/platform/cypress/e2e/Brand/Brand.cy.js
web/portal/platform/src/entities/Brand/Brand.tsx
web/portal/platform/src/entities/TerminalManufacturer/TerminalManufacturer.tsx
web/portal/platform/src/router/EntityMap.ts

[PROVIDER-1697] Update menu icons in platform portal

---

library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksCdr.TrunksCdrAbstract.orm.xml
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.xml
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.xml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/UsersCdrDoctrineRepository.php
microservices/recordings/src/Service/Encoder.php
schema/DoctrineMigrations/Version20250414130820.php
schema/tests/Provider/UsersCdr/UsersCdrRepositoryTest.php

[PROVIDER-2246] Remove unique keys from Cdr tables

---

web/portal/client/cypress/e2e/Calls/BillableCalls.cy.js
web/portal/client/cypress/fixtures/BillableCall/getCollection.json
web/portal/client/src/entities/BillableCall/BillableCall.tsx
web/portal/client/src/entities/BillableCall/BillableCallProperties.tsx
web/portal/client/src/router/EntityMap.ts

[PROVIDER-2200] Automatic recordings by ddi on external calls

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Revert changes introduced in #2785
This lengthen is no longer needed after #2946

[PROVIDER-2167] Kamailio: do not lengthen callids

---

web/portal/client/cypress/e2e/Calls/Recording/Recording.cy.js
web/portal/user/cypress/e2e/Calls/Calls.cy.ts
web/portal/user/cypress/e2e/Calls/Recording/Recording.cy.ts
web/portal/user/cypress/e2e/Preferences/Preferences.cy.ts
web/portal/user/cypress/e2e/Recording/Recording.cy.ts
web/portal/user/cypress/e2e/Voicemail/VoicemailMessage/VoicemailMessage.cy.js
web/portal/user/src/entities/Preferences/Preferences.tsx
web/portal/user/src/entities/Recording/Recording.tsx
web/portal/user/src/entities/UsersCdr/UsersCdr.tsx
web/portal/user/src/entities/Voicemail/Voicemail.tsx

[PROVIDER-1701] Update menu icons user portal

---

web/portal/brand/cypress/e2e/BannedIpAddress/BannedIpAddress.cy.js
web/portal/brand/cypress/e2e/BruteForceAttacks/BruteForceAttacks.cy.js
web/portal/brand/cypress/e2e/Calls/CallCsvSchedulers/CallCsvReport/CallCsvReport.cy.js
web/portal/brand/cypress/e2e/Calls/CallCsvSchedulers/CallCsvScheduler.cy.js
web/portal/brand/cypress/e2e/Clients/Residential/Residentials.cy.js
web/portal/brand/cypress/e2e/Clients/Retails/Retails.cy.js
web/portal/brand/cypress/e2e/Clients/VirtualPbxs/VirtualPbxs.cy.js
web/portal/brand/cypress/e2e/Clients/Wholesales/Wholesales.cy.js
web/portal/brand/cypress/e2e/Corporation/Corporation.cy.js
web/portal/brand/cypress/e2e/Friends/Friends.cy.js
web/portal/brand/cypress/e2e/OutgoingRouting/OutgoingRouting.cy.js
web/portal/brand/cypress/e2e/ResidentialDevice/ResidentialDevice.cy.js
web/portal/brand/cypress/e2e/RetailAccount/RetailAccount.cy.js
web/portal/brand/cypress/e2e/RoutingPattern/RoutingPattern.cy.js
web/portal/brand/cypress/e2e/RoutingPatternGroup/RoutingPatternGroup.cy.js
web/portal/brand/cypress/e2e/RoutingTag/RoutingTag.cy.js
web/portal/brand/cypress/e2e/User/User.cy.js
web/portal/brand/src/router/EntityMap.ts

[PROVIDER-1699] Update menu icons in brand portal

---

library/Ivoz/Provider/Domain/Model/User/UserDto.php
web/rest/client/config/api/raw/provider.yml
web/rest/client/config/routes.yaml
web/rest/client/features/provider/user/getUsersDetailed.feature
web/rest/client/public/apiSpec.json

[PROVIDER-2248] Add api client endpoint for user detailed collection

---

library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrRepository.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrRepository.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/UsersCdrDoctrineRepository.php
schema/tests/Kam/TrunksCdr/TrunksCdrRepositoryTest.php
schema/tests/Kam/UsersCdr/UsersCdrRepositoryTest.php

[PROVIDER-2251] Remove unused callid methods

---

web/portal/package.json
web/portal/yarn.lock

[PROVIDER-2257] Update pact-cypress-adapter dev dependency in portals

---

web/portal/client/cypress/e2e/Ddi/BillableCalls/BillableCalls.cy.js
web/portal/client/cypress/e2e/Ddi/ResidentialDdi/BillableCalls/BillableCalls.cy.js
web/portal/client/src/entities/BillableCall/BillableCall.tsx
web/portal/client/src/entities/Extension/Extension.tsx
web/portal/client/src/entities/MatchList/MatchList.tsx
web/portal/client/src/entities/ResidentialDevice/ResidentialDevice.tsx
web/portal/client/src/entities/RetailAccount/RetailAccount.tsx
web/portal/client/src/entities/Terminal/Terminal.tsx
web/portal/client/src/entities/User/User.tsx
web/portal/client/src/entities/Voicemail/Voicemail.tsx
web/portal/client/src/router/EntityMap.ts

[PROVIDER-1700] Updated menu icons portal clients

---

web/portal/platform/src/router/EntityMap.ts

[PROVIDER-2263] Change calls menu icon portal platform

---

web/portal/brand/cypress/pacts/brand-provider-retails-client-rating-profiles-brand-consumer-retails-client-rating-profiles.json
web/portal/brand/src/entities/RatingProfile/Form.tsx

[PROVIDER-2260] fix show routing tag retail wholesale

---

library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerAbstract.php
library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerDto.php
library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerDtoAbstract.php
library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerInterface.php
library/Ivoz/Provider/Domain/Service/InvoiceScheduler/NextExecutionResolver.php
library/Ivoz/Provider/Domain/Service/InvoiceScheduler/SetExecutionError.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/InvoiceScheduler.InvoiceSchedulerAbstract.orm.xml
library/spec/Ivoz/Provider/Domain/Service/InvoiceScheduler/NextExecutionResolverSpec.php
library/spec/Ivoz/Provider/Domain/Service/InvoiceScheduler/SetExecutionErrorSpec.php
schema/DoctrineMigrations/Version20250514135139.php
schema/tests/Provider/InvoiceScheduler/InvoiceSchedulerLifeCycleTest.php

[PROVIDER-2258] Add automatic retries after failed invoice creation

---

debian/rules

[PROVIDER-2268] Do not restart services on package upgrade

---

debian/ivozprovider-profile-data.postinst
debian/ivozprovider.postinst

[PROVIDER-2267] Use named service to restar DNS server

---

web/portal/brand/cypress/e2e/Billing/DestinationRateGroup/DestinationRate/DestinationRate.cy.js
web/portal/brand/cypress/e2e/Billing/DestinationRateGroup/DestinationRateGroup.cy.js
web/portal/brand/cypress/e2e/Billing/Destinations/Destinations.cy.js
web/portal/brand/cypress/e2e/Billing/RatingPlanGroups/RatingPlanGroups.cy.js
web/portal/brand/cypress/fixtures/Provider/CurrentDayUsages/getCollection.json
web/portal/brand/cypress/fixtures/Provider/CurrentDayUsages/getItem.json
web/portal/brand/cypress/fixtures/Provider/Destination/getCollection.json
web/portal/brand/cypress/fixtures/Provider/Destination/getItem.json
web/portal/brand/cypress/fixtures/Provider/Destination/postItem.json
web/portal/brand/cypress/fixtures/Provider/Destination/put.json
web/portal/brand/cypress/fixtures/Provider/DestinationRateGroup/getCollection.json
web/portal/brand/cypress/fixtures/Provider/DestinationRateGroup/getItem.json
web/portal/brand/cypress/fixtures/Provider/DestinationRateGroup/postItem.json
web/portal/brand/cypress/fixtures/Provider/DestinationRateGroup/put.json
web/portal/brand/cypress/fixtures/Provider/DestinationRates/getCollection.json
web/portal/brand/cypress/fixtures/Provider/DestinationRates/getItem.json
web/portal/brand/cypress/fixtures/Provider/DestinationRates/postItem.json
web/portal/brand/cypress/fixtures/Provider/DestinationRates/put.json
web/portal/brand/cypress/fixtures/Provider/DestinationRatingPlanGroups/getCollection.json
web/portal/brand/cypress/fixtures/Provider/DestinationRatingPlanGroups/postItem.json
web/portal/brand/cypress/fixtures/Provider/RatingPlan/getCollections.json
web/portal/brand/cypress/fixtures/Provider/RatingPlanGroups/getItem.json
web/portal/brand/cypress/fixtures/Provider/RatingPlanGroups/postItem.json
web/portal/brand/cypress/fixtures/Provider/RatingPlanGroups/postSimulateCall.json
web/portal/brand/cypress/fixtures/Provider/RatingPlanGroups/putItem.json
web/portal/brand/cypress/pacts/brand-provider-DestinationRateGroup-brand-consumer-DestinationRateGroup.json
web/portal/brand/cypress/pacts/brand-provider-destinationRateGroup-rates-brand-consumer-destinationRateGroup-rates.json
web/portal/brand/cypress/pacts/brand-provider-destinations-brand-consumer-destinations.json
web/portal/brand/cypress/pacts/brand-provider-ratingPlanGroups-brand-consumer-ratingPlanGroups.json
web/portal/brand/cypress/support/commands/prepareGenericPactInterceptors.js

[PROVIDER-1961] Added cypress tests for billing section

---

library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallRepository.php
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/UsersCdrDoctrineRepository.php
microservices/recordings/src/Model/RawRecordingInfo.php
microservices/recordings/src/Service/Encoder.php
microservices/recordings/src/Service/RawRecordingInfoFactory.php
microservices/recordings/tests/Service/EncoderTest.php
schema/tests/Provider/BillableCall/BillableCallRepositoryTest.php
schema/tests/Provider/UsersCdr/UsersCdrRepositoryTest.php

[PROVIDER-2269] Fixed wrong recording to CDR matching

---

ChangeLog
README.md
asterisk/config/pjsip.conf.in
doc/sphinx/conf.py
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
web/rest/brand/CHANGELOG.md
web/rest/client/CHANGELOG.md
web/rest/platform/CHANGELOG.md
web/rest/user/CHANGELOG.md

[PROVIDER-2271] Update ChangeLog for 4.4.0 release

---

debian/control

[PROVIDER-2277] Added lsof dependency to ivozprovider-recordings package

---

docker/backend/start.sh

[PROVIDER-2299] Add missing xdebug entry in hosts file

---

web/portal/platform/cypress/pacts/platform-provider-default-notification-templates-platform-consumer-default-notification-templates.json
web/portal/platform/src/entities/ActiveCalls/ActiveCalls.tsx
web/portal/platform/src/entities/Administrator/Administrator.tsx
web/portal/platform/src/entities/ApplicationServer/ApplicationServer.tsx
web/portal/platform/src/entities/ApplicationServerSet/ApplicationServerSet.tsx
web/portal/platform/src/entities/BillableCall/BillableCall.tsx
web/portal/platform/src/entities/Brand/Brand.tsx
web/portal/platform/src/entities/Currency/Currency.tsx
web/portal/platform/src/entities/Domain/Domain.tsx
web/portal/platform/src/entities/InvoiceTemplate/InvoiceTemplate.tsx
web/portal/platform/src/entities/MediaRelaySet/MediaRelaySet.tsx
web/portal/platform/src/entities/NotificationTemplate/NotificationTemplate.tsx
web/portal/platform/src/entities/NotificationTemplateContent/NotificationTemplateContent.tsx
web/portal/platform/src/entities/ProxyTrunk/ProxyTrunk.tsx
web/portal/platform/src/entities/ProxyUser/ProxyUser.tsx
web/portal/platform/src/entities/Rtpengine/Rtpengine.tsx
web/portal/platform/src/entities/Service/Service.tsx
web/portal/platform/src/entities/SpecialNumber/SpecialNumber.tsx
web/portal/platform/src/entities/TerminalManufacturer/TerminalManufacturer.tsx
web/portal/platform/src/entities/WebPortal/WebPortal.tsx
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/config/api/resources.yml
web/rest/platform/features/provider/service/getService.feature

[PROVIDER-2292] Fix platform entities default ordering configuration

---

web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/publicEntity/getPublicEntities.feature

[PROVIDER-2301] Add missing entities on restricted admin permissions

---

library/Ivoz/Provider/Domain/Assembler/User/UserAssembler.php
web/rest/user/features/my/profile/putProfile.feature
web/rest/user/psalm-baseline.xml
web/rest/user/src/Controller/My/PutProfileAction.php

[PROVIDER-1883] Fix HTTP error code for password validation in user profile endpoint

---

web/portal/brand/src/entities/Friend/ForeignKeyGetter.tsx

…ns instead of
general company selector

[PROVIDER-2346] Fix Friends company selector to use vpbx-specific options

---

web/portal/brand/src/entities/Company/SelectOptions/ResidentialSelectOptions.ts
web/portal/brand/src/entities/Company/SelectOptions/RetailSelectOptions.ts
web/portal/brand/src/entities/Company/SelectOptions/VpbxSelectOptions.ts
web/portal/brand/src/entities/Company/SelectOptions/WholesaleSelectOptions.ts

[PROVIDER-2345] Updated companies selectors to use itemsPerPage

---

doc/sphinx/administration_portal/client/vpbx/routing_tools/calendars.rst

Added srt Calendar documentation, CSV holiday import example.

[PROVIDER-2313] doc: added CSV holidays example on Calendar

---

library/Ivoz/Kam/Domain/Service/TrunksLcrRuleTarget/UpdateByCarrierServer.php
library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingRepository.php
library/Ivoz/Provider/Domain/Model/OutgoingRoutingRelCarrier/OutgoingRoutingRelCarrierRepository.php
library/Ivoz/Provider/Domain/Service/CarrierServer/CarrierServerLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/CarrierServer/DeleteProtection.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/OutgoingRoutingDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/OutgoingRoutingRelCarrierDoctrineRepository.php
schema/tests/Provider/CarrierServer/CarrierServerDeleteProtectionTest.php
schema/tests/Provider/CarrierServer/CarrierServerLifeCycleTest.php
schema/tests/Provider/OutgoingRouting/OutgoingRoutingRepositoryTest.php
schema/tests/Provider/OutgoingRoutingRelCarrier/OutgoingRoutingRelCarrierRepositoryTest.php

[PROVIDER-2324] Allow removal of CarrierServers only if the Carrier does not become serverless

---

Jenkinsfile

[PROVIDER-2352] ci: fixed mergeability test for subtasks

---

web/portal/brand/src/entities/Company/Company.tsx
web/portal/brand/src/entities/Company/SelectOptions/SelectOptions.ts
web/portal/package.json
web/portal/yarn.lock

- Selector de compañías de Rutas salientes.
- Selector de cliente en DDIs
- Configuración de cliente: Dispositivos residenciales
- Configuración de cliente: Friends
Autocomplete changed to new ivoz-ui component DynamicAutocomplete

[PROVIDER-2344] portal/brand: changed company with new dynamicAutocomplete
