irontec/ivozprovider

library/IvozProvider/Mapper/Sql/Companies.php
It was being called only on company updates
=> mappers: Fixed companies update domain hook condition

portals/application/bin/template.php, portals/application/configs/klear/model/TerminalModels.yaml, portals/application/controllers/KlearCustomRunCodeController.php
Fixed path and minor improvements
=> portals: get provisioning template runner back

library/IvozProvider/Klear/Dynamic/Config/Base.php, library/IvozProvider/Klear/Dynamic/Config/BrandOperator.php, library/IvozProvider/Klear/Dynamic/Config/CompanyAdmin.php, library/IvozProvider/Klear/Dynamic/Config/MainOperator.php
=> portals: update admin header with brand name

library/Ami/Connector.php, library/IvozProvider/Mapper/Sql/Companies.php, library/IvozProvider/Mapper/Sql/Users.php, library/IvozProvider/Model/PricingPlansRelTargetPatterns.php, portals/application/configs/klear/errors.yaml, portals/application/languages/en_US/en_US.po, portals/application/languages/es_ES/es_ES.po
i18n: Fixed typo setted -> set
=> Reviewed translations

portals/templates/provisioning/SPA502G/generic.cfg, portals/templates/provisioning/SPA504G/generic.cfg, portals/templates/provisioning/SPA509G/generic.cfg, portals/templates/provisioning/SPA514G/generic.cfg, portals/templates/provisioning/SPA525G2/generic.cfg
Minor modifications in order to get a better integration with the template tester
=> portals: provisioning default templates

AUTHORS
Merge it yourself :stuck_out_tongue_closed_eyes:
=> doc: Update AUTHORS with new collaborators

library/IvozProvider/Gearmand/Invoices/Generator.php, library/IvozProvider/Mapper/Sql/DbTable/DDIs.php, library/IvozProvider/Mapper/Sql/DbTable/Extensions.php, library/IvozProvider/Mapper/Sql/DbTable/FixedCosts.php, library/IvozProvider/Mapper/Sql/Raw/FixedCosts.php, library/IvozProvider/Model/Raw/DDIs.php, library/IvozProvider/Model/Raw/Extensions.php, library/IvozProvider/Model/Raw/FixedCosts.php, library/IvozProvider/Model/Raw/Friends.php, portals/application/configs/klear/FixedCostsList.yaml, portals/application/configs/klear/conf.d/invoiceTemplateHelp.yaml, portals/application/configs/klear/conf.d/mapperList.yaml, portals/application/configs/klear/model/FixedCosts.yaml, portals/application/configs/klear/model/FixedCostsRelInvoices.yaml, portals/application/configs/klear/model/IVRCommon.yaml, portals/application/configs/klearRaw/model/FixedCosts.yaml, portals/application/configs/klearRaw/model/FixedCostsRelInvoices.yaml, portals/application/modules/rest/controllersRaw/FixedCostsController.php, portals/templates/invoiceFixedCosts.txt, portals/templates/invoiceFixedCostsWithDescriptions.txt, scheme/deltas/042-add-description-fixedCosts.sql
Models, mappers and klear configuration regenerated
portals: 
- Applying required modifications in workers. 
- Added some minor UX improvements (margins, etc.)
- Updated templates
Requires workers to be restarted
=> scheme: added name field in fixedCosts

library/IvozProvider/Mapper/Sql/TerminalModels.php, portals/application/modules/provision/controllers/IndexController.php
Wait until the template is parsed without errors
Fixed Mapper/Sql/TerminalModels.php fatal error in php7
=> portals: changed when the terminal provision date is updated

portals/application/configs/application.ini
This doesn't affect klear because it uses its own configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/irontec/ivozprovider/98)
=> portals: Changed default language and fixed english lang key

doc/sphinx/installation/cd_install.rst, doc/sphinx/installation/debian_install.rst, doc/sphinx/installation/requirements.rst, doc/sphinx/locale/es/LC_MESSAGES/installation.po, portals/application/configs/klear/model/TerminalModels.yaml
Fixes #92
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/irontec/ivozprovider/102)
=> doc: IvozProvider with a single public IP address

asterisk/agi/library/Agi/Wrapper.php
This PR aims to fix #106.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/irontec/ivozprovider/107)
=> as: AoR extract function and URI params

library/IvozProvider/Klear/Auth/Adapter.php, library/IvozProvider/Klear/Auth/Mapper.php, library/IvozProvider/Klear/Dynamic/Builder.php, library/IvozProvider/Klear/Dynamic/Config/Base.php, portals/application/configs/klear/ExtraInfo.yaml, portals/application/controllers/KlearCustomExtraAuthController.php
The brand linked to current god BrandURL was being automatically emulated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/irontec/ivozprovider/104)
=> portals: Avoided main operator to emulate brand automatically

ChangeLog
Release 1.3 is coming...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/irontec/ivozprovider/103)
=> doc: Release 1.3 changelog

doc/sphinx/internal_calls/brand_portal.rst, doc/sphinx/internal_calls/god_portal.rst, doc/sphinx/locale/es/LC_MESSAGES/internal_calls.po, doc/sphinx/locale/es/LC_MESSAGES/pbx_features.po, doc/sphinx/pbx_features/friends.rst, doc/sphinx/pbx_features/index.rst, doc/sphinx/pbx_features/queues.rst
=> doc: Release 1.3 new features

library/IvozProvider/Klear/Filter/OutgoingDDI.php, portals/application/configs/klear/BrandsList.yaml, portals/application/configs/klear/CompaniesList.yaml
Applied for companies as well
Fixed error when multiple companies were selected
=> portals: increased delete security for brands

portals/application/configs/klear/CompaniesList.yaml, portals/application/configs/klear/DDIsList.yaml, portals/application/configs/klear/ExtensionsList.yaml, portals/application/configs/klear/HolidayDatesList.yaml, portals/application/configs/klear/ParsedCDRsBrandList.yaml, portals/application/configs/klear/ParsedCDRsCompanyList.yaml, portals/application/configs/klear/ParsedCDRsList.yaml, portals/application/configs/klear/PricingPlansList.yaml, portals/application/configs/klear/PricingPlansRelTargetPatternsList.yaml, portals/application/configs/klear/TargetPatternsList.yaml, portals/application/configs/klear/TerminalsList.yaml, portals/application/configs/klear/UsersList.yaml, portals/application/configs/klear/model/Companies.yaml, portals/application/controllers/ImportFileController.php
Removed everywhere but Billable calls
Added some minor improvements into ImportFileController.php:
- Show the same field name as in exported csv
- Sort field lists
=> portals: removed importers and exporters

library/IvozProvider/Mapper/Sql/DbTable/BrandOperators.php, library/IvozProvider/Mapper/Sql/DbTable/CompanyAdmins.php, library/IvozProvider/Mapper/Sql/DbTable/MainOperators.php, library/IvozProvider/Model/Raw/BrandOperators.php, library/IvozProvider/Model/Raw/CompanyAdmins.php, library/IvozProvider/Model/Raw/MainOperators.php, portals/application/modules/rest/controllers/BrandOperatorsController.php, portals/application/modules/rest/controllers/CompanyAdminsController.php, portals/application/modules/rest/controllers/MainOperatorsController.php, portals/application/modules/rest/controllersRaw/BrandOperatorsController.php, portals/application/modules/rest/controllersRaw/CompanyAdminsController.php, portals/application/modules/rest/controllersRaw/MainOperatorsController.php, portals/public/apidocs/index.html, scheme/deltas/053-active-operators.sql
Fixed regression introduced in #108 
Main operators had no active value (null)
=> portals: fixed add main operator regression

library/IvozProvider/Gearmand/Invoices/Generator.php
The performance has been almost duplicated. DB accesses only represent 10% of the execution time nonetheless
This PR aims to close https://github.com/irontec/ivozprovider/issues/128
=> workers: Improved invoice db related performance

tests/rest/README.md, tests/rest/environment.json, tests/rest/postman-api-tests.json
Basic tests generated with postman and instructions to run them using newman.
=> tests: add basic mappers tests using Rest API

kamailio/users/config/kamailio.cfg, scheme/deltas/057-fix-notify-uri.sql
This PR aims to fix the problem described in the first commit message.
=> Fix notify uri

library/IvozProvider/Klear/Dynamic/Builder.php, library/IvozProvider/Klear/Importer/AbstractFormBuilder.php, library/IvozProvider/Klear/Importer/CsvParser.php, library/IvozProvider/Klear/Importer/GenericForm.php, library/IvozProvider/Klear/Importer/HolidayDates/FormBuilder.php, library/IvozProvider/Klear/Importer/ImporterControllerTrait.php, portals/application/configs/klear/HolidayDatesList.yaml, portals/application/controllers/ImportFileController.php
Refactored ImportFileController
This PR closes https://github.com/irontec/ivozprovider/issues/131
=> portals: get holiday date importer back

library/IvozProvider/Mapper/Sql/Companies.php, tests/rest/postman-api-tests.json
Fixes company creation mapper where company domain was being created for Retail Clients (that use Brand's domain).
Included a couple of rest API tests for Retail Clients, Accounts and Friends.
This PR fixes #167
=> Fix retail creation

portals/application/bin/translate.pl, portals/application/configs/klear/klear.yaml, portals/application/languages/en_US/en_US.po, portals/application/languages/es_ES/es_ES.po
Generated with the upated script from #157 
General review of all translations of the portals, still lot to complete, but Its a good straring point to detect any template generation errors.
This also aims to fix #151
=> i18n: reviewed portal translations to spanish

debian/ivozprovider-profile-data.install, library/IvozProvider/Model/Raw/Locutions.php, library/IvozProvider/Model/Raw/Recordings.php, portals/application/modules/rest/controllers/LocutionsController.php, portals/application/modules/rest/controllers/RecordingsController.php, portals/application/modules/rest/controllersRaw/LocutionsController.php, portals/application/modules/rest/controllersRaw/RecordingsController.php, scheme/build_dev.xml, scheme/deltas/061-fix-recordings-storage-path.sql, scripts/FSObase2index.sh
This PR fixes https://github.com/irontec/ivozprovider/issues/49
=> mappers: fixed recording path issues

portals/e2e/features/brand_features/companies.feature, portals/e2e/features/brand_features/companyURLs.feature, portals/e2e/features/brand_features/peeringContracts.feature, portals/e2e/features/platform_features/brands.feature, portals/e2e/package.json
Fixed a couple of tests that were not emulating the brand properly
Closed node dependency versions
=> qa: removed some old tests that don't apply anymore

library/IvozProvider/Gearmand/Invoices/Generator.php, portals/application/configs/klear/model/FixedCosts.yaml, portals/application/configs/klear/model/PricingPlansRelTargetPatterns.yaml
=> bug: Ensured empty thousands separator

portals/templates/basic.txt, portals/templates/detailed.txt
Avoid showing an empty row for inbound calls
=> invoices: Hide inbound calls when empty

doc/dev/en/storage.md, portals/application/workers/InvoicerWorker.php
Concurrency potential bug prevention for invoices
=> doc: storage path doc

library/IvozProvider/Mapper/Sql/Users.php, portals/application/configs/klear/errors.yaml, portals/application/languages/en_US/en_US.po, portals/application/languages/es_ES/es_ES.po
Do not show generic error message for duplicated email
=> portals: improved dulicated email error message

portals/application/configs/klear/model/Invoices.yaml, portals/templates/basic.txt, portals/templates/detailed.txt
Add css style class for multiline fields (fixed cost description currently).
Show the name instead of the description in FixedCostsRelInvoices table
=> invoices: added multiline style class

portals/application/modules/userweb/controllers/CallsController.php, portals/application/modules/userweb/controllers/IndexController.php
Fixed sql condition where calls were not being filtered by company properly
=> portals: fixed sql condition

portals/application/configs/klear/KamAccCdrsList.yaml
Make peering contract visible in billable calls
=> portals: make peering contract visible in billable calls

library/IvozProvider/Mapper/Sql/DbTable/Users.php, library/IvozProvider/Mapper/Sql/Raw/Users.php, library/IvozProvider/Model/Companies.php, library/IvozProvider/Model/Raw/Users.php, portals/application/configs/klear/UsersList.yaml, portals/application/configs/klear/model/Users.yaml, portals/application/languages/en_US/en_US.po, portals/application/languages/es_ES/es_ES.po, portals/application/modules/rest/controllers/UsersController.php, portals/application/modules/userweb/controllers/AuthController.php, scheme/deltas/066-users-add-gsQRCode.sql, userweb/app/index.html, userweb/app/languages/locale-es.json, userweb/app/modules/authentication/loginCtrl.js, userweb/app/modules/commonView/headerCtrl.js, userweb/app/scripts/app.js, userweb/app/styles/main.scss, userweb/app/views/commonView/header.html, userweb/bower.json
This adds a feature to insert a field in users configuration form to enable a QR Code in the users portal to provision GS Wave.
GS Wave is a free softphone app available for android and IOS devices
=> GS Wave QR code provision

doc/sphinx/locale/es/LC_MESSAGES/pbx_features.po, doc/sphinx/pbx_features/call_permissions.rst
=> doc: Call ACL pattern must be in E.164

library/IvozProvider/Mapper/Sql/Companies.php, portals/application/configs/klear/errors.yaml
Catch the unique sip domain constraint.
=> portals: companies unique domain constraint

library/IvozProvider/Mapper/Sql/RetailAccounts.php, scheme/deltas/071-retailaccounts-name-constraint.sql
Unique name per brand for retail accounts.
=> portals: retail accounts name constraint

library/IvozProvider/Mapper/Sql/DbTable/Brands.php, library/IvozProvider/Mapper/Sql/DbTable/Terminals.php, scheme/deltas/072-domain-length-fix.sql
Minor bugfixing introduced in https://github.com/irontec/ivozprovider/pull/304
=> scheme: fixed db delta and regenerated models and mappers

portals/application/configs/klear/BrandRetailAccountsList.yaml, portals/application/configs/klear/RetailAccountsList.yaml
Show the SIP domain on retail accounts list
=> portals: show domain on retail accounts list

library/IvozProvider/Mapper/Sql/Brands.php, library/IvozProvider/Model/Brands.php, portals/application/configs/klear/CompaniesList.yaml, portals/application/configs/klear/RetailClientsList.yaml, portals/application/configs/klear/errors.yaml, portals/application/configs/klear/model/Brands.yaml, portals/application/configs/klear/model/Companies.yaml, portals/application/configs/klear/model/RetailClients.yaml
Disallow creation of retail account if brand has not a SIP domain
=> portals: Improved sip domain validation for brands with retail feature

library/IvozProvider/Klear/Ghost/RegisterStatus.php, library/IvozProvider/Model/KamUsersLocation.php, portals/application/configs/klear/FriendsList.yaml, portals/application/configs/klear/RetailAccountsList.yaml, portals/application/configs/klear/TerminalsList.yaml, portals/application/configs/klear/model/Friends.yaml, portals/application/configs/klear/model/RetailAccounts.yaml, portals/application/configs/klear/model/Terminals.yaml
=> portals: Add register information on edit

library/Ivoz/Provider/Domain/Model/LcrGateway/LcrGatewayAbstract.php, library/Ivoz/Provider/Domain/Model/LcrGateway/LcrGatewayInterface.php, library/Ivoz/Provider/Domain/Model/LcrRuleTarget/LcrRuleTargetAbstract.php, library/Ivoz/Provider/Domain/Model/LcrRuleTarget/LcrRuleTargetDTO.php, library/Ivoz/Provider/Domain/Model/LcrRuleTarget/LcrRuleTargetInterface.php, library/Ivoz/Provider/Domain/Model/PeerServer/PeerServer.php, library/Ivoz/Provider/Domain/Model/PeerServer/PeerServerAbstract.php, library/Ivoz/Provider/Domain/Model/PeerServer/PeerServerDTO.php, library/Ivoz/Provider/Domain/Model/PeerServer/PeerServerInterface.php, library/Ivoz/Provider/Domain/Model/PeerServer/PeerServerTrait.php, library/Ivoz/Provider/Domain/Service/LcrGateway/UpdateByPeerServer.php, library/Ivoz/Provider/Domain/Service/LcrRuleTarget/CreateByPeerServer.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/LcrGateway.LcrGatewayAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/LcrRuleTarget.LcrRuleTargetAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/PeerServer.PeerServer.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/PeerServer.PeerServerAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/TransformationRuleSet.TransformationRuleSetAbstract.orm.yml, scheme/src/EntityGeneratorBundle/Tools/AbstractEntityGenerator.php, scheme/src/EntityGeneratorBundle/Tools/DTOGenerator.php, scheme/src/EntityGeneratorBundle/Tools/InterfaceGenerator.php
Improved entity generator in order to handle oneToOne relationships properly
=> core: Make LcrGateway - PeerServer relationship oneToOne

library/Ivoz/Core/Application/Service/DataGateway.php, library/Ivoz/Core/Domain/Service/EntityPersisterInterface.php, library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineEntityPersister.php, library/IvozProvider/Klear/Filter/OutgoingDDIRules.php, web/admin/application/configs/klear/BrandsList.yaml, web/admin/application/configs/klear/model/Brands.yaml
Added removeFromArray method into EntityPersister in order to fix multi delete issues in klear
Fixed brandList filters
=> Fixed multi delete in Klear

library/CoreBundle/Resources/config/lifecycle.yml, library/CoreBundle/Resources/config/lifecycle/ivoz/queue.yml, library/CoreBundle/Resources/config/services.yml, library/CoreBundle/Resources/config/services/assemblers.yml, library/CoreBundle/Resources/config/services/path_resolvers.yml, library/Ivoz/Core/Application/Service/Assembler/DtoAssembler.php, library/Ivoz/Core/Application/Service/CommonStoragePathResolver.php, library/Ivoz/Core/Application/Service/StoragePathResolverCollection.php, library/Ivoz/Core/Application/Service/StoragePathResolverInterface.php, library/Ivoz/Core/Application/Service/Traits/FileContainerEntityAssemblerTrait.php, library/Ivoz/Core/Domain/Service/TempFile.php, library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineEntityPersister.php, library/Ivoz/Core/Infrastructure/Domain/Service/Lifecycle/DoctrineEventSubscriber.php, library/Ivoz/Core/Infrastructure/Domain/Service/Lifecycle/EntityClassToServiceNameTrait.php, library/Ivoz/Core/Infrastructure/Persistence/Filesystem/ScheduleForRemove.php, library/Ivoz/Provider/Application/Service/Brand/BrandAssembler.php, library/Ivoz/Provider/Application/Service/Brand/BrandDtoAssembler.php, library/Ivoz/Provider/Application/Service/GenericMusicOnHold/GenericMusicOnHoldAssembler.php, library/Ivoz/Provider/Application/Service/GenericMusicOnHold/GenericMusicOnHoldDtoAssembler.php, library/Ivoz/Provider/Application/Service/GenericMusicOnHold/StoragePathResolver.php, library/Ivoz/Provider/Application/Service/Locution/LocutionAssembler.php, library/Ivoz/Provider/Application/Service/Locution/LocutionDtoAssembler.php, library/Ivoz/Provider/Application/Service/MusicOnHold/MusicOnHoldAssembler.php, library/Ivoz/Provider/Application/Service/MusicOnHold/MusicOnHoldDtoAssembler.php, library/Ivoz/Provider/Domain/Model/Company/Company.php, library/Ivoz/Provider/Domain/Model/Locution/Locution.php, library/Ivoz/Provider/Domain/Model/Locution/LocutionInterface.php, library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccount.php
fixed fso delete on entity remove
=> fixed fso delete on entity remove

library/IvozProvider/Klear/Filter/Features.php, library/IvozProvider/Klear/Filter/QueueStrategies.php, library/IvozProvider/Klear/Filter/RouteTypes.php, web/admin/e2e/tests/features/2-brand/02-1-peeringContracts.feature, web/admin/e2e/tests/features/2-brand/03-1-companies.feature
=> webadmin: remove pending old model references

library/CoreBundle/Resources/config/services/assemblers.yml, library/CoreBundle/Resources/config/services/path_resolvers.yml, library/Ivoz/Provider/Application/Service/BrandUrl/BrandUrlAssembler.php, library/Ivoz/Provider/Application/Service/BrandUrl/BrandUrlDtoAssembler.php, library/Ivoz/Provider/Application/Service/FaxesInOut/FaxesInOutAssembler.php, library/Ivoz/Provider/Application/Service/FaxesInOut/FaxesInOutDtoAssembler.php, library/Ivoz/Provider/Application/Service/Invoice/InvoiceAssembler.php, library/Ivoz/Provider/Application/Service/Invoice/InvoiceDtoAssembler.php, library/Ivoz/Provider/Application/Service/Recording/RecordingAssembler.php, library/Ivoz/Provider/Application/Service/Recording/RecordingDtoAssembler.php, library/Ivoz/Provider/Domain/Model/BrandUrl/BrandUrl.php, library/Ivoz/Provider/Domain/Model/BrandUrl/BrandUrlDTO.php, library/Ivoz/Provider/Domain/Model/BrandUrl/BrandUrlDTOTrait.php, library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOut.php, library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOutDTO.php, library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOutDTOTrait.php, library/Ivoz/Provider/Domain/Model/Invoice/Invoice.php, library/Ivoz/Provider/Domain/Model/Invoice/InvoiceDTO.php, library/Ivoz/Provider/Domain/Model/Invoice/InvoiceDTOTrait.php, library/Ivoz/Provider/Domain/Model/Recording/RecordingDTO.php, library/Ivoz/Provider/Domain/Model/Recording/RecordingDTOTrait.php, web/admin/application/configs/klear/model/BrandUrls.yaml, web/admin/application/configs/klear/model/FaxesInOut.yaml, web/admin/application/configs/klear/model/Invoices.yaml, web/admin/application/configs/klear/model/Recordings.yaml
Implement FileContainerInterface in BrandUrl, Recording, FaxInOut and Invoice entities
This PR requires https://github.com/irontec/ivozprovider/pull/330 to be merged first
=> Implement pending file container interfaces

library/Ivoz/Provider/Domain/Model/Company/CompanyAbstract.php, library/Ivoz/Provider/Domain/Model/Company/CompanyDTO.php, library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20171120174020.php
Originally defined as boolean, this field can contain '0', '1' and '2' as valid values.
=> scheme: fix Companies onDemandRecord field type

web/rest/app/config/api/resources.yml, web/rest/src/Controller/My/CallHistoryAction.php, web/user/app/modules/calls/callsCtrl.js
Use user timezone instead of UTC
Use startDate ASC as default order
Round up duration
=> web/user: call history enhancements

kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg
Avoid unnecessary and possible faulty logic to requests that don't fulfill sanity checks.
=> kam: Make sanity checks topmost logic

asterisk/agi/src/Agi/Action/HuntGroupCallAction.php, library/Ivoz/Provider/Domain/Model/HuntGroup/HuntGroupAbstract.php, library/Ivoz/Provider/Domain/Model/HuntGroup/HuntGroupDtoAbstract.php, library/Ivoz/Provider/Domain/Model/HuntGroup/HuntGroupInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/HuntGroup.HuntGroupAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20180308143534.php, web/admin/application/configs/klear/HuntGroupsList.yaml, web/admin/application/configs/klear/model/HuntGroups.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
=> Huntgroups: prevent missed calls feature

library/Ivoz/Provider/Domain/Model/Ddi/DdiAbstract.php, library/Ivoz/Provider/Domain/Model/Ddi/DdiInterface.php, library/Ivoz/Provider/Domain/Model/Friend/Friend.php, library/Ivoz/Provider/Domain/Model/HuntGroup/HuntGroupAbstract.php, library/Ivoz/Provider/Domain/Model/HuntGroup/HuntGroupDtoAbstract.php, library/Ivoz/Provider/Domain/Model/HuntGroup/HuntGroupInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Ddi.DdiAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/HuntGroup.HuntGroupAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20180306160405.php, web/admin/application/configs/klear/CompaniesList.yaml, web/admin/application/configs/klear/HuntGroupsList.yaml, web/admin/application/configs/klear/model/Companies.yaml
Minor schema and visual enhancement
=> core: reviewed fields

asterisk/agi/src/Dialplan/Headers.php, kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg, library/Ivoz/Provider/Domain/Model/Brand/BrandAbstract.php, library/Ivoz/Provider/Domain/Model/Brand/BrandDtoAbstract.php, library/Ivoz/Provider/Domain/Model/Brand/BrandInterface.php, library/Ivoz/Provider/Domain/Model/Company/CompanyAbstract.php, library/Ivoz/Provider/Domain/Model/Company/CompanyDtoAbstract.php, library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Brand.BrandAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20180308171319.php, web/admin/application/configs/klear/BrandsList.yaml, web/admin/application/configs/klear/CompaniesList.yaml, web/admin/application/configs/klear/RetailClientsList.yaml, web/admin/application/configs/klear/model/Brands.yaml, web/admin/application/configs/klear/model/Companies.yaml, web/admin/application/configs/klear/model/RetailClients.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
This issue replicates the changes made via #398 and fixed by #401 to achieve the goals described in #394 .
=> Limit the number of voice channels per brand

asterisk/agi/src/Dialplan/Headers.php, kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg
- Reduce the verbosity of both kamailio.cfg-s
- Remove unused logic
=> Kamailio: remove unwanted logics and log messages

library/CoreBundle/Resources/config/services/gearmand.yml, library/Ivoz/Core/Infrastructure/Domain/Service/Gearman/Jobs/RatesImporter.php, microservices/workers/app/config/services.yml, microservices/workers/src/Worker/Rates.php, profiles/portal/etc/supervisor/conf.d/rates-importer.conf, web/admin/application/configs/klear/DestinationRatesList.yaml, web/admin/application/configs/klear/conf.d/importPricesHelp.yaml, web/admin/application/controllers/ImportCustomFileController.php, web/admin/public/zf.php, web/admin/samples/pricesSample.csv
This PR enables the import button in the DestinationRoutes list screen for uploading pricing data from CSV file.
The code still require lots of enhancements like logging and error handling, but it works with the sample file provided in the help section.
=> Restore basic CSV prices importer

library/CoreBundle/Resources/config/logger.yml, library/Ivoz/Provider/Domain/Model/Language/LanguageDto.php, library/Ivoz/Provider/Domain/Model/User/User.php, web/admin/application/bin/template.php, web/admin/application/configs/application.ini, web/admin/application/configs/klear/TerminalManufacturersList.yaml, web/admin/application/controllers/KlearCustomRestoreBackupController.php, web/admin/application/controllers/KlearCustomRestoreDefaultController.php, web/admin/application/controllers/KlearCustomRunCodeController.php, web/admin/application/modules/provision/controllers/IndexController.php, web/admin/public/dev.php, web/admin/public/e2e.php, web/admin/public/index.php, web/admin/public/zf.php, web/admin/templates/provisioning/SPA502G/specific.cfg, web/admin/templates/provisioning/SPA504G/specific.cfg, web/admin/templates/provisioning/SPA509G/specific.cfg, web/admin/templates/provisioning/SPA514G/specific.cfg, web/admin/templates/provisioning/SPA525G2/specific.cfg, web/admin/templates/provisioning/YealinkT21P/specific.cfg, web/admin/templates/provisioning/YealinkT21P_E2/specific.cfg, web/admin/templates/provisioning/YealinkT23P/specific.cfg, web/admin/templates/provisioning/YealinkT27P/specific.cfg, web/admin/templates/provisioning/YealinkT46G/specific.cfg, web/admin/templates/provisioning/YealinkT48G/specific.cfg, web/admin/templates/provisioning/YealinkW5XP/specific.cfg
Terminal provisioning migrated.
=> Get terminal provisioning back

library/CoreBundle/Resources/config/services/assemblers.yml, library/CoreBundle/Resources/config/services/path_resolvers.yml, library/Ivoz/Provider/Application/Service/FaxesInOut/FaxesInOutAssembler.php, library/Ivoz/Provider/Application/Service/FaxesInOut/FaxesInOutDtoAssembler.php, library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOut.php
Uploaded file was not being stored in storage path
=> core: fixed faxesInOut file storage

web/admin/application/configs/klear/model/RoutingPatternGroupsRelPatterns.yaml, web/admin/application/controllers/ImportCustomFileController.php, web/admin/application/controllers/KlearCustomExtraAuthController.php, web/admin/application/controllers/KlearCustomGenerateInvoiceController.php, web/admin/application/controllers/KlearCustomInvoiceTemplateTesterController.php, web/admin/application/controllers/KlearCustomUploadFileController.php, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/library/IvozProvider/Klear/Importer/GenericForm.php
Updated translation files and changed some dialogs to share already existing texts
=> i18n: reviewed web/admin translation files

kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg
This PR aims to improve logging of maxcalls feature (same as 67accbc4d2e906e75bbabfa200d09ddb17ffec29).
For that, log message amount must be reduced too (as in #419).
And some fixes already applied in bleeding have been merged too (67c0fce, 4c22686, ff18ef8, 16f7ebc...)
=> Less logs but more accurate

kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg, library/Ivoz/Kam/Domain/Model/TrunksUacreg/TrunksUacregAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksUacreg/TrunksUacregDtoAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksUacreg/TrunksUacregInterface.php, library/Ivoz/Kam/Domain/Model/UsersActiveWatcher/UsersActiveWatcherAbstract.php, library/Ivoz/Kam/Domain/Model/UsersActiveWatcher/UsersActiveWatcherInterface.php, library/Ivoz/Kam/Domain/Model/UsersLocation/UsersLocationAbstract.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksDomainAttr.TrunksDomainAttrAbstract.orm.yml, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksUacreg.TrunksUacregAbstract.orm.yml, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersActiveWatcher.UsersActiveWatcherAbstract.orm.yml, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersLocation.UsersLocationAbstract.orm.yml, library/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleAbstract.php, library/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleDtoAbstract.php, library/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/LcrRule.LcrRuleAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20180410164407.php
This PR fixes #441 
It contains:
- database migration needed for this version change.
- changes needed in both kamailio.cfg-s
=> Upgrade to Kamailio 5.1.2

library/CoreBundle/Resources/config/model/provider/company.yml, library/CoreBundle/Resources/config/services.yml, library/CoreBundle/Resources/config/services/infraestructure/cgrates.yml, library/Ivoz/Cgr/Domain/Model/TpRatingProfile/SimulatedCall.php, library/Ivoz/Cgr/Domain/Service/TpRatingProfile/BillingServiceInterface.php, library/Ivoz/Core/Application/Service/EntityTools.php, library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/BillingService.php, library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/CompanyBalanceService.php, library/Ivoz/Provider/Domain/Service/Company/CompanyBalanceServiceInterface.php, library/Ivoz/Provider/Domain/Service/Company/IncrementBalance.php, library/Ivoz/Provider/Domain/Service/Company/SyncBalances.php, library/Ivoz/Provider/Domain/Service/CompanyService/RemoveByBrandService.php, library/spec/Ivoz/Provider/Domain/Service/CompanyService/RemoveByBrandServiceSpec.php, web/admin/application/configs/klear/CompaniesList.yaml, web/admin/application/configs/klear/TpRatingProfilesList.yaml, web/admin/application/controllers/KlearCustomTarificatorController.php, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/library/IvozProvider/Klear/Importer/ImporterControllerTrait.php
Add call simulator into rating profiles
=> Call simulator

library/CoreBundle/Resources/config/model/provider/company.yml, library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/CompanyBalanceService.php, library/Ivoz/Provider/Domain/Service/Company/AbstractBalanceOperation.php, library/Ivoz/Provider/Domain/Service/Company/CompanyBalanceServiceInterface.php, library/Ivoz/Provider/Domain/Service/Company/DecrementBalance.php, web/admin/application/assets/js/customIncrementBalance.js, web/admin/application/configs/klear/CompanyBalancesList.yaml, web/admin/application/controllers/KlearCustomIncrementBalanceController.php, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
Allow balance decrement in admin portal
=> Decrement balance

library/Ivoz/Cgr/Domain/Model/TpRatingProfile/SimulatedCall.php, library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/BillingService.php, web/admin/application/assets/js/customTarificator.js, web/admin/application/configs/klear/RatingPlansList.yaml, web/admin/application/configs/klear/TpRatingPlansList.yaml, web/admin/application/configs/klear/model/MediaRelaySets.yaml, web/admin/application/configs/klear/model/TpRatingPlans.yaml, web/admin/application/controllers/KlearCustomTarificatorController.php, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
Include call simulator within rating plans and tp rating plans
=> Brand level call simulator

ChangeLog, README.md, asterisk/config/pjsip.conf, doc/dev/RELEASE.md, doc/sphinx/conf.py, kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg
Documentation update and version changes for 2.2 releasing
=> Version 2.2 documentation

library/IvozProvider/Gearmand/Invoices/Generator.php
This PR aims to fix the issue reported in https://github.com/irontec/ivozprovider/issues/462
=> bug: fixed invoice timezone conversion

debian/ivozprovider.config
=> corrected typo in debian config script

README.md
=> include branch name in doc links - oasis

README.md
This PR contains the original text proposal from our communication crew.
Kudos to @manfer for this tutorial!!
=> Update README with installation tutorial for oasis

web/admin/application/configs/klear/RoutingPatternGroupsList.yaml, web/admin/application/configs/klear/RoutingPatternGroupsRelPatternsList.yaml, web/admin/application/configs/klear/model/RoutingPatternGroups.yaml
Routing Pattern Groups GUI is broken. Not totally sure but I think this is the correct fix.
=> portals: fix Routing Pattern Groups GUI

web/admin/application/configs/klear/CompaniesList.yaml, web/admin/application/configs/klear/DDIsList.yaml, web/admin/application/configs/klear/PeeringContractsList.yaml, web/admin/application/configs/klear/RetailClientsList.yaml, web/admin/application/configs/klear/WholesaleClientsList.yaml, web/admin/application/configs/klear/klear.yaml, web/admin/application/controllers/KlearCustomExtraAuthController.php, web/admin/application/library/IvozProvider/Klear/Auth/Adapter.php
Feature based menus were not working as expected through brand / admin urls.
This PR aims to fix the issue reported at https://github.com/irontec/ivozprovider/issues/507
=> web/admin: fixed feature based klear menu filters

kamailio/trunks/config/kamailio.cfg
=> kamtrunks: Skip GW if contains unresolvable domain

web/admin/application/configs/klear/MatchListsList.yaml, web/admin/application/configs/klear/TransformationRuleSetsList.yaml
Filter by name was not working at numeric transformation section (admin portal)
=> web/admin: wrap rawConditions in order to avoid filtering errors

ChangeLog, README.md
Is anything important missing? :thinking:
=> doc: update ChangeLog for 2.3.0 release

debian/ivozprovider-profile-portal.postinst, profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf
Enable apache http2 module and set it as preferred protocol
=> Enable http2 protocol

library/Ivoz/Provider/Application/Service/Recording/RecordingDtoAssembler.php, microservices/recordings/app/config/services.yml, microservices/recordings/src/Recording/Encoder.php
This PR implements #488 
- Fix Recording path resolver extension bug
- Add support for on-demand and DDI recordings from rtpengine wav files
- Removed all rotation commented logics
=> recordings: update microservice to handle rtpengine-recordings

cgrates/config/cgrates.json, library/CoreBundle/Resources/config/services/infraestructure/cgrates.yml, library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/RerateCallService.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrRepository.php, library/Ivoz/Kam/Domain/Service/TrunksCdr/RerateCallServiceInterface.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php, web/admin/application/configs/klear/KamTrunksCdrsBrandList.yaml, web/admin/application/configs/klear/KamTrunksCdrsList.yaml, web/admin/application/controllers/KlearCustomTarificatorController.php, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
Get rerate feature back
This PR aims to fix https://github.com/irontec/ivozprovider/issues/525
=> Call retarification

ChangeLog, README.md
Changelog mentioning the main changes in the release.
Please review and update with anything missing or not worth to be mentioned.
=> doc: updated ChangeLog for 2.4.0

library/DataFixtures/ORM/ProviderInvoiceNumberSequence.php, library/Ivoz/Provider/Domain/Model/InvoiceNumberSequence/InvoiceNumberSequenceDto.php, library/Ivoz/Provider/Domain/Service/InvoiceNumberSequence/CheckValidity.php, web/rest/app/config/api/raw/provider.yml, web/rest/app/config/api_platform.yml, web/rest/features/provider/invoiceNumberSequence/getInvoiceNumberSequence.feature, web/rest/features/provider/invoiceNumberSequence/postInvoiceNumberSequence.feature, web/rest/features/provider/invoiceNumberSequence/putInvoiceNumberSequence.feature, web/rest/features/provider/invoiceNumberSequence/removeInvoiceNumberSequence.feature, web/rest/tests/Provider/InvoiceNumberSequence/InvoiceNumberSequenceLifeCycleTest.php
Add it into the API, enforce integrity and add some tests
=> Invoice number sequence improvements

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallForwardSetting.CallForwardSettingAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ExternalCallFilter.ExternalCallFilterAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20180713111050.php
This PR fixes some invalid constraints in mentioned tables. Let's the test run!
=> Fix for ExternalCallFilters and CallForwardSettings foreign keys

ChangeLog, README.md, extra/simple-cdd/package.list, web/rest/app/config/api_platform.yml
Main releases changes, based on 2.5.0 milestone
This PR also includes a fix of ChangeLog file, so all the lines have the same indentation. I have splitted the changes in different commits.
=> Updated Changelog for 2.5.0

web/admin/application/configs/klear/model/KamTrunksCdrs.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
=> web/admin: change Peering Contract to Carrier in billable calls

library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/BillingService.php, library/Ivoz/Provider/Domain/Model/RoutingTag/RoutingTagRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/RoutingTagDoctrineRepository.php, web/admin/application/configs/klear/model/RatingProfiles.yaml, web/admin/application/controllers/KlearCustomTarificatorController.php, web/admin/application/library/IvozProvider/Klear/Filter/RouteTag.php
Make simulator work with routingTags in Retail and Wholesale List of Rating Profiles subsection.
This PR aims to close https://github.com/irontec/ivozprovider/issues/599
=> Routing tags into call simulator

web/admin/application/configs/klear/CompanyBalancesList.yaml, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/library/IvozProvider/Klear/Dynamic/Config/Base.php
Several minor web/admin fixes.
=> web/admin: minor fixes

library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/RerateCallService.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrRepository.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php, library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallRepository.php, library/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromTrunksCdr.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php, web/admin/application/controllers/KlearCustomTarificatorController.php
This PR fixes #614, applying changes to rerating mechanism to make it work with new BillableCalls table.
=> Use BillableCalls table in rerating mechanism

library/Ivoz/Core/Infrastructure/Persistence/Doctrine/Traits/GetGeneratorByConditionsTrait.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrRepository.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php, library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallRepository.php, library/Ivoz/Provider/Domain/Service/Invoice/CheckValidity.php, library/Ivoz/Provider/Domain/Service/Invoice/Generator.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php, library/spec/Ivoz/Provider/Domain/Service/Invoice/CheckValiditySpec.php, microservices/workers/src/Worker/Invoices.php
This PR fixes #616 by removing unused entities from the Invoicer Task.
=> Update invoicer process with new entity BillableCall

ChangeLog, README.md
Changelog entry and Readme updated for 2.6.0 release
=> doc: update changelog for 2.6.0

kamailio/trunks/config/kamailio.cfg, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrDtoAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrInterface.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksCdr.TrunksCdrAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20180817101632.php
Remove these unused fields from kam_trunks_cdrs table:
- invoiceId
- price
- priceDetails
- referrer
- referee
=> Remove kam_trunks_cdrs unneeded fields

library/Ivoz/Cgr/Domain/Model/TpRatingProfile/SimulatedCall.php
Update call simulator to the latest database schema. This PR fixes https://github.com/irontec/ivozprovider/issues/628
=> bug: fixed call to nonexistent method

microservices/workers/src/Worker/Rates.php
=> microservices: fix Rates importer tp_destination_rates tag

kamailio/trunks/config/kamailio.cfg
=> Fix routing failover

web/admin/application/controllers/KlearCustomDownloadFileController.php, web/admin/application/controllers/KlearCustomExtraAuthController.php, web/admin/application/controllers/KlearCustomForwardFaxController.php, web/admin/application/controllers/KlearCustomIncrementBalanceController.php, web/admin/application/controllers/KlearCustomInvoiceTemplateTesterController.php, web/admin/application/controllers/KlearCustomRestoreBackupController.php, web/admin/application/controllers/KlearCustomRestoreDefaultController.php, web/admin/application/controllers/KlearCustomRunCodeController.php, web/admin/application/controllers/KlearCustomUploadFileController.php, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
=> web/admin: fix transltions in web custom popup dialogs

kamailio/trunks/config/kamailio.cfg, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRouting.php, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingAbstract.php, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingDtoAbstract.php, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/OutgoingRouting.OutgoingRoutingAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20180906173440.php, web/admin/application/configs/klear/OutgoingRoutingList.yaml, web/admin/application/configs/klear/model/OutgoingRouting.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
=> Numeric transformations depending on outgoing route

kamailio/trunks/config/kamailio.cfg
=> kamtrunks: Avoid failover for 480 responses

library/Ivoz/Provider/Domain/Model/RatingPlan/RatingPlanAbstract.php, library/Ivoz/Provider/Domain/Model/RatingPlan/RatingPlanInterface.php, library/Ivoz/Provider/Domain/Model/RatingPlanGroup/RatingPlanGroupDtoAbstract.php, library/Ivoz/Provider/Domain/Model/RatingPlanGroup/RatingPlanGroupInterface.php, library/Ivoz/Provider/Domain/Model/RatingPlanGroup/RatingPlanGroupRepository.php, library/Ivoz/Provider/Domain/Model/RatingPlanGroup/RatingPlanGroupTrait.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/RatingPlan.RatingPlanAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/RatingPlanGroup.RatingPlanGroup.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/RatingPlanGroupDoctrineRepository.php, web/admin/application/configs/klear/RatingProfilesCompanyList.yaml, web/admin/application/configs/klear/RatingProfilesList.yaml, web/admin/application/configs/klear/klear.yaml, web/admin/application/controllers/KlearCustomDownloadRatingPlanController.php, web/admin/application/controllers/KlearCustomTarificatorController.php, web/admin/application/library/IvozProvider/Service/RestClient.php, web/rest/brand/app/config/api/raw/provider.yml, web/rest/brand/app/config/api/resources.yml, web/rest/brand/app/config/routing.yml, web/rest/brand/app/config/services.yml, web/rest/brand/src/Controller/My/RatingPlanPricesAction.php, web/rest/brand/src/Model/RatingPlanPrices.php, web/rest/client/app/config/services.yml
=> Pricing plan csv

library/Ivoz/Provider/Domain/Model/User/UserDto.php, web/rest/client/app/config/api/raw/provider.yml, web/user/app/modules/preferences/preferencesCtrl.js
Save timezone from user portal properly
=> Fixed user portal preferences

cgrates/config/cgrates.json, library/Ivoz/Cgr/Domain/Model/TpRatingProfile/SimulatedCall.php
=> billing: rounding precision and method

scheme/deltas/085-create-cdr-indexes.sql
=> scheme: add indexes to make portals faster

kamailio/recordings/application/controllers/RecordingsController.php, library/IvozProvider/Klear/Ghost/RecordingsType.php
Keep callId information in ID3 artist tag
This PR fixes #659
=> recordings: Improved downloaded file name

portals/application/configs/klear/RecordingsList.yaml
Make use of the feature introduced here: https://github.com/irontec/klearMatrix/commit/0740aaad67a0deb30d49de40f87804277b7a6beb
This PR aims to fix #658
=> web/admin: download multiple recording files

cgrates/config/cgrates.json
This PR along as irontec/cgrates@9eb5d7d76e1433557ac771944be8fb2c6a3e90aa tries to fix #703.
=> cgrates: use sm_costs for initial rating of prepaid calls

library/Ivoz/Ast/Domain/Service/Queue/UpdateByIvozQueue.php
=> queues: periodic announcements are not reproduced

web/admin/application/controllers/KlearCustomExtraAuthController.php
There was an error on retail client emulation from list screen
This PR aims to fix https://github.com/irontec/ivozprovider/issues/707
=> web/admin: fixed retail emulation from list screen

library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/RerateCallService.php, web/admin/application/controllers/KlearCustomTarificatorController.php
Log API error responses to syslog and show an error message on klear
This PR fixes https://github.com/irontec/ivozprovider/issues/697
=> Improve rerate feedback on error

library/bin/cache-clear, library/bin/cache-rm
Updated application paths and added cache-rm script
=> core: updated cache clear scripts

asterisk/agi/src/Agi/Action/HuntGroupCallAction.php
This aims to solve https://github.com/irontec/ivozprovider/issues/719
=> remove duplicate g option

library/DataFixtures/ORM/ProviderInvoice.php, library/Ivoz/Provider/Domain/Model/Invoice/Invoice.php, library/Ivoz/Provider/Domain/Service/Invoice/CheckValidity.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php, web/admin/application/configs/klear/InvoicesList.yaml, web/admin/application/library/IvozProvider/Klear/Auth/User.php, web/admin/application/library/IvozProvider/Klear/Options/OptionsCustomizer.php, web/rest/brand/features/provider/fixedCostsRelInvoice/getFixedCostsRelInvoice.feature, web/rest/brand/features/provider/fixedCostsRelInvoice/postFixedCostsRelInvoice.feature, web/rest/brand/features/provider/fixedCostsRelInvoice/putFixedCostsRelInvoice.feature
This PR aims to fix https://github.com/irontec/ivozprovider/issues/716
=> Allow invoice regeneration

web/admin/application/configs/klear/CarriersList.yaml, web/admin/application/configs/klear/DdiProviderAddressesList.yaml, web/admin/application/configs/klear/DdiProvidersList.yaml, web/admin/application/configs/klear/model/DdiProviderRegistrations.yaml
=> Fix DDI provider registration delete

doc/sphinx/administration_portal/client/retail/retail_accounts.rst, doc/sphinx/administration_portal/platform/billable_calls.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrDtoAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrInterface.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksCdr.TrunksCdrAbstract.orm.yml, library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallAbstract.php, library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallDto.php, library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallDtoAbstract.php, library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallInterface.php, library/Ivoz/Provider/Domain/Service/BillableCall/CsvExporter.php, library/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromTrunksCdr.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20181019144832.php, web/admin/application/configs/klear/BillableCallsBrandList.yaml, web/admin/application/configs/klear/BillableCallsClientList.yaml, web/admin/application/configs/klear/BillableCallsList.yaml, web/admin/application/configs/klear/RetailAccountsList.yaml, web/admin/application/configs/klear/model/BillableCalls.yaml, web/admin/application/configs/klear/model/RetailAccounts.yaml, web/admin/application/controllers/KlearCustomBillableCallsController.php, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
=> CDRs: transport retailAccountId to kam_trunks_cdrs

debian/ivozprovider.postinst
To solve the problem explained in https://github.com/irontec/ivozprovider/issues/747
=> pkg: update demo company domain fix

doc/sphinx/administration_portal/brand/clients/residential.rst, doc/sphinx/administration_portal/brand/clients/retail.rst, doc/sphinx/administration_portal/brand/clients/virtual_pbx.rst, doc/sphinx/administration_portal/brand/clients/wholesale.rst, doc/sphinx/administration_portal/brand/invoicing/invoices.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, doc/sphinx/locale/es/LC_MESSAGES/third_party_integrations.po, library/Ivoz/Provider/Domain/Model/Company/CompanyAbstract.php, library/Ivoz/Provider/Domain/Model/Company/CompanyDtoAbstract.php, library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20181024151114.php, web/admin/application/configs/klear/CompaniesList.yaml, web/admin/application/configs/klear/CompanyInvoicesList.yaml, web/admin/application/configs/klear/ResidentialClientsList.yaml, web/admin/application/configs/klear/RetailClientsList.yaml, web/admin/application/configs/klear/WholesaleClientsList.yaml, web/admin/application/configs/klear/klear.yaml, web/admin/application/configs/klear/model/Companies.yaml, web/admin/application/configs/klear/model/ResidentialClients.yaml, web/admin/application/configs/klear/model/RetailClients.yaml, web/admin/application/configs/klear/model/WholesaleClients.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/library/IvozProvider/Klear/Auth/User.php, web/rest/brand/features/provider/company/putCompanies.feature, web/rest/client/features/provider/matchList/postMatchList.feature, web/rest/client/features/provider/matchList/putMatchList.feature
Include a new boolean field in Company table to configure Invoice visibility in Clients section/portals. The client version of the section has very limited information but allows invoices download.
This PR fixes #732
=> Client invoices views

web/rest/brand/app/config/config.yml, web/rest/client/app/config/config.yml
Brand and Client API endpoints are broken into production environment
=> web/rest: fixed API endpoints in prod env

asterisk/agi/app/config/services.yml, asterisk/agi/src/Agi/Action/FaxReceiveAction.php, asterisk/agi/src/Agi/Action/FaxReceiveStatusAction.php, web/admin/application/controllers/KlearCustomForwardFaxController.php, web/admin/application/controllers/PortalController.php
Fix several typos and make tests to ensure it works as expected.
=> Fix virtual fax system

doc/sphinx/administration_portal/brand/settings/notification_templates.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po
=> doc: Notification body type

microservices/scheduler/bin/run
=> microservices: fix scheduler paths

library/Ivoz/Ast/Domain/Model/Voicemail/VoicemailAbstract.php, library/Ivoz/Ast/Domain/Model/Voicemail/VoicemailDtoAbstract.php, library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/Voicemail.VoicemailAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20181121130028.php
=> voicemail: say source cid when calling to voicemail service code

library/Ivoz/Core/Infrastructure/Domain/Service/Lifecycle/DoctrineEventSubscriber.php
Fixed regression introduced in https://github.com/irontec/ivozprovider/pull/779
=> core: avoid premature markAsPersisted

doc/sphinx/administration_portal/brand/calls/call_csv_schedulers.rst, doc/sphinx/administration_portal/brand/invoicing/invoice_schedulers.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerDtoAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerInterface.php, library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerAbstract.php, library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerDtoAbstract.php, library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerInterface.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/CreateByScheduler.php, library/Ivoz/Provider/Domain/Service/Invoice/CreateByScheduler.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallCsvScheduler.CallCsvSchedulerAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/InvoiceScheduler.InvoiceSchedulerAbstract.orm.yml, library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/CreateBySchedulerSpec.php, library/spec/Ivoz/Provider/Domain/Service/Invoice/CreateBySchedulerSpec.php, scheme/app/DoctrineMigrations/Version20181121085714.php, web/admin/application/configs/klear/CallCsvSchedulersList.yaml, web/admin/application/configs/klear/InvoiceSchedulersList.yaml, web/admin/application/configs/klear/model/CallCsvSchedulers.yaml, web/admin/application/configs/klear/model/InvoiceSchedulers.yaml, web/admin/application/library/IvozProvider/Klear/Ghost/SchedulerSuccess.php
Persist and show in admin portal any error happened during call csv scheduler execution
=> Schedulers last execution error

tests/docker/Dockerfile, web/admin/e2e/Dockerfile
Update Dockerfile to minimize image size and speedup tests.
=> devops: update Dockerfile with only required packages

library/Ivoz/Provider/Domain/Model/Company/CompanyAbstract.php, library/Ivoz/Provider/Domain/Model/Company/CompanyDtoAbstract.php, library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSender.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml, library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSenderSpec.php, scheme/app/DoctrineMigrations/Version20181121165124.php, web/admin/application/configs/klear/CompaniesList.yaml, web/admin/application/configs/klear/CompanyBalancesList.yaml, web/admin/application/configs/klear/ResidentialClientsList.yaml, web/admin/application/configs/klear/RetailClientsList.yaml, web/admin/application/configs/klear/WholesaleClientsList.yaml, web/admin/application/configs/klear/model/Companies.yaml, web/admin/application/configs/klear/model/ResidentialClients.yaml, web/admin/application/configs/klear/model/RetailClients.yaml, web/admin/application/configs/klear/model/WholesaleClients.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/library/IvozProvider/Klear/Filter/NotificationTemplateCallCsv.php, web/rest/brand/features/provider/administrator/putAdministrators.feature, web/rest/brand/features/provider/company/getCompanies.feature, web/rest/brand/features/provider/company/postCompanies.feature, web/rest/brand/features/provider/company/putCompanies.feature
Allow custom call CSV notification template selection by company
=> web/admin: make CSV notification templates configurable by client

doc/sphinx/administration_portal/brand/calls/call_csv_schedulers.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, library/Ivoz/Provider/Domain/Model/CallCsvReport/CallCsvReportAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvReport/CallCsvReportDtoAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvReport/CallCsvReportInterface.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvScheduler.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerInterface.php, library/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateDtoByTrunksCdr.php, library/Ivoz/Provider/Domain/Service/BillableCall/CsvExporter.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/CreateByScheduler.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/CsvAttacher.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSender.php, library/Ivoz/Provider/Domain/Service/InvoiceScheduler/NextExecutionResolverTrait.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallCsvReport.CallCsvReportAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallCsvScheduler.CallCsvSchedulerAbstract.orm.yml, library/spec/Ivoz/Provider/Domain/Service/BillableCall/CsvExporterSpec.php, library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/CreateBySchedulerSpec.php, scheme/app/DoctrineMigrations/Version20181127120015.php, web/admin/application/configs/klear/CallCsvReportsList.yaml, web/admin/application/configs/klear/CallCsvSchedulersList.yaml, web/admin/application/configs/klear/model/CallCsvSchedulers.yaml, web/admin/application/controllers/KlearCustomBillableCallsController.php, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
Allow to create brand level call CSV schedulers without company id
=> Brand call csv schedulers

library/Ivoz/Provider/Domain/Model/CallCsvReport/CallCsvReport.php, library/Ivoz/Provider/Domain/Model/CallCsvReport/CallCsvReportInterface.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/CsvAttacher.php, library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/CsvAttacherSpec.php, scheme/tests/Provider/CallCsvReport/CallCsvReportLifeCycleTest.php
Some minor bug fixing:
- Apply date time conversion even though it has not scheduler
- Prefer company name over brand name on attached CSV file
=> Call csv report revision

ChangeLog, README.md
Updated changelog entry and Readme for release 2.8.0
=> doc: update changelog for 2.8.0

web/admin/application/configs/klear/model/ExternalCallFiltersResidential.yaml
Delete button was broken on residential clients > external call filters
=> web/admin: fixed broken order argument in ExternalCallFiltersResidential

web/admin/application/configs/klear/CarriersList.yaml
Fixed billable calls screen access from carrier list
=> web/admin: fixed carrier billable calls screen

asterisk/agi/src/Agi/Action/ExternalFaxCallAction.php, asterisk/agi/src/Agi/Action/FaxReceiveAction.php, asterisk/agi/src/Agi/Action/FaxReceiveStatusAction.php, asterisk/agi/src/Agi/Action/ServiceAction.php, asterisk/agi/src/Dialplan/FaxDial.php, asterisk/agi/src/Dialplan/FaxDialStatus.php, asterisk/agi/src/Dialplan/FaxSendStatus.php, microservices/recordings/src/Recording/Encoder.php, microservices/workers/app/config/services.yml, microservices/workers/src/Worker/Multimedia.php, microservices/workers/src/Worker/Rates.php, microservices/workers/src/Worker/Xmlrpc.php
Propagate entityTools within AGIs and microservices
=> Updated abstractions

library/Ivoz/Provider/Domain/Model/Carrier/CarrierRepository.php, library/Ivoz/Provider/Domain/Service/Carrier/SyncBalances.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CarrierDoctrineRepository.php, library/spec/Ivoz/Provider/Domain/Service/Carrier/SyncBalancesSpec.php, scheme/tests/Provider/Carrier/CarrierRepositoryTest.php
Move query logic from the service into the repository and add tests
=> core: carrier sync balances refactoring

library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/BillingService.php, web/admin/application/controllers/KlearCustomTarificatorController.php
This PR combines #810 and #811, adding necessary changes suggested by @mikelmadariaga in https://github.com/irontec/ivozprovider/pull/810#issuecomment-443678455.
Thanks @powerpbx for your work!
=> web/admin: fix simulators timezones

ChangeLog, README.md
Next patch Artemis release Changelog entry
=> doc: update ChangeLog for 2.8.1 release

scheme/initial.sql
This PR updates initial.sql with all 2.x changes applied so new installations only require current minor database changes.
=> scheme: update initial.sql for 2.9 version

library/ApiBundle/Resources/config/services.yml, library/Ivoz/Api/Swagger/Metadata/Property/Factory/PropertySwaggerContextFactory.php, library/Ivoz/Api/Swagger/Metadata/Resource/ResourceMetadata/OperationMetadataFactory.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/CustomParameterDecorator.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/OrphanAttributeFixerDecorator.php
Resolve enums, default values, lengths, etc. from orm mapping metadata
=> web/rest: improved API spec

FAQ.md, README.md
This is only a basic initial version, feel free to add any missing point or remove what you don't find useful
=> doc: add basic faq documentation

doc/sphinx/administration_portal/client/vpbx/calls/call_recordings.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, kamailio/users/config/kamailio.cfg, web/admin/application/configs/klear/conf.d/recordingHelp.yaml, web/admin/application/configs/klear/model/Companies.yaml, web/admin/application/configs/klear/model/ResidentialClients.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
=> Remove on-demand record via xfer

web/admin/application/configs/application.ini, web/admin/public/zf.php
DomainExceptionListener is not being called properly on Zend framework applications
=> web/admin: log errors properly

doc/sphinx/locale/es/LC_MESSAGES/basic_concepts.po
Spanish translation for de Install section of documentation.
This PR is part of #723
=> i18n: update doc installation spanish translations

library/DataFixtures/ORM/ProviderHolidayDate.php, library/Ivoz/Provider/Domain/Model/Calendar/Calendar.php, library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDate.php, library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDateRepository.php, library/Ivoz/Provider/Domain/Service/HolidayDate/CheckEventDateCollision.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/HolidayDateDoctrineRepository.php, library/bin/test-all, library/spec/Ivoz/Provider/Domain/Model/Calendar/CalendarSpec.php, library/spec/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDateSpec.php, library/spec/Ivoz/Provider/Domain/Service/HolidayDate/CheckEventDateCollisionSpec.php, scheme/tests/Provider/HolidayDate/HolidayDateRepositoryTest.php, web/rest/client/features/provider/holidayDate/getHolidayDate.feature, web/rest/client/features/provider/holidayDate/postHolidayDate.feature
Added tests for features introduced in https://github.com/irontec/ivozprovider/pull/838
Includes some code refactoring in order to prevent errors
=> Calendar events tests

library/Ivoz/Provider/Domain/Model/Country/CountryDto.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20190114171641.php, web/admin/application/configs/klear/WholesaleClientsList.yaml, web/admin/application/configs/klear/model/WholesaleClients.yaml, web/rest/brand/features/provider/country/getCountry.feature, web/rest/client/app/config/api/resources.yml, web/rest/client/app/config/routing.yml, web/rest/client/features/provider/country/getCountry.feature, web/rest/client/src/Controller/My/CompanyCountryAction.php, web/rest/platform/features/provider/country/getCountry.feature, web/user/app/modules/detours/detoursCtrl.js, web/user/app/modules/detours/detoursEditCtrl.js, web/user/app/modules/detours/detoursNewCtrl.js, web/user/app/views/detours/edit.html, web/user/app/views/detours/new.html
Added country selector in user portal
=> User portal cfw settings

library/Ivoz/Provider/Domain/Model/Country/CountryDto.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml, scheme/app/DoctrineMigrations/Version20190114171641.php, web/admin/application/configs/klear/WholesaleClientsList.yaml, web/admin/application/configs/klear/model/WholesaleClients.yaml, web/rest/brand/features/provider/country/getCountry.feature, web/rest/client/app/config/api/resources.yml, web/rest/client/app/config/routing.yml, web/rest/client/features/provider/country/getCountry.feature, web/rest/client/src/Controller/My/CompanyCountryAction.php, web/rest/platform/features/provider/country/getCountry.feature, web/user/app/modules/detours/detoursCtrl.js, web/user/app/modules/detours/detoursEditCtrl.js, web/user/app/modules/detours/detoursNewCtrl.js, web/user/app/views/detours/edit.html, web/user/app/views/detours/new.html
Cherry-pick #859 changes to Artemis.
=> User portal cfw settings artemis

doc/sphinx/locale/es/LC_MESSAGES/basic_concepts.po
Spanish translation for platform roles documentation section
=> i18n: Platform roles

doc/sphinx/administration_portal/brand/calls/call_csv_schedulers.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvScheduler.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerDtoAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerInterface.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSender.php, library/Ivoz/Provider/Domain/Service/NotificationTemplateContent/CallCsvNotificationTemplateByCallCsvReport.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Brand.BrandAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallCsvScheduler.CallCsvSchedulerAbstract.orm.yml, library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSenderSpec.php, library/spec/Ivoz/Provider/Domain/Service/NotificationTemplateContent/CallCsvNotificationTemplateByCallCsvReportSpec.php, scheme/app/DoctrineMigrations/Version20190117144921.php, web/admin/application/configs/klear/CallCsvSchedulersBrandList.yaml, web/admin/application/configs/klear/CallCsvSchedulersList.yaml, web/admin/application/configs/klear/InvoicesList.yaml, web/admin/application/configs/klear/model/BalanceNotifications.yaml, web/admin/application/configs/klear/model/CallCsvSchedulers.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
Add the ability to receive brand call csv reports through email
This PR fixes #803
=> Call csv notification template for brands

scheme/app/DoctrineMigrations/Version20190121183004.php
Update default Numeric Transformations for Russia with NationaLength 10 and InternationalCode 810
This PR fixes #861
=> scheme: update russian numeric transformation to E.164

scheme/app/DoctrineMigrations/Version20190115143446.php
=> scheme: set aors for retail accounts

doc/sphinx/administration_portal/brand/clients/retail.rst, doc/sphinx/administration_portal/client/retail/ddis.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, kamailio/users/config/kamailio.cfg, web/admin/application/configs/klear/RetailClientsList.yaml, web/admin/application/configs/klear/RetailDdisList.yaml, web/admin/application/configs/klear/klear.yaml, web/admin/application/configs/klear/model/RetailClients.yaml, web/admin/application/library/IvozProvider/Klear/Filter/RetailFeatures.php
Currently all retail clients' calls are recorded.
This PR:
- Adds Recordings feature to Retail Clients.
- Clients with Recordings feature can enable/disable call recordings by DDI as Residential clients do.
=> retail clients: recordings feature

kamailio/users/config/kamailio.cfg, kamailio/users/config/multisocket.cfg.in
Read multisocket.cfg.in for further details
=> kamusers: add support for KamUsers additional IP addresses

library/ApiBundle/Resources/config/api_platform_base.yml, library/ApiBundle/Resources/config/services.yml, library/ApiBundle/Resources/config/services/hydra.yml, library/ApiBundle/Resources/config/services/swagger.yml, library/Ivoz/Api/Json/EventListener/AddCollectionHeaders.php, library/Ivoz/Api/Json/Serializer/Normalizer/EntityNormalizer.php, library/Ivoz/Api/JsonLd/Metadata/Property/Factory/PropertyNameCollectionFactory.php, library/Ivoz/Api/JsonLd/Serializer/Normalizer/EntityNormalizer.php, library/Ivoz/Api/Swagger/Metadata/Property/Factory/PropertySwaggerContextFactory.php, library/Ivoz/Api/Swagger/Metadata/Resource/ResourceMetadata/FilterMetadataFactory.php, library/Ivoz/Api/Swagger/Metadata/Resource/ResourceMetadata/OperationMetadataFactory.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/CollectionResponseHeaderFixedDecorator.php, web/rest/brand/app/config/routing.yml, web/rest/brand/app/config/security.yml, web/rest/brand/src/Service/AuthEndpointDecorator.php, web/rest/client/app/config/routing.yml, web/rest/client/app/config/security.yml, web/rest/client/src/Service/AuthEndpointDecorator.php, web/rest/platform/app/config/config.yml, web/rest/platform/app/config/routing.yml, web/rest/platform/app/config/security.yml, web/rest/platform/src/Service/AuthEndpointDecorator.php
- Reviewed OpenAPI specification: fixed typo on 'minimum' attribute and some other minor improvements
- Improved Hydra spec: resolve entity attributes properly
- Added some headers into collection json requests: X-Total-Items, X-Total-Pages, X-First-Page, X-Next-Page, X-Last-Page
- Set a proper password field format for admin login endpoints
=> Improved api spec

library/ApiBundle/Resources/config/api_platform_base.yml, library/ApiBundle/Resources/config/services/swagger.yml, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/CustomParameterDecorator.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/MissingReferenceFixerDecorator.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/ReferenceFixerDecorator.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/SearchFilterDecorator.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/UnusedDefinitionRemover.php, library/Ivoz/Api/Swagger/Ui/SwaggerUiAction.php, web/rest/brand/bin/test-api-spec, web/rest/client/bin/test-api-spec, web/rest/platform/bin/test-api-spec
Make APIs fully OpenAPI 2.0 spec compliant
=> Open api v2 spec compliant

library/ApiBundle/Resources/config/config.yml, library/Ivoz/Api/Swagger/Metadata/Resource/ResourceMetadata/FilterMetadataFactory.php, web/rest/brand/app/config/config.yml, web/rest/client/app/config/config.yml, web/rest/platform/app/config/config.yml
Some minor enhancements:
- allow to order by id
- use `like '%term%'` strategy on text search
- Expose API headers on CORS requests
=> Api improved list parameters

library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingDto.php, web/rest/brand/app/config/api/raw/provider.yml, web/rest/brand/features/provider/outgoingRouting/getOutgoingRouting.feature, web/rest/brand/features/provider/outgoingRouting/postOutgoingRouting.feature, web/rest/brand/features/provider/outgoingRouting/putOutgoingRouting.feature, web/rest/brand/features/provider/outgoingRouting/removeOutgoingRouting.feature, web/rest/client/app/config/api/raw/provider.yml
Move Outgoing Routing from client API to Brand API
=> Outgoing routing api endpoints

web/admin/application/controllers/KlearCustomBillableCallsController.php, web/admin/application/library/IvozProvider/Service/RestClient.php
Make use of the proper API based on logged in user
=> Fixed brand and client billable call CSV exporter

ChangeLog, README.md
Changelog update for the next release.
Please check and comment :)
=> doc: update changelog for 2.9.2 release

library/Ivoz/Provider/Domain/Model/HuntGroupsRelUser/HuntGroupsRelUser.php, web/admin/application/configs/klear/UsersList.yaml, web/admin/application/configs/klear/model/Users.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/library/IvozProvider/Klear/Filter/HuntGroupsRelUsers.php
Reviewed HuntGroupRelUser logic:
- Made priority and timeout required for non ringAll hunt groups
- Fixed klear error on user -> huntGroupRelUser -> delete dialog
- Do not allow to edit/create huntGroupRelUser through user screen anymore. It's still possible to check the list and remove items
=> Hunt groups rel user filters

Jenkinsfile
Reorder steps and reuse agents when possible. This way each step can have its own docker image if they want.
This also implements #886 by running a sidecar container with mysql for scheme tests
=> ci: add specific agent for each pipeline step

Jenkinsfile
Using Workspace Cleanup plugin
=> ci: Jenkins workspace cleanup

web/admin/application/configs/klear/CompaniesList.yaml, web/admin/application/configs/klear/CompanyBalancesList.yaml, web/admin/application/configs/klear/FaxesList.yaml, web/admin/application/configs/klear/FriendsList.yaml, web/admin/application/configs/klear/ResidentialClientsList.yaml, web/admin/application/configs/klear/RetailClientsList.yaml, web/admin/application/configs/klear/WholesaleClientsList.yaml, web/admin/application/configs/klear/model/Companies.yaml, web/admin/application/configs/klear/model/Faxes.yaml, web/admin/application/configs/klear/model/Friends.yaml, web/admin/application/configs/klear/model/ResidentialClients.yaml, web/admin/application/configs/klear/model/RetailClients.yaml, web/admin/application/library/IvozProvider/Klear/Auth/Adapter.php
Show API connection errors properly and fix some orders on list screens
=> Minor klear fixes

scheme/app/DoctrineMigrations/Version20190312114056.php
Enable all features in default brand DemoBrand, including Retail, Residential and Wholesale clients features.
=> scheme: enable all features in DemoBrand

ChangeLog, README.md
Update changelog with 2.9.3 main changes
=> doc: update changelog for 2.9.3 release

library/Ivoz/Cgr/Domain/Model/TpCdr/TpCdr.php, library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilter.php, library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOut.php, library/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThreshold.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/CreateByScheduler.php, library/Ivoz/Provider/Domain/Service/Invoice/CreateByScheduler.php
Do not trust that php default timezone is set to UTC
=> core: add timezone to every date time

cgrates/config/cgrates.json, web/admin/application/configs/klear/CarriersList.yaml
This PR disables temporarily ASR/ACD stats calculation added in #602 due to performance issues.
=> Disable carrier ASR/ACD quality measurements

library/Ivoz/Provider/Domain/Model/Administrator/AdministratorRepository.php, library/Ivoz/Provider/Domain/Service/Administrator/AdministratorLifecycleEventHandlerInterface.php, library/Ivoz/Provider/Domain/Service/Administrator/AdministratorLifecycleServiceCollection.php, library/Ivoz/Provider/Domain/Service/Administrator/CheckUniqueness.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/AdministratorDoctrineRepository.php
There was no unique constrait for platform admin names
=> core: ensure no duplicated username on platform admins

Jenkinsfile, asterisk/agi/app/config/security.yml, library/CoreBundle/Resources/config/security.yml, library/bin/test-app-console, microservices/balances/app/config/security.yml, microservices/recordings/app/config/security.yml, microservices/scheduler/app/config/security.yml, microservices/workers/app/config/security.yml
Ensure that application dependencies aren't broken by executing their bin/console
=> App console tests

library/Ivoz/Api/Core/Security/DataAccessControlParser.php, library/Ivoz/Api/EventListener/WriteListener.php, library/Ivoz/Api/Operation/ExchangeToken.php, web/rest/brand/app/config/api/resources.yml, web/rest/brand/app/config/routing.yml, web/rest/brand/app/config/security.yml, web/rest/brand/app/config/services.yml, web/rest/brand/src/Controller/Auth/TokenExchangeAction.php, web/rest/brand/src/Model/Token.php, web/rest/client/app/config/api/resources.yml, web/rest/client/app/config/routing.yml, web/rest/client/app/config/security.yml, web/rest/client/app/config/services.yml, web/rest/client/src/Controller/Auth/TokenExchangeAction.php, web/rest/client/src/Model/Token.php
Added token exchange endpoint to allow Platform/Brand admins to use brand/client APIS
=> web/rest: added token exchange endpoint

library/Ivoz/Core/Application/RegisterCommandTrait.php, microservices/balances/app/MicroKernel.php, microservices/recordings/app/MicroKernel.php, microservices/scheduler/src/BillableCallController.php, microservices/scheduler/src/CallCsvController.php, microservices/scheduler/src/InvoiceSchedulerController.php, microservices/workers/src/Worker/Cgrates.php, microservices/workers/src/Worker/Invoices.php, microservices/workers/src/Worker/Multimedia.php, microservices/workers/src/Worker/Rates.php, microservices/workers/src/Worker/Xmlrpc.php
Avoid generic / fall back command info on database changes triggered by microservices
=> core: register commands on microservices

library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointAbstract.php, library/Ivoz/Ast/Domain/Model/Queue/QueueAbstract.php, library/Ivoz/Ast/Domain/Model/Voicemail/VoicemailAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrAbstract.php, library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrAbstract.php, library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallAbstract.php, library/Ivoz/Provider/Domain/Model/Changelog/ChangelogAbstract.php, library/Ivoz/Provider/Domain/Model/Commandlog/CommandlogAbstract.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/File.php, library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOutAbstract.php, library/Ivoz/Provider/Domain/Model/FixedCost/FixedCostAbstract.php, library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDateAbstract.php, library/Ivoz/Provider/Domain/Model/InvoiceNumberSequence/InvoiceNumberSequenceAbstract.php, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingAbstract.php, library/Ivoz/Provider/Domain/Model/Queue/QueueAbstract.php, scheme/src/EntityGeneratorBundle/Tools/AbstractEntityGenerator.php
Remove some unnecessary auto generated code
=> Fixed empty conditions

web/admin/e2e/tests/dataFixtures/brand/companyURLs/new.json, web/admin/e2e/tests/dataFixtures/brand/webPortals/admin.json, web/admin/e2e/tests/dataFixtures/brand/webPortals/client.json, web/admin/e2e/tests/dataFixtures/brand/webPortals/new.json, web/admin/e2e/tests/dataFixtures/company/faxes/new.json, web/admin/e2e/tests/dataFixtures/company/friends/new.json, web/admin/e2e/tests/dataFixtures/platform/webPortal/new.json, web/admin/e2e/tests/features/1-platform/01-3-webPortals.feature, web/admin/e2e/tests/features/2-brand/04-1-clientPortals.feature, web/admin/e2e/tests/features/2-brand/04-2-companyURLs.feature, web/admin/e2e/tests/features/3-company/04-2-friendsPatterns.feature
=> tests: updated e2e admin tests

library/CoreBundle/Resources/config/lifecycle.yml, library/CoreBundle/Resources/config/logger.yml, microservices/recordings/app/config/config.yml, microservices/recordings/app/config/logger.yml, microservices/recordings/app/config/services.yml, microservices/workers/app/config/services.yml
=> core: reviewed loggers

web/admin/application/library/IvozProvider/Klear/Auth/Adapter.php, web/admin/application/library/IvozProvider/Service/RestClient.php, web/admin/e2e/nightwatch.conf.js, web/admin/e2e/package.json, web/admin/e2e/tests/dataFixtures/brand/webPortals/admin.json, web/admin/e2e/tests/dataFixtures/brand/webPortals/client.json, web/admin/e2e/tests/dataFixtures/platform/brandOperators/new.json, web/admin/e2e/tests/dataFixtures/platform/webPortal/new.json, web/admin/e2e/tests/features/1-platform/01-2-brandOperator.feature, web/admin/e2e/tests/features/1-platform/01-3-webPortals.feature, web/admin/e2e/tests/features/1-platform/09-mainOperators.feature, web/admin/e2e/tests/features/2-brand/03-3-companyAdmins.feature, web/admin/e2e/tests/features/2-brand/04-1-clientPortals.feature, web/admin/e2e/tests/features/2-brand/04-2-brandPortals.feature, web/admin/e2e/tests/features/login.feature, web/admin/e2e/tests/steps/login.js
Make use of specific API type urls
=> Client klear login

library/Ivoz/Provider/Domain/Model/HuntGroupsRelUser/HuntGroupsRelUser.php, library/spec/Ivoz/Provider/Domain/Model/HuntGroupsRelUser/HuntGroupsRelUserSpec.php
Fixed error when an user was added into random strategy hunt group
=> core: do not require user priority on random strategy hunt groups

library/CoreBundle/Resources/config/lifecycle/provider/friend.yml, library/Ivoz/Provider/Domain/Service/Friend/PersistErrorHandler.php, web/admin/application/configs/klear/errors.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po
=> core: improved duplicated friend priority error handler

library/Ivoz/Provider/Domain/Model/WebPortal/WebPortal.php, scheme/app/DoctrineMigrations/Version20190429075931.php, web/admin/application/configs/klear/ClientPortalsList.yaml, web/admin/application/configs/klear/PlatformPortalsList.yaml
Bugfix: God portals with brandId were being filtered on platform portal list
=> God web portal filter

kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg, library/DataFixtures/ORM/ProviderCompany.php, library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php, scheme/tests/Provider/Company/CompanySoftDeleteTest.php, web/rest/brand/app/config/api/resources.yml, web/rest/brand/app/config/routing.yml, web/rest/brand/features/my/activeCalls/getActiveCalls.feature, web/rest/brand/features/provider/company/postCompanies.feature, web/rest/brand/src/Controller/My/ActiveCallsAction.php, web/rest/brand/src/Model/ActiveCalls.php, web/rest/platform/app/config/api/resources.yml, web/rest/platform/app/config/routing.yml, web/rest/platform/app/config/services.yml, web/rest/platform/features/my/activeCalls/getActiveCalls.feature, web/rest/platform/src/Controller/My/ActiveCallsAction.php, web/rest/platform/src/Model/ActiveCalls.php
Expose platform/brand/company active calls through API
=> Active call endpoints

ChangeLog, README.md
=> doc: update changelog for 2.10.0 release

doc/dev/RELEASE.md, library/ApiBundle/Resources/config/api_platform_base.yml
API version bump and updated release doc so that we don't forget it the next time
=> web/admin: version bump to 2.11

library/Ivoz/Api/Swagger/Metadata/Property/Factory/PropertySwaggerContextFactory.php
Mark required fields on API model definitions
=> web/rest: add required attribute to API doc

library/Ivoz/Api/Behat/Context/FeatureContext.php, library/Ivoz/Api/EventListener/RegisterCommandListener.php, web/rest/brand/features/auth.feature, web/rest/brand/features/bootstrap/FeatureContext.php, web/rest/client/features/auth.feature, web/rest/client/features/bootstrap/FeatureContext.php
Fixed regression on anonymous security endpoints
=> Token exchange regression

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.yml, schema/app/DoctrineMigrations/Version20190515094552.php, web/admin/application/configs/klear/BillableCallsClientList.yaml
Add an index on startTime and optimize conditions on web portal
=> schema: speed up external calls

library/composer.json, library/composer.lock, schema/src/Entity/AbstractRefreshToken.orm.yml, schema/src/Entity/RefreshToken.orm.yml, web/rest/brand/app/config/config.yml, web/rest/brand/composer.lock, web/rest/client/app/config/config.yml, web/rest/client/composer.lock, web/rest/platform/app/config/config.yml, web/rest/platform/composer.json, web/rest/platform/composer.lock
Updated dependency for security fixes
Set custom user provider to refresh token so that new token roles are the correct ones (ROLE_USER currently)
=> Fixed roles on refreshed token

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php
Replace wrong condition with the right one.
Fixes regression introduced in 310ce72d397dbdbb901d7f23c8cbe98bf5da94f5.
=> Fix rerating condition in findUnratedInGroup

asterisk/agi/composer.json, asterisk/agi/composer.lock, library/CoreBundle/Resources/config/services/infraestructure/http.yml, library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/ApiClient.php, library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/ProcessExternalCdr.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdr.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrInterface.php, library/Ivoz/Provider/Domain/Service/BillableCall/UpdateByTpCdr.php, library/spec/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/ProcessExternalCdrSpec.php, library/spec/Ivoz/Provider/Domain/Service/BillableCall/UpdateByTpCdrSpec.php, microservices/recordings/composer.json, microservices/recordings/composer.lock
Try to avoid some manual work in case that cgrates was down during the call
=> Retry to rate calls without cgrid on cdr to BillableCall migration

library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpCdr.TpCdrAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.yml, schema/app/DoctrineMigrations/Version20190603115458.php
Added new indexes to BillableCalls and TpCdrs to speedup Call migration process.
=> schema: add indexes to speedup cdrmixer call migrator

library/DataFixtures/ORM/ProviderCompany.php, library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineEntityPersister.php, library/Ivoz/Core/Infrastructure/Domain/Service/Gearman/Jobs/Cgrates.php, library/Ivoz/Kam/Infrastructure/Domain/Service/Trusted/SendUsersPermissionsReloadRequest.php, library/Ivoz/Provider/Domain/Service/Brand/BrandLifecycleEventHandlerInterface.php, library/Ivoz/Provider/Domain/Service/DdiProvider/DdiProviderLifecycleEventHandlerInterface.php, library/Ivoz/Provider/Domain/Service/DdiProvider/DdiProviderLifecycleServiceCollection.php, library/Ivoz/Provider/Domain/Service/Domain/DeleteByBrand.php, library/Ivoz/Provider/Domain/Service/Domain/DeleteByCompany.php, library/Ivoz/Provider/Domain/Service/Domain/UpdateByBrand.php, library/Ivoz/Provider/Domain/Service/RoutingPattern/UpdateByBrand.php, library/Ivoz/Provider/Domain/Service/Service/UpdateByBrand.php, library/Ivoz/Provider/Infrastructure/Domain/Service/Company/SendUsersAddressPermissionsReloadRequest.php, library/Ivoz/Provider/Infrastructure/Domain/Service/Company/SendUsersTrustedPermissionsReloadRequest.php, library/Ivoz/Provider/Infrastructure/Domain/Service/DdiProvider/SendTrunksAddressPermissionsReloadRequest.php, library/Ivoz/Provider/Infrastructure/Domain/Service/RoutingPattern/SendTrunksLcrReloadRequest.php, library/Ivoz/Provider/Infrastructure/Domain/Service/RoutingPatternGroup/SendTrunksLcrReloadRequest.php, schema/tests/DbIntegrationTestHelperTrait.php, schema/tests/Provider/ApplicationServer/ApplicationServerLifeCycleTest.php, schema/tests/Provider/Company/CompanyLifeCycleTest.php, schema/tests/Provider/Company/CompanySoftDeleteTest.php, schema/tests/Provider/DdiProvider/DdiProviderLifeCycleTest.php, web/rest/brand/features/provider/company/postCompanies.feature
Added some missing reload requests:
- domain.reload on company/brand remove (any case with domain)
- kamtrunks.addressReload on DDI provider remove
- kamusers.addressReload on company remove
- kamusers.trustedReload and kamtrunks.trustedReload on wholesale remove
=> Kamailio reload request

asterisk/agi/src/Agi/Agents/UserAgent.php, doc/sphinx/administration_portal/client/vpbx/user_configuration/outgoing_ddi_rules.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, kamailio/users/config/kamailio.cfg, library/DataFixtures/ORM/ProviderOutgoingDdiRulesPattern.php, library/Ivoz/Provider/Domain/Model/OutgoingDdiRule/OutgoingDdiRule.php, library/Ivoz/Provider/Domain/Model/OutgoingDdiRule/OutgoingDdiRuleInterface.php, library/Ivoz/Provider/Domain/Model/OutgoingDdiRulesPattern/OutgoingDdiRulesPattern.php, library/Ivoz/Provider/Domain/Model/OutgoingDdiRulesPattern/OutgoingDdiRulesPatternAbstract.php, library/Ivoz/Provider/Domain/Model/OutgoingDdiRulesPattern/OutgoingDdiRulesPatternDtoAbstract.php, library/Ivoz/Provider/Domain/Model/OutgoingDdiRulesPattern/OutgoingDdiRulesPatternInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/OutgoingDdiRulesPattern.OutgoingDdiRulesPatternAbstract.orm.yml, library/spec/Ivoz/Provider/Domain/Model/OutgoingDdiRulesPattern/OutgoingDdiRulesPatternSpec.php, schema/app/DoctrineMigrations/Version20190604091022.php, web/admin/application/configs/klear/OutgoingDDIRulesPatternsList.yaml, web/admin/application/configs/klear/model/OutgoingDdiRulesPatterns.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/library/IvozProvider/Klear/Ghost/OutgoingRule.php, web/rest/client/features/provider/outgoingDdiRulesPattern/getOutgoingDdiRulesPattern.feature, web/rest/client/features/provider/outgoingDdiRulesPattern/postOutgoingDdiRulesPattern.feature
Add prefix-alike DDI forcing for vPBX users using existing Outgoing DDI Rules framework.
=> Choose outbound DDI using prefix

library/ApiBundle/Resources/config/services.yml, library/Ivoz/Api/Behat/Context/FeatureContext.php, library/Ivoz/Api/Entity/Serializer/Normalizer/EntityDenormalizer.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/CustomParameterDecorator.php, library/Ivoz/Api/Symfony/EventListener/MultipartRequestListener.php, library/Ivoz/Api/Symfony/HttpFoundation/File/UploadedFile.php, library/Ivoz/Core/Domain/Service/TempFile.php, library/Ivoz/Provider/Domain/Model/Brand/BrandDto.php, library/Ivoz/Provider/Domain/Model/Locution/LocutionDto.php, library/Ivoz/Provider/Domain/Model/MusicOnHold/MusicOnHoldDto.php, library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalDto.php, web/rest/client/features/provider/locution/postLocution.feature, web/rest/client/features/provider/locution/putLocution.feature, web/rest/client/features/provider/musicOnHold/postMusicOnHold.feature, web/rest/client/features/provider/musicOnHold/putMusicOnHold.feature, web/rest/platform/app/config/routing.yml, web/rest/platform/features/provider/brand/postBrands.feature, web/rest/platform/features/provider/brand/putBrands.feature, web/rest/platform/features/provider/webPortal/getWebPortal.feature, web/rest/platform/features/provider/webPortal/postWebPortal.feature, web/rest/platform/features/provider/webPortal/putWebPortal.feature
Allow to upload files from the APIs
=> Handle api file uploads

ChangeLog, README.md
Documented main release changes
=> doc: update changelog for 2.11.0 release

library/DataFixtures/ORM/ProviderResidentialDevice.php, library/DataFixtures/ORM/ProviderRetailAccount.php, library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceDto.php, library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccountDto.php, web/rest/client/features/provider/residentialDevices/getResidentialDevice.feature, web/rest/client/features/provider/residentialDevices/postResidentialDevice.feature, web/rest/client/features/provider/residentialDevices/putResidentialDevice.feature, web/rest/client/features/provider/retailAccount/getRetailAccount.feature, web/rest/client/features/provider/retailAccount/postRetailAccount.feature, web/rest/client/features/provider/retailAccount/putRetailAccount.feature
There is no need to hide password
=> Show passwd on retail and residential

web/rest/brand/CHANGELOG.md, web/rest/brand/app/config/api/raw/provider.yml, web/rest/client/CHANGELOG.md, web/rest/client/app/config/api/raw/kam.yml, web/rest/client/app/config/api/raw/provider.yml, web/rest/client/app/config/api/resources.yml, web/rest/platform/CHANGELOG.md
Reviewed exposed API endpoints and added changelog files
=> Add API changelog

library/Ivoz/Core/Application/Service/Assembler/CustomDtoAssemblerInterface.php, library/Ivoz/Provider/Application/Service/Brand/BrandAssembler.php, library/Ivoz/Provider/Application/Service/Brand/BrandDtoAssembler.php, library/Ivoz/Provider/Application/Service/CallCsvReport/CallCsvReportAssembler.php, library/Ivoz/Provider/Application/Service/CallCsvReport/CallCsvReportDtoAssembler.php, library/Ivoz/Provider/Application/Service/DestinationRateGroup/DestinationRateGroupAssembler.php, library/Ivoz/Provider/Application/Service/DestinationRateGroup/DestinationRateGroupDtoAssembler.php, library/Ivoz/Provider/Application/Service/FaxesInOut/FaxesInOutAssembler.php, library/Ivoz/Provider/Application/Service/FaxesInOut/FaxesInOutDtoAssembler.php, library/Ivoz/Provider/Application/Service/Friend/FriendDtoAssembler.php, library/Ivoz/Provider/Application/Service/Invoice/InvoiceAssembler.php, library/Ivoz/Provider/Application/Service/Invoice/InvoiceDtoAssembler.php, library/Ivoz/Provider/Application/Service/Locution/LocutionAssembler.php, library/Ivoz/Provider/Application/Service/Locution/LocutionDtoAssembler.php, library/Ivoz/Provider/Application/Service/MusicOnHold/MusicOnHoldAssembler.php, library/Ivoz/Provider/Application/Service/MusicOnHold/MusicOnHoldDtoAssembler.php, library/Ivoz/Provider/Application/Service/Recording/RecordingAssembler.php, library/Ivoz/Provider/Application/Service/Recording/RecordingDtoAssembler.php, library/Ivoz/Provider/Application/Service/ResidentialDevice/ResidentialDeviceDtoAssembler.php, library/Ivoz/Provider/Application/Service/RetailAccount/RetailAccountDtoAssembler.php, library/Ivoz/Provider/Application/Service/Terminal/TerminalDtoAssembler.php, library/Ivoz/Provider/Application/Service/User/UserAssembler.php, library/Ivoz/Provider/Application/Service/WebPortal/WebPortalAssembler.php, library/Ivoz/Provider/Application/Service/WebPortal/WebPortalDtoAssembler.php
Fixed some comparisons that were wasting cpu cycles
There is no need of param comments if the they're properly hinted.
Renamed some variables in order to get cleaner code.
=> Updated assembler

library/Ivoz/Provider/Domain/Model/User/UserDto.php, web/rest/client/app/config/api/raw/provider.yml, web/rest/client/features/provider/user/getUser.feature, web/rest/client/features/provider/user/postUser.feature, web/rest/client/features/provider/user/putUser.feature, web/rest/client/features/provider/user/removeUser.feature, web/rest/client/tests/DataAccessControl/Provider/UserTest.php
Fixed access control rules
Fixed  new user pass treatment
This PR aims to fix https://github.com/irontec/ivozprovider/issues/1027
=> API create user regression

library/Ivoz/Core/Domain/Service/PersistErrorHandlerServiceCollection.php, library/Ivoz/Provider/Domain/Service/RatingPlan/PersistErrorHandler.php, library/spec/HelperTrait.php, library/spec/Ivoz/Core/Infrastructure/Domain/Service/Lifecycle/DoctrineEventSubscriberSpec.php
Fixed custom message on RatingPlan weight collision 
Fixed fallback error handler invocation when custom error handler exists
=> Fixed rating plan duplicated weight error

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Changelog.ChangelogAbstract.orm.yml, schema/app/DoctrineMigrations/Version20190625143639.php, schema/tests/Provider/Extension/ExtensionLifeCycleTest.php
Add indexes into:
- BillableCall (callid)
- Changelog (entity + entityId)
=> schema: add indexes on Changelog and BillableCall

library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineQueryRunner.php, library/Ivoz/Core/Infrastructure/Domain/Service/Lifecycle/CommandPersister.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php, schema/tests/Kam/TrunksCdr/TrunksCdrRepositoryTest.php, schema/tests/Provider/BillableCall/BillableCallRepositoryTest.php
Register mass updates into the changelog
=> Log mass updates

library/Ivoz/Api/Core/Security/DataAccessControlParser.php
Avoid unnecessary queries on API data access parser by caching the result
=> core: added response cache on DataAccessControlParser

web/admin/application/configs/klear/model/BillableCalls.yaml
Made BillableCall direction translatable
=> web/admin: made BillableCall direction translatable

library/Ivoz/Core/Application/Service/QueryBuilderFactory.php, web/admin/application/configs/klear/model/DestinationRates.yaml
Fixed sort rates by destination and added compatibility with the latest klearMatrix package
This PR aims to fix https://github.com/irontec/ivozprovider/issues/1036
=> Sort rates by destination

web/admin/application/controllers/ImportFileController.php
Fixed holiday date importer regression
=> web/admin: fixed holiday date importer

library/Ivoz/Api/Swagger/Metadata/Resource/ResourceMetadata/FileOperationMetadataFactory.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/CustomParameterDecorator.php, library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/MissingReferenceFixerDecorator.php, library/Ivoz/Core/Domain/Model/TempFileContainnerTrait.php, library/Ivoz/Core/Domain/Service/FileContainerInterface.php, library/Ivoz/Provider/Domain/Model/Brand/Brand.php, library/Ivoz/Provider/Domain/Model/Brand/BrandInterface.php, library/Ivoz/Provider/Domain/Model/CallCsvReport/CallCsvReport.php, library/Ivoz/Provider/Domain/Model/CallCsvReport/CallCsvReportInterface.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroup.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupInterface.php, library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOut.php, library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOutInterface.php, library/Ivoz/Provider/Domain/Model/Invoice/Invoice.php, library/Ivoz/Provider/Domain/Model/Invoice/InvoiceInterface.php, library/Ivoz/Provider/Domain/Model/Locution/Locution.php, library/Ivoz/Provider/Domain/Model/Locution/LocutionInterface.php, library/Ivoz/Provider/Domain/Model/MusicOnHold/MusicOnHold.php, library/Ivoz/Provider/Domain/Model/MusicOnHold/MusicOnHoldInterface.php, library/Ivoz/Provider/Domain/Model/Recording/Recording.php, library/Ivoz/Provider/Domain/Model/Recording/RecordingInterface.php, library/Ivoz/Provider/Domain/Model/WebPortal/WebPortal.php, library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalInterface.php, web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
Filter download only files
Skip file download endpoints if no item getter is found
=> Restrict file uploads on api

ChangeLog, README.md, library/ApiBundle/Resources/config/api_platform_base.yml
=> doc: Release 2.11.1 changelog

library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineQueryRunner.php
Retry transaction on mass update lock issues
=> core: retry mass updates on lock issues

web/admin/application/library/IvozProvider/Klear/Filter/QueueStrategies.php
=> web/admin: fixed multi delete on queues

library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/UnusedDefinitionRemover.php, web/rest/brand/CHANGELOG.md, web/rest/brand/app/config/api/raw/provider.yml, web/rest/client/CHANGELOG.md
Minor bugfix so that all unused models are removed
Added API changelogs for 2.11.2
=> Remove unused api models

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, FAQ.md, README.md
Also include all ivozprovider-users group in documentation and
updates FAQ to a numeric list for easy reference.
Fixes  #1079
=> github: add templates for bug reports and pull requests

ChangeLog, README.md
Main release changes. Pending API changes (if any)
=> doc: update changelog for 2.11.2 release

library/Ivoz/Core/Infrastructure/Domain/Service/Gearman/Jobs/AbstractJob.php, library/Ivoz/Core/Infrastructure/Domain/Service/Gearman/Jobs/Xmlrpc.php, web/admin/application/controllers/KlearCustomGenerateInvoiceController.php
Ensure gearman response is successful or log & show the error
=> Check gearman client response

library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineQueryRunner.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php
Reduce mass update lock times by getting target ids first.
Wait 2 seconds on transaction retries as well
=> core: reduced mass update table lock times and added delayed retries

doc/sphinx/administration_portal/client/residential/residential_devices.rst, doc/sphinx/administration_portal/client/vpbx/users.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, doc/sphinx/locale/es/LC_MESSAGES/basic_concepts.po, web/admin/application/configs/klear/OutgoingRoutingList.yaml, web/admin/application/configs/klear/model/Ddis.yaml, web/admin/application/configs/klear/model/Faxes.yaml, web/admin/application/configs/klear/model/Friends.yaml, web/admin/application/configs/klear/model/OutgoingDdiRules.yaml, web/admin/application/configs/klear/model/OutgoingDdiRulesPatterns.yaml, web/admin/application/configs/klear/model/ResidentialDevices.yaml, web/admin/application/configs/klear/model/RetailAccounts.yaml, web/admin/application/configs/klear/model/Users.yaml, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/user/app/languages/locale-en.json, web/user/app/languages/locale-es.json, web/user/app/views/preferences/preferences.html
Minor web changes (no functional changes):
- replace endpoint maxcalls with call waiting
- replace company with client
- order Outgoing Routes by prio and weight
Documentation and translations updated accordingly.
=> web/admin: web UI non-functional changes

web/rest/client/app/config/api/raw/provider.yml, web/rest/client/features/provider/residentialDevices/postResidentialDevice.feature, web/rest/client/features/provider/residentialDevices/removeResidentialDevice.feature, web/rest/client/features/provider/retailAccount/postRetailAccount.feature, web/rest/client/features/provider/retailAccount/removeRetailAccount.feature
Removed POST and DELETE methods from ResidentialDevice and RetailAccount (client API)
=> Reviewed client api endpoints

library/Ivoz/Api/Core/Security/DataAccessControlParser.php, web/rest/brand/app/config/api/raw/provider.yml, web/rest/client/app/config/api/raw/provider.yml, web/rest/platform/app/config/api/raw/provider.yml
=> Simplified api security config

library/Ivoz/Cgr/Domain/Model/TpCdr/TpCdr.php, library/Ivoz/Cgr/Domain/Model/TpRatingProfile/SimulatedCall.php, library/Ivoz/Cgr/Domain/Service/TpRatingPlan/UpdateByRatingPlan.php, library/spec/HelperTrait.php, library/spec/Ivoz/Cgr/Domain/Model/TpCdr/TpCdrSpec.php, library/spec/Ivoz/Cgr/Domain/Model/TpRate/TpRateSpec.php, library/spec/Ivoz/Cgr/Domain/Model/TpRatingProfile/SimulatedCallSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpDestination/CreatedByDestinationSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpDestinationRate/UpdatedByDestinationRateSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpLcrRule/CreatedByOutgoingRoutingSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpRate/UpdatedByDestinationRateSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpRatingPlan/UpdateByRatingPlanSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpRatingProfile/CreatedByCarrierRatingProfileSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpRatingProfile/CreatedByOutgoingRoutingRelCarrierSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpRatingProfile/UpdateByRatingProfileSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpTiming/CreatedByRatingPlanSpec.php, library/spec/Ivoz/Cgr/Domain/Service/TpTiming/DeletedByRatingPlanSpec.php
Minor error prevention patches and some unit test
=> Error prevention on cgr models and services

library/CoreBundle/Resources/config/services/infraestructure/kam.yml, library/Ivoz/Kam/Domain/Service/TrunksClientInterface.php, library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php, web/admin/application/configs/klear/DdiProviderRegistrationsList.yaml, web/admin/application/configs/klear/model/DdiProviderRegistrations.yaml, web/admin/application/library/IvozProvider/Klear/Ghost/RegisterStatus.php
=> Ddi provider registration status

web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> docs: added API changelog for 2.12

ChangeLog, README.md, web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> doc: Changelog for 2.12

library/Ivoz/Core/Application/Helper/LifecycleServiceHelper.php, library/Ivoz/Core/Domain/Service/LifecycleEventHandlerInterface.php, library/Ivoz/Core/Infrastructure/Symfony/DependencyInjection/Compiler/DomainServiceCompiler.php, library/Ivoz/Provider/Domain/Service/BalanceNotification/BalanceNotificationLifecycleServiceCollection.php, library/Ivoz/Provider/Domain/Service/BillableCall/BillableCallLifecycleServiceCollection.php, schema/src/EntityGeneratorBundle/Command/UpdateServiceCollectionsCommand.php
List domain event handlers on service collections
=> Show domain event subscribers on service collections

schema/app/DoctrineMigrations/Version20190912162641.php
Added notification templates for CA (based on spanish) and IT (based on english)
- Call CSV Notifications
- Invoice Notifications
- Voicemail Notifications
- Fax Notifications
- Low balance Notifications
=> schema: add notification templates for CA and IT languages

web/admin/application/languages/en_US/en_US.po
syntax error
Syntax error located while doing CA translation
=> i18n syntax correction Update en_US.po

doc/sphinx/administration_portal/brand/invoicing/invoices.rst, doc/sphinx/administration_portal/brand/providers/carriers.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, schema/tests/Provider/CallCsvReport/CreateBySchedulerServiceTest.php, web/admin/application/controllers/KlearCustomBillableCallsController.php, web/admin/application/library/IvozProvider/Service/RestClient.php
Switch target API by screen on external call CSV exporters
=> web/admin: fixed filters on external call CSV exporters

library/Ivoz/Core/Application/Service/EntityTools.php, library/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromUnparsedTrunksCdr.php
Clear entities from unit of work on each unparsed call loop
=> microservices: release memory on trunksCdr migrationprocess

library/Ivoz/Core/Application/Helper/LifecycleServiceHelper.php, library/Ivoz/Core/Infrastructure/Symfony/DependencyInjection/Compiler/DomainServiceCompiler.php, library/Ivoz/Kam/Domain/Service/TrunksCdr/TrunksCdrLifecycleServiceCollection.php
Set domain event handlers on their proper service collection
=> core: fixed domain event representation on service collections

schema/app/DoctrineMigrations/Version20191008111009.php
This commit should not affect to existing Artemis generated data and it's designed to make consistent Oasis migrated rows.
=> schema: update migrated OutgoingDDIRulesPatterns type field

schema/app/DoctrineMigrations/Version20191008113235.php
This commit should not affect to existing Artemis generated data and it's designed to make consistent Oasis migrated rows.
=> schema: update migrated IVrEntries number country

web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> docs: updated API changelog for 2.12.1

doc/sphinx/administration_portal/brand/billing/destination_rates.rst, doc/sphinx/administration_portal/client/vpbx/routing_tools/calendars.rst, doc/sphinx/administration_portal/client/vpbx/routing_tools/match_lists.rst, doc/sphinx/administration_portal/client/vpbx/user_configuration/call_acls.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, doc/sphinx/locale/es/LC_MESSAGES/security_and_maintenance.po, doc/sphinx/security_and_maintenance/security/firewall.rst, web/admin/application/configs/klear/model/MatchListPatterns.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
- WS(S) ports in security
- E.164 number in regexp must escape plus symbol.
- Hints about importing multiple price CSV in the same destination-rates row.
- Difference between partial holiday event and timetible events.
=> doc: improve several explanations

ChangeLog, README.md
Main features and fixes for 2.12.1 release
=> doc: updated changelog for 2.12.1

library/CoreBundle/Resources/config/model/provider/carrier.yml, library/CoreBundle/Resources/config/model/provider/company.yml
Fixed regression on balance operations (both company and carrier)
=> core: fixed balance operations

asterisk/agi/composer.lock, library/Ivoz/Provider/Domain/Service/Invoice/Generator.php, library/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.json, microservices/workers/composer.lock, schema/composer.lock, web/admin/application/controllers/KlearCustomInvoiceTemplateTesterController.php, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.json, web/rest/platform/composer.lock
Updated php dependencies and removed i386 architecture references
Removing h4cc/wkhtmltopdf-i386 (0.12.3)
Updating symfony/polyfill-ctype (v1.10.0 => v1.12.0)
Updating twig/twig (v1.35.4 => v1.42.3)
Updating paragonie/random_compat (v2.0.17 => v2.0.18)
Updating symfony/polyfill-php70 (v1.10.0 => v1.12.0)
Updating symfony/polyfill-util (v1.10.0 => v1.12.0)
Updating symfony/polyfill-php56 (v1.10.0 => v1.12.0)
Updating symfony/polyfill-mbstring (v1.10.0 => v1.12.0)
Updating symfony/symfony (v3.4.18 => v3.4.32)
Updating symfony/polyfill-intl-icu (v1.10.0 => v1.12.0)
Updating symfony/polyfill-apcu (v1.10.0 => v1.12.0)
Updating psr/log (1.0.2 => 1.1.0)
Updating doctrine/lexer (v1.0.1 => 1.0.2)
Updating api-platform/core (v2.2.9 => v2.2.10)
Updating beberlei/assert (v2.9.6 => v2.9.9)
Updating …
=> Updated composer dependencies

doc/sphinx/administration_portal/platform/default_invoice_templates.rst, doc/sphinx/administration_portal/platform/index.rst, doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, library/DataFixtures/ORM/ProviderInvoiceTemplate.php, library/Ivoz/Provider/Domain/Model/InvoiceTemplate/InvoiceTemplateAbstract.php, library/Ivoz/Provider/Domain/Model/InvoiceTemplate/InvoiceTemplateInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/InvoiceTemplate.InvoiceTemplateAbstract.orm.yml, schema/app/DoctrineMigrations/Version20191025092721.php, web/admin/application/configs/klear/DefaultInvoiceTemplatesList.yaml, web/admin/application/configs/klear/klear.yaml, web/admin/application/configs/klear/model/InvoiceSchedulers.yaml, web/admin/application/configs/klear/model/Invoices.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po, web/admin/application/library/IvozProvider/Klear/Filter/InvoiceTemplates.php, web/admin/application/library/IvozProvider/Klear/Options/OptionsCustomizer.php, web/rest/brand/app/config/api/raw/provider.yml, web/rest/brand/tests/DataAccessControl/Provider/InvoiceTemplateTest.php, web/rest/brand/tests/DataAccessControl/Provider/InvoiceTest.php, web/rest/platform/app/config/api/raw/provider.yml, web/rest/platform/features/provider/invoiceTemplate/getInvoiceTemplate.feature, web/rest/platform/features/provider/invoiceTemplate/postInvoiceTemplate.feature, web/rest/platform/features/provider/invoiceTemplate/putInvoiceTemplate.feature, web/rest/platform/features/provider/invoiceTemplate/removeInvoiceTemplate.feature
Add a new platform section to create Invoice templates that any brand in the platform can reuse.
=> Default invoice templates

library/Ivoz/Core/Infrastructure/Persistence/Doctrine/LoggableMigration.php, library/Ivoz/Provider/Domain/Model/RoutingPattern/RoutingPattern.php, library/Ivoz/Provider/Domain/Model/RoutingPattern/RoutingPatternInterface.php, library/Ivoz/Provider/Domain/Model/RoutingPatternGroupsRelPattern/RoutingPatternGroupsRelPattern.php, library/Ivoz/Provider/Domain/Model/RoutingPatternGroupsRelPattern/RoutingPatternGroupsRelPatternInterface.php, schema/app/DoctrineMigrations/Version20191017111612.php
Allow migrations to be logged in changelog.
Added some entities to changelog as well.
=> Loggable migrations

ChangeLog, README.md, web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> doc: updated changelog for 2.13

library/Ivoz/Provider/Domain/Service/BillableCall/BillableCallLifecycleEventHandlerInterface.php
Added LifecycleEventHandlerInterface for BillableCalls
=> core: added BillableCall LifecycleEventHandlerInterface

library/Ivoz/Cgr/Domain/Service/CgratesReloadNotificator.php, library/Ivoz/Cgr/Domain/Service/TpDestination/UpdatedTpDestinationNotificator.php, library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/ReloadService.php, library/Ivoz/Core/Infrastructure/Domain/Service/Gearman/Jobs/Cgrates.php, microservices/workers/src/Worker/Cgrates.php, microservices/workers/src/Worker/Rates.php
DisableDestinations toggle has been introduced in https://github.com/irontec/cgrates/commit/cdfd396aed7f52077928fa66e9e809a37d5cd4e8 destination and reverse destination logic can be skipped if no changes have been made.
This PR always sets DisableDestinations to true except:
- CSV import with new prefixes.
- New Destination added through web portal.
=> Cgr reload optimizations

library/DataFixtures/ORM/ProviderCalendarPeriod.php, library/Ivoz/Provider/Domain/Model/CalendarPeriod/CalendarPeriodDto.php, web/rest/client/app/config/api/raw/provider.yml, web/rest/client/features/provider/calendarPeriod/getCalendarPeriod.feature, web/rest/client/features/provider/calendarPeriod/postCalendarPeriod.feature, web/rest/client/features/provider/calendarPeriod/putCalendarPeriod.feature, web/rest/client/features/provider/calendarPeriod/removeCalendarPeriod.feature, web/rest/client/tests/DataAccessControl/Provider/CalendarPeriodTest.php
Add calendar periods to client API
=> Api calendar periods

ChangeLog, README.md, web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
Main features and fixes for 2.13.1 release
=> doc: updated changelog for 2.13.1

library/CoreBundle/Resources/config/services/entities.yml, library/CoreBundle/Resources/config/services/infraestructure/doctrine.yml, library/DataFixtures/ORM/ProviderBillableCalls.php, library/Ivoz/Cgr/Domain/Model/TpDestination/TpDestinationRepository.php, library/Ivoz/Cgr/Domain/Model/TpDestinationRate/TpDestinationRateRepository.php, library/Ivoz/Cgr/Domain/Model/TpRate/TpRateRepository.php, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/TpDestinationDoctrineRepository.php, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/TpDestinationRateDoctrineRepository.php, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/TpRateDoctrineRepository.php, library/Ivoz/Core/Domain/Event/QueryWasExecuted.php, library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineQueryRunner.php, library/Ivoz/Core/Infrastructure/Domain/Service/Lifecycle/CommandPersister.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php, library/Ivoz/Provider/Domain/Model/Destination/DestinationRepository.php, library/Ivoz/Provider/Domain/Model/DestinationRate/DestinationRateRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/DestinationDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/DestinationRateDoctrineRepository.php, microservices/workers/src/Worker/Rates.php, schema/tests/Provider/BillableCall/BillableCallRepositoryTest.php, web/rest/brand/features/provider/billableCalls/getBillableCalls.feature, web/rest/platform/features/provider/billableCalls/getBillableCalls.feature
Return affected rows on DoctrineQueryRunner and use it on Worker/Rates
=> Query runner affected rows

web/admin/application/controllers/KlearCustomRunCodeController.php, web/admin/application/modules/provision/controllers/IndexController.php
Cisco templates require terminal extension on specific provisioning step
=> web/admin: expose extension on terminal provisioning

library/Ivoz/Provider/Domain/Model/Company/CompanyRepository.php, library/Ivoz/Provider/Domain/Service/CompanyService/RemoveByBrandService.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CompanyDoctrineRepository.php, library/spec/Ivoz/Provider/Domain/Service/CompanyService/RemoveByBrandServiceSpec.php, schema/tests/Provider/Company/CompanyRepositoryTest.php
Do not instantiate companies if the id is all we need
=> Optimized CompanyService/RemoveByBrandService queries

library/Ivoz/Api/Swagger/Metadata/Resource/ResourceMetadata/FilterMetadataFactory.php
Allow to filter any nullable field on APIs by is [not] null
=> Api nullable filter

library/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromUnparsedTrunksCdr.php, library/spec/HelperTrait.php, library/spec/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThresholdSpec.php, library/spec/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateByTrunksCdrSpec.php, library/spec/Ivoz/Provider/Domain/Service/BillableCall/CsvExporterSpec.php, library/spec/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromTrunksCdrSpec.php, library/spec/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromUnparsedTrunksCdrSpec.php, library/spec/Ivoz/Provider/Domain/Service/BillableCall/UpdateByTpCdrSpec.php, library/spec/Ivoz/Provider/Domain/Service/BillableCall/UpdateDtoByDefaultRunTpCdrSpec.php, library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/CreateBySchedulerSpec.php, library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/CsvAttacherSpec.php, library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSenderSpec.php, library/spec/Ivoz/Provider/Domain/Service/CallCsvScheduler/NextExecutionResolverSpec.php, library/spec/Ivoz/Provider/Domain/Service/CallForwardSetting/CheckUniquenessSpec.php, library/spec/Ivoz/Provider/Domain/Service/Carrier/DecrementBalanceSpec.php, library/spec/Ivoz/Provider/Domain/Service/Carrier/IncrementBalanceSpec.php, library/spec/Ivoz/Provider/Domain/Service/Carrier/SearchBrokenThresholdsSpec.php, library/spec/Ivoz/Provider/Domain/Service/Carrier/SyncBalancesSpec.php, library/spec/Ivoz/Provider/Domain/Service/Company/DecrementBalanceSpec.php, library/spec/Ivoz/Provider/Domain/Service/Company/IncrementBalanceSpec.php, library/spec/Ivoz/Provider/Domain/Service/Company/SyncBalancesSpec.php, library/spec/Ivoz/Provider/Domain/Service/CompanyService/PropagateBrandServicesSpec.php, library/spec/Ivoz/Provider/Domain/Service/CompanyService/RemoveByBrandServiceSpec.php
Improve and speed up unit tests removing unnecesary test doubles
=> Unit test refactoring

asterisk/agi/src/Agi/Action/IvrAction.php, web/admin/application/configs/klear/CompaniesList.yaml, web/admin/application/configs/klear/InvoiceTemplatesList.yaml, web/admin/application/configs/klear/ResidentialClientsList.yaml, web/admin/application/configs/klear/RetailClientsList.yaml, web/admin/application/configs/klear/model/CallForwardSettings.yaml, web/admin/application/configs/klear/model/Companies.yaml, web/admin/application/configs/klear/model/Friends.yaml, web/admin/application/configs/klear/model/IvrEntries.yaml, web/admin/application/configs/klear/model/ResidentialClients.yaml, web/admin/application/configs/klear/model/ResidentialDevices.yaml, web/admin/application/configs/klear/model/RetailAccounts.yaml, web/admin/application/configs/klear/model/RetailClients.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Just minor bugs on portals titles and helpers.
=> web/admin: minimal web changes

library/Ivoz/Api/Doctrine/Orm/Extension/UnpaginatedResultGeneratorExtension.php, library/phpstan.neon
It performs better on large datasets
=> web/rest: don't use limit/offset on unpaginated API requests

library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalDto.php, web/rest/brand/app/config/api/raw/provider.yml, web/rest/brand/features/provider/webPortal/getWebPortal.feature, web/rest/brand/features/provider/webPortal/postWebPortal.feature, web/rest/brand/tests/DataAccessControl/Provider/WebPortalTest.php, web/rest/platform/features/provider/webPortal/getWebPortal.feature
Expose WebPortal.urlType on collections
=> Api web portal url type

doc/sphinx/api_rest/multilevel.rst, doc/sphinx/api_rest/use_case.rst, doc/sphinx/index.rst
=> doc: added API use case example

web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> doc: updated API changelog for 2.13.2

ChangeLog, README.md
Main features and fixes for 2.13.2 release
=> doc: update changelog for 2.13.2 release

library/Ivoz/Provider/Domain/Model/Administrator/AdministratorDto.php, library/Ivoz/Provider/Domain/Model/Company/CompanyDto.php, web/rest/brand/features/provider/administrator/getAdministrators.feature, web/rest/brand/features/provider/company/getCompanies.feature, web/rest/client/features/provider/company/getCompany.feature, web/rest/platform/features/provider/administrator/getAdministrators.feature
Expose 2 new fields on brand API collections:
- Administrators.username
- Companies.type
=> web/rest: Expose new fields on api

library/Ivoz/Provider/Domain/Model/CalendarPeriod/CalendarPeriod.php, library/spec/Ivoz/Provider/Domain/Model/CalendarPeriod/CalendarPeriodSpec.php, web/admin/application/configs/klear/errors.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Added a check to prevent CalendarPeriods endDate can be before than startDate.
=> Calendar period date sanitize

library/DataFixtures/ORM/ProviderCalendarPeriodsRelSchedule.php, library/Ivoz/Provider/Domain/Model/CalendarPeriodsRelSchedule/CalendarPeriodsRelScheduleDto.php, web/rest/client/app/config/api/raw/provider.yml, web/rest/client/features/provider/calendarPeriodsRelSchedule/getCalendarPeriodsRelSchedule.feature, web/rest/client/features/provider/calendarPeriodsRelSchedule/postCalendarPeriodsRelSchedule.feature, web/rest/client/features/provider/calendarPeriodsRelSchedule/putCalendarPeriodsRelSchedule.feature, web/rest/client/features/provider/calendarPeriodsRelSchedule/removeCalendarPeriodsRelSchedule.feature, web/rest/client/tests/DataAccessControl/Provider/CalendarPeriodsRelScheduleTest.php
Add CalendarPeriodsRelSchedule entity to client API
=> Api schedules

doc/sphinx/administration_portal/brand/billing/destination_rates.rst, microservices/workers/src/Worker/Rates.php
=> microservices: validate rates csv before it is imported

library/composer.lock, schema/app/AppKernel.php, schema/app/config/services.yml, schema/composer.lock
Update IvozDevTools dependency and register CommandlogBundle on schema wich includes: https://github.com/irontec/ivoz-dev-tools/pull/1
=> Ivoz dev tools 2.2

schema/app/DoctrineMigrations/Version20191226104551.php
Original default invoice template migration in #1163 uses local filesystem to get the template contents. These files may be not present as they don't belong schema package, so it's better to hardcode the values in the migration.
=> schema: fix Default InvoiceTemplate contents

library/Ivoz/Kam/Domain/Model/UsersAddress/UsersAddressDto.php, web/rest/brand/app/config/api/raw/kam.yml, web/rest/brand/features/kam/usersAddresses/getUsersAddresses.feature, web/rest/brand/features/kam/usersAddresses/postUsersAddresses.feature, web/rest/brand/features/kam/usersAddresses/putUsersAddresses.feature, web/rest/brand/features/kam/usersAddresses/removeUsersAddresses.feature
Add Kam/UsersAddress into brand API
=> Expose kam users address on api

asterisk/agi/app/MicroKernel.php, asterisk/agi/composer.lock, library/composer.lock, microservices/balances/app/MicroKernel.php, microservices/balances/composer.lock, microservices/recordings/app/MicroKernel.php, microservices/recordings/composer.lock, microservices/scheduler/app/MicroKernel.php, microservices/scheduler/composer.lock, microservices/workers/app/MicroKernel.php, microservices/workers/composer.lock, schema/app/AppKernel.php, schema/composer.lock, web/rest/brand/app/AppKernel.php, web/rest/brand/composer.lock, web/rest/client/app/AppKernel.php, web/rest/client/composer.lock, web/rest/platform/app/AppKernel.php, web/rest/platform/composer.lock
Unify irontec/* dependecy namepsaces
=> Fixed bundle namespaces

doc/sphinx/administration_portal/brand/routing/outgoing_routings.rst, kamailio/trunks/config/kamailio.cfg, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingAbstract.php, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingDtoAbstract.php, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/OutgoingRouting.OutgoingRoutingAbstract.orm.yml, schema/app/DoctrineMigrations/Version20200116124851.php, web/admin/application/configs/klear/OutgoingRoutingList.yaml, web/admin/application/configs/klear/model/OutgoingRouting.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Outgoing routes marked as stopper will prevent routes with higher priority to apply.
Routes with same priority as stopper rule will continue applying.
=> Routing: Stopper routes

web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> doc: updated API changelog for 2.14

web/admin/e2e/tests/dataFixtures/brand/numericTransformation/auto.json, web/admin/e2e/tests/dataFixtures/brand/numericTransformation/new.json, web/admin/e2e/tests/dataFixtures/brand/routingPatterns/new.json, web/admin/e2e/tests/dataFixtures/company/callForwardSettings/new.json, web/admin/e2e/tests/features/2-brand/03-4-outgoingRouting.feature, web/admin/e2e/tests/features/2-brand/05-2-calleeIn.feature, web/admin/e2e/tests/features/2-brand/05-3-callerIn.feature, web/admin/e2e/tests/features/2-brand/05-4-calleeOut.feature, web/admin/e2e/tests/features/2-brand/05-5-callerOut.feature, web/admin/e2e/tests/features/login.feature
=> tests: updated web e21e tests

ChangeLog, README.md
Main features and fixes for 2.14.0 release
=> doc: update changelog for 2.14.0 release

library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksCdr.TrunksCdrAbstract.orm.yml, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Changelog.ChangelogAbstract.orm.yml, schema/app/DoctrineMigrations/Version20200127164702.php, schema/app/DoctrineMigrations/Version20200127164703.php, schema/tests/Provider/Extension/ExtensionLifeCycleTest.php
Remove db indexes that don't make sense any more
=> Reviewed db indexes

library/Ivoz/Provider/Domain/Service/DestinationRateGroup/SendImporterOrder.php, library/spec/Ivoz/Provider/Domain/Service/DestinationRateGroup/SendImporterOrderSpec.php
Do not invoke Rates worker on destinationRateGroup removal.
=> Fix rates worker invocation

web/admin/application/configs/klear/klear.yaml, web/admin/application/library/IvozProvider/Klear/Dynamic/Config/Base.php
=> web/admin: updated year on the footer

web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.json, web/rest/platform/composer.lock
Get back some API dependencies that are shared with admin portal
=> web/admin: fixed invoice template tester

library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php
Parse records with parsed = NULL from trunks_cdrs to BillableCalls
=> core: parse trunksCdrs with parsed = null

library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/PsEndpoint.PsEndpointAbstract.orm.yml, library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/Voicemail.VoicemailAbstract.orm.yml, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpAccountAction.TpAccountActionAbstract.orm.yml, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpCdr.TpCdrAbstract.orm.yml, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpDestination.TpDestinationAbstract.orm.yml, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpDestinationRate.TpDestinationRateAbstract.orm.yml, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpRate.TpRateAbstract.orm.yml, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpRatingPlan.TpRatingPlanAbstract.orm.yml, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpRatingProfile.TpRatingProfileAbstract.orm.yml, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksCdr.TrunksCdrAbstract.orm.yml, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.yml, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersPresentity.UsersPresentityAbstract.orm.yml, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersPua.UsersPuaAbstract.orm.yml, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersXcap.UsersXcapAbstract.orm.yml, schema/app/DoctrineMigrations/Version20200131103107.php
Some keys were already covered by another multi-column keys
=> schema: removed duplicated keys

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/OutgoingDdiRulesPattern.OutgoingDdiRulesPatternAbstract.orm.yml, schema/app/DoctrineMigrations/Version20200203125704.php, tests/docker/Dockerfile
detected by pt-duplicate-key percona tool
=> Remove some unnecessary indexes 

web/admin/application/library/IvozProvider/Klear/Ghost/Companies.php
Round Daily usage section values to 2 decimals.
=> web/admin: round daily usage value

library/Ivoz/Provider/Domain/Service/Domain/DeleteByBrand.php, library/Ivoz/Provider/Domain/Service/Domain/DeleteByCompany.php, library/Ivoz/Provider/Domain/Service/Domain/UpdateByBrand.php, library/Ivoz/Provider/Domain/Service/Domain/UpdateByCompany.php, library/Ivoz/Provider/Domain/Service/Invoice/SetInvoiceNumber.php, library/Ivoz/Provider/Domain/Service/User/UpdateByExtension.php, library/spec/Ivoz/Provider/Domain/Service/Domain/UpdateByBrandSpec.php, library/spec/Ivoz/Provider/Domain/Service/Domain/UpdateByCompanySpec.php, library/spec/Ivoz/Provider/Domain/Service/User/UpdateByExtensionSpec.php
Replace entity direct setters on services by dtos
=> Do not use entity setter on services

library/composer.lock
It fixes cost calculation on external cdrs
=> core: updated ivoz-core dependency

library/Ivoz/Provider/Domain/Model/Administrator/Administrator.php, library/Ivoz/Provider/Domain/Model/Administrator/AdministratorInterface.php, library/Ivoz/Provider/Domain/Model/Administrator/AdministratorSecurityTrait.php, library/Ivoz/Provider/Domain/Model/Company/Company.php, library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php, library/Ivoz/Provider/Domain/Model/User/User.php, library/Ivoz/Provider/Domain/Model/User/UserInterface.php, schema/app/DoctrineMigrations/Version20200130155353.php, web/admin/application/configs/klear/AdministratorsList.yaml, web/admin/application/configs/klear/BrandsList.yaml, web/admin/application/configs/klear/CompaniesList.yaml, web/admin/application/configs/klear/ResidentialClientsList.yaml, web/admin/application/configs/klear/RetailClientsList.yaml, web/admin/application/configs/klear/WholesaleClientsList.yaml, web/rest/brand/features/requestPayloadTzConversions.feature
Fixed time zone inheritance on sanitizes
=> core: reviewed tz inheritance on Administrator, Company and User

kamailio/trunks/config/kamailio.cfg, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRouting.php, schema/app/DoctrineMigrations/Version20200205123949.php, web/admin/application/configs/klear/model/OutgoingRouting.yaml
Route selection logic is quite complex. This PR improves log messages so that problems can be easily debugged.
No functional change, just logs.
=> kamtrunks: Improve routing selection logic logs

web/admin/application/configs/klear/FriendsList.yaml, web/admin/application/configs/klear/ResidentialDevicesList.yaml, web/admin/application/configs/klear/RetailAccountsList.yaml, web/admin/application/configs/klear/model/Friends.yaml, web/admin/application/configs/klear/model/ResidentialDevices.yaml, web/admin/application/configs/klear/model/RetailAccounts.yaml
- directConnectivity defaults to No for new retail/residential/friends
- ddiIn defaults to No for new retail/residential/friends
=> web/admin: default values for retails/residentials/friends

web/rest/brand/CHANGELOG.md
=> doc: updated API changelog for 2.14.1

library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerAbstract.php, library/Ivoz/Provider/Domain/Model/DdiProviderAddress/DdiProviderAddressAbstract.php, library/Ivoz/Provider/Domain/Model/DdiProviderRegistration/DdiProviderRegistrationAbstract.php, library/Ivoz/Provider/Domain/Model/Destination/DestinationAbstract.php, library/Ivoz/Provider/Domain/Model/DestinationRate/DestinationRateAbstract.php, library/composer.lock, schema/composer.lock, schema/tests/Provider/DdiProviderAddress/DdiProviderAddressLifeCycleTest.php, schema/tests/Provider/Destination/DestinationLifeCycleTest.php
Update ivoz-dev-tools v2.5 witch includes (https://github.com/irontec/ivoz-dev-tools/commit/77862369461e16492782e834f043a966a7c07300) so that entities are properly synced with dtos
=> Sync one to one relationships between entities and dtos

asterisk/agi/composer.lock, library/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
Update symfony/symfony and symfony/phpunit-bridge versions because of security issues.
More info:
- https://github.com/advisories/GHSA-w2fr-65vp-mxw3
- https://github.com/symfony/symfony/blob/v3.4.37/CHANGELOG-3.4.md
=> Dependencies security update

kamailio/users/config/kamailio.cfg
To block REGISTERs from non-granted IPs and frauds derived from these
registrations (e.g. call-forwards)
=> kamusers: IP filter for non-INVITE requests

doc/sphinx/administration_portal/brand/billing/rating_plans.rst, doc/sphinx/administration_portal/brand/providers/carriers.rst, doc/sphinx/administration_portal/brand/routing/outgoing_routings.rst
Just documentation:
- Improve routing logic explanation
- Improve Cost calculation help
=> doc: improve Cost calculation and Routing explanation

library/Ivoz/Provider/Domain/Model/AdministratorRelPublicEntity/AdministratorRelPublicEntityDto.php, library/Ivoz/Provider/Domain/Model/PublicEntity/PublicEntityDto.php, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/features/provider/administratorRelPublicEntities/getAdministratorRelPublicEntities.feature, web/rest/brand/features/provider/administratorRelPublicEntities/postAdministratorRelPublicEntities.feature, web/rest/brand/features/provider/administratorRelPublicEntities/putAdministratorRelPublicEntities.feature, web/rest/brand/features/provider/administratorRelPublicEntities/removeAdministratorRelPublicEntities.feature, web/rest/brand/features/provider/publicEntity/getPublicEntities.feature, web/rest/brand/features/provider/publicEntity/postPublicEntities.feature, web/rest/brand/features/provider/publicEntity/putPublicEntities.feature, web/rest/brand/features/provider/publicEntity/removePublicEntities.feature, web/rest/brand/tests/DataAccessControl/Provider/AdministratorRelPublicEntitiesTest.php, web/rest/brand/tests/DataAccessControl/Provider/PublicEntityTest.php, web/rest/platform/config/api/raw/provider.yml, web/rest/platform/features/provider/administrator/getAdministrators.feature, web/rest/platform/features/provider/administrator/putAdministrators.feature, web/rest/platform/features/provider/administrator/removeAdministrators.feature, web/rest/platform/features/provider/administratorRelPublicEntities/getAdministratorRelPublicEntities.feature, web/rest/platform/features/provider/administratorRelPublicEntities/postAdministratorRelPublicEntities.feature, web/rest/platform/features/provider/administratorRelPublicEntities/putAdministratorRelPublicEntities.feature, web/rest/platform/features/provider/administratorRelPublicEntities/removeAdministratorRelPublicEntities.feature, web/rest/platform/features/provider/publicEntity/getPublicEntities.feature, web/rest/platform/features/provider/publicEntity/postPublicEntities.feature, web/rest/platform/features/provider/publicEntity/putPublicEntities.feature, web/rest/platform/features/provider/publicEntity/removePublicEntities.feature
Expose PublicEntity and AdministratorRelPublicEntity on APIs
=> Expose administrator ACLs on API

web/rest/brand/config/api/raw/provider.yml, web/rest/brand/features/provider/company/postCompanies.feature, web/rest/brand/features/provider/outgoingRouting/postOutgoingRouting.feature, web/rest/client/config/api/raw/provider.yml, web/rest/client/features/provider/conditionalRoutesCondition/postConditionalRoutesCondition.feature, web/rest/client/features/provider/externalCallFilter/postExternalCallFilter.feature, web/rest/client/features/provider/ivr/postIvr.feature, web/rest/client/features/provider/user/postUser.feature, web/rest/platform/config/api/raw/provider.yml, web/rest/platform/features/provider/brand/postBrands.feature
Fixes some API response model so that they fit their response spec. This PR partially fixes https://github.com/irontec/ivozprovider/issues/1307
=> Fixed api post response custom models

asterisk/agi/composer.lock, library/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/rest/brand/composer.lock, web/rest/brand/config/api/raw/provider.yml, web/rest/client/composer.lock, web/rest/client/config/api/raw/provider.yml, web/rest/platform/composer.json, web/rest/platform/composer.lock
Mark required fields in application layer. This PR partially fixes #1307
=> Api reviewed required fields

library/DataFixtures/ORM/ProviderAdministratorRelPublicEntities.php, library/DataFixtures/ORM/ProviderPublicEntities.php, library/Ivoz/Provider/Domain/Model/Administrator/Administrator.php, library/Ivoz/Provider/Domain/Model/Administrator/AdministratorInterface.php, library/Ivoz/Provider/Domain/Model/Administrator/AdministratorSecurityTrait.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/AdministratorRelPublicEntity.AdministratorRelPublicEntityAbstract.orm.yml, web/rest/brand/config/api/raw/kam.yml, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/config/api/resources.yml, web/rest/brand/features/acl.feature, web/rest/brand/features/provider/administratorRelPublicEntities/getAdministratorRelPublicEntities.feature, web/rest/brand/features/provider/administratorRelPublicEntities/putAdministratorRelPublicEntities.feature, web/rest/brand/features/provider/publicEntity/getPublicEntities.feature, web/rest/client/config/api/raw/kam.yml, web/rest/client/config/api/raw/provider.yml, web/rest/client/config/api/resources.yml, web/rest/platform/config/api/raw/kam.yml, web/rest/platform/config/api/raw/provider.yml, web/rest/platform/config/api/resources.yml, web/rest/platform/features/provider/administratorRelPublicEntities/getAdministratorRelPublicEntities.feature, web/rest/platform/features/provider/administratorRelPublicEntities/putAdministratorRelPublicEntities.feature, web/rest/platform/features/provider/publicEntity/getPublicEntities.feature
=> Apply ACLs on API

doc/sphinx/administration_portal/brand/views/index.rst, doc/sphinx/administration_portal/brand/views/users.rst, library/Ivoz/Provider/Domain/Model/User/UserDto.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/UserDoctrineRepository.php, web/admin/application/configs/klear/BrandUsersList.yaml, web/admin/application/configs/klear/klear.yaml, web/admin/application/configs/klear/model/Users.yaml, web/admin/application/library/IvozProvider/Klear/Filter/Extensions.php, web/admin/application/library/IvozProvider/Klear/Ghost/RegisterStatus.php, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/features/provider/user/getUser.feature, web/rest/brand/features/provider/user/postUser.feature, web/rest/brand/features/provider/user/putUser.feature, web/rest/brand/features/provider/user/removeUser.feature
New section under Views group from Brand operators: Users.
This section lists Users in all vPBX clients of emulated brand.
=> web/admin: new Users view section for brand 

doc/sphinx/administration_portal/client/residential/residential_devices.rst, doc/sphinx/administration_portal/client/vpbx/users.rst, web/admin/application/configs/klear/model/ResidentialDevices.yaml, web/admin/application/configs/klear/model/Users.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Call waiting 0 value for users and residential devices means unlimited call reception.
=> Call waiting zero means unlimited

asterisk/agi/composer.lock, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/doctrine.yml, library/composer-packages/irontec/ivoz-provider-bundle/composer.json, library/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/admin/application/configs/klear/BillableCallsList.yaml, web/admin/application/configs/klear/KamUsersCdrsList.yaml, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
=> Limit cdrs to one year

asterisk/agi/composer.lock, doc/sphinx/administration_portal/client/vpbx/extensions.rst, library/Ivoz/Provider/Domain/Model/Country/CountryRepository.php, library/Ivoz/Provider/Domain/Model/Extension/ExtensionRepository.php, library/Ivoz/Provider/Domain/Service/Extension/AliasImporter.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CountryDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/ExtensionDoctrineRepository.php, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/services/domain.yml, library/composer-packages/irontec/ivoz-provider-bundle/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, schema/tests/Provider/Country/CountryRepositoryTest.php, schema/tests/Provider/Extension/ExtensionRepositoryTest.php, web/admin/application/configs/klear/ExtensionsList.yaml, web/admin/application/controllers/ImportAliasesCustomFileController.php, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
Added extension alias importer
=> Alias importer

library/Ivoz/Provider/Domain/Service/Domain/UpdateByCompany.php, library/spec/Ivoz/Provider/Domain/Service/Domain/UpdateByCompanySpec.php
Only vPBX have their own domain
=> core: do not update domains if company is not vPBX

Jenkinsfile, schema/bin/test-orm, tests/docker/bin/prepare-and-run, web/rest/brand/bin/test-api, web/rest/client/bin/test-api, web/rest/platform/bin/test-api
Create sqlite database one single time
=> Optimized CI pipeline

doc/sphinx/administration_portal/brand/calls/call_csv_schedulers.rst, doc/sphinx/administration_portal/client/vpbx/calls/call_csv_schedulers.rst, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvScheduler.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerDto.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerDtoAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerInterface.php, library/Ivoz/Provider/Domain/Service/BillableCall/CsvExporter.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/CsvAttacher.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallCsvScheduler.CallCsvSchedulerAbstract.orm.yml, schema/DoctrineMigrations/Version20200309102734.php, web/admin/application/configs/klear/CallCsvSchedulersBrandList.yaml, web/admin/application/configs/klear/CallCsvSchedulersList.yaml, web/admin/application/configs/klear/model/CallCsvSchedulers.yaml, web/admin/application/configs/klear/model/Carriers.yaml, web/admin/application/library/IvozProvider/Klear/Filter/BrandCompanies.php, web/admin/e2e/commands/jqueryFillOutForm.js, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/features/provider/callCsvScheduler/getCallCsvScheduler.feature, web/rest/brand/features/provider/callCsvScheduler/postCallCsvScheduler.feature, web/rest/brand/features/provider/callCsvScheduler/putCallCsvScheduler.feature, web/rest/brand/features/provider/fax/getFax.feature, web/rest/brand/features/provider/friend/getFriend.feature, web/rest/brand/tests/DataAccessControl/Provider/FaxTest.php, web/rest/brand/tests/DataAccessControl/Provider/FriendTest.php, web/rest/client/features/provider/callCsvScheduler/getCallCsvScheduler.feature, web/rest/client/features/provider/callCsvScheduler/postCallCsvScheduler.feature, web/rest/client/features/provider/callCsvScheduler/putCallCsvScheduler.feature
Added new call CSV scheduler criteria for outgoing calls:
- Friend
- Fax
- User
Requires https://github.com/irontec/klearMatrix/commit/d2301bec3b84cfea2f2f5e389f6e1095a346a0bc or greater
=> Improved call csv scheduler

web/admin/application/assets/css/klearCustomRtCallList.tmpl.css, web/admin/application/assets/js/plugins/jquery.rt.js, web/admin/application/assets/template/klearCustomRtCallBrandList.tmpl.html, web/admin/application/assets/template/klearCustomRtCallClientList.tmpl.html, web/admin/application/assets/template/klearCustomRtCallList.tmpl.html, web/admin/application/configs/klear/ActiveCallsBrandList.yaml, web/admin/application/configs/klear/ActiveCallsClientList.yaml, web/admin/application/configs/klear/ActiveCallsList.yaml, web/admin/application/configs/klear/klear.yaml, web/admin/application/controllers/KlearCustomRtController.php, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po, web/admin/application/library/IvozProvider/Utils/TokenHelper.php
Show active calls in realtime in klear
=> Realtime klear

microservices/realtime/src/Model/Subscriber.php, microservices/realtime/src/Services/RedisPool.php, microservices/realtime/src/Services/WsServer.php
Error prevention when multiple sockets were closed at the same time
=> WS bugfixes

profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf, web/admin/application/assets/js/plugins/jquery.rt.js
Let apache handle ssl connections
=> WSS through apache

microservices/realtime/config/parameters.yml, microservices/realtime/src/Services/AbstractWsServer.php
It's already handled by apache
=> microservices: removed ssl related code on realtime service

asterisk/agi/composer.lock, library/Ivoz/Provider/Domain/Service/Company/CompanyLifecycleServiceCollection.php, library/Ivoz/Provider/Domain/Service/Domain/UpdateByCompany.php, library/composer.lock, library/spec/Ivoz/Provider/Domain/Service/Domain/UpdateByCompanySpec.php, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
- Do not create domains before the company is created
- Avoid invalid http status codes to propagate validation exceptions
- Improved journal tags
Updated irontec dependencies:
https://github.com/irontec/ivoz-api/commit/c4fb637e625e30b9573d17f1476dfcf9933aa806
https://github.com/irontec/ivoz-core-bundle/commit/10afbfeef44d380f36371dcc08aa231b331e67a8
=> Better transaction error handling

asterisk/agi/composer.json, asterisk/agi/composer.lock, library/composer.lock, microservices/balances/composer.json, microservices/balances/composer.lock, microservices/realtime/composer.json, microservices/realtime/composer.lock, microservices/recordings/composer.json, microservices/recordings/composer.lock, microservices/scheduler/composer.json, microservices/scheduler/composer.lock, microservices/workers/composer.json, microservices/workers/composer.lock, schema/composer.json, schema/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.json, web/rest/platform/composer.lock
=> Updated symfony

library/Ivoz/Provider/Domain/Model/Friend/Friend.php, library/Ivoz/Provider/Domain/Model/Friend/FriendAbstract.php, library/Ivoz/Provider/Domain/Model/Friend/FriendInterface.php, library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDevice.php, library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceAbstract.php, library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceInterface.php, library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccount.php, library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccountAbstract.php, library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccountInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Friend.FriendAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ResidentialDevice.ResidentialDeviceAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/RetailAccount.RetailAccountAbstract.orm.yml, schema/DoctrineMigrations/Version20200407133940.php
Make transport nullable for friends/retails/residentials and control in sanitizer whether null is valid or not.
=> schema: make transport nulllable for friends/retails/residentials

debian/ivozprovider-profile-portal.postinst
Enable proxy, proxy_http and proxy_wstunnel apache modules
=> pkg: enable apache modules for ws service

web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> Api changelog

ChangeLog, README.md
Main features and fixes for 2.15.0 release
=> doc: update changelog for 2.15.0 release

web/admin/application/library/IvozProvider/Klear/Ghost/RegisterStatus.php
Add a hint line in register status that tries to guess awkward registrations:
- Public IP address in REGISTER Contact (SIP ALG/STUN)
- Private address in both Contact and Received (internal routing)
Nothing serious, just a humble guess.
=> web/admin: easy ALG/STUN guesser

microservices/workers/src/Worker/Rates.php
Prevent huge files from generating transaction errors
=> microservices: limit destination rates import file length

web/admin/application/controllers/KlearCustomRtController.php, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Fix Carrier plural translation.
=> i18n: fix Carrier plural translation

microservices/realtime/src/Services/WsServer.php
Sort realtime initial state before sending it
=> microservices: sort inital realtime calls

web/admin/application/configs/klear/BillableCallsList.yaml
It doesn't perform well on brands with large datasets
=> web/admin: removed BillableCalls only last year raw condition

kamailio/users/config/kamailio.cfg
Allow REGISTERs from roadwarrior from non-authorized IP ranges.
Fixes 58402a375 introduced in #1293
=> kamusers: fix roadwarrior registration ip filter

microservices/realtime/spec/Services/RegistrationChannelResolverSpec.php, microservices/realtime/src/Services/RegistrationChannelResolver.php, microservices/realtime/src/Services/WsServer.php, web/admin/application/assets/js/plugins/jquery.rt.js
- Added Proceeding event icon
- Updated journal log levels
=> RT minor bug fixes

asterisk/agi/composer.lock, library/Ivoz/Provider/Domain/Service/ProxyTrunksRelBrand/AvoidRemovingInUseAddresses.php, library/composer.lock, library/spec/Ivoz/Provider/Domain/Service/ProxyTrunksRelBrand/AvoidRemovingInUseAddressesSpec.php, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
Skip ProxyTrunksRelBrand\AvoidRemovingInUseAddresses service on brand removal. Let mysql do cascade deletes.
Includes: https://github.com/irontec/ivoz-core/commit/14daa0d9860c1d374ad35cc539aaa16111e8f14d
=> Remove brand delete regression

library/DataFixtures/ORM/ProviderProxyTrunk.php, library/DataFixtures/ORM/ProviderProxyTrunkRelBrand.php, library/Ivoz/Provider/Domain/Model/Administrator/Administrator.php, library/Ivoz/Provider/Domain/Model/ProxyTrunksRelBrand/ProxyTrunksRelBrandDto.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CompanyDoctrineRepository.php, schema/DoctrineMigrations/Version20200414145121.php, schema/tests/Provider/Brand/BrandLifeCycleTest.php, web/rest/platform/config/api/raw/provider.yml, web/rest/platform/features/provider/proxyTrunkRelBrand/getProxyTrunkRelBrand.feature, web/rest/platform/features/provider/proxyTrunkRelBrand/postProxyTrunkRelBrand.feature, web/rest/platform/features/provider/proxyTrunkRelBrand/putProxyTrunkRelBrand.feature, web/rest/platform/features/provider/proxyTrunkRelBrand/removeProxyTrunkRelBrand.feature
Register ProxyTrunksRelBrands on ACLs and expose it on platform API
=> Expose proxy trunk rel brand on platform api

library/Ivoz/Provider/Domain/Model/ProxyTrunksRelBrand/ProxyTrunksRelBrandRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/ProxyTrunksRelBrandDoctrineRepository.php, schema/tests/Provider/ProxyTrunksRelBrand/ProxyTrunkRelBrandRepositoryTest.php, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/config/services.yml, web/rest/brand/features/provider/proxyTrunk/getProxyTrunk.feature, web/rest/brand/tests/DataAccessControl/Provider/ProxyTrunkTest.php
=> Expose proxy trunk on brand api

kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg, microservices/realtime/src/Feeder/TrunksCall.php, microservices/realtime/src/Feeder/UsersCall.php, web/admin/application/assets/js/plugins/jquery.rt.js
Remove unneeded Name fields in redis structure as they are not used.
=> realtime: remove unneeded Name fields

kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg, microservices/realtime/src/Feeder/AbstractCall.php, microservices/realtime/src/Feeder/TrunksCall.php, microservices/realtime/src/Feeder/UsersCall.php, web/admin/application/assets/js/plugins/jquery.rt.js
Fix carrier failover representation in realtime god/brand sections.
=> realtime: fix carrier failover

microservices/realtime/src/Services/AbstractWsServer.php, microservices/realtime/src/Services/Sentinel.php
Handle redis sentinel +switch-master event
=> microservices: improved sentinel suport in RT service

library/Ivoz/Provider/Domain/Model/Brand/BrandRepository.php, library/Ivoz/Provider/Domain/Model/Carrier/CarrierRepository.php, library/Ivoz/Provider/Domain/Model/Company/CompanyRepository.php, library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BrandDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CarrierDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CompanyDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/DdiProviderDoctrineRepository.php, microservices/realtime/src/Services/RegistrationChannelResolver.php, web/admin/application/assets/js/plugins/jquery.rt.js, web/admin/application/assets/template/filters.tmpl.html, web/admin/application/assets/template/klearCustomRtCallBrandList.tmpl.html, web/admin/application/assets/template/klearCustomRtCallList.tmpl.html, web/admin/application/controllers/KlearCustomRtController.php
=> RT filters

ChangeLog, README.md, web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> update changelog for 2.15.1 release

web/admin/application/assets/template/filters.tmpl.html, web/admin/application/controllers/KlearCustomRtController.php, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Make realtime fillters multi language
=> web/admin: multilang RT filters

microservices/realtime/src/Services/WsServer.php
=> realtime: reduce redis log level

asterisk/agi/composer.lock, debian/ivozprovider-web-rest.postinst, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/parameters.yml, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/parameters.yml.dist, library/composer-packages/irontec/ivoz-provider-bundle/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, tests/docker/bin/prepare-and-run, web/rest/.gitignore, web/rest/brand/composer.lock, web/rest/brand/config/config_test.yml, web/rest/brand/var/jwt, web/rest/client/composer.lock, web/rest/client/config/config_test.yml, web/rest/client/var/jwt, web/rest/platform/bin/generate-keys, web/rest/platform/composer.lock, web/rest/platform/config/config_test.yml
Moved key path to shared storage
=> Share JWT key between cluster nodes

library/DataFixtures/ORM/AstPsEndpoint.php, library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByResidentialDevice.php, schema/DoctrineMigrations/Version20200525104541.php, schema/tests/Provider/ResidentialDevice/ResidentialDeviceLifeCycleTest.php
_ast_ps_endpoints.mailboxes_ was not correctly updated for residential devices. This made unsolicited NOTIFY for MWI fail.
=> Fix unsolicited MWI for residential clients

library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccount.php, library/Ivoz/Provider/Domain/Model/User/User.php, library/Ivoz/Provider/Domain/Service/BillableCall/UpdateDtoByDefaultRunTpCdr.php, library/Ivoz/Provider/Domain/Service/RoutingPatternGroup/UpdateByRoutingPatternAndCountry.php, library/spec/Ivoz/Provider/Domain/Service/BillableCall/UpdateDtoByDefaultRunTpCdrSpec.php, microservices/realtime/src/Services/AbstractWsServer.php, microservices/workers/src/Worker/Invoices.php, microservices/workers/src/Worker/Multimedia.php, microservices/workers/src/Worker/Rates.php, microservices/workers/src/Worker/Xmlrpc.php, web/rest/brand/src/Controller/My/ActiveCallsAction.php, web/rest/brand/src/Controller/Provider/PutBillableCallRatingAction.php, web/rest/client/src/Controller/My/CallForwardSettingsAction.php, web/rest/client/src/Controller/My/CallHistoryAction.php, web/rest/client/src/Controller/My/CallStatsAction.php, web/rest/client/src/Controller/My/CompanyAssistantsAction.php, web/rest/client/src/Controller/My/CompanyCountryAction.php, web/rest/client/src/Controller/My/CompanyExtensionsAction.php, web/rest/client/src/Controller/My/CompanyVoicemailsAction.php, web/rest/client/src/Controller/My/PostCallForwardSettingsAction.php, web/rest/client/src/Controller/My/ProfileAction.php, web/rest/client/src/Controller/My/PutProfileAction.php, web/rest/client/src/Controller/My/StatusAction.php, web/rest/client/src/Controller/My/WebThemeAction.php, web/rest/client/src/Controller/Provider/RatingPlanPricesAction.php, web/rest/platform/src/Controller/My/ActiveCallsAction.php, web/rest/platform/src/Controller/Provider/PutBillableCallRatingAction.php
Fixed some phpstan level 4 issues
=> Phpstan level 4

kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg
Reduce the amount of log messages per call in both proxies.
There should be no functional change in this PR.
=> kam: less logs per call

web/admin/application/controllers/KlearCustomExtraAuthController.php
Close edition tabs on emulation because of security reasons
=> web/admin: fixed emulation issues

library/Ivoz/Provider/Domain/Model/Administrator/Administrator.php, library/Ivoz/Provider/Domain/Model/Administrator/AdministratorInterface.php, library/Ivoz/Provider/Domain/Model/Brand/Brand.php, library/Ivoz/Provider/Domain/Model/Brand/BrandInterface.php, library/Ivoz/Provider/Domain/Model/Company/Company.php, library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php, web/rest/client/config/api/raw/kam.yml, web/rest/client/config/api/raw/provider.yml
Improved API entity access control
=> Improved api security checks

library/Ivoz/Kam/Domain/Model/UsersLocation/UsersLocationRepository.php, library/Ivoz/Kam/Domain/Service/UsersLocation/BrandRegistrationSummary.php, library/Ivoz/Kam/Domain/Service/UsersLocation/CompanyRegistrationSummary.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/UsersLocationDoctrineRepository.php, library/Ivoz/Provider/Domain/Model/Friend/FriendRepository.php, library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceRepository.php, library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccountRepository.php, library/Ivoz/Provider/Domain/Model/Terminal/TerminalRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/FriendDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/ResidentialDeviceDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/RetailAccountDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/TerminalDoctrineRepository.php, web/rest/brand/config/api/resources.yml, web/rest/brand/features/my/registrationSummary/getRegistrationSummary.feature, web/rest/brand/src/Controller/My/RegistrationSummaryAction.php, web/rest/client/config/api/resources.yml, web/rest/client/config/routing.yml, web/rest/client/features/my/registrationSummary/getRegistrationSummary.feature, web/rest/client/src/Controller/My/RegistrationSummaryAction.php, web/rest/client/src/Model/RegistrationSummary.php
Allow to filter device registration summary on brand API and expose it on client API
=> Registration summary company filter

asterisk/agi/composer.lock, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/admin/application/library/IvozProvider/Klear/Ghost/CarrierServerStatus.php, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
Fix Carrier and Carrier server status icons (ghost fields) when CGRateS accounts are missing and when KamTrunks is down.
=> web/admin: fix carrier and carrier server ghost fields

web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> Updated API changelog

doc/sphinx/administration_portal/brand/billing/destination_rates.rst, library/Ivoz/Cgr/Domain/Model/TpDestinationRate/TpDestinationRateAbstract.php, library/Ivoz/Cgr/Domain/Model/TpDestinationRate/TpDestinationRateInterface.php, library/Ivoz/Cgr/Domain/Model/TpDestinationRate/TpDestinationRateRepository.php, library/Ivoz/Cgr/Domain/Model/TpRatingProfile/SimulatedCall.php, library/Ivoz/Cgr/Domain/Service/TpDestinationRate/UpdatedByDestinationRate.php, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpDestinationRate.TpDestinationRateAbstract.orm.yml, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/TpDestinationRateDoctrineRepository.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroup.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupAbstract.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupDtoAbstract.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/DestinationRateGroup.DestinationRateGroupAbstract.orm.yml, microservices/workers/src/Worker/Rates.php, schema/DoctrineMigrations/Version20200604125512.php, web/admin/application/configs/klear/DestinationRateGroupsList.yaml, web/admin/application/configs/klear/errors.yaml, web/admin/application/configs/klear/model/DestinationRateGroups.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po, web/rest/brand/features/provider/destinationRateGroup/postDestinationRateGroup.feature
This PR adds _Deductible ConnectionFee_ aka _Minimal Cost_ feature. Read documentation for further explanation.
Needs CGRateS being patched with irontec/cgrates@a1f37f08291da69852cb1b90c0e93d80f6d6308c
=> billing: deductible ConnectionFee (minCost)

ChangeLog, README.md
=> doc: update changelog for 2.15.2

library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByTerminal.php, library/Ivoz/Cgr/Domain/Service/TpAccountAction/CreateByCarrier.php, library/Ivoz/Cgr/Domain/Service/TpLcrRule/CreatedByOutgoingRouting.php, library/Ivoz/Cgr/Domain/Service/TpRatingPlan/UpdateByRatingPlan.php, library/Ivoz/Cgr/Domain/Service/TpTiming/CreatedByRatingPlan.php, library/Ivoz/Kam/Domain/Model/TrunksUacreg/DdiProviderRegistrationStatus.php, library/Ivoz/Provider/Application/Service/Brand/BrandAssembler.php, library/Ivoz/Provider/Domain/Model/Company/Company.php, library/Ivoz/Provider/Domain/Model/User/User.php, library/Ivoz/Provider/Domain/Service/BrandService/UpdateByBrand.php, library/Ivoz/Provider/Domain/Service/CallForwardSetting/CheckUniqueness.php, library/Ivoz/Provider/Domain/Service/CompanyService/PropagateBrandServices.php, library/Ivoz/Provider/Domain/Service/CompanyService/RemoveByBrandService.php, library/Ivoz/Provider/Domain/Service/InvoiceScheduler/NextExecutionResolverTrait.php, library/Ivoz/Provider/Domain/Service/RoutingPatternGroup/UpdateByRoutingPatternAndCountry.php, library/composer.lock, library/phpstan.neon
=> Phpstan fixed issues

schema/DoctrineMigrations/Version20170911135717.php, schema/initial.sql
Merge all migrations into the initial database dump.
I forgot to do this for 2.15 release, so following changes include 2.14 and 2.15 deltas together.
=> schema: update initial.sql for 2.16 version

library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpDestination.TpDestinationAbstract.orm.yml, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Ddi.DdiAbstract.orm.yml, schema/DoctrineMigrations/Version20200617093620.php
Added a couple of missing db indexes
Removed unnecesary tp_destination index as well
=> Db index review

library/Ivoz/Ast/Infrastructure/Asterisk/ARI/ARIConnector.php, library/Ivoz/Cgr/Infrastructure/Cgrates/Service/CarrierBalanceService.php, library/Ivoz/Cgr/Infrastructure/Cgrates/Service/CompanyBalanceService.php, library/Ivoz/Cgr/Infrastructure/Cgrates/Service/FetchCallStatsService.php, library/Ivoz/Cgr/Infrastructure/Cgrates/Service/ProcessExternalCdr.php, library/spec/Ivoz/Cgr/Infrastructure/Cgrates/Service/ProcessExternalCdrSpec.php
Apply suggestions done in https://github.com/irontec/ivozprovider/pull/1426
=> Minor services fixes

asterisk/agi/composer.lock, library/Ivoz/Provider/Domain/Model/Company/Company.php, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/parameters.yml, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/parameters.yml.dist, library/composer-packages/irontec/ivoz-provider-bundle/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, schema/config/config_local.yml, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
Allow to connect to local mysql node through unix socket
=> Doctrine unix socket support

library/DataFixtures/ORM/AstPsEndpoint.php, library/DataFixtures/ORM/AstQueue.php, library/DataFixtures/ORM/AstVoicemail.php, library/DataFixtures/Stub/Ast/PsEndpointStub.php, library/DataFixtures/Stub/Ast/QueueStub.php, library/DataFixtures/Stub/Ast/VoicemailStub.php, library/DataFixtures/Stub/StubTrait.php
Separate entity instatiation from fixtures so that entities can be used on unit tests as well
=> Split fixture data and persistance 

library/Ivoz/Provider/Domain/Model/Company/Company.php, web/admin/application/controllers/KlearCustomTarificatorController.php, web/admin/application/library/IvozProvider/Klear/Auth/User.php, web/admin/application/library/IvozProvider/Klear/Filter/CallForwardTypes.php, web/admin/application/library/IvozProvider/Klear/Filter/RouteTypes.php, web/admin/application/library/IvozProvider/Klear/Filter/TargetTypes.php, web/admin/application/library/IvozProvider/Klear/Ghost/Companies.php
Replace them by auto generated once
=> core: removed deprecated constants

web/rest/client/config/api/raw/provider.yml, web/rest/client/features/provider/recording/removeRecording.feature
There was no remove endpoint on API
=> web/rest: allow DELETE on recordings

microservices/workers/src/Worker/Cgrates.php, microservices/workers/src/Worker/Invoices.php, microservices/workers/src/Worker/Multimedia.php, microservices/workers/src/Worker/Rates.php, microservices/workers/src/Worker/Xmlrpc.php
Avoid entity state to get into inconsistent state (waiting after the job has failed in DestinationRateGrou file importer por instance)
=> microservices: wrap every worker code in try/catch

web/admin/application/assets/js/customMenu.js, web/admin/application/controllers/KlearCustomExtraAuthController.php, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Allow to filter brand / compny on emulation dialog
=> web/admin: filter field for emulation options

schema/DoctrineMigrations/Version20200701093454.php, web/rest/client/config/api/resources.yml, web/rest/client/config/routing.yml, web/rest/client/src/Controller/My/ActiveCallsAction.php, web/rest/client/src/Model/ActiveCalls.php
Expose active calls on client API
=> Expose active calls on client API

library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroup.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupAbstract.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupDtoAbstract.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/DestinationRateGroup.DestinationRateGroupAbstract.orm.yml, microservices/workers/src/Worker/Rates.php, schema/DoctrineMigrations/Version20200619074304.php, web/admin/application/configs/klear/model/DestinationRateGroups.yaml, web/admin/application/library/IvozProvider/Klear/Ghost/DestinationRateGroups.php, web/rest/brand/features/provider/destinationRateGroup/getDestinationRateGroup.feature, web/rest/brand/features/provider/destinationRateGroup/postDestinationRateGroup.feature, web/rest/brand/features/provider/destinationRateGroup/putDestinationRateGroup.feature
Show last execution error on DestinationRateGroups
=> Improved rate importer

doc/UPGRADE-2.16.md, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Administrator.AdministratorAbstract.orm.yml, schema/DoctrineMigrations/Version20200703083313.php
Make admin usernames unique across the entire platform
=> schema: unique administrator user names

web/admin/application/library/IvozProvider/Klear/Dynamic/Config/Base.php, web/admin/application/library/IvozProvider/Klear/Dynamic/Config/BrandOperator.php, web/admin/application/library/IvozProvider/Klear/Dynamic/Config/CompanyAdmin.php
- Show correctly logged user's name.
- Remove brackets from title.
=> web/admin: minor aesthetic changes

doc/UPGRADE-2.16.md, library/Ivoz/Provider/Domain/Model/Terminal/Terminal.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Terminal.TerminalAbstract.orm.yml, schema/DoctrineMigrations/Version20200707132513.php, web/rest/client/features/provider/terminal/getTerminal.feature, web/rest/client/features/provider/terminal/postTerminal.feature, web/rest/client/features/provider/user/getUser.feature
Make terminals mac address unique as non-unique entries break provisioning system.
=> Make terminals mac address unique

asterisk/agi/src/Dialplan/Friends.php
This PR enables friends calling to vPBX services codes. Some services won't work for friends, though (e.g. group pickup).
=> agis: add service handling for friends

library/DataFixtures/Stub/Ast/VoicemailStub.php, library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/PsEndpoint.PsEndpointAbstract.orm.yml, library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/Voicemail.VoicemailAbstract.orm.yml, schema/DoctrineMigrations/Version20200721074242.php
Although it should not be possible, these unique constraints ensures database integrity. This fields are unique and a relation 1 on 1 with their business tables.
=> scheme: add uniques in asterisk Endpoint/Voicemail tables

library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvScheduler.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerDto.php, web/admin/application/configs/klear/CallCsvSchedulersBrandList.yaml, web/admin/application/configs/klear/CallCsvSchedulersList.yaml, web/admin/application/configs/klear/model/CallCsvSchedulers.yaml
Allow to filter by fax in call CSV scheduler for residential clients
=> CallCSvScheduler residential fax filter

library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvScheduler.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerDtoAbstract.php, library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerInterface.php, library/Ivoz/Provider/Domain/Service/BillableCall/CsvExporter.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallCsvScheduler.CallCsvSchedulerAbstract.orm.yml, schema/DoctrineMigrations/Version20200715110449.php, web/admin/application/configs/klear/CallCsvSchedulersBrandList.yaml, web/admin/application/configs/klear/CallCsvSchedulersList.yaml, web/admin/application/configs/klear/model/CallCsvSchedulers.yaml, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/features/provider/callCsvScheduler/getCallCsvScheduler.feature, web/rest/brand/features/provider/callCsvScheduler/postCallCsvScheduler.feature, web/rest/brand/features/provider/callCsvScheduler/putCallCsvScheduler.feature, web/rest/brand/tests/DataAccessControl/Provider/CallCsvSchedulerTest.php
Allow to filter by ddi provider on call CSV schedulers
=> Csv scheduler ddi provider

doc/sphinx/administration_portal/client/retail/retail_accounts.rst, kamailio/users/config/kamailio.cfg, web/admin/application/library/IvozProvider/Klear/Filter/CallForwardTypes.php
This PR adds unconditional call forward for retail accounts.
=> Add unconditional call forward for retail accounts

library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSetting.php, library/spec/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingSpec.php
Ensure that only USER_NOT_REGISTERED CFS are created into retail clients
=> core: validate retail call forward settings

doc/sphinx/administration_portal/brand/views/bruteforce_attacks.rst, doc/sphinx/administration_portal/brand/views/index.rst, doc/sphinx/security_and_maintenance/security/antibruteforce.rst, kamailio/users/config/kamailio.cfg, library/Ivoz/Provider/Domain/Model/BannedAddress/BannedAddressAbstract.php, library/Ivoz/Provider/Domain/Model/BannedAddress/BannedAddressDtoAbstract.php, library/Ivoz/Provider/Domain/Model/BannedAddress/BannedAddressInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BannedAddress.BannedAddressAbstract.orm.yml, schema/DoctrineMigrations/Version20200824140640.php, web/admin/application/configs/klear/BruteForceAttacksList.yaml, web/admin/application/configs/klear/IpFilterBlockedAddressesList.yaml, web/admin/application/configs/klear/klear.yaml, web/admin/application/configs/klear/model/BannedAddresses.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po, web/rest/platform/features/provider/bannedAddress/getBannedAddress.feature
Add *Brute- force attacks* section at brand level that lists currently banned sources.
No buttons to allow a banned source yet, but will be added soon via #1484 .
=> web/admin: new Brute-force attacks section

doc/sphinx/security_and_maintenance/security/current_day_max_usage.rst, kamailio/trunks/config/kamailio.cfg, schema/DoctrineMigrations/Version20200825140817.php
Max Daily Usage mechanism now ends calls as soon as configured usage is reached.
This feature needs irontec/kamailio#2.
=> Max daily usage ends company calls

web/admin/application/controllers/KlearCustomTarificatorController.php
Fix RerateCallService path to fix call retarification.
=> web/admin: fix RerateCallService path

asterisk/agi/composer.lock, doc/sphinx/administration_portal/brand/views/bruteforce_attacks.rst, library/Ivoz/Kam/Domain/Service/UsersClientInterface.php, library/Ivoz/Kam/Infrastructure/Gearman/TrunksClient.php, library/Ivoz/Kam/Infrastructure/Gearman/UsersClient.php, library/Ivoz/Kam/Infrastructure/Kamailio/JsonRpcRequestTrait.php, library/Ivoz/Provider/Domain/Service/BannedAddress/Unban.php, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/services/domain.yml, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/services/infraestructure/gearman.yml, library/composer-packages/irontec/ivoz-provider-bundle/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/admin/application/configs/klear/BruteForceAttacksList.yaml, web/admin/application/controllers/KlearCustomBruteForceUnbanController.php, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
Added unban button into brute force attacks web admin page.
=> Unban anti brute-force banned sources

web/admin/application/configs/klear/CarriersList.yaml
Add view and rerate options to Billable Call list in Carriers section.
=> web/admin: add options in carrier BillableCalls list

web/admin/application/languages/it_IT/it_IT.po
Updated italian translations
- changed some translations for clarity
- translated most recently added strings
- fixed some typos
=> i18n: updated Italian translations

kamailio/trunks/config/kamailio.cfg, library/Ivoz/Kam/Domain/Service/TrunksClientInterface.php, library/Ivoz/Kam/Infrastructure/Gearman/TrunksClient.php, web/rest/brand/features/my/activeCalls/getActiveCalls.feature, web/rest/brand/src/Controller/My/ActiveCallsAction.php, web/rest/brand/src/Model/ActiveCalls.php, web/rest/client/features/my/activeCalls/getActiveCalls.feature, web/rest/client/src/Controller/My/ActiveCallsAction.php, web/rest/platform/features/my/activeCalls/getActiveCalls.feature, web/rest/platform/src/Controller/My/ActiveCallsAction.php, web/rest/platform/src/Model/ActiveCalls.php
/my/activeCalls platform/brand/client API endpoint returns total active external calls.
This PR adds inbound and outbound calls to returned response.
=> API: add inbound and outbound calls to activeCalls endpoint

ChangeLog, README.md, web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> doc: update changelog for 2.16.0

library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSetting.php, library/spec/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingSpec.php
It was throwing an exception o non user call forwards
=> core: fixed CFS refression

library/Ivoz/Cgr/Domain/Model/TpCdr/TpCdr.php
CostDetails may be 'null' (string) breaking entity getter signature
=> core: fixed TpCdr instantiation under some circumstances

doc/sphinx/administration_portal/brand/calls/call_csv_schedulers.rst, doc/sphinx/administration_portal/client/residential/calls/call_csv_schedulers.rst, doc/sphinx/administration_portal/client/retail/calls/call_csv_schedulers.rst, doc/sphinx/administration_portal/client/vpbx/calls/call_csv_schedulers.rst, doc/sphinx/administration_portal/client/wholesale/calls/call_csv_schedulers.rst, doc/sphinx/administration_portal/platform/external_calls.rst, web/admin/application/configs/klear/BillableCallsClientList.yaml, web/admin/application/configs/klear/BillableCallsList.yaml, web/admin/application/configs/klear/model/BillableCalls.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Some commits were missed in #1489 
- Show field in web portal
- Translations
- Documentation
=> Show endpoint name on web portal

ChangeLog, README.md
Update changelog for 2.16.1 release
=> doc: update changelog for 2.16.1 release

schema/DoctrineMigrations/Version20201106131908.php
New entry in Country table for +800 UIFN (Universal International Freephone Number).
=> schema: new country for International Freephone Numbers

kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg, profiles/proxy/usr/sbin/kamlog
- set debug core param to 1 (prints L_NOTICE and higher)
- L_NOTICE: standard minimal log messages (move acc/cdr logs here)
- L_WARNING: external error messages
- L_ERR: platform error messages
Adapt kamlog helper script too.
=> kam: reduce amount of log messages

library/Ivoz/Kam/Domain/Model/Rtpengine/Rtpengine.php, library/Ivoz/Kam/Domain/Model/Rtpengine/RtpengineInterface.php, library/Ivoz/Kam/Domain/Model/Trusted/Trusted.php, library/Ivoz/Kam/Domain/Model/Trusted/TrustedInterface.php, library/Ivoz/Kam/Domain/Model/UsersAddress/UsersAddress.php, library/Ivoz/Kam/Domain/Model/UsersAddress/UsersAddressInterface.php
Add Changelog to some Kamailio entities that were not logged.
=> core: review loggable entities

ChangeLog, README.md
Update changelog for 2.16.2 release
=> doc: update changelog for 2.16.2 release

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.yml, schema/DoctrineMigrations/Version20201126114632.php
- Add _caller_ and _callee_ indexes to make web filters faster.
- Create a _brand+company_ index to make web dashboard faster.
- _brand+company_ index makes _brand_ index unnecessary.
=> schema: add new indexes to BillableCalls

asterisk/agi/composer.lock, library/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/admin/application/configs/klear/model/BillableCalls.yaml, web/admin/application/controllers/KlearCustomBillableCallsController.php, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.json, web/rest/platform/composer.lock
Improved klear and API string filters. Added starts with, ends with, contains and exact search modifiers
updated dependencies:
- https://github.com/irontec/ivoz-api/releases/tag/3.2
- https://github.com/irontec/ivoz-api-bundle/releases/tag/3.4
- https://github.com/irontec/klearMatrix/commit/495cfcde97f9c74212c57b6cb6995af33fa4ca4d
=> Improved search forms

microservices/recordings/src/Recording/Encoder.php
Prevent recordings encoder from getting stuck if any KamAccCdr has not company id
=>  microservices: skip recording if empty company

ChangeLog, README.md
Update changelog for 2.16.3 release
=> doc: update changelog for 2.16.3 release

library/Ivoz/Provider/Domain/Model/Ddi/DdiDto.php, library/composer.lock, microservices/realtime/composer.lock, web/rest/brand/composer.lock, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/features/provider/ddi/getDdi.feature, web/rest/brand/features/provider/ddi/postDdi.feature, web/rest/brand/features/provider/ddi/putDdi.feature, web/rest/client/composer.lock, web/rest/client/config/api/raw/provider.yml, web/rest/client/features/provider/billableCall/getBillableCall.feature, web/rest/client/features/provider/ddi/getDdi.feature, web/rest/client/features/provider/ddi/putDdi.feature, web/rest/platform/composer.lock
Added ddie164 into API DDI collection response.
Updated ivoz-api library so that read only fields are properly filtered from input data (https://github.com/irontec/ivoz-api/commits/3.3.1)
=> Show ddie164 in ddi collection

web/admin/application/library/IvozProvider/Klear/Ghost/Invoice.php
Single quotes break error message tooltip
=> web/admin: escape invoices error msg properly

web/admin/application/configs/klear/CalendarsList.yaml, web/admin/application/configs/klear/HolidayDatesList.yaml, web/admin/application/configs/klear/conf.d/mapperList.yaml, web/admin/application/configs/klear/model/HolidayDatesRange.yaml, web/admin/application/controllers/KlearCustomCalendarController.php, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Added range holiday date creation screen
=> web/admin: allow holiday date range creation

debian/ivozprovider-profile-portal.postinst, profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf, profiles/portal/etc/apache2/sites-available/060-ivozprovider-api.conf, tests/stackhawk/bin/run, tests/stackhawk/stackhawk.yml
Added required configuration to run security tests on APIs
=> tests: added stackhawk configuration for APIs

library/Ivoz/Provider/Domain/Model/Terminal/TerminalAbstract.php, library/Ivoz/Provider/Domain/Model/Terminal/TerminalInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Terminal.TerminalAbstract.orm.yml, library/spec/Ivoz/Provider/Domain/Model/Terminal/TerminalSpec.php, schema/DoctrineMigrations/Version20210215095653.php
Made terminal name required in database
=> schema: not nullable terminal name

library/Ivoz/Provider/Application/Service/User/CsvStaticValidator.php, library/Ivoz/Provider/Application/Service/User/SyncFromCsv.php, library/Ivoz/Provider/Domain/Model/Terminal/Terminal.php, library/Ivoz/Provider/Domain/Model/Terminal/TerminalInterface.php, library/Ivoz/Provider/Domain/Model/TerminalModel/TerminalModelRepository.php, library/Ivoz/Provider/Domain/Model/User/UserRepository.php, library/Ivoz/Provider/Domain/Service/Ddi/DdiFactory.php, library/Ivoz/Provider/Domain/Service/Extension/ExtensionFactory.php, library/Ivoz/Provider/Domain/Service/Terminal/TerminalFactory.php, library/Ivoz/Provider/Domain/Service/User/UserFactory.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/TerminalModelDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/UserDoctrineRepository.php, library/composer.lock, library/spec/Ivoz/Provider/Application/Service/User/CsvStaticValidatorSpec.php, library/spec/Ivoz/Provider/Application/Service/User/SyncFromCsvSpec.php, library/spec/Ivoz/Provider/Domain/Service/Ddi/DdiFactorySpec.php, library/spec/Ivoz/Provider/Domain/Service/Extension/ExtensionFactorySpec.php, library/spec/Ivoz/Provider/Domain/Service/Terminal/TerminalFactorySpec.php, library/spec/Ivoz/Provider/Domain/Service/User/UserFactorySpec.php, schema/tests/Provider/User/UserRepositoryTest.php, web/rest/brand/config/api/resources.yml
Static CSV validation before the importer is run.
=> User mass importer improved validations

ChangeLog
=> 2.17 Changelog

web/admin/application/modules/provision/controllers/IndexController.php
Do not log failed provisioning responses as application errors.
Improve Terminal not found error string to display tried provisioning URL
=> web/admin: Terminal provisioning error handling

library/composer.json, library/composer.lock, microservices/workers/composer.json, microservices/workers/composer.lock
Replace mmadariaga/wkhtmltopdf-amd64 with irontec/wkhtmltopdf-amd64 dependency
Replace mmadariaga/TestDoubleBundle with irontec/TestDoubleBundle dependency
=> core: update composer dependencies namespace

web/admin/application/controllers/KlearCustomBillableCallsController.php
Removed unecessary webportal look up in order to download a external calls csv
=> fixed external call CSV download error

web/admin/application/controllers/KlearCustomDownloadRatingPlanController.php, web/rest/client/src/Controller/Provider/RatingPlanPricesAction.php
Multiple fixes:
- Fixed Content-Length header
- Removed web portal look up
- Require a non restricted admin
- Fixed RatingPlanPrices company admin validation
=> Rating plan prices download issues

schema/DoctrineMigrations/Version20210309081308.php
Added table compatibility with DoctrineMigrationsBundle 3.x
=> schema: prepare migration_versions for ivoz provider 3.x

web/admin/application/library/IvozProvider/Klear/Auth/User.php
Replace quotes by &quot; so that klear.yaml doesn't break
=> admin: avoid quotes in company name to break admin web

web/admin/application/controllers/KlearCustomCalendarController.php
Transform input date formats based on user UI language
=> web/admin: fixed holiday date range creation for non english languages

library/Ivoz/Kam/Infrastructure/Gearman/TrunksClient.php, library/Ivoz/Kam/Infrastructure/Gearman/UsersClient.php, library/Ivoz/Kam/Infrastructure/Kamailio/JsonRpcRequestTrait.php, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/services/infraestructure/kamailio.yml, library/composer-packages/irontec/ivoz-provider-bundle/composer.json, library/composer.lock
Avoid eternal requests when kamailio hangs out
=> set timeout into Kamailio JSON RPC requests

ChangeLog, README.md
Update changelog for 2.17.1 release
=> doc: update changelog for 2.17.1 release

web/admin/application/configs/klear/model/FaxesInOut.yaml, web/admin/application/configs/klear/model/Locutions.yaml, web/admin/application/configs/klear/model/MusicOnHold.yaml
Add extensions filters for Locutions and Music on Hold (WAV and MP3 files allowed) and Outgoing Faxes (PDF files allowed)
=> web/admin: uploaded file extensions for Locutions/Moh and Faxes

library/Ivoz/Provider/Domain/Service/Locution/SendRecodingOrder.php, library/Ivoz/Provider/Domain/Service/MusicOnHold/SendRecodingOrder.php
Do not enqueue recording order on deleted locutions / MOH
=> core: avoid unnecessary gearman jobs

README.md
=> doc: update software versions in README.md

web/admin/application/assets/js/plugins/jquery.rt.js, web/admin/application/assets/template/klearCustomRtCallBrandList.tmpl.html, web/admin/application/assets/template/klearCustomRtCallClientList.tmpl.html, web/admin/application/assets/template/klearCustomRtCallList.tmpl.html, web/admin/application/controllers/KlearCustomRtController.php, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Add copy callid feature into active calls
=> Active call copy callid feature

doc/sphinx/administration_portal/platform/global_special_numbers.rst, kamailio/trunks/config/kamailio.cfg, kamailio/users/config/kamailio.cfg
Skip calls to special numbers in Active Calls.
=> Skip calls to special numbers in Active Calls

web/admin/application/configs/klear/RecordingsList.yaml
Fix Delete and View (labeled as Edit) secctions in Recordings screens so it takes into account Admin configured ACLs
=> web/admin: fix Client Recordings section ACLs

microservices/realtime/src/Services/RedisClientFactory.php
Retry 3 times in 30 seconds before an exception is thrown
=> microservices: [realtime] retry on redis connect error

FAQ.md, README.md, doc/sphinx/basic_concepts/intro/getting_help.rst, doc/sphinx/locale/es/LC_MESSAGES/basic_concepts.po
Update documentation to point to the new IRC channel at irc.libera.chat
=> doc: update documentation with Libera.chat IRC channel

asterisk/agi/composer.lock, library/Ivoz/Provider/Infrastructure/Api/Jwt/AdminTokenAuthenticator.php, library/Ivoz/Provider/Infrastructure/Api/Jwt/UserTokenAuthenticator.php, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
Updated lexik/jwt-authentication-bundle and symfony/security composer dependencies in order to fix some low/moderate security issues
=> core: updated composer dependencies

library/composer.lock, web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
Entities with multiple collection responses weren't showing proper filter options
=> Fixed API filter issues

web/admin/application/configs/klear/BillableCallsClientList.yaml, web/admin/application/configs/klear/BrandDDIsList.yaml, web/admin/application/configs/klear/DdiProvidersList.yaml, web/admin/application/configs/klear/DdisList.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Show External Calls option in following related entities:
- Brand DDIs.
- Client DDIs.
- DDI Providers.
=> web/admin: show External Calls option in related entities

library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointAbstract.php, library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/PsEndpoint.PsEndpointAbstract.orm.yml, schema/DoctrineMigrations/Version20210607075411.php
Increase named pickup group Asterisk database field from 40 characters to 255.
=> Increase named pickup group size

ChangeLog, README.md
Update changelog for 2.17.2 release
=> doc: update changelog for 2.17.2 release

asterisk/agi/composer.lock, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupDto.php, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/rest/brand/composer.lock, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/features/provider/destinationRateGroup/postDestinationRateGroup.feature, web/rest/client/composer.lock, web/rest/platform/composer.lock
API was ignoring uploaded files at [POST] /destination_rate_groups
=> Fixed destination rate groups file uploads through the API

library/Ivoz/Cgr/Domain/Model/TpAccountAction/TpAccountActionAbstract.php, library/Ivoz/Cgr/Domain/Model/TpAccountAction/TpAccountActionInterface.php, library/Ivoz/Cgr/Domain/Model/TpDerivedCharger/TpDerivedChargerAbstract.php, library/Ivoz/Cgr/Domain/Model/TpDerivedCharger/TpDerivedChargerInterface.php, library/Ivoz/Cgr/Domain/Model/TpDestination/TpDestinationAbstract.php, library/Ivoz/Cgr/Domain/Model/TpDestination/TpDestinationInterface.php, library/Ivoz/Cgr/Domain/Model/TpDestinationRate/TpDestinationRateAbstract.php, library/Ivoz/Cgr/Domain/Model/TpDestinationRate/TpDestinationRateInterface.php, library/Ivoz/Cgr/Domain/Model/TpLcrRule/TpLcrRuleAbstract.php, library/Ivoz/Cgr/Domain/Model/TpLcrRule/TpLcrRuleInterface.php, library/Ivoz/Cgr/Domain/Model/TpRate/TpRateAbstract.php, library/Ivoz/Cgr/Domain/Model/TpRate/TpRateInterface.php, library/Ivoz/Cgr/Domain/Model/TpRatingPlan/TpRatingPlanAbstract.php, library/Ivoz/Cgr/Domain/Model/TpRatingPlan/TpRatingPlanInterface.php, library/Ivoz/Cgr/Domain/Model/TpTiming/TpTimingAbstract.php, library/Ivoz/Cgr/Domain/Model/TpTiming/TpTimingInterface.php, library/Ivoz/Kam/Domain/Model/TrunksAddress/TrunksAddressAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksAddress/TrunksAddressInterface.php, library/Ivoz/Kam/Domain/Model/TrunksLcrGateway/TrunksLcrGatewayAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksLcrGateway/TrunksLcrGatewayInterface.php, library/Ivoz/Kam/Domain/Model/TrunksUacreg/TrunksUacregAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksUacreg/TrunksUacregInterface.php, library/composer.lock, schema/composer.lock, web/rest/user/composer.lock
Regenerate one-to-one generated methods using entity interfaces instead of entity classes
=> Fix Generator one to one relations code

library/Ivoz/Kam/Domain/Model/TrunksUacreg/TrunksUacregAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksUacreg/TrunksUacregDtoAbstract.php, library/Ivoz/Kam/Domain/Model/TrunksUacreg/TrunksUacregInterface.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksUacreg.TrunksUacregAbstract.orm.xml, schema/DoctrineMigrations/Version20210802143904.php, schema/tests/Provider/DdiProviderRegistration/DdiProviderRegistrationLifeCycleTest.php
Changes in Kamailio database scheme to upgrade from Kamailio 5.4.4 to Kamailio 5.5.1.
+info: https://www.kamailio.org/wiki/install/upgrade/5.4.x-to-5.5.0
=> Upgrade to Kamailio 5.5.1

doc/sphinx/administration_portal/brand/views/bruteforce_attacks.rst, kamailio/users/config/kamailio.cfg, web/admin/application/configs/klear/BruteForceAttacksList.yaml
Add User-Agent header content in Description column of Anti-bruteforce section, to make it easier to detect an endpoint with wrong password.
=> Show User-Agent in anti-bruteforce list section

library/Ivoz/Provider/Domain/Model/BrandService/BrandServiceRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BrandServiceDoctrineRepository.php, schema/tests/Provider/BrandService/BrandServiceRepositoryTest.php, web/rest/client/config/api/raw/provider.yml, web/rest/client/config/services.yml, web/rest/client/features/provider/service/getServices.feature, web/rest/client/tests/DataAccessControl/Provider/ServiceTest.php
Service list must be filtered in client API
=> Restrict service list in client api

library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersPresentity.UsersPresentityAbstract.orm.xml, schema/DoctrineMigrations/Version20210413112300.php
Sqlite requires unique index names
=> Fixed index name

library/Ivoz/Provider/Domain/Model/Brand/BrandDto.php, web/rest/brand/features/provider/brand/getBrands.feature, web/rest/brand/features/provider/brand/putBrands.feature, web/rest/platform/features/provider/brand/getBrands.feature
Updated API response model attributes
=> Brand api response fields

library/DataFixtures/ORM/ProviderBrandService.php, library/DataFixtures/ORM/ProviderService.php, library/Ivoz/Provider/Domain/Model/CompanyService/CompanyServiceRepository.php, library/Ivoz/Provider/Domain/Model/Service/ServiceRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CompanyServiceDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/ServiceDoctrineRepository.php, schema/tests/Provider/CompanyService/CompanyServiceRepositoryTest.php, schema/tests/Provider/Service/ServiceRepositoryTest.php, web/rest/brand/features/provider/brandService/getBrandService.feature, web/rest/brand/features/provider/brandService/postBrandService.feature, web/rest/brand/features/provider/service/getService.feature, web/rest/client/config/api/raw/provider.yml, web/rest/client/config/routing.yml, web/rest/client/features/provider/service/getServices.feature, web/rest/client/features/provider/service/getUnassignedServices.feature, web/rest/client/src/Controller/Provider/ServicesUnassignedAction.php, web/rest/platform/features/provider/brandService/postBrandService.feature, web/rest/platform/features/provider/service/getService.feature
Added /api/client/services/unassigned API endpoint
=> Api client unassigned services endpoint

asterisk/agi/composer.json, asterisk/agi/composer.lock, library/Ivoz/Provider/Domain/Model/Brand/BrandDto.php, library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupDto.php, library/Ivoz/Provider/Domain/Model/Locution/LocutionDto.php, library/Ivoz/Provider/Domain/Model/MusicOnHold/MusicOnHoldDto.php, library/Ivoz/Provider/Domain/Model/WebPortal/WebPortalDto.php, library/composer.lock, microservices/balances/composer.json, microservices/balances/composer.lock, microservices/realtime/composer.json, microservices/realtime/composer.lock, microservices/recordings/composer.json, microservices/recordings/composer.lock, microservices/scheduler/composer.json, microservices/scheduler/composer.lock, microservices/workers/composer.json, microservices/workers/composer.lock, schema/composer.json, schema/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/client/config/api/raw/provider.yml, web/rest/platform/composer.json, web/rest/platform/composer.lock, web/rest/platform/features/provider/brand/postBrands.feature, web/rest/platform/features/provider/brand/putBrands.feature
Improved API spec related to entities with uploadable/downloadable files
=> Api improved files spec

library/Ivoz/Provider/Domain/Model/Company/Company.php, library/spec/Ivoz/Provider/Domain/Model/Company/CompanySpec.php
Require vpbx or residential client
=> Companies on demand record validation

web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
**This release includes a breaking change in client API TerminalModel response model**: genericTemplate, specificTemplate, genericUrlPattern and specificUrlPattern have been removed. Clients should never have had access to this properties but it's still a BC.
=> doc: updated API changelog for 2.18.1

ChangeLog, README.md
Update changelog for 2.18.1 release
=> doc: update changelog for 2.18.1 release

library/Ivoz/Provider/Domain/Model/Brand/BrandAbstract.php, library/Ivoz/Provider/Domain/Model/Brand/BrandDto.php, library/Ivoz/Provider/Domain/Model/Brand/BrandInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Brand.BrandAbstract.orm.yml, library/spec/Ivoz/Provider/Domain/Model/Brand/BrandSpec.php, schema/DoctrineMigrations/Version20210930091127.php, schema/tests/Provider/Brand/BrandLifeCycleTest.php, web/rest/platform/config/api/raw/provider.yml, web/rest/platform/features/provider/brand/getBrands.feature, web/rest/platform/features/provider/brand/postBrands.feature, web/rest/platform/features/provider/brand/putBrands.feature, web/rest/platform/features/provider/currency/getCurrency.feature, web/rest/platform/features/provider/currency/postCurrency.feature, web/rest/platform/features/provider/currency/putCurrency.feature, web/rest/platform/features/provider/currency/removeCurrency.feature, web/rest/platform/features/provider/featuresRelBrand/getFeaturesRelBrand.feature, web/rest/platform/features/provider/featuresRelBrand/postFeaturesRelBrand.feature, web/rest/platform/features/provider/proxyTrunkRelBrand/getProxyTrunkRelBrand.feature, web/rest/platform/features/provider/proxyTrunkRelBrand/postProxyTrunkRelBrand.feature
Brand currency must be mandatory in db and application
=> Make brand currency mandatory 

library/Ivoz/Provider/Domain/Model/BalanceNotification/BalanceNotification.php, library/Ivoz/Provider/Domain/Model/BalanceNotification/BalanceNotificationInterface.php, library/Ivoz/Provider/Domain/Model/Brand/Brand.php, library/Ivoz/Provider/Domain/Model/Brand/BrandAbstract.php, library/Ivoz/Provider/Domain/Model/Brand/BrandInterface.php, library/Ivoz/Provider/Domain/Model/Company/Company.php, library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php, library/Ivoz/Provider/Domain/Model/User/User.php, library/Ivoz/Provider/Domain/Model/User/UserInterface.php, library/Ivoz/Provider/Domain/Service/MaxUsageNotification/NotifyMaxDailyUsage.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Brand.BrandAbstract.orm.xml, library/bin/test-psalm, library/bin/test-psalm-update-baseline, library/phpstan-baseline.neon, library/psalm-baseline.xml, library/spec/Ivoz/Provider/Domain/Model/Brand/BrandSpec.php, schema/DoctrineMigrations/Version20211004094635.php, schema/tests/Provider/Brand/BrandLifeCycleTest.php, web/rest/platform/features/provider/brand/postBrands.feature
Made brand language required and set it into companies on sanitizeValues if empty
=> Required brand language

Jenkinsfile
=> tests: remove prepare and run from schema tests

asterisk/agi/phpstan-baseline.neon, asterisk/agi/src/Agi/Action/FaxReceiveStatusAction.php, asterisk/agi/src/Voicemail/Sender.php, library/DataFixtures/ORM/ProviderNotificationTemplate.php, library/Ivoz/Provider/Domain/Model/BalanceNotification/BalanceNotification.php, library/Ivoz/Provider/Domain/Model/BalanceNotification/BalanceNotificationInterface.php, library/Ivoz/Provider/Domain/Model/NotificationTemplate/NotificationTemplateRepository.php, library/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThreshold.php, library/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSender.php, library/Ivoz/Provider/Domain/Service/Invoice/EmailSender.php, library/Ivoz/Provider/Domain/Service/MaxUsageNotification/NotifyMaxDailyUsage.php, library/Ivoz/Provider/Domain/Service/MaxUsageNotification/SearchBrokenMaxDailyUsage.php, library/Ivoz/Provider/Domain/Service/NotificationTemplateContent/CallCsvNotificationTemplateByCallCsvReport.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/NotificationTemplateDoctrineRepository.php, library/phpstan-baseline.neon, library/psalm-baseline.xml, library/spec/Ivoz/Provider/Domain/Model/BalanceNotification/BalanceNotificationSpec.php, library/spec/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThresholdSpec.php, library/spec/Ivoz/Provider/Domain/Service/NotificationTemplateContent/CallCsvNotificationTemplateByCallCsvReportSpec.php, schema/tests/Provider/NotificationTemplate/NotificationTemplateRepositoryTest.php, web/rest/brand/features/provider/notificationTemplate/postNotificationTemplate.feature
Ignore notification templates without content for required language
=> Notification template repository refactoring

doc/sphinx/administration_portal/brand/clients/retail.rst, doc/sphinx/administration_portal/brand/clients/wholesale.rst, web/admin/application/configs/klear/RetailClientsList.yaml, web/admin/application/configs/klear/WholesaleClientsList.yaml, web/admin/application/configs/klear/model/RetailClients.yaml, web/admin/application/configs/klear/model/WholesaleClients.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Avoid selecting all codecs in transcoding multi-select of retail/wholesale clients:
- Hide onNew.
- Add helper linking to doc.
- Add warning note in doc explaining transcoding feature.
=> Add disclaimer about transcoding in retail/wholesale clients

web/rest/brand/CHANGELOG.md, web/rest/platform/CHANGELOG.md
DC: Brand creation through API requires currency to be set
=> doc: updated API changelog for 2.19.0

asterisk/agi/composer.lock, library/DataFixtures/ORM/KamUsersLocation.php, library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallDto.php, library/Ivoz/Provider/Domain/Model/Friend/FriendDto.php, library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceDto.php, library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccountDto.php, library/Ivoz/Provider/Domain/Model/Terminal/TerminalDto.php, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/rest/brand/composer.lock, web/rest/brand/features/provider/residentialDevice/getResidentialDeviceStatus.feature, web/rest/client/composer.lock, web/rest/client/features/provider/residentialDevices/getResidentialDeviceStatus.feature, web/rest/platform/composer.lock
Fixed devices/status API responses. It was showing only the first status row
=> Api device status error

web/client/src/lib/components/List/ContentTable/ContentTable.tsx, web/client/src/lib/components/List/ContentTable/ContentTableHead.tsx, web/client/src/lib/components/List/ContentTable/ContentTablePagination.tsx, web/client/src/lib/components/List/Filter/FilterCriteria.tsx, web/client/src/lib/components/List/Filter/icons/FilterIconFactory.tsx, web/client/src/lib/components/List/List.helpers.ts, web/client/src/lib/components/List/List.tsx, web/client/src/lib/components/List/useQueryStringParams.tsx, web/client/src/store/api.ts, web/client/src/store/route.ts
Add sort and pagination arguments into the URL so that links can be shared and history navigation doesn't lose information
=> Pagination params into url

library/composer.lock
disables DQL query cache on DataGateway
@see https://github.com/irontec/ivoz-core/commit/9f7417f523ebf1af7929fe9d04ac3661ec18a936
=> Disable DQL query cache on DataGateway

asterisk/agi/src/MicroKernel.php, asterisk/agi/src/Voicemail/Sender.php
Fix exception handling in voicemail sender to properly show errors in logs.
This script does not have fastagi so errors must be displayed using logger.
=> agi: fix error handling in voicemail sender service

schema/DoctrineMigrations/Version20220121095227.php
Custom uploaded files for brand and clients MoH was being played sequentially.
Now files will be played in random order.
=> Random custom Music on Hold

schema/DoctrineMigrations/Version20220207082635.php
Add primary key to BillableCallHistorics
=> schema: add primary key to BillableCallHistorics

Jenkinsfile
=> ci: add Jira notifications to Jenkinsfile

asterisk/agi/composer.lock, library/Ivoz/Provider/Domain/Model/Changelog/Changelog.php, library/Ivoz/Provider/Domain/Model/Changelog/ChangelogInterface.php, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
Fixes duplicated change detection in post persist changes on root entity.
Includes https://github.com/irontec/ivoz-core/commit/e55ec9ac28757b8e068ad46158c6fedc3e9efc21
=> Improved changelog

library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingDto.php, library/Ivoz/Provider/Domain/Model/ConditionalRoutesCondition/ConditionalRoutesConditionDto.php, library/Ivoz/Provider/Domain/Model/ConditionalRoutesConditionsRelMatchlist/ConditionalRoutesConditionsRelMatchlistDto.php, library/Ivoz/Provider/Domain/Model/ConditionalRoutesConditionsRelRouteLock/ConditionalRoutesConditionsRelRouteLockDto.php, library/Ivoz/Provider/Domain/Model/IvrEntry/IvrEntryDto.php, web/rest/brand/features/provider/user/postUser.feature, web/rest/brand/features/provider/user/postUserMassImport.feature, web/rest/client/config/api/raw/provider.yml, web/rest/client/features/provider/callForwardSetting/getCallForwardSetting.feature, web/rest/client/features/provider/conditionalRoutesCondition/getConditionalRoutesCondition.feature, web/rest/client/features/provider/conditionalRoutesConditionsRelRouteLock/getConditionalRoutesConditionsRelRouteLock.feature, web/rest/client/features/provider/conditionalRoutesConditionsRelRouteLock/postConditionalRoutesConditionsRelRouteLock.feature, web/rest/client/features/provider/ivrEntry/getIvrEntry.feature, web/rest/client/tests/DataAccessControl/Provider/HuntGroupsRelUserTest.php
- Added some missing fields in collection responses
- Fixed ConditionalRoutesConditionsRelRouteLock response model
- Fixed HuntGroupsRelUser access control
=> Updated API collection responses

library/Ivoz/Provider/Application/Service/User/SyncFromCsv.php
Assign just created ddis to it's user in /users/mass_import API endpoint
=> core: User/SyncFromCsv assign new ddis to user

library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServer.php, library/Ivoz/Provider/Domain/Model/DdiProviderRegistration/DdiProviderRegistration.php, library/Ivoz/Provider/Domain/Model/Friend/Friend.php, library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDevice.php, library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccount.php, library/Ivoz/Provider/Domain/Model/Terminal/Terminal.php
Trim passwords to avoid issues
=> core: trim passwords

asterisk/agi/composer.lock, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock
- Updating irontec/ivoz-core-bundle (3.5.1 => 3.5.2)
- Updating symfony/polyfill-ctype (v1.18.1 => v1.19.0):  Checking out aed596913b
- Updating symfony/inflector (v3.4.43 => v3.4.47):  Checking out b557c5d061
- Updating symfony/property-info (v3.4.43 => v3.4.47):  Checking out a5f1e77c88
- Updating symfony/serializer (v3.4.43 => v3.4.47):  Checking out 6d69ccc1dc
- Updating symfony/polyfill-util (v1.18.1 => v1.19.0):  Checking out 8df0c3e6a4
- Updating symfony/polyfill-php56 (v1.18.1 => v1.19.0):  Checking out ea19621731
- Updating symfony/polyfill-php70 (v1.18.1 => v1.19.0):  Checking out 3fe4140772
- Updating symfony/polyfill-mbstring (v1.18.1 => v1.19.0):  Checking out b5f7b932ee
- Updating symfony/polyfill-intl-icu (v1.18.1 => v1.19.0):  Checking out f740dd60a5
- Updating …
=> core: updated symfony composer dependencies

ChangeLog, web/rest/client/CHANGELOG.md
Work in progress
Changelog for 2.20.0 release
=> doc: update changelog for 2.20.0

debian/ivozprovider-profile-data.config, debian/ivozprovider-profile-data.postinst, debian/ivozprovider-profile-data.templates, profiles/data/etc/bind/db.ivozprovider.local
New dns entry for future configurations in Kamailio & Asterisk hep modules.
=> New local dns entry hep.ivozprovider.local

web/rest/client/config/api/raw/provider.yml, web/rest/client/tests/DataAccessControl/Provider/CallForwardSettingTest.php
This was missed in #1731 and includes friend field validation so only a friend of the same company can be entered in API requests
=> Add missing ACLs for Call Forward Settings client API endpoint 

tests/bbs/2530-test-friend-cfw-unregisted.yaml, tests/bbs/2531-test-friend-cfw-busy.yaml, tests/bbs/2532-test-friend-cfw-noanswer.yaml, tests/bbs/dataset.json
=> tests: add new BBS tests for friends call forward settings

debian/ivozprovider-profile-portal.postinst
Remove existing errors with non-existant modules and changed postinstall commands to make them more clear.
This also enables HTTP/2 Module for #1698
=> Rework apache modules and sites configurations

library/DataFixtures/ORM/CgrTpCdr.php, library/DataFixtures/ORM/KamTrunksCdr.php, library/Ivoz/Cgr/Domain/Model/TpCdr/TpCdrRepository.php, library/Ivoz/Cgr/Infrastructure/Cgrates/Service/RerateCallService.php, library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/TpCdrDoctrineRepository.php, library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrRepository.php, library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php, schema/tests/Cgr/TpCdr/TpCdrRepositoryTest.php, schema/tests/Kam/TrunksCdr/TrunksCdrRepositoryTest.php
Remove corrupted tp_cdr rows before rerating
=> Enhanced rerating

library/bin/test-codestyle
Select the php files to be checked by comparing the changes against target branch.
This PR is used for testing the changes in the test rather than reviewing the changes.
=> Fix branch comparison mode in test-codestyle 

web/admin/application/configs/klear/DdiProvidersList.yaml
Hide retail account in DDI list of DDI Provider (Brand sub-section).
=> web/admin: hide retailAccount in DDI list section

web/rest/client/config/services.yaml, web/rest/client/src/Controller/My/ActiveCallsAction.php
=> web/rest: restore client my/active_calls controller

web/client/src/entities/Extension/Extension.tsx
Extensions route type selector was not showing conditional route field.
=> web/client: fixed extension.conditionalRoute visual toggle

web/client/src/components/Dashboard/Dashboard.tsx, web/client/src/components/Dashboard/DashboardBlock.tsx, web/client/src/entities/Ddi/Ddi.tsx, web/client/src/entities/Ddi/Field/RouteType.tsx, web/client/src/entities/Ddi/Form.tsx, web/client/src/entities/Ddi/foreignKeyGetter.tsx, web/client/src/entities/Extension/Extension.tsx, web/client/src/entities/Queue/Field/Strategy.tsx, web/client/src/entities/Queue/Form.tsx, web/client/src/entities/Queue/Queue.tsx, web/client/src/router/EntityMap.tsx, web/client/src/router/useAclFilteredEntityMap.tsx, web/client/yarn.lock
Removed fake vpbx admin validations
=> vPbx admin validations in client portal

library/Ivoz/Provider/Domain/Model/FeaturesRelCompany/FeaturesRelCompanyRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/FeaturesRelCompanyDoctrineRepository.php, schema/tests/Provider/FeaturesRelCompany/FeaturesRelCompanyRepositoryTest.php, web/client/src/entities/ConditionalRoute/ConditionalRoute.tsx, web/client/src/entities/ConditionalRoute/ConditionalRouteProperties.tsx, web/client/src/entities/ConditionalRoute/Field/RouteType.tsx, web/client/src/entities/ConditionalRoute/Form.tsx, web/client/src/entities/ConditionalRoute/foreignKeyGetter.tsx, web/client/src/entities/ConditionalRoutesCondition/ConditionalRoutesCondition.tsx, web/client/src/entities/ConditionalRoutesCondition/ConditionalRoutesConditionProperties.tsx, web/client/src/entities/ConditionalRoutesCondition/Field/RouteType.tsx, web/client/src/entities/ConditionalRoutesCondition/Form.tsx, web/client/src/entities/ConditionalRoutesCondition/foreignKeyGetter.tsx, web/client/src/entities/Ddi/DdiProperties.tsx, web/client/src/entities/Ddi/Field/RouteType.tsx, web/client/src/entities/Ddi/Form.tsx, web/client/src/entities/Ddi/foreignKeyGetter.tsx, web/client/src/entities/Extension/Extension.tsx, web/client/src/entities/Extension/ExtensionProperties.tsx, web/client/src/entities/Extension/Field/RouteType.tsx, web/client/src/entities/Extension/Form.tsx, web/client/src/entities/Extension/foreignKeyGetter.tsx, web/client/src/store/clientSession/aboutMe.ts, web/rest/client/features/my/profile/getProfile.feature, web/rest/client/src/Controller/My/ProfileAction.php, web/rest/client/src/Model/Profile.php
=> check company features in client portal

web/client/src/router/EntityMap.tsx
Filter entities for wholesale administrators
=> web/client: added entity access validation for wholesale admins

web/client/src/entities/CallForwardSetting/Field/TargetType.tsx, web/client/src/entities/CallForwardSetting/Form.tsx, web/client/src/entities/Ddi/Field/RouteType.tsx, web/client/src/entities/Ddi/Form.tsx, web/client/src/router/EntityMap.tsx, web/client/src/store/clientSession/aboutMe.ts, web/rest/client/features/my/profile/getProfile.feature, web/rest/client/src/Model/Profile.php
Rename pbx by vpbx in API /my/profile response model
=> rename my profile pbx by vpbx

library/DataFixtures/ORM/ProviderAdministrator.php, library/DataFixtures/ORM/ProviderCompany.php, web/rest/brand/features/provider/administrator/postAdministrators.feature, web/rest/client/config/api/raw/provider.yml, web/rest/client/features/provider/voicemail/getVoicemail.feature, web/rest/client/src/Service/Behat/FeatureContext.php, web/rest/platform/features/provider/administrator/postAdministrators.feature
Voicemail is only accessible by vpbx and residential admins
=> Voicemail API validation

asterisk/agi/composer.lock, library/Ivoz/Provider/Application/Service/Terminal/TerminalDtoAssembler.php, library/Ivoz/Provider/Domain/Model/Terminal/TerminalDto.php, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/parameters.yml, library/composer-packages/irontec/ivoz-provider-bundle/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, schema/composer.lock, web/client/src/entities/RetailAccount/Form.tsx, web/client/src/entities/Terminal/Form.tsx, web/client/src/entities/Terminal/Terminal.tsx, web/client/src/entities/Terminal/TerminalProperties.tsx, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/client/features/provider/terminal/getTerminal.feature, web/rest/client/features/provider/terminal/getUnassignedTerminals.feature, web/rest/platform/composer.lock, web/rest/user/composer.lock
Show domain name and terminal status properly in new client portal
=> Fixed terminal domain resolution in API

web/client/src/router/EntityMap.tsx, web/client/src/store/clientSession/aboutMe.ts, web/rest/client/config/api/raw/provider.yml
Restrict entity access based on client features
=> Check client features

web/admin/application/configs/klear/VoicemailMessagesList.yaml, web/admin/application/configs/klear/VoicemailsList.yaml, web/admin/application/configs/klear/conf.d/mapperList.yaml, web/admin/application/configs/klear/model/VoicemailMessages.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
This PR contains the implementation of #1755 for web/admin component
=> web/admin: realtime voicemail messages

debian/ivozprovider-web-user.install, debian/rules, web/user/package.json
Enable again the building of ivozprovider-web-user package
=> pkg: enable web/user package build

web/admin/application/configs/klear/LocationsList.yaml, web/admin/application/configs/klear/UsersList.yaml, web/admin/application/configs/klear/conf.d/mapperList.yaml, web/admin/application/configs/klear/klear.yaml, web/admin/application/configs/klear/model/Locations.yaml, web/admin/application/configs/klear/model/Users.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
web/admin adaptations required for #1746 
This changes have been taken directly from the implementation done for artemis in #1716
=> web/admin: vPBX Users Location

web/admin/application/configs/klear/ExternalCallFiltersList.yaml, web/admin/application/configs/klear/model/ExternalCallFilters.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Implementation of #1740 for web/admin component
=> web/admin: update Call Filters screens with Out of Schedule enabled

web/admin/application/configs/klear/ExternalCallFiltersList.yaml, web/admin/application/configs/klear/model/ExternalCallFilters.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po
Implementation of #1750 for web/admin component
=> web/admin: update Call Filters screens with Holiday enabled

web/admin/application/configs/klear/CallForwardSettingsList.yaml, web/admin/application/configs/klear/FriendsList.yaml, web/admin/application/configs/klear/model/CallForwardSettings.yaml
Implementation of #1715 for web/client component
=> web/admin: add CallForwardSettings screens for Friends

debian/ivozprovider-profile-portal.postinst
Add missing settings for php-fpm
=> pkg: add php fpm settings in postinstall

asterisk/agi/composer.lock, library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/parameters.yml, library/composer-packages/irontec/ivoz-provider-bundle/composer.json, library/composer.lock, microservices/balances/composer.lock, microservices/realtime/composer.lock, microservices/recordings/composer.lock, microservices/scheduler/composer.lock, microservices/workers/composer.lock, microservices/workers/config/services.yaml, microservices/workers/src/Worker/AsteriskDialplan.php, microservices/workers/src/Worker/AsteriskHintUpdater.php, microservices/workers/src/Worker/Cgrates.php, microservices/workers/src/Worker/Invoices.php, microservices/workers/src/Worker/KamRpc.php, microservices/workers/src/Worker/Multimedia.php, microservices/workers/src/Worker/Rates.php, schema/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock, web/rest/user/composer.lock
Update Wokers to fix an issue that caused reconnection errors after a minute waiting for a task.
=> Set workers connection timeout to 3600 seconds

library/Ivoz/Kam/Domain/Service/Dispatcher/UpdateByApplicationServer.php, library/Ivoz/Provider/Domain/Model/ApplicationServer/ApplicationServerAbstract.php, library/Ivoz/Provider/Domain/Model/ApplicationServer/ApplicationServerDtoAbstract.php, library/Ivoz/Provider/Domain/Model/ApplicationServer/ApplicationServerInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ApplicationServer.ApplicationServerAbstract.orm.xml, schema/DoctrineMigrations/Version20220603094200.php
=> Make Application Server name not nullable

schema/DoctrineMigrations/Version20220607135943.php
=> schema: fix wrong escaped Public entities fqdns

web/client/src/entities/CalendarPeriod/Field/Target.tsx, web/client/src/entities/CallForwardSetting/Field/TargetTypeValue.tsx, web/client/src/entities/ConditionalRoutesCondition/Field/ConditionMatch.tsx, web/client/src/entities/ConditionalRoutesCondition/Field/Target.tsx, web/client/src/entities/HolidayDate/Field/Calendar.tsx, web/client/src/entities/HolidayDate/Field/Target.tsx, web/client/src/entities/IvrEntry/Field/Target.tsx, web/client/src/entities/MatchListPattern/Field/MatchValue.tsx
Found during the implementation of #1814 
Not sure if there are others.
=> web/client: fix copy&paste typos in multiple entities

library/Ivoz/Provider/Domain/Model/Country/CountryAbstract.php, library/Ivoz/Provider/Domain/Model/Country/CountryDtoAbstract.php, library/Ivoz/Provider/Domain/Model/Country/Name.php, library/Ivoz/Provider/Domain/Service/RoutingPattern/UpdateByBrand.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Country.Name.orm.xml, library/psalm-baseline.xml, schema/DoctrineMigrations/Version20220603091748.php
=> Make country names not nullable

asterisk/agi/src/Agi/Action/IvrAction.php, library/DataFixtures/ORM/ProviderIvrEntry.php, library/Ivoz/Provider/Domain/Model/IvrEntry/IvrEntryAbstract.php, library/Ivoz/Provider/Domain/Model/IvrEntry/IvrEntryDto.php, library/Ivoz/Provider/Domain/Model/IvrEntry/IvrEntryDtoAbstract.php, library/Ivoz/Provider/Domain/Model/IvrEntry/IvrEntryInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/IvrEntry.IvrEntryAbstract.orm.xml, schema/DoctrineMigrations/Version20220608140537.php, tests/bbs/2011-test-ivr-custom-displayname.yaml, tests/bbs/dataset.json, web/admin/application/configs/klear/IvrEntriesList.yaml, web/admin/application/configs/klear/model/IvrEntries.yaml, web/client/src/entities/IvrEntry/Form.tsx, web/client/src/entities/IvrEntry/IvrEntry.tsx, web/client/src/entities/IvrEntry/IvrEntryProperties.tsx, web/rest/client/features/provider/ivrEntry/getIvrEntry.feature, web/rest/client/features/provider/ivrEntry/postIvrEntry.feature, web/rest/client/features/provider/ivrEntry/putIvrEntry.feature
This allows setting a custom display name like DDIs already have to provide additional information to callee.
=> Add IVR entry custom display name support

web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md, web/rest/user/CHANGELOG.md
=> doc: updated client API changelog for 3.0.0

microservices/recordings/src/Recording/Encoder.php, microservices/recordings/src/Service/Encoder.php, microservices/workers/src/Worker/Multimedia.php
=> microservices: replace avconv with ffmpeg

.gitignore, web/client/src/entities/User/User.tsx
This minor change performs a process that compares if the given password value contains asterisks.
=> web client fix password save

doc/sphinx/basic_concepts/installation/debian_install.rst, doc/sphinx/basic_concepts/installation/extra_components.rst, doc/sphinx/basic_concepts/installation/requirements.rst
=> doc: update installation documentation for halliday

kamailio/trunks/config/kamailio.cfg
Upport https://github.com/irontec/ivozprovider/pull/1836
=> kamtrunks: avoid gw failover on bounced calls

web/admin/application/configs/klear/CompaniesList.yaml
Companies screen belongs to Brand and should not be filtered based on emulated company type.
=> web/admin: fix Company creation/deletion ACLs

debian/control, scripts/FSOVoicemailMessages.py
Add a new script to import existing voicemails in storage to realtime, so they can be managed through web interface
=> Import voicemail realtime script

doc/sphinx/security_and_maintenance/security/antiflooding.rst, kamailio/users/config/kamailio.cfg
Upports https://github.com/irontec/ivozprovider/pull/1842
=> kamusers: skip options count in antiflood

schema/initial.sql
Update initial.sql file generated with mysqldump 8.0.25-15
=> schema: update initial.sql to mysql 8.0 format

doc/UPGRADE-3.0.md
=> Documentation for upgrading standalone installations

doc/sphinx/administration_portal/brand/invoicing/invoice_schedulers.rst, library/Ivoz/Provider/Domain/Model/Ddi/DdiRepository.php, library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoice/FixedCostsRelInvoice.php, library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoice/FixedCostsRelInvoiceInterface.php, library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceScheduler.php, library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerAbstract.php, library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerDto.php, library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerDtoAbstract.php, library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerInterface.php, library/Ivoz/Provider/Domain/Service/FixedCostsRelInvoice/CreateByScheduler.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/DdiDoctrineRepository.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/FixedCostsRelInvoiceScheduler.FixedCostsRelInvoiceSchedulerAbstract.orm.yml, schema/DoctrineMigrations/Version20220707084112.php, schema/tests/Provider/Ddi/DdiRepositoryTest.php, web/admin/application/configs/klear/FixedCostsRelInvoiceSchedulersList.yaml, web/admin/application/configs/klear/conf.d/ddisMatchHelp.yaml, web/admin/application/configs/klear/model/FixedCostsRelInvoiceSchedulers.yaml, web/admin/application/languages/ca_ES/ca_ES.po, web/admin/application/languages/en_US/en_US.po, web/admin/application/languages/es_ES/es_ES.po, web/admin/application/languages/it_IT/it_IT.po, web/admin/application/library/IvozProvider/Klear/Ghost/FixedCostsRelInvoiceSchedulers.php, web/rest/brand/features/provider/fixedCostsRelInvoiceScheduler/getFixedCostsRelInvoiceScheduler.feature, web/rest/brand/features/provider/fixedCostsRelInvoiceScheduler/postFixedCostsRelInvoiceScheduler.feature
Add DDI criteria in dynamic fixed costs added in https://github.com/irontec/ivozprovider/pull/1847
You may choose the country you want and only DDIs of that country will be taken into account.
=> Dynamic fixed costs by client DDI in scheduled invoices

ChangeLog, web/rest/brand/CHANGELOG.md
=> doc: update ChangeLog for 2.21.0

library/composer.lock, microservices/realtime/composer.lock, web/client/package.json, web/client/src/entities/FaxesIn/FaxesIn.tsx, web/client/src/entities/FaxesInOut/FaxesInOut.tsx, web/client/src/entities/FaxesInOut/FaxesInOutProperties.tsx, web/client/src/entities/FaxesOut/FaxesOut.tsx, web/client/src/entities/FaxesOut/Form.tsx, web/client/src/entities/FaxesOut/foreignKeyGetter.tsx, web/client/yarn.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/client/config/api/raw/provider.yml, web/rest/client/features/provider/faxesInOut/postFaxesInOut.feature, web/rest/client/tests/DataAccessControl/Provider/FaxesInOutTest.php, web/rest/platform/composer.lock, web/rest/user/composer.lock
Allow to send faxes from new client portal
=> Send fax from new client portal

ChangeLog, README.md, web/rest/brand/CHANGELOG.md, web/rest/client/CHANGELOG.md, web/rest/platform/CHANGELOG.md
=> doc: update ChangeLog for 3.0.0 release

web/portal/user/.eslintrc.json, web/portal/user/package.json, web/portal/user/src/entities/Account/Account.tsx, web/portal/user/src/entities/Account/Form.tsx, web/portal/user/src/entities/User/User.tsx, web/portal/user/yarn.lock
=> Provider 414 add password validation in user portal

library/composer.lock, microservices/realtime/composer.lock, web/rest/brand/composer.lock, web/rest/client/composer.lock, web/rest/platform/composer.lock, web/rest/user/composer.lock
Updated ivoz-api dependencies to add multi delete support
=> API multidelete support

web/portal/user/.eslintrc.json, web/portal/user/.prettierrc.json, web/portal/user/package.json, web/portal/user/src/components/header/avatar/Avatar.tsx, web/portal/user/src/components/header/avatar/StyledBadge.tsx, web/portal/user/src/components/header/menuItems/MenuItems.styles.tsx, web/portal/user/src/components/header/menuItems/MenuItems.tsx, web/portal/user/src/components/header/useTerminalStatus.ts, web/portal/user/src/components/header/useWebTheme.ts, web/portal/user/src/router/AppRouteContentWrapper/AppRouteContentWrapper.tsx, web/portal/user/src/router/AppRoutes.tsx, web/portal/user/yarn.lock
=> web/user: Added Status section and custom Avatar

library/Ivoz/Provider/Application/Service/User/UserDtoAssembler.php, library/Ivoz/Provider/Domain/Model/User/UserDto.php, web/portal/client/src/entities/User/User.tsx, web/portal/client/src/entities/User/UserProperties.tsx, web/rest/brand/features/provider/user/getUser.feature, web/rest/client/features/provider/huntGroup/getHuntGroupUsersAvailable.feature, web/rest/client/features/provider/user/getUser.feature
Show terminal status into users list
=> Users terminal status

web/rest/brand/config/api/raw/provider.yml, web/rest/client/config/api/raw/provider.yml, web/rest/platform/config/api/raw/provider.yml, web/rest/user/config/api/raw/provider.yml
=> web/rest: Replaced plain text contexts by its Entity's constants.

asterisk/agi/config/packages/prod/monolog.yaml, microservices/balances/config/packages/framework.yaml, microservices/balances/config/packages/prod/monolog.yaml, microservices/balances/src/Kernel.php, microservices/realtime/config/packages/framework.yaml, microservices/realtime/config/packages/security.yaml, microservices/realtime/src/Kernel.php, schema/config/packages/framework.yaml, web/rest/brand/config/packages/framework.yaml, web/rest/client/config/packages/framework.yaml, web/rest/client/config/packages/test/framework.yaml, web/rest/platform/config/packages/framework.yaml, web/rest/user/config/packages/framework.yaml
=> Provider 416 revisar deprecation warning

debian/Dockerfile, debian/control, debian/rules, tests/docker/Dockerfile, tests/packaging/Dockerfile, web/portal/client/bin/build, web/portal/user/bin/build
Required to work with nodejs 18.x introduced in #1881
=> ci: upgrade yarn package to 1.22.19

web/portal/client/bin/build, web/portal/client/bin/start, web/portal/client/index.html, web/portal/client/package.json, web/portal/client/src/App.tsx, web/portal/client/src/config.js, web/portal/client/src/entities/index.ts, web/portal/client/src/router/AppRoutes.tsx, web/portal/client/src/router/useEntityMap.ts, web/portal/client/src/store/index.ts, web/portal/client/tsconfig.json, web/portal/client/tsconfig.node.json, web/portal/client/vite.config.ts, web/portal/client/yarn.lock
=> Client portal: Vite as webpack replacement

debian/ivozprovider-web-client.install, debian/ivozprovider-web-user.install, debian/rules, profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf, web/portal/client/.gitignore, web/portal/client/bin/build, web/portal/user/.gitignore, web/portal/user/bin/build
=> update web portals build path

web/portal/client/src/entities/HuntGroupMember/Form.tsx
Linear and round robin hunt group memebers must set their prioriry
=> Show HuntGroupMember.priority field

kamailio/trunks/config/kamailio.cfg, kamailio/trunks/config/siptrace.cfg.in, kamailio/users/config/kamailio.cfg, kamailio/users/config/siptrace.cfg.in
Add _siptrace_ module pointing to Homer SIP Capture renaming _siptrace.cfg.in_ to _siptrace.cfg_ after setting variables of the specific environment.
=> kam: add HEP forwarding support

web/portal/client/.gitignore, web/portal/user/.gitignore, web/portal/user/src/entities/UsersCdr/Field/Duration.tsx, web/portal/user/src/entities/UsersCdr/UsersCdr.tsx
=> web/user: Added ceil method to duration property

web/portal/user/src/router/EntityMap.tsx
=> web/user: Modified position CallForwardSetting entity

library/Ivoz/Provider/Application/Service/Company/CompanyDtoAssembler.php, library/Ivoz/Provider/Domain/Model/Company/CompanyDto.php, web/rest/brand/features/provider/company/getCompanies.feature, web/rest/client/features/provider/company/getCompany.feature
=> Show domain in API client responses

web/portal/user/src/router/EntityMap.tsx
This feature hide the View button in UsersCdr List.
=> web/user: Hidden view button in Call List.

web/portal/user/src/entities/CallForwardSetting/CallForwardSetting.tsx
=> web/user: Renamed Call forward setting -> Call Forward Settings

ChangeLog, debian/changelog, web/rest/client/CHANGELOG.md
Update Changelog and package version for 2.21.1
=> Update ChangeLog for 2.21.1

web/portal/client/package.json, web/portal/client/yarn.lock
Updated ivoz-ui with expanded menu
=> Updated ivoz-ui

web/portal/client/package.json, web/portal/client/src/entities/Invoice/Invoice.tsx, web/portal/client/yarn.lock
Changed format date-time to date in inDate & outDate
=> Provider 511 date fields are shown as date time in lists

doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po, doc/sphinx/locale/es/LC_MESSAGES/api_rest.po, doc/sphinx/locale/es/LC_MESSAGES/basic_concepts.po, doc/sphinx/locale/es/LC_MESSAGES/security_and_maintenance.po, doc/sphinx/security_and_maintenance/security/firewall.rst
Update firewall ports for web services with http 80 port (generic terminal provision) and 3443 (Snom specific terminal provision) 
This PR also updates translations although it does not effort in translating any existing text.
=> doc: Update firewall ports for web services

library/DataFixtures/ORM/ProviderDdi.php, library/Ivoz/Provider/Domain/Model/Ddi/DdiAbstract.php, library/Ivoz/Provider/Domain/Model/Ddi/DdiDto.php, library/Ivoz/Provider/Domain/Model/Ddi/DdiDtoAbstract.php, library/Ivoz/Provider/Domain/Model/Ddi/DdiInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Ddi.DdiAbstract.orm.yml, schema/DoctrineMigrations/Version20221103163102.php, web/admin/application/configs/klear/BrandDDIsList.yaml, web/admin/application/configs/klear/DdisList.yaml, web/admin/application/configs/klear/RetailDdisList.yaml, web/admin/application/configs/klear/model/Ddis.yaml, web/rest/brand/features/provider/ddi/getDdi.feature, web/rest/brand/features/provider/ddi/postDdi.feature, web/rest/brand/features/provider/ddi/putDdi.feature, web/rest/client/features/provider/ddi/getDdi.feature, web/rest/client/features/provider/ddi/postDdi.feature, web/rest/client/features/provider/ddi/putDdi.feature
Add new field description to Ddi entity. This field will appear in all lists and can be edited by brand and client admins.
=> Add Desciption field to DDIs

library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php, library/Ivoz/Provider/Application/Service/CarrierServer/CarrierServerDtoAssembler.php, library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerDto.php, library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerRegistrationStatus.php, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/features/provider/carrierServer/getCarrierServerStatus.feature
Created custom endpoint for carrier_server, for status retrieval.
=> Provider 503 expose carrier server status in brand api

Jenkinsfile
=> ci: remove artemis branch specific conditions from Pipeline

asterisk/agi/src/Agi/Action/QueueAction.php, library/DataFixtures/ORM/ProviderQueue.php, library/Ivoz/Provider/Domain/Model/Queue/QueueAbstract.php, library/Ivoz/Provider/Domain/Model/Queue/QueueDtoAbstract.php, library/Ivoz/Provider/Domain/Model/Queue/QueueInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Queue.QueueAbstract.orm.yml, schema/DoctrineMigrations/Version20221108082529.php, web/admin/application/configs/klear/QueuesList.yaml, web/admin/application/configs/klear/model/Queues.yaml, web/rest/client/features/provider/queue/getQueue.feature, web/rest/client/features/provider/queue/postQueue.feature, web/rest/client/features/provider/queue/putQueue.feature, web/rest/client/features/provider/queueMember/getQueueMember.feature, web/rest/client/features/provider/queueMember/postQueueMember.feature
Add a new field displayName to override CallerIDName in calls from this queue.
=> Add Queue display name to update agents CallerIDName

asterisk/agi/src/Agi/Action/QueueAction.php, library/DataFixtures/ORM/ProviderQueue.php, library/Ivoz/Provider/Domain/Model/Queue/QueueAbstract.php, library/Ivoz/Provider/Domain/Model/Queue/QueueDtoAbstract.php, library/Ivoz/Provider/Domain/Model/Queue/QueueInterface.php, library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Queue.QueueAbstract.orm.xml, schema/DoctrineMigrations/Version20221108082529.php, web/admin/application/configs/klear/QueuesList.yaml, web/admin/application/configs/klear/model/Queues.yaml, web/portal/client/src/entities/Queue/Form.tsx, web/portal/client/src/entities/Queue/Queue.tsx, web/portal/client/src/entities/Queue/QueueProperties.tsx, web/rest/client/features/provider/queue/getQueue.feature, web/rest/client/features/provider/queue/postQueue.feature, web/rest/client/features/provider/queue/putQueue.feature, web/rest/client/features/provider/queueMember/getQueueMember.feature, web/rest/client/features/provider/queueMember/postQueueMember.feature
=> Add Queue display name to update agents CallerIDName #1929

library/Ivoz/Provider/Application/Service/CarrierServer/CarrierServerDtoAssembler.php, library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerDto.php, library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerStatus.php
=> Renamed CarrierServerRegistrationStatus -> CarrierServerStatus

web/portal/brand/package.json, web/portal/brand/src/router/AppRoutes.tsx, web/portal/brand/yarn.lock
Updated ivoz-ui and react router
=> Updated dependencies

library/Ivoz/Provider/Application/Service/OutgoingRouting/OutgoingRoutingDtoAssembler.php, library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingDto.php, web/portal/brand/src/entities/Country/SelectOptions.ts, web/portal/brand/src/entities/OutgoingRouting/Field/Operator.tsx, web/portal/brand/src/entities/OutgoingRouting/Form.tsx, web/portal/brand/src/entities/OutgoingRouting/OutgoingRouting.tsx, web/portal/brand/src/entities/OutgoingRouting/SelectOptions.ts, web/portal/brand/src/entities/RoutingPattern/Form.tsx, web/portal/brand/src/entities/RoutingPattern/SelectOptions.ts, web/portal/brand/src/entities/RoutingPatternGroup/Form.tsx, web/portal/brand/src/entities/RoutingPatternGroup/SelectOptions.ts, web/portal/brand/src/entities/RoutingTag/Form.tsx, web/portal/brand/src/entities/RoutingTag/SelectOptions.ts, web/rest/brand/config/api/raw/provider.yml, web/rest/brand/features/provider/outgoingRouting/getOutgoingRouting.feature, web/rest/brand/features/provider/outgoingRouting/postOutgoingRouting.feature
=> portal/brand: Added brand portal routing forms

web/portal/brand/src/entities/BalanceNotification/BalanceNotification.tsx, web/portal/brand/src/entities/BalanceNotification/ForeignKeyGetter.tsx, web/portal/brand/src/entities/NotificationTemplate/NotificationTemplate.tsx, web/portal/brand/src/entities/NotificationTemplate/SelectOptions/LowBalanceSelectOptions.ts, web/portal/brand/src/entities/NotificationTemplate/SelectOptions/index.ts
=> Provider 600 filter templates by types in prepaid balances

library/DataFixtures/ORM/ProviderTerminalModel.php, microservices/provision/behat.yml.dist, microservices/provision/bin/prepare-test-db, microservices/provision/bin/test-provision, microservices/provision/composer.json, microservices/provision/composer.lock, microservices/provision/config/bundles.php, microservices/provision/config/packages/test/behat.yaml, microservices/provision/config/packages/test/doctrine.yaml, microservices/provision/config/services.yaml, microservices/provision/features/bootstrap/bootstrap.php, microservices/provision/features/test.feature, microservices/provision/psalm.xml, microservices/provision/src/Behat/Context/FeatureContext.php, microservices/provision/symfony.lock, microservices/provision/your-baseline.xml
Added base code and dependencies for future provision tests
=> Add behat to provision microservice
