irontec/ivozprovider

library/IvozProvider/Mapper/Sql/Companies.php
library/IvozProvider/Model/Companies.php
portals/application/configs/klear/errors.yaml

Added sip domain value verification in the model.
Removed empty sip domain value checker in the mapper because It's not necessary any more.

mappers: Ensure valid domain value and remove unnecessary mapper logic

---

asterisk/agi/library/Agi/Action/ExternalFriendCallAction.php
asterisk/agi/library/Agi/Action/ExternalUserCallAction.php
library/IvozProvider/Model/Features.php
scheme/deltas/038-voice-error-notifications.sql

This introduces a new Brand and Company feature 'Voice Notifications'. When
enabled, some errors will play a locution to the caller over progress (not
answering the call).
This provides extra information to the administrators in order to detect why
a call is not being processed.
It may also introduce some other weird scenarios where a user fordwards its
call to a destination that can not actually call and the locution is played to
the caller rather than the user who configured the call fordward (at least
provides extra information of why the fordward is not being done).

agi: error notifications over progress feature

---

library/IvozProvider/Klear/Filter/RouteTypes.php

Filter/RouteTypes.php: Call to a member function on null 
when there was no company being emulated

portals: Fixed php execution error

---

asterisk/agi/application/configs/application.ini
asterisk/agi/library/Agi/Action/FaxCallAction.php
asterisk/agi/templates/faxmail/default/en/body
asterisk/agi/templates/faxmail/default/en/subject
asterisk/agi/templates/faxmail/default/es/body
asterisk/agi/templates/faxmail/default/es/subject

When a Fax is received and the send email option is enabled, the PBX will send
a notification with the fax converted to PDF attached.
The goal of this change is to use the email notification name and address
configurable at brand screen to customize email From header. We have also used
the template logics like we already do for voicemail notifications.
This also removes the extra mail notification that was being sent when an
outgoing fax failed to be sent as it's already displayed in the screen that is
used to send the fax. If this is not clear enough we can change the description
of the send email Fax field to 'send received fax to email'.
This PR aims to fix issue #55

as: use brand notification address for received faxes

---

portals/application/bin/template.php
portals/application/configs/klear/TerminalModelsList.yaml
portals/application/configs/klear/model/InvoiceTemplates.yaml
portals/application/configs/klear/model/TerminalModels.yaml
portals/application/controllers/KlearCustomRunCodeController.php

Fixed multiple break lines issue in provisioning template editor
Scaped xml alike templates in provisioning tester
Disabled warnings in provisioning tester
Requires klear to be updated

portals: provisioning editor and tester enhandments

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
scheme/deltas/040-kamailio-version.sql

All the tables that proxies use start with kam_ followed by the proxy name (users or trunks)
There are also some views and tables shared by both proxies but they still have kam_ prefix.
One exception to this is the table version who belongs to the proxies but doesn't have prefix.

scheme: replace kamailio version table with kam_version

---

library/IvozProvider/Mapper/Sql/DbTable/Companies.php
library/IvozProvider/Mapper/Sql/DbTable/DDIs.php
library/IvozProvider/Mapper/Sql/DbTable/Terminals.php
library/IvozProvider/Mapper/Sql/DbTable/Users.php
library/IvozProvider/Model/Raw/Companies.php
library/IvozProvider/Model/Raw/DDIs.php
library/IvozProvider/Model/Raw/Terminals.php
library/IvozProvider/Model/Raw/Users.php

Alphabetically ordered foreign keys in models and mappers so that they don't change randomly on every regeneration.
Depends on sorted-foreign-keys branch on https://github.com/irontec/klear-generator.git

mappers: fixed foreign key order

---

asterisk/agi/application/controllers/CallsController.php

That header only makes sense for proxyuser channels that are the only one
than can request on-demand recording.

as: avoid sending X-Info-RecordCode to KamTrunks

---

library/IvozProvider/Klear/Filter/OutgoingDDI.php
library/IvozProvider/Mapper/Sql/DbTable/Companies.php
library/IvozProvider/Mapper/Sql/DbTable/DDIs.php
library/IvozProvider/Mapper/Sql/Raw/Companies.php
library/IvozProvider/Mapper/Sql/Raw/DDIs.php
library/IvozProvider/Model/Faxes.php
library/IvozProvider/Model/Friends.php
library/IvozProvider/Model/Raw/Companies.php
library/IvozProvider/Model/Raw/DDIs.php
library/IvozProvider/Model/Users.php
portals/application/configs/klear/CompaniesList.yaml
portals/application/configs/klear/model/Companies.yaml
portals/application/configs/klear/model/Faxes.yaml
portals/application/configs/klear/model/Friends.yaml
portals/application/configs/klear/model/Users.yaml
portals/application/configs/klearRaw/DDIsList.yaml
portals/application/configs/klearRaw/model/Companies.yaml
portals/application/languages/en_US/en_US.po
portals/application/languages/es_ES/es_ES.po
portals/application/modules/rest/controllers/CompaniesController.php
portals/application/modules/rest/controllersRaw/CompaniesController.php
scheme/deltas/043-company-outgoing-ddi.sql

When Company has only one DDI for all their Users/Faxes, it can be handy to
have it defined in the Company configuration rather than per caller.
This commit adds a new a DDI field at company level that will be used if the
caller (User/Friend/Fax/...) has no outgoing DDI defined.
This PR aims to fix #6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/irontec/ivozprovider/93)

portals: add support for default company DDI #6

---

library/IvozProvider/Mapper/Sql/PricingPlansRelCompanies.php

This PR aims to fix #87
Removed save hook logic in the mapper in order to fix pricing plan metric issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/irontec/ivozprovider/97)

mappers: fixed new pricingPlan-company metric issues

---

library/IvozProvider/Klear/Options/OptionsCustomizerFilterForFax.php
library/IvozProvider/Mapper/Sql/FaxesInOut.php
portals/application/configs/klear/FaxesInOutList.yaml
portals/application/configs/klear/FaxesList.yaml
portals/application/configs/klear/InvoicesList.yaml
portals/application/configs/klear/model/Invoices.yaml
portals/application/languages/en_US/en_US.po
portals/application/languages/es_ES/es_ES.po

This PR aims to fix #81
**Requires klear to be updated.**
Faxes with no error are not editable anymore, read only screen is shown instead.
The pdf in faxes is not editable anymore
Fixed: set fax status to error when an exception is thrown
Removed invoice thumbnails from lists
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/irontec/ivozprovider/96)

portals: cache file thumbnails

---

asterisk/config/dialplan/bouncer.conf
asterisk/config/pjsip.conf
kamailio/trunks/config/kamailio.cfg

Proxytrunks implements a logic that avoids forwarding medialiberation re-invites
in bounced calls. The reason behind this logic was that forwarding this re-invites
lead to a loop (as they were forwarded to AS, that was the source of this requests).
This commits deletes this logic and avoids this loop with a different approach:
- 'proxybouncer' pjsip endpoint is used to bounce calls.
- This new endpoint has direct_media to 'no', stopping the loop.
Deleted logic prevented T.38 reinvites too, so this change fixes #99 too.

trunks+as: bounced faxes are not negociating T.38.

---

library/IvozProvider/Klear/Dynamic/Builder.php

This changes completes #104 PR that was only considering reaching Main administration portal using the fallback matching (that only redirects to that portal if URL doesn't match any BrandURL at all)

portals: Avoid brand/company emulation when god portal url is used

---

portals/application/configs/klear/BrandsList.yaml

It is not needed and it will be used in next release for another purpose.
Related to #42 and #85.

portals: Hide Brands' SIP domain

---

asterisk/agi/library/Agi/Action/IVRCustomAction.php
asterisk/agi/library/Agi/Wrapper.php

This locutions where implmented in the portal interface but was not being
actually used. This changes also includes an improvement in playback wrapper
function to ignore playback requests on not configured locutions.
IVRCustom Success locution can be used to indicate a generic message to confirm
the entered input has been accepted. IVRCustom Entry Welcome locution can be
used to provide specific information what destination is being contacted.
Take into account that if both locutions are specified, both will be played.
This can be safely cherry-picked into _oasis_ branch.

agi: implemented IVRCustom success locution and entry welcome

---

asterisk/agi/application/controllers/VoicemailController.php
asterisk/config/voicemail.conf

Voicemal handler for sending notifications was only checking the voicemail
number but not the context, sending the nofications to first user found with
same voicemail number that the expected destination.
This changes includes the context in voicemail notification so we can get the
destination user properly.
There's also included a couple of minor fixes, formatting cleanup and extra
checks.

voicemail: use voicemail context when checking destination email

---

asterisk/agi/library/Agi/Action/ServiceAction.php
asterisk/agi/library/Agi/Wrapper.php

Prior to this change the Voicemail check service only allowed checking the caller voicemail.
This changes allows to provide an extra extension after the service code, to check other user's.
voicemail (p.e. *981001 to check user 1001 voicemail).
Users can still secure their voicemails using the voicemail settings menu and configure a password.
Password won't be requested when the caller checks its own voicemail.
This PR is related with #15 and fixes #136

agi: support extension in voicemail check services

---

asterisk/agi/application/configs/application.ini
asterisk/agi/library/Agi/Action/ServiceAction.php
asterisk/agi/library/Agi/Wrapper.php
asterisk/config/modules.conf
doc/sphinx/locale/es/LC_MESSAGES/pbx_features.po
doc/sphinx/pbx_features/sounds.rst
library/IvozProvider/Klear/Ghost/RecordLocution.php
portals/application/configs/klear/LocutionsList.yaml
portals/application/configs/klear/model/Locutions.yaml
scheme/deltas/055-record-locution-service.sql

Introduced a new service to record existing locutions by dialing an specific extension.
This change includes a new service with iden RecordLocution configurable at Brand and Company
levels. By default, the Service is enabled in all existing companies with code *00
This allows dialing a specific code followed by the locution id to record the locution sound.
Converting from the original recorded format into asterisk specific format is done by the
existing gearmand multimedia worker.
This change requires record-*.wav files in ivozprovider-asterisk-sounds package in order to
reproduce recording instructions.
This PR fixes #52 
This PR must be merged **AFTER** #133 (due to scheme changes)

Locution record service

---

library/IvozProvider/Mapper/Sql/DbTable/KamAccCdrs.php
library/IvozProvider/Model/Raw/Brands.php
library/IvozProvider/Model/Raw/Companies.php
library/IvozProvider/Model/Raw/KamAccCdrs.php
library/IvozProvider/Model/Raw/ParsedCDRs.php
scheme/deltas/056-delete-stats-on-delete.sql

This PR aims to fix the problem of the tarificator process when parsing calls of deleted brands/companies.
The goal of this delta file is to remove all the stats related to deleted companies/brands, as saving them is not really useful.

Remove stats on delete

---

tests/bbs/0500-test-extension.yaml
tests/bbs/1000-test-ddi.yaml
tests/bbs/2000-test-ivr-common.yaml
tests/bbs/2010-test-ivr-custom.yaml
tests/bbs/2100-test-voicemail.yaml
tests/bbs/2200-test-pickup-group.yaml
tests/bbs/2210-test-pickup-direct.yaml
tests/bbs/2300-test-conference.yaml
tests/bbs/3000-test-cfw-busy.yaml
tests/bbs/3100-test-cfw-noanswer.yaml
tests/bbs/3200-test-cfw-unregistered.yaml
tests/bbs/4000-test-attxfer.yaml
tests/bbs/4100-test-blindxfer.yaml
tests/bbs/4200-test-blondexfer.yaml
tests/bbs/README.md
tests/bbs/environment.yaml

Files for simple SIP tests using BBS tool.
This tests are extremely superficial and they should be couple with
traditional [SIPP](https://github.com/SIPp/sipp) tests.

tests: add initial bbs SIP tests

---

kamailio/users/config/kamailio.cfg
scheme/deltas/059-simplify-kam_users-view.sql

$terminalName -> $extension conversion is now made in GENERATE_PUBLISH route, so both main query and kam_users view can be simplified.

Simplify kam users view

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Skip discarding last AS was a mistake, even in standalone installations. This
decision masks a problem and prevents potential self-healing logics
(e.g. trigger some event when a AS is discarded so that it gets back asap).
With current configuration, when dispatcher module marks a GW as inactive,
it starts sending OPTIONS every 5 seconds. Retransmissions of those OPTIONS
mean that inactive GWs are monitored at least once every 1,5 seconds.
This commit reverts this decision made in #64.

users+trunks: Inactivate even last AS

---

asterisk/config/features.conf

Default Asterisk builtin feature code for pickup is *8
This can clash with configured Service feature codes, and not knowing how to disable this feature,
we'll change it to something that won't be dialed (easily).
This allow dialplan execution for *8 services codes.
This PR fixes #163

as: replace default pickup builtin feature code

---

library/IvozProvider/Gearmand/Invoices/Generator.php
portals/application/controllers/KlearCustomInvoiceTemplateTesterController.php
portals/templates/basic.txt
portals/templates/detailed.txt

Zend_Locale wasn't providing us a proper date format for invoices: newither in spanish nor english. 
It has been replaced by dd-mm-yyyy so that it fits spanish, and [aparently](https://en.wikipedia.org/wiki/Date_format_by_country), UK format as well

Changed invoice date format to dd-mm-yyyy

---

library/IvozProvider/Gearmand/Invoices/Generator.php

It used to be 1 min. This value should be enough for everybody, tested rendering 2000 page invoice.

Changed invoice pdf generation timeout to 10min

---

asterisk/config/dialplan/default.conf

Current users/friends/retails pattern does not allow using + instead of
international prefix (e.g. +34944048182 instead of 0034944048182).
Underlying logic (see Countries.e164Pattern) is already adapted, changing
dialplan pattern should be enough.

as: Allow using + instead of international prefix

---

asterisk/agi/application/controllers/CallsController.php
library/IvozProvider/Model/Companies.php

This bug only affects companies with on demand recordings enabled by DTMFs.
The code being detected as start/stop recording was not considering the '*' prefix, so any captured DTMFs that matched the code was not being sent to the other end and ativated the recording process.

as: enable DTMF on-demand recording with * prefix

---

scripts/FSObase2index.sh

The original version of the script was not properly
handling files with id greater than 100.
Also, changed the file permissions for all dirs after
the fix has been applied.
If you want to reapply the fix in some dir, be sure
the files are in the base model storage path before
running this script.
```
cd storage/ivozprovider_model_xxxxx.xxxx
find -type f -exec mv {} . \;
```

scripts: fix fso base2index upgrade script

---

kamailio/recordings/application/bin/cli.php
kamailio/recordings/application/controllers/RecordingsController.php
library/composer.json
library/composer.lock

This commit changes the way recordings duration is
calculated. Insted of using the created and modified
dates of the file, we let zend-mp3[0] library to
do the task.
We have also changed the recording date to match
the call start-time instead of using the current
timestamp. Note that this will set all on-demand
recordings within the same call with the same
timestamp.
[0] https://github.com/debach/zend-mp3.git

recordings: fix duration and date for created recordings

---

doc/dev/en/storage.md
library/IvozProvider/Mapper/Sql/TerminalModels.php
portals/application/configs/klear/model/TerminalModels.yaml
portals/application/modules/provision/controllers/IndexController.php
scheme/deltas/063-Specific-provision-route-fix.sql

Make speficic provision file name editable as requested in https://github.com/irontec/ivozprovider/issues/200
This is the proposed flow:
1 - Extract any posible mac from the url
2 - Search thoose values into Terminals table
3 - Double check against specificUrlPattern in TerminalModels table
This PR aims to close https://github.com/irontec/ivozprovider/issues/200
Apart from custom file formats, the following mac formats should work from now on:
- https://test/provision/xxXXxxXXxxXX.cfg
- https://test/provision/xx:xx:xx:xx:xx:xx.cfg
- https://test/provision/xx-xx-xx-xx-xx-xx.cfg

provision: customizable specific provision routes

---

COPYING
LICENSE
README.md

EUPL v1.2 was released on May 2017. Our initial plan was to switch
as soon as it was published with the hope that some of the new license
compatibilities will be dropped to ensure the strong copyleft.
Sadly, this is not the case, and EUPL still has some compatible licenses
that can't ensure the forever freedom of the licensed software.
Most of the software used and installed with IvozProvider is under
General Public License version 2 or version 3, so the most coherent
free license to use for the whole software could be GPLv3.
This change can be attained directly if all project authors agree, or
via a two step licensing through CeCILL v2.
- **asterisk**: GNU General Public License v2.0
- **kamailio**: GNU General Public License v2.0
- **rtpproxy**: BSD 2-clause "Simplified" License
- …

license: switch from EUPLv1.1 to GPLv3 License

---

library/IvozProvider/Mapper/Sql/KamUsersAddress.php

Simply remove the /24 limitation for network mask in allowed company IPs
Mapper stills validate the netmask is between 0 and 32
This PR aims to fix #179

portals: allow IP networks with lower masks

---

portals/application/configs/klear/model/Locutions.yaml
portals/application/languages/en_US/en_US.po
portals/application/languages/es_ES/es_ES.po

Added a text next to the field to specify what the extension is for:
_You can call this extension from any company terminal to record this locution_
[Current documentation](https://god.oasis-kai.irontec.com/doc/en/pbx_features/sounds.html#locutions) for this section is:
_Locutions can be recorded from any terminal by dialing the Recording extension displayed in their edit screen._
This PR aims to fix #199

portals: added hint text for recording extension field

---

library/IvozProvider/Mapper/Sql/Companies.php
portals/application/configs/klear/CompaniesList.yaml
portals/application/configs/klear/RetailClientsList.yaml
portals/application/configs/klear/model/Companies.yaml
portals/application/configs/klear/model/RetailClients.yaml

Show both mechanisms on creation:
* Limit external calls (default value 2 in retail, 10 in vPBX)
* IP filter (disabled by default)
This way, on fast company creation, at least external calls will be limited.

portals: Enable company security by default

---

portals/application/assets/css/global.css

There is nothing that prevents the logo from being wider. There is a lot of white space to the right.
Wouldn't it be better to limit the logo size by height?
I decided to set it to 96px which is your actual logo height.

portals: logo size limited by height

---

ChangeLog

Blocked by all pending 1.5.0 task
https://github.com/irontec/ivozprovider/milestone/7

doc: Release 1.5.0 changelog

---

portals/e2e/features/brand_features/outgoingRouting.feature
portals/e2e/features/pages/edit.js
portals/e2e/features/step_definitions/edit.js
portals/e2e/nightwatch.conf.js

outgoing routing e2e tests were failing because of timeouts.

qa: Adjusted timeouts

---

kamailio/trunks/config/kamailio.cfg

Some time ago we disabled dialog track_cseq_updates modparam.
This setting aims to adapt cseq numbers one Kamailio's UAC uac_auth is done.
This mechanism had some errors with retransmissions and cancel events, so it was disabled as no carrier at the moment seems to be annoyed if two transactions use the same CSeq.
Even though any carrier at the moment seems to be annoyed if two transactions use the same CSeq for the unauth initial INVITE and the auth one, adapting these CSeqs is more RFC-compliant.
This PR enables it again.

trunks: Enable dialog cseq tracking mechanism

---

asterisk/agi/application/controllers/CallsController.php
asterisk/agi/library/Agi/Action/IVRAction.php
asterisk/agi/library/Agi/Action/IVRCommonAction.php
asterisk/agi/library/Agi/Action/IVRCustomAction.php

Fixed a bug where the IVRCustom handlers were not properly processed.
The logic stored the IVR id but not the IVR type. While processing the handlers
for a IVRCustom, if a IVRCommon with the same id was found they were processed
instead of the original IVRCustom handlers.
This commit includes an extra channel variable IVRTYPE to determine if the
IVR handlers being processed belong to a IVRCustom or a IVRCommon.

ivr: fix IVRCustom handlers for timeout and error

---

asterisk/agi/library/Agi/Action/IVRAction.php
asterisk/agi/library/Agi/Action/IVRCommonAction.php
asterisk/agi/library/Agi/Action/IVRCustomAction.php
asterisk/config/dialplan/default.conf
doc/sphinx/locale/es/LC_MESSAGES/pbx_features.po
doc/sphinx/pbx_features/ivrs.rst
portals/application/configs/klear/IVRCommonList.yaml
portals/application/configs/klear/IVRCustomList.yaml
portals/application/configs/klear/model/IVRCommon.yaml
portals/application/configs/klear/model/IVRCustom.yaml
portals/application/languages/en_US/en_US.po
portals/application/languages/es_ES/es_ES.po
tests/bbs/2002-test-ivr-common-noinput-extension.yaml
tests/bbs/2003-test-ivr-common-usercfw-noanswer.yaml
tests/bbs/2004-test-ivr-common-usercfw-busy.yaml
tests/bbs/2012-test-ivr-custom-noinput-extension.yaml
tests/bbs/2013-test-ivr-custom-usercfw-noanswer.yaml
tests/bbs/2014-test-ivr-custom-usercfw-busy.yaml
tests/bbs/dataset.json

This PR replaces existing noAnswer handler of IVRs with noInput
The noAnswer handler was triggering when IVRs dial an extension pointing to a user, by checking the dial result was NOANSWER. This was preventing the triggering of users call forwards setting as IVR handlers was being processed instead.
We should avoid having "mid logic" handlers: only the last element of the call should have handlers.
This implements #182 and clarifies #275

IVR: replace noAnswer with noInput handler

---

portals/application/configs/klear/model/OutgoingRouting.yaml

OutgoingRouting model has type field as its default field so on the popup confirmation when you try to delete one of those routes you have not much information about which one you are actually going to delete.
Changing the default field to companyId gives better information.

portals: change default field for OutgoingRouting

---

portals/application/configs/klear/model/RetailAccounts.yaml

Actual default field for Retails Accounts is companyId. Name is a better default field.

portals: change default field for Retail Accounts

---

library/IvozProvider/Mapper/Sql/Companies.php
portals/application/configs/klear/errors.yaml

This aims to solve https://github.com/irontec/ivozprovider/issues/292 changing the constraint to allow same name for vpbx companies and retail companies and catching the exception on saving companies.

portals: companies name constraint

---

portals/application/configs/klear/model/Friends.yaml

Current default fields for Friends is companyId so when you are going to delete a friend that is what is shown in the popup confirmation. The name is a better default field in my opinion.

portals: change default field for Friends

---

portals/application/configs/klear/model/Brands.yaml
portals/application/configs/klear/model/Terminals.yaml
scheme/deltas/072-domain-length-fix.sql

Domain length must be 190. This aims to fix some places where it is set to 255.

portals: fix domain length

---

library/IvozProvider/Klear/Filter/QueueStrategies.php
portals/application/configs/klear/model/Queues.yaml

Linear strategy can only be used if queue has been already created with
that strategy or after an asterisk restart. At least until [1] has been
implemented.
This changes the edit screen strategy select box to disable 'linear'
strategy if queue has been already created with other strategy.
[1] https://issues.asterisk.org/jira/browse/ASTERISK-17049

portals: avoid selecting linear strategy in already created queues

---

debian/control
extra/simple-cdd/package.list
kamailio/users/config/kamailio.cfg

Redis was included as an experimental approach to have some realtime
statistics (total calls, calls per company, etc.).
This approach has been discarded and this commits tries to erase all
references to it.

kamusers: Remove redis and redis modules

---

kamailio/trunks/config/kamailio.cfg

'422 Session Interval Too Small' is treated as a generic failure code, causing
GW failover and discarding that GW.
2 options here:
1) Make KamTrunks resend an INVITE request with the Session-Expires specified in
422 response (adapting CSeqs onwards).
2) Forward 422 to AS and make him resend the INVITE.
As session-timers are negotiated between endpoints and CSeq adaptation is not
wanted, option 2 is implemented.

trunks: Forward 422 to AS to adapt minSE value

---

kamailio/users/config/kamailio.cfg

DETECT_TRANSPORT route tries to detect if WS(S) is involved in current session and
rtpengine should be used instead of rtpproxy.
This decision was made using:
- $proto: Protocol of received message
- $rP: Assuming that UACs registered with WSS would use ;transport=wss R-URI param.
Improve this last escenario using xavp(ulattrs=>transport) saved on register for
R-URI without transport param that use WSS.

users: Improve websockets detection logic

---

library/Ivoz/Provider/Domain/Model/User/UserRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/UserDoctrineRepository.php
library/IvozProvider/Klear/Filter/Terminals.php
web/admin/application/configs/klear/model/Users.yaml

When creating a new user or editing an existing one
the listbox must only display available terminals and the
one already assigned to the user.
This commit removes the function from repository and
implements it in the filter as its code is not expected
to be reused in the near future.

webadmin: fix available terminals listbox

---

library/CoreBundle/Resources/config/lifecycle/ivoz/domain.yml
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByDomain.php
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByFriend.php
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByRetailAccount.php
library/Ivoz/Provider/Domain/Model/Domain/DomainDTO.php
library/Ivoz/Provider/Domain/Model/Domain/DomainInterface.php
library/Ivoz/Provider/Domain/Model/Domain/DomainTrait.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Domain.Domain.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Friend.FriendAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/RetailAccount.RetailAccountAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Terminal.TerminalAbstract.orm.yml

ast_ps_endpoints.from_domain determines the domain used by Asterisk in From header
for outgoing calls.
It has this value:
- For terminals: always company domain.
- For friends: company domain, unless "From domain" is set in Friends section.
- For retail accounts: brand domain, unless "From domain" is set in Retail accounts section.
This commit aims to keep this value updated accordingly.

core: Update from_domain accordingly

---

library/IvozProvider/Klear/Filter/Terminals.php

Company users without terminal were breaking the filter query

klear: skip null terminal ids

---

library/CoreBundle/Resources/config/lifecycle/ivoz/brand.yml
library/CoreBundle/Resources/config/lifecycle/ivoz/company.yml
library/Ivoz/Provider/Domain/Service/Domain/DeleteByBrand.php
library/Ivoz/Provider/Domain/Service/Domain/DeleteByCompany.php

Both Brands and Companies have a relation with Domains, but not the other way around, so this can not be done with database ON DELETE constraints.
Implemented two post_remove services to delete the related domain of Brands and Companies.
This fixes #362

core: remove Domains when their owners are removed

---

library/CoreBundle/Resources/config/lifecycle/ivoz/extension.yml
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByExtension.php
library/Ivoz/Ast/Domain/Service/Voicemail/UpdateByExtension.php

Ast/PsEndpoint and Ast/Voicemail were only being updated when
the User changed the extension. This two tables contain the extension
number, so must be updated if the Extension itself changes, not only
its relation with the user.
This change only applies to those extension that are used as screen
extension for the user, not all the extension that route to user.

core: update Endpoint/Voicemail when Extension number changes

---

asterisk/agi/library/Agi/Action/UserCallAction.php
library/IvozProvider/Mapper/Sql/CallForwardSettings.php
library/IvozProvider/Mapper/Sql/DbTable/CallForwardSettings.php
library/IvozProvider/Mapper/Sql/Raw/CallForwardSettings.php
library/IvozProvider/Model/CallForwardSettings.php
library/IvozProvider/Model/Raw/CallForwardSettings.php
library/IvozProvider/Model/Users.php
portals/application/configs/klear/CallForwardSettingsList.yaml
portals/application/configs/klear/UsersList.yaml
portals/application/configs/klear/model/CallForwardSettings.yaml
portals/application/languages/en_US/en_US.po
portals/application/languages/es_ES/es_ES.po
portals/application/modules/rest/controllers/CallForwardSettingsController.php
portals/application/modules/userweb/controllers/CallForwardSettingsController.php
scheme/deltas/079-disable-cfw.sql
userweb/app/languages/locale-es.json
userweb/app/modules/detours/detoursCtrl.js
userweb/app/modules/detours/detoursEditCtrl.js
userweb/app/views/detours/edit.html
userweb/app/views/detours/new.html
userweb/app/views/detours/table-detours.html

- User call forward can now be enabled/disabled from both admin portal and user portal.
- Disabled call forward settings are ignored.
- You can have multiple colliding call forwards but only one of them can be enabled at a time.
This PR fixes #378.

Add enable/disable toggle to user call forward settings

---

asterisk/agi/application/controllers/CallsController.php
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
portals/application/configs/klear/model/Brands.yaml
portals/application/configs/klear/model/Companies.yaml
portals/application/languages/en_US/en_US.po
portals/application/languages/es_ES/es_ES.po

This commit fixes the misleading implementation made in #398 for maxcalls.
Before this commit:
- KamUsers had an independent counter that counted dialogs in both directions:
- UAC -> KamUsers -> AS
- AS -> KamUsers -> UAC
- KamTrunks had an independent counter that counted dialogs in both directions:
- Carrier -> KamTrunks -> AS
- AS -> KamTrunks -> Carrier
This made difficult to answer the question "how many calls can I handle with this
setting set to 10":
- 10 external outgoing calls made by users.
or
- 10 external incoming calls received by users.
or
- 10 external incoming calls forwarded outside again + 10 internal calls.
After this commit:
- KamUsers has an independent counter but only counts (and limits) UAC->AS calls.
- KamTrunks has an independent counter but only counts (and …

kam+agis: Fix misleading maxcalls implementation

---

asterisk/agi/library/Agi/Action/HuntGroupAction.php
asterisk/agi/library/Agi/Action/UserCallAction.php
library/IvozProvider/Mapper/Sql/DbTable/HuntGroups.php
library/IvozProvider/Mapper/Sql/Raw/HuntGroups.php
library/IvozProvider/Model/Raw/HuntGroups.php
portals/application/configs/klear/HuntGroupsList.yaml
portals/application/configs/klear/model/HuntGroups.yaml
portals/application/languages/en_US/en_US.po
portals/application/languages/es_ES/es_ES.po
portals/application/modules/rest/controllers/HuntGroupsController.php
scheme/deltas/080-ringall-missed-calls.sql

**RingAll huntgroups:** Add a selector to avoid generating missed calls for ringall huntgroups (current behaviour) or to generate them only when no member answers (new behaviour).
**Remaining huntgroups:** Add selector to avoid generating missed calls (new behaviour).
This PR fixes #393

RingAll huntgroup: CANCEL with "Answered elsewhere" as an option

---

asterisk/agi/application/controllers/CallsController.php
asterisk/agi/library/Agi/Action/CallForwardRetailAction.php
asterisk/agi/library/Agi/Action/VoiceMailAction.php
library/IvozProvider/Mapper/Sql/Companies.php
library/IvozProvider/Mapper/Sql/DbTable/AstVoicemail.php
library/IvozProvider/Mapper/Sql/DbTable/RetailAccounts.php
library/IvozProvider/Mapper/Sql/Raw/AstVoicemail.php
library/IvozProvider/Mapper/Sql/Raw/RetailAccounts.php
library/IvozProvider/Mapper/Sql/RetailAccounts.php
library/IvozProvider/Model/Brands.php
library/IvozProvider/Model/Raw/AstVoicemail.php
library/IvozProvider/Model/Raw/RetailAccounts.php
library/IvozProvider/Model/RetailAccounts.php
portals/application/configs/klear/CallForwardSettingsList.yaml
portals/application/modules/rest/controllers/AstVoicemailController.php
scheme/deltas/082-retailaccount-voicemail.sql

Add support for Call Forward Settings route to Voicemail.
All retail accounts will have a voicemail by default that can checked using the Voicemail brand's service code.
This PR fixes #395

Retail account voicemail

---

asterisk/agi/library/Agi/Action/VoiceMailAction.php
debian/ivozprovider-profile-data.install
library/IvozProvider/Model/Users.php
scheme/deltas/083-fix-user-voicemail.sql
scripts/UpdateMailboxNames.pl

This PR changes userExtension<->mailbox relationship to user<->mailbox.
This way, extension changes do not lead to orphan mailboxes or users listening messages of the previous person who had his extension.
- Mailboxes linked to users have userX name now, being X userId (inmutable name).
- DB mailbox names are adapted via delta sql.
- FS mailbox names are adapted via helper script (it should be decided how this script will be distributed, if so).
As a side effect of this renaming, voicemail greeting does not say user extension anymore.
This PR fixes #161

Fix user voicemail names

---

asterisk/agi/src/Agi/Action/VoiceMailAction.php
library/Ivoz/Provider/Domain/Model/User/User.php

Voicemail are now related to users, not to user's extension.
This is equivalent to #407 done in Oasis.
It assumes that you come from 1.7 (where existing voicemails are already fixed) or you have no voicemail yet. Otherwise you must apply 50396bf2fffef30c0059398702895975633f8c71 and 9662c7deb4ba43a5abadc709e56dfaeebe0a9e4c manually (read [1.7 upgrade guide](https://github.com/irontec/ivozprovider/blob/oasis/doc/UPGRADE-1.7.md) for further information).

Fix voicemail-user-extension logic

---

asterisk/agi/src/Agi/Action/UserCallAction.php
library/Ivoz/Api/Core/Security/DataAccessControlParser.php
library/Ivoz/Core/Infrastructure/Persistence/Doctrine/Model/Helper/CriteriaHelper.php

The `g` flag of dials that enables the UserStatus checking is only required if there are Call Forward settings that apply after the call. 
This logic can still improve by checking If found call forwards are enabled (when #400 is moved to artemis). I have left the code to check enabled status commented.

agis: only check after call dial status when there are call forwards

---

asterisk/agi/application/controllers/VoicemailController.php
asterisk/agi/library/Agi/Action/FaxCallAction.php

No UI changes, but if directory 'brandX' exists, those templates will be used
instead of default ones.
Valid for faxes and voicemail mails.

agis: Make mail template configurable by brand

---

web/rest/src/Controller/My/StatusAction.php

The logic used to obtain the terminal registration information of the user must use company domain to avoid mixing things up.

web/user: Fix terminal registration info

---

library/Ivoz/Cgr/Domain/Model/TpRatingPlan/TpRatingPlanAbstract.php
library/Ivoz/Cgr/Domain/Model/TpRatingPlan/TpRatingPlanDtoAbstract.php
library/Ivoz/Cgr/Domain/Model/TpRatingPlan/TpRatingPlanInterface.php
library/Ivoz/Cgr/Domain/Service/TpRatingPlan/InheritRatingPlanTag.php
library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpRatingPlan.TpRatingPlanAbstract.orm.yml
scheme/app/DoctrineMigrations/Version20180405103050.php
web/admin/application/configs/klear/TpRatingPlansList.yaml

Timings selector is currently useless as it is not possible to add new timings.
This PR just hides it and makes '*any' default timing_tag for all rating plans (*any keyword behaves equal to 'ALWAYS' timing we used prior to this PR).

Hide Timings selector in RatingPlans list

---

library/Ivoz/Kam/Domain/Model/Trusted/Trusted.php
library/Ivoz/Provider/Domain/Model/Company/Company.php
library/Ivoz/Provider/Domain/Model/Company/CompanyAbstract.php
library/Ivoz/Provider/Domain/Model/Feature/Feature.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml
scheme/app/DoctrineMigrations/Version20180418161848.php
web/admin/application/assets/js/customMenu.js
web/admin/application/configs/klear/CompaniesList.yaml
web/admin/application/configs/klear/KamTrunksCdrsWholesaleList.yaml
web/admin/application/configs/klear/KamTrustedList.yaml
web/admin/application/configs/klear/KamUsersCdrsRetailList.yaml
web/admin/application/configs/klear/RetailDDIsList.yaml
web/admin/application/configs/klear/WholesaleClientsList.yaml
web/admin/application/configs/klear/conf.d/mapperList.yaml
web/admin/application/configs/klear/klear.yaml
web/admin/application/configs/klear/model/WholesaleClients.yaml
web/admin/application/controllers/KlearCustomExtraAuthController.php
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/library/IvozProvider/Klear/Auth/User.php
web/admin/application/library/IvozProvider/Klear/Filter/Features.php
web/admin/application/library/IvozProvider/Klear/Filter/RetailFeatures.php
web/admin/application/library/IvozProvider/Klear/Ghost/Companies.php

This PR adds a new Brand feature to enable Wholesale clients creation on brands, allowing access to its configuration sections in the portal.
This does not include any logic related to those screens, so the entered data won't be used until proxies logics are updated.

Implement basic wholesale client interfaces

---

debian/ivozprovider.postinst
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

This PR contains needed changes in both kamailio configuration files to add support for basic wholesale clients:
- Wholesale clients just make outgoing calls.
- IP authentication only (no register, no SIP auth).
- Calls go directly from users to trunks, without any application server in the middle (unique SIP dialog).
- KamUsers calls to rtpproxy/rtpengine, trunks skips this logic.
**Known limitation**: bouncing calls (calls from wholesale clients to DDIs in IvozProvider) are not supported yet.

Kamailio wholesale basics

---

debian/ivozprovider-asterisk-agi.postinst
debian/ivozprovider-profile-common.dirs
debian/ivozprovider-recordings.postinst

The tmp dir was being used for uploading files from administration portal without using FSO.
Right now there is no upload without FSO, so this is no longer required
This is a dummy change, but I want to use this PR to test CI tests :-)

pkg: remove unnecessary tmp dir in storage

---

doc/sphinx/basics/installation/debian_install.rst

To install bleeding version we have to use debian stretch 9 as base system and bleeding as ivozprovider package and tayler as klear package.

doc: install from packages repositories

---

README.md

To partially fix #476 
There are no latex, pdf, epub for bleeding. The artemis version is used on those links and I didn't change them.

include branch name in doc links

---

scheme/initial.sql

Now the initial passwords for the demo terminals are hardcoded. This aims to randomize those initial passwords.

Fix initial terminal passwords

---

library/DataFixtures/ORM/ProviderRoutingPattern.php
library/Ivoz/Provider/Domain/Model/LcrRule/LcrRule.php
library/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleInterface.php
library/Ivoz/Provider/Domain/Model/RoutingPattern/RoutingPattern.php
library/Ivoz/Provider/Domain/Model/RoutingPattern/RoutingPatternAbstract.php
library/Ivoz/Provider/Domain/Model/RoutingPattern/RoutingPatternDto.php
library/Ivoz/Provider/Domain/Model/RoutingPattern/RoutingPatternDtoAbstract.php
library/Ivoz/Provider/Domain/Model/RoutingPattern/RoutingPatternInterface.php
library/Ivoz/Provider/Domain/Service/LcrRule/CreateByOutgoingRoutingAndRoutingPattern.php
library/Ivoz/Provider/Domain/Service/LcrRule/UpdateByRoutingPattern.php
library/Ivoz/Provider/Domain/Service/RoutingPattern/UpdateByBrand.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/RoutingPattern.RoutingPatternAbstract.orm.yml
library/spec/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleSpec.php
library/spec/Ivoz/Provider/Domain/Service/LcrRule/CreateByOutgoingRoutingAndRoutingPatternSpec.php
library/spec/Ivoz/Provider/Domain/Service/LcrRule/UpdateByRoutingPatternSpec.php
scheme/app/DoctrineMigrations/Version20180523162834.php
web/admin/application/configs/klear/model/OutgoingRouting.yaml
web/admin/application/configs/klear/model/RoutingPatterns.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/rest/features/provider/routingPattern/getRoutingPattern.feature
web/rest/features/provider/routingPattern/postRoutingPattern.feature
web/rest/features/provider/routingPattern/putRoutingPattern.feature
web/rest/features/provider/routingPatternGroupsRelPattern/getRoutingPatternGroupsRelPattern.feature
web/rest/features/provider/routingPatternGroupsRelPattern/postRoutingPatternGroupsRelPattern.feature
web/rest/features/provider/routingPatternGroupsRelPattern/putRoutingPatternGroupsRelPattern.feature

This PR introduces a breaking change:
- Routing patterns no longer admit a regexp, it can only be a prefix now.
- This prefix must start with '+' and may be followed with zero or more digits.
The reason behind this change is that Kamailio's LCR module orders selected gateways using prefix length as a main criteria and that's ok. But it does not compute matching length of regexp, producing unexpected results.
As regexps made possible to add a catch-all pattern (with ^[0-9]+$), this will be possible creating a pattern with just a '+' symbol.

Remove route by regexp

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
library/DataFixtures/ORM/ProviderLcrGateway.php
library/DataFixtures/ORM/ProviderLcrRule.php
library/Ivoz/Provider/Domain/Model/LcrGateway/LcrGatewayAbstract.php
library/Ivoz/Provider/Domain/Model/LcrGateway/LcrGatewayDtoAbstract.php
library/Ivoz/Provider/Domain/Model/LcrGateway/LcrGatewayInterface.php
library/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleAbstract.php
library/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleDto.php
library/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleDtoAbstract.php
library/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleInterface.php
library/Ivoz/Provider/Domain/Model/PeerServer/PeerServer.php
library/Ivoz/Provider/Domain/Model/PeerServer/PeerServerInterface.php
library/Ivoz/Provider/Domain/Service/LcrGateway/UpdateByPeerServer.php
library/Ivoz/Provider/Domain/Service/LcrRule/CreateByOutgoingRoutingAndRoutingPattern.php
library/Ivoz/Provider/Domain/Service/LcrRule/UpdateByRoutingPattern.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/LcrGateway.LcrGatewayAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/LcrRule.LcrRuleAbstract.orm.yml
library/spec/Ivoz/Provider/Domain/Model/LcrRule/LcrRuleSpec.php
library/spec/Ivoz/Provider/Domain/Service/LcrGateway/UpdateByPeerServerSpec.php
library/spec/Ivoz/Provider/Domain/Service/LcrRule/CreateByOutgoingRoutingAndRoutingPatternSpec.php
library/spec/Ivoz/Provider/Domain/Service/LcrRule/UpdateByRoutingPatternSpec.php
scheme/app/DoctrineMigrations/Version20180524170318.php

This PR:
- Drops LcrRules.tag and LcrRules.descriptions from database as they were not used anywhere.
- Drops LcrGateways.flags as LCR module loads peerServerId directly now.
- Removes awkward RPID/PAI logic from trunks kamailio.cfg
- Removes unnecessary logics that kept synced some database fields.
No functional changes.

trunks: LCR AVPs and database fields reordered

---

asterisk/agi/src/Agi/ChannelInfo.php
tests/bbs/1102-test-ddi-external-cfw.yaml
tests/bbs/dataset.json

Reported in #503 
We use the ORIGIN and CALLER channel variables to store entities ids in the form Entity#id
The ORIGIN variable is mainly used to apply OutgoingDDIRules on its presentation, but when the call is external, the ORIGIN is empty and no conversion or check is required. This PR updates the code to handle this case.
It also contains a test to validate this scenario with the dataset updated with latest tables changes.

Fix crash during external user call fordwards

---

portals/application/configs/klear/CallForwardSettingsList.yaml

Extension combobox is not displayed in edit screen in CallForwardSettings

portals: fix extension for CallForwardsettings edit screen

---

library/Ivoz/Provider/Domain/Model/Ivr/IvrRepository.php
library/Ivoz/Provider/Domain/Service/Ivr/UpdateByExtension.php
library/Ivoz/Provider/Domain/Service/Ivr/UpdateByUser.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/IvrDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/IvrEntry.IvrEntryAbstract.orm.yml
library/spec/Ivoz/Provider/Domain/Service/Ivr/UpdateByExtensionSpec.php
library/spec/Ivoz/Provider/Domain/Service/Ivr/UpdateByUserSpec.php
scheme/app/DoctrineMigrations/Version20180611142317.php

Set noInputRouteType and errorRouteType to null when target entities have been deleted.
Set on delete cascade constraints in IvrEntry
This PR aims to fix https://github.com/irontec/ivozprovider/issues/538 at artemis and #534

core: clean up ivr state on user/extension delete

---

library/IvozProvider/Mapper/Sql/Users.php

Set extension routeType to null when user has been deleted
This PR aims to fix #534 at oasis

core: clean up extensions properly on user delete

---

asterisk/agi/application/controllers/VoicemailController.php
asterisk/agi/library/Agi/Action/FaxCallAction.php
kamailio/recordings/application/controllers/RecordingsController.php
portals/application/workers/XmlrpcWorker.php
portals/application/workers/XmlrpcdelayedproxytrunksWorker.php

Fixed utf-8 charset typo
This PR aims to fix the issue reported at https://github.com/irontec/ivozprovider/issues/565

library: fixed email charset header

---

web/admin/application/library/IvozProvider/Klear/Dynamic/Builder.php

When current URL doesn't match one of the existing BrandURLs, the logic simply search the table for an entry of type `god`. If none is found, then the portal crashes.
This PR improves that logic to avoid searching for any god url, but instead create a dynamic BrandURL object with title _Global Administration Portal_ and Redmon as theme.
This fixes #581 for artemis release

Improve global administration portal fallback 

---

library/IvozProvider/Klear/Dynamic/Builder.php

When current URL doesn't match one of the existing BrandURLs, the logic simply search the table for an entry of type god. If none is found, then the portal crashes.
This PR improves that logic to avoid searching for any god url, but instead create a dynamic BrandURL object with title Global Administration Portal and Redmon as theme.
This fixes #581 for oasis release

Improve global administration portal fallback (oasis)

---

kamailio/trunks/config/kamailio.cfg
library/CoreBundle/Resources/config/lifecycle/core/xml_rpc.yml
library/CoreBundle/Resources/config/lifecycle/kam/trunks_address.yml
library/Ivoz/Kam/Domain/Model/TrunksAddress/TrunksAddressAbstract.php
library/Ivoz/Kam/Domain/Model/TrunksAddress/TrunksAddressDtoAbstract.php
library/Ivoz/Kam/Domain/Model/TrunksAddress/TrunksAddressInterface.php
library/Ivoz/Kam/Domain/Service/TrunksAddress/TrunksAddressLifecycleEventHandlerInterface.php
library/Ivoz/Kam/Domain/Service/TrunksAddress/TrunksAddressLifecycleServiceCollection.php
library/Ivoz/Kam/Domain/Service/TrunksAddress/UpdateByDdiProviderAddress.php
library/Ivoz/Kam/Infrastructure/Domain/Service/TrunksAddress/SendTrunksPermissionsReloadRequest.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksAddress.TrunksAddressAbstract.orm.yml
library/Ivoz/Provider/Domain/Model/DdiProviderAddress/DdiProviderAddressAbstract.php
library/Ivoz/Provider/Domain/Model/DdiProviderAddress/DdiProviderAddressDto.php
library/Ivoz/Provider/Domain/Model/DdiProviderAddress/DdiProviderAddressDtoAbstract.php
library/Ivoz/Provider/Domain/Model/DdiProviderAddress/DdiProviderAddressInterface.php
library/Ivoz/Provider/Domain/Service/DdiProviderAddress/DdiProviderAddressLifecycleEventHandlerInterface.php
library/Ivoz/Provider/Domain/Service/DdiProviderAddress/DdiProviderAddressLifecycleServiceCollection.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/DdiProviderAddress.DdiProviderAddressAbstract.orm.yml
scheme/app/DoctrineMigrations/Version20180717150551.php
web/rest/features/provider/ddiProviderAddress/getDdiProviderAddress.feature
web/rest/features/provider/ddiProviderAddress/postDdiProviderAddress.feature

This PR complements #527 and makes both incoming and outgoing calls work after changes in #578 and #585 .

kamtrunks: kamailio.cfg changes after carrier/ddiprovider split

---

library/Ivoz/Provider/Domain/Model/Feature/Feature.php
scheme/app/DoctrineMigrations/Version20180718132230.php
web/admin/application/configs/klear/klear.yaml
web/admin/application/library/IvozProvider/Klear/Filter/Features.php
web/admin/application/library/IvozProvider/Klear/Filter/ResidentialFeatures.php

Now that the other 3 client types have features to enable/disable its sections in portal, it makes sense to do the same with virtual pbx clients.
Disabling the feature at brand level will hide following sections in Brand configuration menu:
- Virtual PBX
- Generic Music on Hold
- Generic Match Lists
- Services
The migration also enables this feature for all existing brands (including the demo one for initial installations)

Virtual PBX as Brand feature

---

library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceScheduler.php
library/Ivoz/Provider/Domain/Service/InvoiceScheduler/NextExecutionResolver.php
web/admin/application/configs/klear/InvoiceSchedulersList.yaml
web/admin/application/configs/klear/model/InvoiceSchedulers.yaml
web/admin/application/library/IvozProvider/Klear/Filter/InvoiceSchedulerCompany.php

Small fixes related to invoice schedulers #579 
web/admin:
- Reorder columns in Invoice Scheduler list
- Set default frequency to months
- Allow empty email
- Remove optional unassigned InoviceNumbers and InvoiceTemplate
core:
- Fixed calculation of next execution for Month and Year frequencies

Invoice scheduler fixes

---

debian/systemd/cgrates-loader.service
library/Ivoz/Cgr/Domain/Model/TpRatingPlan/TpRatingPlan.php
library/Ivoz/Cgr/Domain/Model/TpRatingPlan/TpRatingPlanAbstract.php
library/Ivoz/Cgr/Domain/Model/TpRatingPlan/TpRatingPlanDtoAbstract.php
library/Ivoz/Cgr/Domain/Model/TpRatingPlan/TpRatingPlanInterface.php
library/Ivoz/Cgr/Domain/Model/TpTiming/TpTiming.php
library/Ivoz/Cgr/Domain/Service/TpRatingPlan/InheritRatingPlanTag.php
library/Ivoz/Cgr/Domain/Service/TpTiming/CreatedByTpRatingPlan.php
library/Ivoz/Cgr/Domain/Service/TpTiming/DeletedByTpRatingPlan.php
library/Ivoz/Cgr/Domain/Service/TpTiming/TpTimingLifecycleEventHandlerInterface.php
library/Ivoz/Cgr/Domain/Service/TpTiming/TpTimingLifecycleServiceCollection.php
library/Ivoz/Cgr/Domain/Service/TpTiming/UpdatedTpTimingNotificator.php
library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpRatingPlan.TpRatingPlanAbstract.orm.yml
library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineEntityPersister.php
library/Ivoz/Core/Infrastructure/Domain/Service/Lifecycle/DoctrineEventSubscriber.php
library/Ivoz/Provider/Domain/Model/Destination/Destination.php
library/Ivoz/Provider/Domain/Model/DestinationRate/DestinationRate.php
library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroup.php
library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupInterface.php
scheme/app/DoctrineMigrations/Version20180802142456.php
web/admin/application/configs/klear/TpRatingPlansList.yaml
web/admin/application/configs/klear/model/TpRatingPlans.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/library/IvozProvider/Klear/Filter/RouteTag.php

This PR closes #543 by adding timing fields in TpRatingPlan structure.
Depending on how those fields are filled, the default _*any_ timing will be used or a new one will be created with the configured data.

Add support for Timings to Rating plans

---

asterisk/agi/src/Agi/Action/ServiceAction.php
asterisk/agi/src/Agi/Wrapper.php

read and playback functions in agi-wrapper were not deducing file paths correctly.
This caused that trying to play a locution in AGIs ended in CLI errors and no locution was played.

agis: fix agi read and playback apps

---

asterisk/agi/src/Agi/Action/ConditionalRouteAction.php
asterisk/agi/src/Agi/Action/DdiAction.php
asterisk/agi/src/Agi/Action/ExternalFilterAction.php
asterisk/agi/src/Agi/Action/HuntGroupStatusAction.php
asterisk/agi/src/Agi/Action/IvrAction.php
asterisk/agi/src/Agi/Action/QueueFullAction.php
asterisk/agi/src/Agi/Action/QueueTimeoutAction.php
asterisk/agi/src/Agi/Action/ServiceAction.php
asterisk/agi/src/Agi/Action/VoiceMailAction.php
asterisk/agi/src/Agi/Wrapper.php

This commit adds two new functions (_readLocution_ and _playbackLocution_) to agi wrapper for properly checking Locutions in dialplan.
Original functions (_read_ and _playback_) will only handle the locution string or full path to the filename of a Locution entity.

Update AGI wrapper with readLocution and playbackLocution

---

library/Ivoz/Provider/Domain/Model/Invoice/Invoice.php
library/Ivoz/Provider/Domain/Model/Invoice/InvoiceInterface.php
library/Ivoz/Provider/Domain/Service/Invoice/CreateByScheduler.php
library/Ivoz/Provider/Domain/Service/Invoice/SendGenerateOrder.php
library/spec/Ivoz/Provider/Domain/Model/Invoice/InvoiceSpec.php
web/admin/application/configs/klear/InvoicesList.yaml

This PR restores the old invoice generation behaviour for manual invoices.
Invoices generated from web/admin must be created in some steps:
1. Generate an Invoice entry with all invoice information
2. Add Fixed costs to the invoice or update its information (Optional)
3. Press generate invoice button in the interface

Fix manual inovice generation from web interface

---

library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdr.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrInterface.php
library/Ivoz/Provider/Domain/Model/User/User.php
library/Ivoz/Provider/Domain/Model/User/UserInterface.php
web/admin/application/configs/klear/KamUsersCdrsList.yaml
web/admin/application/configs/klear/KamUsersCdrsResidentialList.yaml
web/admin/application/configs/klear/klear.yaml
web/admin/application/configs/klear/model/KamUsersCdrs.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/library/IvozProvider/Klear/Auth/User.php
web/admin/application/library/IvozProvider/Klear/Dynamic/Config/BrandOperator.php
web/admin/application/library/IvozProvider/Klear/Dynamic/Config/MainOperator.php
web/admin/application/library/IvozProvider/Klear/Ghost/UsersCdr.php

Besides Billable Calls, retail and residential clients need call registries to show incoming calls.

Show Call registries for retail/residential client types

---

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ExternalCallFilter.ExternalCallFilter.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Invoice.Invoice.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/InvoiceScheduler.InvoiceScheduler.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/RoutingPattern.RoutingPattern.orm.yml

Avoid 'A new entity was found through the relationship 'Ivoz\Provider\Domain\Model\XXX#yyy' that was not configured to cascade persist operations for entity' errors

core: ensure cascade persist on n-m relationships

---

library/Ivoz/Core/Domain/Service/PersistErrorHandlerInterface.php
library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineEntityPersister.php
library/Ivoz/Core/Infrastructure/Domain/Service/Lifecycle/DoctrineEventSubscriber.php
library/Ivoz/Core/Infrastructure/Persistence/Doctrine/Events.php
library/Ivoz/Core/Infrastructure/Persistence/Doctrine/OnErrorEventArgs.php
library/Ivoz/Provider/Domain/Service/User/PersistErrorHandler.php

Persistence error handlers were not being executed in some scenarios
This PR fixes https://github.com/irontec/ivozprovider/issues/639

bug: persistence error handler enhancement

---

library/Ivoz/Kam/Domain/Model/TrunksLcrRuleTarget/TrunksLcrRuleTargetRepository.php
library/Ivoz/Kam/Domain/Service/TrunksLcrRuleTarget/RemoveByOutgoingRouting.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksLcrRuleTargetDoctrineRepository.php

This PR adds a new service to remove orphaned entries in kam_trunks_lcr_rule_targets after OutgoingRouting updates. It fixes a problem where old entries were being kept after changing Carriers servers in OutgoingRouting.

core: remove orphaned TrunksLcrRuleTargets service

---

web/admin/application/configs/klear/BrandDDIsList.yaml
web/admin/application/configs/klear/DdiProvidersList.yaml
web/admin/application/configs/klear/DdisList.yaml
web/admin/application/configs/klear/RetailDdisList.yaml
web/admin/application/configs/klear/model/Ddis.yaml

This PR fixes  #665 and the other screens that have ddi number as possible filter field.
This field is a bit messy. According to [orm definition](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Ddi.DdiAbstract.orm.yml#L9), the field is LowerCamelCase (ddi), but the column is UpperCamelCase (Ddi) , but actually the database column is Uppercase (DDI).
There are other DDIs fields like outgoingDDI, forcedDDI and multiDDI, but I left them untouched.

web/admin: fix list filtering using Ddi.ddi field

---

library/CoreBundle/Resources/config/services/infraestructure/cgrates.yml
web/admin/application/configs/klear/model/Companies.yaml
web/admin/application/library/IvozProvider/Klear/Ghost/Carriers.php
web/admin/application/library/IvozProvider/Klear/Ghost/Companies.php

This PR fixes #655 by replacing current balance fields with a ghost field that request current balance status to CGRateS.
The request already existed in a service so I just changed the field type and updated the existing ghosts.

web/admin: Carrier/Company balances changed to ghost fields

---

library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilter.php
library/Ivoz/Provider/Domain/Model/Schedule/Schedule.php

As soon as a external call filter is assigned to a DDI, incoming calls crash.
This PR tries to fix #676

core: fix external call filter

---

debian/ivozprovider-profile-proxy.config
debian/ivozprovider-profile-proxy.postinst
debian/ivozprovider-profile-proxy.templates

This PR fixes #678 by adding a new configurable option to debconf.
This option can be configured using ivozprovider-profile-proxy menu like the AUDIO_SOCK value.

pkg: make rtpengine private address configurable from install menu

---

scheme/app/DoctrineMigrations/Version20180726142227.php
scheme/app/DoctrineMigrations/Version20180802142456.php

This PR fixes some old scheme migrations that caused tp_rating_plans contents to be removed due to a on-delete-cascade constraint with tp_destination_rates.
By removing the constraint before migrating tp_destination_rates we can keep the data for later migration. 
This was discovered while testing #681

scheme: fix old migrations to avoid rating plans loss

---

library/bin/test-i18n
web/admin/application/configs/klear/model/Carriers.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po

This updates _test-i18_ to also handle empty and fuzzy translations
I have also added these checks to documentation translations, but I have commented them out because there are too many errors and we're scheduling a documentation revision for next patch release.

i18n: improved tests to detect empty and fuzzy translations

---

web/admin/application/configs/klear/CarriersList.yaml
web/admin/application/controllers/KlearCustomTarificatorController.php

Carrier rating profiles section was using company call simulating, so the call simulator data displayed for carrier=1 was actually the company=1.
This PR adds the required logic to use carrier active rating profile to simulate a call.

web/admin: fix call simulator for Carrier rating profiles

---

library/CoreBundle/Resources/config/lifecycle/provider/rating_plan.yml
library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpRatingPlan.TpRatingPlanAbstract.orm.yml
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php
library/Ivoz/Provider/Domain/Service/RatingPlan/PersistErrorHandler.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/RatingPlan.RatingPlanAbstract.orm.yml
scheme/app/DoctrineMigrations/Version20180919144526.php
web/admin/application/configs/klear/RatingPlansList.yaml
web/admin/application/configs/klear/errors.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po

Timings usage is quite misleading as different timings may collide.
This PR forces each destinationRate - timing association to have a different weight. It also orders entries sorting by descending weight.
This aims to make this feature a bit more usable.

web/admin: add uniques to destinationRate-timings

---

web/admin/application/configs/klear/DestinationRatesList.yaml

Enable full template search feature introduced in https://github.com/irontec/klearMatrix/commit/7f61f542649cd98b7c6ac5b35544f8100cd98ca5
This PR fixes https://github.com/irontec/ivozprovider/issues/656

web/admin: improved destination autocomplete filter

---

scheme/initial-artemis.sql
scheme/initial.sql

This PR updates the initial.sql file to contain the original _initial.sql_ + all migrations. In order to keep original dump for 2.0.0 I have moved it to _initial-artemis.sql_
This is an idea to speed up installation from iso or latests packages and scheme tests. This way the only migrations applied are the one done related to the minor version changes. This _initial.sql_ should be regenerated whenever a minor version is done to apply all the scheme changes done in previous minor (ie next one will be in 2.9.0)

scheme: update initial.sql for 2.8.0 release

---

library/Ivoz/Cgr/Infrastructure/Domain/Service/Cgrates/FetchCallStatsService.php
library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/AbstractBalanceService.php
web/admin/application/library/IvozProvider/Klear/Ghost/Carriers.php
web/admin/application/library/IvozProvider/Klear/Ghost/Companies.php

Improve Ghost Fields to handle CGRateS connection exceptions.
Instead of crashing the whole screen, those ghost fields will display _Unavailable_

web/admin: improve CGRateS ghost fields error handling

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Retail and wholesale clients' calls do not traverse any Application Server. This means that a unique SIP dialog is involved.
In these 2 bouncing scenarios:
- Retail calling to another (or same) retail DDI.
- Wholesale calling to a retail DDI.
2 CDR entries must be created in kam_users_cdrs, the same way kam_trunks_cdrs does for bounced calls.
This PR disables [detect_spirals dialog modparam](http://kamailio.org/docs/modules/5.1.x/modules/dialog.html#dialog.p.detect_spirals) and implements a manual mechanism to call [dlg_manage()](http://kamailio.org/docs/modules/5.1.x/modules/dialog.html#dialog.f.dlg_manage) twice for such calls. Prior to that, logic has to be reordered/adapted to avoid using dlg_vars before dlg_manage() call.
This PR tries to fix #724.

kam: fix bounce scenarios in non-AS calls

---

asterisk/agi/app/MicroKernel.php
asterisk/agi/app/config/services.yml
asterisk/agi/src/Agi/Action/CallForwardResidentialAction.php
asterisk/agi/src/Agi/Action/ExternalResidentialCallAction.php
asterisk/agi/src/Agi/Action/ResidentialCallAction.php
asterisk/agi/src/Agi/Action/ResidentialStatusAction.php
asterisk/agi/src/Agi/Action/VoiceMailAction.php
asterisk/agi/src/Agi/Wrapper.php
asterisk/agi/src/Dialplan/ResidentialStatus.php
asterisk/agi/src/Dialplan/Residentials.php
asterisk/config/dialplan/default.conf
library/Ivoz/Ast/Domain/Service/Voicemail/UpdateByResidentialDevice.php
library/Ivoz/Provider/Domain/Model/Brand/Brand.php
library/Ivoz/Provider/Domain/Model/Brand/BrandInterface.php
library/Ivoz/Provider/Domain/Model/BrandService/BrandServiceRepository.php
library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDevice.php
library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceDtoAbstract.php
library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceInterface.php
library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceTrait.php
library/Ivoz/Provider/Domain/Model/Service/Service.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BrandServiceDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallForwardSetting.CallForwardSettingAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ResidentialDevice.ResidentialDevice.orm.yml
scheme/app/DoctrineMigrations/Version20181019153700.php
scheme/tests/Provider/ResidentialDevice/ResidentialDeviceLifeCycleTest.php
web/admin/application/configs/klear/CallForwardSettingsList.yaml
web/admin/application/configs/klear/ResidentialDevicesList.yaml
web/admin/application/configs/klear/model/CallForwardSettings.yaml
web/admin/application/library/IvozProvider/Klear/Filter/TargetTypes.php

This PR fixes #545 by implementing required logics in AGIs and interface to enable Call Forward Settings for Residential Devices.
This feature already existed in Oasis release and the fields in the tables already existed, so no API changes should occur. Scheme changes only create any missing asterisk voicemails and update their information.

Residential cfw voicemail

---

scheme/app/DoctrineMigrations/Version20181022130854.php

Update the field content based on the Company's default Country. This delta apply required changes for Users and Residential Devices forwards.
This was missing in the global E.164 standarization done in #313

scheme: populate numberCountryId in CallForwardSettings

---

web/rest/client/src/Controller/My/WebThemeAction.php

User's portal download the company logo to be displayed from an URL provider in the /web_theme request. When the filename to be download contained spaces, the URL provided was not properly encoded.
This PR urlencodes the filename to return valid Logo URLs.
By the way: I found WebThemeAction twice: one in platform API and another one in client API. I've only changed the client one. Not sure if the other one is deprecated or something.

Fix userportal logo when filename has spaces

---

web/admin/application/configs/klear/AdministratorsList.yaml

Private administrator (Administrator with id = 0) is an internal user used for Rest API requests (afaik).
This administrator should not be visible in Main operators list.

web/admin: hide Rest API private administrator from lists

---

library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceRepository.php
library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccountRepository.php
library/Ivoz/Provider/Domain/Service/ResidentialDevice/CheckUniqueness.php
library/Ivoz/Provider/Domain/Service/RetailAccount/CheckUniqueness.php
library/Ivoz/Provider/Domain/Service/RetailAccount/RetailAccountLifecycleEventHandlerInterface.php
library/Ivoz/Provider/Domain/Service/RetailAccount/RetailAccountLifecycleServiceCollection.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/ResidentialDeviceDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/RetailAccountDoctrineRepository.php
web/admin/application/configs/klear/errors.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po

This PR adds two services to check Retail Accounts and Residential Devices does't have the same name. 
The same behaviour could be implemented in the future for Terminals and Friends for #308

core: residential retail uniqueness

---

asterisk/agi/src/Helpers/EndpointResolver.php
library/Ivoz/Provider/Domain/Model/Friend/FriendRepository.php
library/Ivoz/Provider/Domain/Model/Terminal/TerminalRepository.php
library/Ivoz/Provider/Domain/Service/Friend/CheckUniqueness.php
library/Ivoz/Provider/Domain/Service/Terminal/CheckUniqueness.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/FriendDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/TerminalDoctrineRepository.php
web/admin/application/configs/klear/errors.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po

This PR is like #753 for Terminals and Friends.
The added services check Terminal and Friends does't have the same name in the same Company (or, in other words, with the same domain).
The TerminalRepository already had a method to find by name and domain, but I have update its signature so now is like the Residential Device, Friend, Retail Account ones. That's the reason why an agi commit is present in the PR.
This fixes #308

core: terminal friend uniqueness

---

web/admin/public/dev.php
web/admin/public/e2e.php
web/admin/public/zf.php

There is no reason to keep development as default environment anymore. Access through dev.php or look into the journal in order to check error messages out. Notice that dev.php is broken on repository installations due to missing dependencies.
This PR aims to fix https://github.com/irontec/ivozprovider/issues/766

web/admin: do not use development env by default anymore

---

asterisk/agi/src/Agi/Action/FaxReceiveStatusAction.php
asterisk/agi/src/Voicemail/Sender.php
library/Ivoz/Core/Domain/Model/Mailer/Message.php
library/Ivoz/Provider/Domain/Model/NotificationTemplateContent/NotificationTemplateContentAbstract.php
library/Ivoz/Provider/Domain/Model/NotificationTemplateContent/NotificationTemplateContentDtoAbstract.php
library/Ivoz/Provider/Domain/Model/NotificationTemplateContent/NotificationTemplateContentInterface.php
library/Ivoz/Provider/Domain/Service/BalanceNotification/NotifyBrokenThreshold.php
library/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSender.php
library/Ivoz/Provider/Domain/Service/Invoice/EmailSender.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/NotificationTemplateContent.NotificationTemplateContentAbstract.orm.yml
library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSenderSpec.php
scheme/app/DoctrineMigrations/Version20181113095345.php
web/admin/application/configs/klear/NotificationTemplatesContentsList.yaml
web/admin/application/configs/klear/model/NotificationTemplatesContents.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/rest/brand/features/provider/notificationTemplateContent/getNotificationTemplateContent.feature
web/rest/brand/features/provider/notificationTemplateContent/postNotificationTemplateContent.feature
web/rest/brand/features/provider/notificationTemplateContent/putNotificationTemplateContent.feature

>Mail templates newlines are not applying as text/html is used instead of text/plain (for agis tasks).
>
>This issue aims to evaluate this same change for every task that sends an email.
Edit: This PR now includes the required changes to add a new field to Notification Template Contents in order to specify the body MIME type. The supported types are _text/html_ and _text/plain_

Add Body MIME type selector to Notification Template Contents

---

doc/sphinx/administration_portal/platform/default_notification_templates.rst
doc/sphinx/administration_portal/platform/index.rst
doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po
web/admin/application/configs/klear/DefaultNotificationTemplatesList.yaml
web/admin/application/configs/klear/NotificationTemplatesContentsList.yaml
web/admin/application/configs/klear/NotificationTemplatesList.yaml
web/admin/application/configs/klear/conf.d/notificationTemplateHelp.yaml
web/admin/application/configs/klear/klear.yaml
web/admin/application/configs/klear/model/NotificationTemplates.yaml
web/admin/application/configs/klear/model/NotificationTemplatesContents.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/library/IvozProvider/Klear/Options/OptionsCustomizerFilterForNotificationCallCsv.php

This PR adds a new portal section under Platform menu to allow administrators to edit default Notification templates. This new section is limited to edition, so new and delete have been removed.
The PR also includes the missing screens for Call CSV Notification Templates contents.

web/admin: Platform Default Notification Templates section

---

debian/ivozprovider-web-rest.install
debian/ivozprovider-web-rest.ivozprovider-jwt.service
debian/ivozprovider.postinst
debian/rules
debian/systemd/ivozprovider-jwt.service
debian/systemd/ivozprovider-jwt.timer

Remove expired JWT refresh tokens from refresh_tokens table in database

devops: added systemd timer to clear expired API refresh tokens

---

web/admin/application/configs/klear/UsersList.yaml
web/admin/application/configs/klear/model/Users.yaml
web/admin/application/library/IvozProvider/Klear/Ghost/RegisterStatus.php

It may be handy to see terminal register status icon directly in Users section.
This PR fixes #794

web/admin: show terminal register status in Users

---

library/DataFixtures/ORM/KamTrunksCdr.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrRepository.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrRepository.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/UsersCdrDoctrineRepository.php
microservices/recordings/src/Recording/Encoder.php
scheme/tests/Kam/TrunksCdr/TrunksCdrRepositoryTest.php
scheme/tests/Kam/UsersCdr/UsersCdrRepositoryTest.php

Improve Recordings encoder to handle multiple Cdrs entries for each Call-Id (like in bounced calls). The core tagged commit is not necessary if #734 is merged before this.
This PR fixes #549

microservices: call recordings in bounced calls

---

library/CoreBundle/Resources/config/config.yml
library/CoreBundle/Resources/config/parameters.yml.dist

Do not resolve SMTP identification through the request object, read it from parameters instead

core: use parameter instead of request on smtp identification

---

library/DataFixtures/ORM/ProviderCallCsvScheduler.php
library/DataFixtures/ORM/ProviderInvoiceScheduler.php
library/DataFixtures/ORM/ProviderNotificationTemplate.php
library/DataFixtures/ORM/ProviderNotificationTemplateContent.php
library/Ivoz/Provider/Application/Service/CallCsvReport/CallCsvReportDtoAssembler.php
library/Ivoz/Provider/Domain/Service/CallCsvReport/CreateByScheduler.php
library/Ivoz/Provider/Domain/Service/Invoice/CreateByScheduler.php
library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/CreateBySchedulerSpec.php
library/spec/Ivoz/Provider/Domain/Service/Invoice/CreateBySchedulerSpec.php
scheme/app/config/config_test.yml
scheme/app/config/services_test.yml
scheme/tests/DbIntegrationTestHelperTrait.php
scheme/tests/Provider/CallCsvReport/CreateBySchedulerServiceTest.php
scheme/tests/Provider/CallCsvScheduler/CallCsvSchedulerLifeCycleTest.php
scheme/tests/Provider/Invoice/CreateBySchedulerServiceTest.php
scheme/tests/Provider/InvoiceScheduler/InvoiceSchedulerSchedulerLifeCycleTest.php
scheme/tests/Provider/NotificationTemplate/NotificationTemplateRepositoryTest.php
web/rest/brand/features/provider/notificationTemplate/postNotificationTemplate.feature
web/rest/brand/features/provider/notificationTemplateContent/postNotificationTemplateContent.feature

Do not modify input argument before service execution, nextExecution was
being updated before report creation.
This PR aims to fix https://github.com/irontec/ivozprovider/issues/821

core: fixed CallCsvReport/CreateByScheduler service

---

library/DataFixtures/ORM/CgrTpRatingProfile.php
library/Ivoz/Cgr/Domain/Model/TpRatingProfile/TpRatingProfileAbstract.php
library/Ivoz/Cgr/Domain/Model/TpRatingProfile/TpRatingProfileDtoAbstract.php
library/Ivoz/Cgr/Domain/Model/TpRatingProfile/TpRatingProfileInterface.php
library/Ivoz/Cgr/Domain/Service/TpRatingProfile/UpdateByRatingProfile.php
library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpRatingProfile.TpRatingProfileAbstract.orm.yml
scheme/app/DoctrineMigrations/Version20181221113443.php

As reported by @powerpbx in https://github.com/irontec/ivozprovider/pull/807#issue-234711702, CGRateS does not handle properly rating profiles activation_time if this field has datetime type.
This PR changes type to varchar (as CGRateS original field) and needs https://github.com/irontec/cgrates/commit/72fa43d91251d413591665f20ed1b3239a9f59bf to work properly.
This issue closes #801 and #807.
Thanks @powerpbx  for your report.

scheme: change rp.activation_time type

---

asterisk/agi/src/Agi/Action/DdiAction.php
asterisk/agi/src/Agi/Action/ExternalFilterAction.php
doc/sphinx/administration_portal/client/vpbx/routing_tools/calendars.rst
doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po
library/Ivoz/Provider/Domain/Model/Calendar/Calendar.php
library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilter.php
library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDate.php
library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDateAbstract.php
library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDateDtoAbstract.php
library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDateInterface.php
library/Ivoz/Provider/Domain/Service/HolidayDate/CheckEventDateCollision.php
library/Ivoz/Provider/Domain/Service/HolidayDate/HolidayDateLifecycleEventHandlerInterface.php
library/Ivoz/Provider/Domain/Service/HolidayDate/HolidayDateLifecycleServiceCollection.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/HolidayDate.HolidayDateAbstract.orm.yml
scheme/app/DoctrineMigrations/Version20181227122711.php
web/admin/application/configs/klear/CalendarsList.yaml
web/admin/application/configs/klear/HolidayDatesList.yaml
web/admin/application/configs/klear/model/HolidayDates.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/rest/client/features/provider/holidayDate/getHolidayDate.feature
web/rest/client/features/provider/holidayDate/postHolidayDate.feature
web/rest/client/features/provider/holidayDate/putHolidayDate.feature

This PR add extra fields to Holiday dates to allow entering a start and end time and specific routing options.
Holiday Dates can now be a whole day event or just during a Time Period.
Optionally, it can override both locution and treatment. If this fields are left empty, the external call filter locutions and handlers will be used.
Fixes #22

Add support for calendar events

---

debian/ivozprovider.postinst
kamailio/trunks/config/kamailio.cfg

This PR fixes KamTrunks bouncing in scenarios where KamUsers and KamTrunks share the same IP address.

Fix shared ip setup

---

kamailio/trunks/config/kamailio.cfg

Asterisk trunks endpoint has direct_media to 'no', so this is no longer used.

kamtrunks: remove media liberation delay mechanism

---

web/admin/application/library/IvozProvider/Service/RestClient.php

Avoid unnecessary point of failure

web/admin: Access API through localhost instead of server name

---

kamailio/users/config/kamailio.cfg

It should only be mangled in initial requests from wholesale clients
that do not use PAI nor RPID. Otherwise, leave it unchanged.

kamusers: fix incorrect From username mangling

---

library/Ivoz/Provider/Domain/Model/Carrier/Carrier.php
library/Ivoz/Provider/Domain/Service/Carrier/ForceExternallyRated.php
web/admin/application/configs/klear/CarriersList.yaml
web/admin/application/configs/klear/model/Carriers.yaml

This PR adds a service to force Carrier.externallyRated field when Brand has no billing feature enabled.
Additionally, it updates Carrier screens to hide fields based on that feature and includes a Carrier sanitize method to ensure hidden fields have default values.

Force Carrier externally rated when Billing feature is disabled 

---

kamailio/trunks/config/kamailio.cfg

This PR fixes DDI recognition current logic, that crashes if more than 100 DDIs are assigned to the same DDI Provider (loop exceeded).
New logic does:
- Gets all DDI Providers matching IP address and get their transformation sets.
- Apply transformation set to R-URI username.
- Find transformated DDI within brand's DDIs.

kamtrunks: fix DDI recognition logic

---

kamailio/trunks/config/custom_settings.cfg.in
kamailio/trunks/config/kamailio.cfg

Bouncer mechanism avoids an external call to a DDI existing in DDIs table to
reach the carrier.
This commit makes this behaviour optional, so that all outgoing DDIs reach a
carrier, even those to DDIs belonging to the platform.

trunks: make bouncer optional

---

doc/sphinx/administration_portal/client/residential/residential_devices.rst
doc/sphinx/administration_portal/client/retail/retail_accounts.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends.rst
doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po
web/admin/application/configs/klear/model/FriendsPatterns.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po

Two doc quick-fixes here:
- Use PAI to specify caller in retail/residential/friends.
- Do not use \d in friend's regexps, use [0-9].

doc: use pai for caller and do not use pcre in friends

---

web/admin/application/configs/klear/BrandsList.yaml

Brand currency should be required. Language and timezone have been just added because of aesthetic reasons

web/admin: show locale fields on new brand screen

---

kamailio/users/config/kamailio.cfg

Application servers send an out-of-dialog NOTIFY message for unsolicited MWI service whenever a voicemail message is received.
This PR fixes handling of this NOTIFY request.

kamusers: fix NOTIFY handling (for unsolicited MWI)

---

library/Ivoz/Core/Domain/Model/ChangelogTrait.php
scheme/tests/Provider/ApplicationServer/ApplicationServerLifeCycleTest.php
scheme/tests/Provider/CallCsvReport/CallCsvReportLifeCycleTest.php
scheme/tests/Provider/Carrier/CarrierLifeCycleTest.php
scheme/tests/Provider/DdiProviderAddress/DdiProviderAddressLifeCycleTest.php
scheme/tests/Provider/DdiProviderRegistration/DdiProviderRegistrationLifeCycleTest.php
scheme/tests/Provider/Queue/QueueLifeCycleTest.php
scheme/tests/Provider/RoutingPatternGroupsRelPattern/RoutingPatternGroupsRelPatternLifeCycleTest.php

Because a non strict comparation, some change were not being properly registered. Null to zero value change for instead.

Strict change detection

---

library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByExtension.php
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByUser.php
library/spec/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByExtensionSpec.php
scheme/tests/Provider/Extension/ExtensionLifeCycleTest.php
scheme/tests/Provider/User/UserLifeCycleTest.php

For vPBX users, PsEndpoints store some Terminal and User data. When user is assigned a new Terminal, the PsEndpoint data is updated with new User related data.
This PR fixes the field PsEndpoints.named_pickup_groups that was only being updated when the user is added or removed from a PickupGroup. If this user still doesn't have a Terminal assigned, [the service in charge or filling named_pickup_group](https://github.com/irontec/ivozprovider/blob/1c280aa7cf56eec8129f9c8503ac8ad97af5d5d3/library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByPickUpRelUser.php) won't do anything at all.
This may break some tests 0:-)

core: update endpoints pickupgroups when user or extension changes

---

asterisk/agi/app/MicroKernel.php
library/Ivoz/Core/Application/RegisterCommandTrait.php
microservices/balances/app/MicroKernel.php
microservices/recordings/app/MicroKernel.php

Fixed bug introduced on https://github.com/irontec/ivozprovider/pull/937 because of merge order

core: added agent argument on CommandWasExecuted

---

asterisk/agi/src/Agi/Action/CallForwardAction.php
asterisk/agi/src/Agi/Action/RouterAction.php
asterisk/agi/src/Agi/Action/ServiceAction.php
asterisk/agi/src/Agi/Action/VoiceMailAction.php
asterisk/agi/src/Agi/Agents/AgentInterface.php
asterisk/agi/src/Agi/Agents/AgentTrait.php
asterisk/agi/src/Agi/Agents/ResidentialAgent.php
asterisk/agi/src/Agi/Agents/UserAgent.php

Fixes Voicemail action implementation for Residential Devices.
Originally, this action only supported voicemail for Users, so I have added required methods to AgentInterface to support the same action for any other agent (included Residential).
Fixes #934

agis: fix Voicemail action for Residential Devices

---

microservices/recordings/src/Recording/Encoder.php

This PR updates the recordings microservice to ignore too small recodings files.
According to our tests this files belong to calls that has been answered with just a couple of seconds and cause a division by zero error when trying to get recording metadata.
Fixes #959

recordings: ignore files below a size threshold

---

kamailio/trunks/config/kamailio.cfg

Kamtrunks controls maxcalls in CONTROL_MAXCALLS route.
When exceeded, "403 Maxcalls exceeded" was replied.
This PR changes this behaviour for external incoming calls, converting that reply into a 486 Busy.

kamtrunks: 486 in incoming maxcalls rejected calls

---

library/Ivoz/Kam/Domain/Service/Rtpengine/RtpengineLifecycleEventHandlerInterface.php
library/Ivoz/Kam/Domain/Service/Rtpengine/RtpengineLifecycleServiceCollection.php
library/Ivoz/Kam/Domain/Service/TrunksClientInterface.php
library/Ivoz/Kam/Domain/Service/UsersClientInterface.php
library/Ivoz/Kam/Infrastructure/Domain/Service/Rtpengine/SendTrunksRtpengineReloadRequest.php
library/Ivoz/Kam/Infrastructure/Domain/Service/Rtpengine/SendUsersRtpengineReloadRequest.php
library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php
library/Ivoz/Kam/Infrastructure/Kamailio/UsersClient.php

Currently kamailio processes must be restarted.

core: run rtpengine.reload when changes in media-relays

---

kamailio/users/config/kamailio.cfg

Application servers set a preferred display name in vPBX/residential calls for certain DDIs.
KamUsers was overriding this display name.
This PR fixes this feature.

kamusers: keep From displayName

---

library/ApiBundle/Resources/config/services.yml
library/CoreBundle/Resources/config/services/events.yml
library/Ivoz/Api/Behat/Context/FeatureContext.php
library/Ivoz/Core/Infrastructure/Symfony/DependencyInjection/Compiler/RepositoryCompiler.php

make public directly accessed services so that they don't throw deprecation erros like:
`php.INFO: User Deprecated: The "Ivoz\Core\Domain\Service\DomainEventPublisher" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. `

core: remove some deprecation warnings

---

asterisk/agi/src/Agi/Action/ExternalNumberAction.php
asterisk/agi/src/Agi/Agents/AgentInterface.php
asterisk/agi/src/Agi/Agents/AgentTrait.php
asterisk/agi/src/Agi/Agents/FriendAgent.php
asterisk/agi/src/Agi/Agents/ResidentialAgent.php
asterisk/agi/src/Agi/Agents/RetailAgent.php
asterisk/agi/src/Agi/Agents/UserAgent.php
asterisk/agi/src/Dialplan/Retails.php
doc/sphinx/administration_portal/client/residential/residential_devices.rst
doc/sphinx/administration_portal/client/retail/retail_accounts.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends/remote_friends.rst
doc/sphinx/administration_portal/client/vpbx/terminals.rst
doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po
doc/sphinx/locale/es/LC_MESSAGES/security_and_maintenance.po
doc/sphinx/security_and_maintenance/security/firewall.rst
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointAbstract.php
library/Ivoz/Ast/Domain/Model/PsEndpoint/PsEndpointDtoAbstract.php
library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping/PsEndpoint.PsEndpointAbstract.orm.yml
library/Ivoz/Provider/Domain/Model/Friend/Friend.php
library/Ivoz/Provider/Domain/Model/Friend/FriendInterface.php
library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccount.php
library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccountInterface.php
schema/app/DoctrineMigrations/Version20190520145100.php
schema/tests/Provider/ResidentialDevice/ResidentialDeviceLifeCycleTest.php

After some T.38 passthrough real-life tests, we have learnt:
- t38_udptl_ec: 'redundancy' seems better than 'none'.
- t38_udptl_maxdatagram: 1440 seems an standard value (and fixes some problems).
- t38_udptl_nat: set to 'no' as rtpengine does relay t.38 traffic.
This last point is very important: no Application Server exposure is needed.

T38 passthrough fix

---

kamailio/trunks/config/kamailio.cfg

LCR kamailio module orders by prefix length, then by prio.
This changes this behaviour, causing strict prio ordering.
e.g.
- Calling +34676000000
* Prio 1: +34 CarrierA
* Prio 2: +346 CarrierB
Prior to this change, CarrierB would be used. After this change, CarrierA.

kamtrunks: order outgoing routes by priority

---

library/Ivoz/Core/Infrastructure/Domain/Service/Mailer/Client.php

Check if connection to MTA is ready before sending mail. If not, reset connection.

core: reset mailer transport before sending mail

---

schema/app/DoctrineMigrations/Version20190529132608.php

This PR includes a query to update DDIE164 field of DDIs table with the concatenation of countryCode + DDI (including plus sign)
This change should not change anything in _artemis_ release, but data migrated from previous releases will include the plus sign (_oasis_ uses E.164 without sign).

schema: update DDI E.164 number field with country information

---

debian/ivozprovider-web-admin.postinst
library/CoreBundle/Resources/config/services/path_resolvers.yml
library/Ivoz/Provider/Application/Service/DestinationRateGroup/DestinationRateGroupDtoAssembler.php
library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroup.php
library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupDto.php
web/admin/application/configs/klear/DestinationRateGroupsList.yaml
web/admin/application/configs/klear/model/DestinationRateGroups.yaml

Requieres to increase upload_max_filesize and post_max_size on php.ini

web/rest: allow file sizes up to 30M on destinationRateGroup importer

---

kamailio/users/config/kamailio.cfg

I could not make call transfer to an external number. After some debugging, it turns out that the external number was not properly transformed so it was rejected by kamailio@trunks.
The bug is due to a tiny typo in kamailio.cfg of kamailio@users.

Fix typo in transferred external calls.

---

asterisk/agi/src/Agi/Action/RouterAction.php
library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingAbstract.php
library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallForwardSetting.CallForwardSettingAbstract.orm.yml
schema/app/DoctrineMigrations/Version20190604110803.php
web/admin/application/configs/klear/model/CallForwardSettings.yaml
web/user/app/languages/locale-en.json
web/user/app/languages/locale-es.json
web/user/app/modules/detours/detoursEditCtrl.js
web/user/app/modules/detours/detoursNewCtrl.js
web/user/app/views/detours/edit.html
web/user/app/views/detours/new.html
web/user/app/views/detours/table-detours.html

This allows creating Call Forward settings without handler.
Although this may not seem to have too much logic, it could be used to setup dial timeout by adding a NoAnswer CallForwardSettings to ResidentialDevices or Users

Allow unassigned route in Call Forward Settings

---

library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingAbstract.php
library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingInterface.php
library/Ivoz/Provider/Domain/Model/Company/CompanyAbstract.php
library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php
library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDateAbstract.php
library/Ivoz/Provider/Domain/Model/HolidayDate/HolidayDateInterface.php
library/Ivoz/Provider/Domain/Model/IvrEntry/IvrEntryAbstract.php
library/Ivoz/Provider/Domain/Model/IvrEntry/IvrEntryInterface.php
library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingAbstract.php
library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingInterface.php
library/Ivoz/Provider/Domain/Model/QueueMember/QueueMemberAbstract.php
library/Ivoz/Provider/Domain/Model/QueueMember/QueueMemberInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallForwardSetting.CallForwardSettingAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/HolidayDate.HolidayDateAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/IvrEntry.IvrEntryAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/OutgoingRouting.OutgoingRoutingAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/QueueMember.QueueMemberAbstract.orm.yml
schema/app/DoctrineMigrations/Version20190618064619.php

Mark explicitly nullable on delete cascade foreign keys (default behaviour when nullablility is not defined) so that models and API are properly documented

Map nullable on delete cascade fk fields properly

---

Jenkinsfile

PR label must be set during PR creation, otherwise a first run of the tests will be triggered.
This can be handy while creating documentation or application configuration changes that can not be tested right now.

ci: skip Pull Request tests when ci-no-test label is present

---

web/admin/application/assets/js/customMenu.js
web/admin/application/controllers/KlearCustomExtraAuthController.php
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po

Close edit/add tabs when a brand/client is emulated so that you don't end up adding an entity with unexpected company/brand values

web/admin: forced close of add/edit tabs on emulation

---

library/Ivoz/Provider/Domain/Service/Invoice/CheckValidity.php
library/spec/Ivoz/Provider/Domain/Service/Invoice/CheckValiditySpec.php

- Do not check unmetered calls before in date
- Do not check unmetered calls after out date
- Just check that calls in invoice date range have been metered

core: removed some invoice validity checks

---

library/Ivoz/Provider/Domain/Model/Friend/FriendDto.php
library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceDto.php
library/Ivoz/Provider/Domain/Model/RetailAccount/RetailAccountDto.php
library/Ivoz/Provider/Domain/Model/Terminal/TerminalDto.php
web/rest/brand/app/config/api/raw/kam.yml
web/rest/brand/app/config/api/raw/provider.yml
web/rest/brand/features/provider/friend/getFriendStatus.feature
web/rest/brand/features/provider/residentialDevice/getResidentialDeviceStatus.feature
web/rest/brand/features/provider/retailAccount/getRetailAccountStatus.feature
web/rest/brand/features/provider/terminal/getTerminalStatus.feature

Expose user locations on brand API. Added methods:
- /friends/status
- /residential_devices/status
- /retail_accounts/status
- /terminals/status

Brand user locations

---

Jenkinsfile
tests/docker/Dockerfile

This way we avoid to download the sources of phpunit
every time a new build is scheduled.

ci: include phpunit in docker testing image

---

asterisk/agi/src/Agi/Agents/UserAgent.php
doc/sphinx/administration_portal/brand/routing/routing_tags.rst
doc/sphinx/administration_portal/client/vpbx/user_configuration/outgoing_ddi_rules.rst
doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po
doc/sphinx/locale/es/LC_MESSAGES/basic_concepts.po
kamailio/users/config/kamailio.cfg
library/DataFixtures/ORM/ProviderRoutingTag.php
library/Ivoz/Provider/Domain/Model/OutgoingDdiRulesPattern/OutgoingDdiRulesPattern.php
library/Ivoz/Provider/Domain/Model/RoutingTag/RoutingTag.php
library/spec/Ivoz/Provider/Domain/Model/OutgoingDdiRulesPattern/OutgoingDdiRulesPatternSpec.php
library/spec/Ivoz/Provider/Domain/Model/RoutingTag/RoutingTagSpec.php
schema/tests/Provider/RoutingPatternGroupsRelPattern/RoutingPatternGroupsRelPatternLifeCycleTest.php
schema/tests/Provider/RoutingTag/RoutingTagLifeCycleTest.php
web/admin/application/configs/klear/model/OutgoingDdiRulesPatterns.yaml
web/admin/application/configs/klear/model/RoutingTags.yaml
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/rest/brand/features/provider/outgoingRouting/getOutgoingRouting.feature
web/rest/brand/features/provider/routingTag/getRoutingTag.feature
web/rest/brand/features/provider/routingTag/postRoutingTag.feature
web/rest/brand/features/provider/routingTag/putRoutingTag.feature
web/rest/client/features/provider/outgoingDdiRulesPattern/putOutgoingDdiRulesPattern.feature

This PR introduces restrictions in DDI-prefix and routing-tags format to avoid ambiguity in destination number. From now on:
- DDI-prefix must have this format: 1-3 digits ended by *.
- Routing-tag must have this format: 1-3 digits ended by #.
This way it is possible to distinguish prefix part from destination number.

Avoid destination ambiguity in DDI-prefix and routing-tags

---

library/Ivoz/Provider/Domain/Model/OutgoingDdiRule/OutgoingDdiRule.php

Action Keep was not being handled by Outgoing DDI rule pattern action using matchlists.

core: properly handle OutgoingDDIRule keep action

---

asterisk/agi/src/Agi/Action/QueueCallAction.php

If a User is a member of a queue, but with DND activated, he should not get any call from this queue.

agis : avoid calls to a DND User members of a Queue

---

kamailio/trunks/config/kamailio.cfg

CGRATES_AUTH_REQUEST route asks CGRateS whether a call can be billed before placing a call. If CGRateS is unreachable, no call is allowed.
[_allow_calls_without_cgrates_](https://github.com/irontec/ivozprovider/blob/41ff0905e5e200b49a92d955ad59d91ee70df875/kamailio/trunks/config/kamailio.cfg#L37) runtime variable disabled this check temporarily, for maintenance operations that need stopping CGRateS.
This PR aims to allow within country calls despite CGRateS being unreachable and _allow_calls_without_cgrates_ is not set.

kamtrunks: allow within country calls if CGRateS is unreachable

---

kamailio/trunks/config/kamailio.cfg

*ApierV1.GetLcr* call in kamailio.cfg for LCR routes fails with _LCR_COMPUTE_ERRORS_ when a carrier of LCR route cannot bill given destination.
This PR silently skips carriers that cannot bill given destination, adding only to Suppliers array those who can.

kamtrunks: cgrates ignore errors in LcrGet

---

library/ApiBundle/Resources/config/filters.yml
library/Ivoz/Api/Doctrine/Orm/Filter/OrderFilter.php
library/Ivoz/Api/Entity/Metadata/Property/Factory/PropertyNameCollectionFactory.php
library/Ivoz/Api/Swagger/Metadata/Resource/ResourceMetadata/FilterMetadataFactory.php
library/Ivoz/Api/Swagger/Serializer/DocumentationNormalizer/SearchFilterDecorator.php

Added is null / is not null filter on foreign keys
Do not filter by fields that are not in response model (Except for foreign keys)
Improved order by parameter documentation (enum instead of raw string)
Sort API filter parameters

Improved api filters

---

library/CoreBundle/Resources/config/services/assemblers.yml
library/Ivoz/Core/Application/Model/DtoNormalizer.php
library/Ivoz/Kam/Domain/Model/TrunksUacreg/DdiProviderRegistrationStatus.php
library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php
library/Ivoz/Provider/Application/Service/DdiProviderRegistration/DdiProviderRegistrationDtoAssembler.php
library/Ivoz/Provider/Domain/Model/DdiProviderRegistration/DdiProviderRegistrationDto.php
library/spec/Ivoz/Provider/Application/Service/DdiProviderRegistration/DdiProviderRegistrationDtoAssemblerSpec.php
web/rest/brand/app/config/api/raw/kam.yml
web/rest/brand/app/config/api/raw/provider.yml
web/rest/brand/features/provider/ddiProviderRegistration/getDdiProviderRegistration.feature

Show DdiProviderRegistration status on API collection response

web/rest: show register status on ddi provider registrations

---

web/admin/application/configs/klear/CompaniesList.yaml
web/admin/application/configs/klear/model/Companies.yaml
web/admin/application/configs/klear/model/ResidentialClients.yaml
web/admin/application/configs/klear/model/RetailClients.yaml
web/admin/application/configs/klear/model/WholesaleClients.yaml

This PR includes the configuration to filter timezone fields based on selected country in the same screen. This can only be applied in Client's screens because the rest of screens with timezone does not include a country field.

web/admin: filter timezone based on selected country

---

schema/app/DoctrineMigrations/Version20190912161620.php

Update brandId field in Adminsitrators table. This PR will only update Oasis migrated rows and shouldn't have any effect in datasets created in Artemis.

schema: update migrated Administrators brandid

---

web/admin/application/configs/klear/ExternalCallFiltersResidentialList.yaml
web/admin/application/configs/klear/model/ExternalCallFiltersResidential.yaml

Enable the country listbox in Residential External Call filter screens. Previously only the number input was enabled making impossible to convert the destination to E.164

web/admin: country code in residential external filter screens

---

web/admin/application/configs/klear/CompaniesList.yaml
web/admin/application/configs/klear/ResidentialClientsList.yaml
web/admin/application/configs/klear/RetailClientsList.yaml
web/admin/application/configs/klear/model/Companies.yaml
web/admin/application/configs/klear/model/ResidentialClients.yaml
web/admin/application/configs/klear/model/RetailClients.yaml
web/admin/application/library/IvozProvider/Klear/Filter/OutgoingDDI.php
web/admin/application/library/IvozProvider/Klear/Ghost/Companies.php

Fixed outgoing ddi filter on list screens. It was applying no filters and leading to out of memory exception when DDIs dataset was big enough (> 15000).

web/admin: filter outgoing ddis by brand on list screens

---

kamailio/trunks/config/kamailio.cfg
library/Ivoz/Cgr/Domain/Model/TpDerivedCharger/TpDerivedChargerAbstract.php
library/Ivoz/Cgr/Domain/Model/TpDerivedCharger/TpDerivedChargerDtoAbstract.php
library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpDerivedCharger.TpDerivedChargerAbstract.orm.yml
schema/app/DoctrineMigrations/Version20190919120015.php

Currently CGRateS inserts 3 entries per call:
- *raw
- *default
- carrier
This last entry is inserted even if selected carrier has calculateCost disabled. This generates lots of error log messages and makes tp_cdrs heavier than it should be.
This PR needs cgr-engine to be upgraded with irontec/cgrates@4de71ee0f00adb15bfbf92be98705cf7bdfe0898 changes and reloading database info with cgr-loader command.

cgrates: do not generate carrier CDRs unless calculateCost is enabled

---

library/Ivoz/Kam/Domain/Service/TrunksCdr/SetParsed.php
library/Ivoz/Provider/Domain/Service/BalanceMovement/CreateByCarrier.php
library/Ivoz/Provider/Domain/Service/BalanceMovement/CreateByCompany.php
library/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromTrunksCdr.php
library/Ivoz/Provider/Domain/Service/Brand/BrandLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/BrandService/UpdateByBrand.php
library/Ivoz/Provider/Domain/Service/CallCsvReport/CreateByScheduler.php
library/Ivoz/Provider/Domain/Service/CallCsvScheduler/SetExecutionError.php
library/Ivoz/Provider/Domain/Service/CallCsvScheduler/UpdateLastExecutionDate.php
library/Ivoz/Provider/Domain/Service/Carrier/AbstractBalanceOperation.php
library/Ivoz/Provider/Domain/Service/Company/AbstractBalanceOperation.php
library/Ivoz/Provider/Domain/Service/FixedCostsRelInvoice/CreateByScheduler.php
library/Ivoz/Provider/Domain/Service/Invoice/CreateByScheduler.php
library/Ivoz/Provider/Domain/Service/InvoiceScheduler/SetExecutionError.php
library/Ivoz/Provider/Domain/Service/InvoiceScheduler/UpdateLastExecutionDate.php
library/Ivoz/Provider/Domain/Service/TransformationRule/GenerateRules.php
library/Ivoz/Provider/Domain/Service/TransformationRuleSet/DisableGenerateRules.php
library/spec/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromTrunksCdrSpec.php
library/spec/Ivoz/Provider/Domain/Service/BrandService/UpdateByBrandSpec.php
library/spec/Ivoz/Provider/Domain/Service/CallCsvReport/CreateBySchedulerSpec.php
library/spec/Ivoz/Provider/Domain/Service/Carrier/DecrementBalanceSpec.php
library/spec/Ivoz/Provider/Domain/Service/Carrier/IncrementBalanceSpec.php
library/spec/Ivoz/Provider/Domain/Service/Company/DecrementBalanceSpec.php
library/spec/Ivoz/Provider/Domain/Service/Company/IncrementBalanceSpec.php
library/spec/Ivoz/Provider/Domain/Service/Invoice/CreateBySchedulerSpec.php
library/spec/Ivoz/Provider/Domain/Service/TransformationRule/GenerateRulesSpec.php

Slit services so that there are no persist operations out of their entity service folder

Service split

---

schema/app/DoctrineMigrations/Version20191008111715.php

Artemis uses E.164 with plus, while Oasis used E.164 without plus, so regular expressions in patterns (Call ACLs and Match Lists) require some adaptation.

schema: update migrated MatchListPatterns regular expressions

---

debian/ivozprovider-profile-portal.templates

Added Italian and Catalan languages to portals profile menu  default language

pkg: add italian and catalan to install screens

---

README.md

This only removes 32 bits iso link in the README, but also implies removing all support in jenkins and packages to this architecture. 
Additionally it addresses the problem with rtpengine and linux-image-amd64 virtual package described in #606

pkg: remove 32 bits packages support

---

kamailio/trunks/config/kamailio.cfg

Introduce _cgrates_mode_ runtime parameter that replaces _allow_calls_without_cgrates_.
- allow_calls_without_cgrates:
Only applied when CGRateS was down:
* If set, calls were allowed.
* If not set, calls were declined (unless they were national).
- cgrates_mode:
Applies no matter CGRateS is down:
* If set, CGRateS is disabled for every call (equals to enabling externallyRated
for all carriers).
* If not set, CGRateS is asked for every call:
1. If it is up, CGRateS will allow/decline calls.
2. If it is down, only national calls are allowed.
The difference is that CGRateS is skipped no matter if it is up or down. National
calls continue being allowed in CGRateS down scenarios.

kamtrunks: cgrates_mode runtime parameter

---

asterisk/agi/src/Agi/Action/FaxReceiveStatusAction.php
asterisk/agi/src/Voicemail/Sender.php
doc/sphinx/administration_portal/brand/settings/notification_templates.rst
doc/sphinx/administration_portal/platform/brands.rst
doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po
library/Ivoz/Provider/Domain/Model/Brand/BrandAbstract.php
library/Ivoz/Provider/Domain/Model/Brand/BrandDtoAbstract.php
library/Ivoz/Provider/Domain/Model/Brand/BrandInterface.php
library/Ivoz/Provider/Domain/Service/Invoice/EmailSender.php
library/Ivoz/Provider/Domain/Service/NotificationTemplateContent/CallCsvNotificationTemplateByCallCsvReport.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Brand.BrandAbstract.orm.yml
library/spec/Ivoz/Provider/Domain/Service/NotificationTemplateContent/CallCsvNotificationTemplateByCallCsvReportSpec.php
schema/app/DoctrineMigrations/Version20191017111612.php
web/admin/application/configs/klear/BrandsList.yaml
web/admin/application/configs/klear/model/Brands.yaml
web/admin/application/library/IvozProvider/Klear/Filter/Brand.php

Add four new Brand fields to configure Clients notifications templates default values. If company has no template configured for a given notification, it will use the brand one. If brand has no template configured for a given notification, it will use the generic one.

Brand notification templates

---

library/Ivoz/Core/Infrastructure/Symfony/DependencyInjection/Compiler/DomainServiceCompiler.php

Made service_collection aliases public so that DoctrineEventSubscriber does not trigger warnings

core: removed deprecation warning

---

library/Ivoz/Core/Infrastructure/Domain/Service/Lifecycle/CommandPersister.php
library/Ivoz/Provider/Domain/Model/Terminal/Terminal.php

Don't register terminal.lastProvisionDate changes on changelog

Improved changelog

---

library/CoreBundle/Resources/config/logger.yml
library/Ivoz/Core/Application/Service/EntityTools.php
library/Ivoz/Provider/Domain/Service/BillableCall/MigrateFromUnparsedTrunksCdr.php

Do not clear Commands from unit of work unit cdr mixer is done

core: keep Commands in memory through cdr mixer loops

---

library/DataFixtures/ORM/KamUsersCdr.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.yml
schema/app/DoctrineMigrations/Version20191021113146.php
schema/tests/Kam/UsersCdr/UsersCdrRepositoryTest.php

This PR avoids duplicate entries in kam_users_cdrs that may happen if database connection is lagged.

schema: avoid duplicate entries in userCdrs

---

doc/sphinx/administration_portal/brand/routing/outgoing_routings.rst
doc/sphinx/locale/es/LC_MESSAGES/administration_portal.po
kamailio/trunks/config/kamailio.cfg
library/Ivoz/Kam/Domain/Service/TrunksLcrRuleTarget/TrunksLcrRuleTargetFactory.php
library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRouting.php
library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingAbstract.php
library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/OutgoingRouting.OutgoingRoutingAbstract.orm.yml
schema/app/DoctrineMigrations/Version20191021131531.php
web/admin/application/configs/klear/OutgoingRoutingList.yaml
web/admin/application/configs/klear/model/OutgoingRouting.yaml
web/admin/application/languages/ca_ES/ca_ES.po
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/languages/it_IT/it_IT.po
web/admin/application/library/IvozProvider/Klear/Filter/OutgoingRoutingMode.php
web/admin/application/library/IvozProvider/Klear/Ghost/OutgoingRouting.php

Add **Block routes** concept to _Outgoing Routings_.
They are evaluated first (because they are enforced to have 0 priority) and make it easy to block wanted prefixed for all clients with a unique blocking route.

Add block routes to Outgoing Routings

---

schema/composer.json
schema/composer.lock

Moved beberlei/assert schema dependecy from dev to all that LoggableMigrations do not end on error

core: fixed schema dependecy for LoggableMigrations

---

library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallDto.php
web/rest/brand/features/provider/billableCalls/putBillableCalls.feature
web/rest/brand/src/Controller/Provider/PutBillableCallRatingAction.php
web/rest/platform/features/provider/billableCalls/putBillableCalls.feature
web/rest/platform/src/Controller/Provider/PutBillableCallRatingAction.php

Allow to set cost on /billable_calls/callid/rate API endpoint

Api expose cost on billable calls rate

---

schema/app/DoctrineMigrations/Version20190618171752.php

This PR updates delta generated in e590fdf688694fa30c9ef83df271d48fbc35fef3 to avoid integrity errors while creating the unique index.
This PR addresses one of the problems reported in #1141

scheme: delete duplicates before trunks cdr unique callid index

---

web/admin/application/configs/klear/CompaniesList.yaml
web/admin/application/configs/klear/CompanyBalancesList.yaml
web/admin/application/configs/klear/CurrentdayUsageList.yaml
web/admin/application/configs/klear/ResidentialClientsList.yaml
web/admin/application/configs/klear/RetailClientsList.yaml
web/admin/application/configs/klear/WholesaleClientsList.yaml
web/admin/application/configs/klear/model/Companies.yaml
web/admin/application/configs/klear/model/ResidentialClients.yaml
web/admin/application/configs/klear/model/RetailClients.yaml
web/admin/application/configs/klear/model/WholesaleClients.yaml
web/admin/application/languages/ca_ES/ca_ES.po
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/languages/it_IT/it_IT.po

Display Externally Rater custom options field in edit screens for vPBX/residential/retail/wholesale clientes.

web/admin: recover Externally rater custom options

---

schema/app/DoctrineMigrations/Version20191114115328.php
web/admin/application/configs/klear/DefaultInvoiceTemplatesList.yaml

This PR include two commits that addresses following bugs:
- Administration portal default Invoice templates was assigned to emulated brand after being edited
- Migrated Invoice Templates from 1.x didn't show Brand Invoice related data

Invoice templates fixes

---

kamailio/trunks/config/kamailio.cfg
schema/app/DoctrineMigrations/Version20191115154014.php

- Prevent malformed Diversion header for Wholesale clients (as they don't have any domain).
- Ensure Company.domainId is correctly set for retail/residential clients (mostly for Oasis->Artemis migrations).

Fix company domain

---

web/admin/application/languages/ca_ES/ca_ES.po
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/languages/it_IT/it_IT.po

KamAccCdrsBrand.yaml removal in 6d98d6287745869640e5d1876f376c0397a14b69 broke translations tests.
This PR aims to fix it.

i18n: fix translations after unused model removal

---

library/Ivoz/Provider/Domain/Service/TerminalModel/PersistTemplates.php
library/spec/Ivoz/Provider/Domain/Service/TerminalModel/PersistTemplatesSpec.php

When a Terminal Model provisioning template is saved, the current template is renamed appending a .back to the file. If a file already exists with that name, an error raises because `rename()` is not able to overwrite files.
Following commit deletes the backup file before renaming current to .back, preventing the error.

core: fix terminal model template backup overwrite

---

asterisk/agi/composer.lock
library/composer.lock
microservices/balances/composer.lock
microservices/recordings/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/composer.json
schema/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock

Fixes some vulnerabilities 
- https://github.com/advisories/GHSA-xhh6-956q-4q69
- https://github.com/advisories/GHSA-79gr-58r3-pwm3

core: bump symfony/symfony from 3.4.32 to 3.4.36

---

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php

Call that should have price where guessed looking at _carrierId_ field. As incoming calls tarification is no longer supported, this PR stops looking at _carrierId_ and looks at outbound direction calls only.

core: filter billable calls with direction instead of carrierId

---

library/Ivoz/Provider/Domain/Service/TransformationRule/GenerateInRules.php
library/spec/Ivoz/Provider/Domain/Service/TransformationRule/GenerateInRulesSpec.php
schema/app/DoctrineMigrations/Version20191127124853.php
web/admin/application/configs/klear/TransformationRulesList.yaml

Calling in E.164 without + as national format caused transformations problems:
e.g. 34945945945 instead of 945945945 lead to +3434945945945
Current rules assumed that caller uses agreed formats, but some didn't. This new rules are more flexible.
This PR changes both rules generators and predefined existing rules.

Allow E.164 without plus as inbound number format

---

doc/sphinx/administration_portal/client/residential/calls/call_registry.rst
doc/sphinx/administration_portal/client/residential/calls/index.rst
doc/sphinx/administration_portal/client/retail/calls/call_registry.rst
doc/sphinx/administration_portal/client/retail/calls/index.rst
web/admin/application/configs/klear/klear.yaml

_kam_users_cdrs_ stores client side CDRs. For wholesale, retail and residential clients this information is nearly redundant with that in _kam_trunks_cdrs_, as they have no internal call concept.
This PR hides just hide _Call Registries_ web sections. An upcoming PR will avoid this information being stored at all.

web/admin: hide call registry for non vpbx

---

library/Ivoz/Provider/Domain/Model/CalendarPeriod/CalendarPeriod.php
library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilter.php
library/Ivoz/Provider/Domain/Model/Schedule/Schedule.php
library/Ivoz/Provider/Domain/Model/Schedule/ScheduleInterface.php
library/spec/Ivoz/Provider/Domain/Model/Schedule/ScheduleSpec.php

Refactor Schedule checks to use a single function that uses client timezone for comparisons.

core: use client timezone in schedule checks

---

library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/ProcessExternalCdr.php
library/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/ReloadService.php
library/Ivoz/Kam/Domain/Service/TrunksClientInterface.php
library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php
library/Ivoz/Provider/Domain/Service/Invoice/AutoRateCalls.php
library/spec/Ivoz/Core/Infrastructure/Domain/Service/Cgrates/ProcessExternalCdrSpec.php

cgrates_mode introduced in #1153 skip CGRateS from being called in KamTrunks. This PR gets that parameters value in order to skip CGRateS calls also in invoicer and cdr-mixer.

core: skip cgrates calls on cdrmixer/invoicer if cgrates_mode is 1

---

library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvScheduler.php
library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerInterface.php
library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceScheduler.php
library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerInterface.php
library/Ivoz/Provider/Domain/Service/InvoiceScheduler/NextExecutionResolverTrait.php
library/spec/Ivoz/Provider/Domain/Service/CallCsvScheduler/NextExecutionResolverSpec.php
library/spec/Ivoz/Provider/Domain/Service/InvoiceScheduler/NextExecutionResolverSpec.php

This PR aims to fix daily scheduler issues on daylight saving time changes. 
Some scenarios cannot be avoided, for instance Europe/Madrid 2020-03-29 02:00:00 does not exist: 2020-03-28 02:00:00 will turn into 2020-03-29 03:00:00.

Scheduler dst bug

---

asterisk/agi/src/Agi/Action/DdiAction.php
asterisk/agi/src/Agi/Action/RetailCallAction.php
asterisk/agi/src/Agi/Action/RouterAction.php
asterisk/config/dialplan/default.conf
doc/sphinx/administration_portal/client/retail/retail_accounts.rst
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
web/admin/application/configs/klear/RetailAccountsList.yaml
web/admin/application/library/IvozProvider/Klear/Options/OptionsCustomizer.php

2 changes here:
- If matching DDI belongs to a retail client but is not pointing to any retail
account, drop call.
- If points to a retail account in T.38 mode, route to AS. Otherwise, route
to KamUsers directly.

kamtrunks: handle incoming calls to T.38 retail accounts

---

asterisk/agi/src/Agi/Action/DdiAction.php
library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilter.php

When multiple calendars are selected in a single ExternalCallFilter,
the logic should loop searching a calendar period in all of them,
but instead it only looks for calendar periods in the first calendar.

agis: fix CalendarPeriod checking in ExternalCallFilter

---

asterisk/agi/src/Dialplan/Headers.php
asterisk/agi/src/Dialplan/Residentials.php
kamailio/trunks/config/kamailio.cfg
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrAbstract.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrDtoAbstract.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrInterface.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksCdr.TrunksCdrAbstract.orm.yml
library/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateByTrunksCdr.php
schema/app/DoctrineMigrations/Version20191220152436.php

#737 transported _retailAccountId_ to _kam_trunks_cdrs_ table. This PR does the same with _residentialDeviceId_.
_kam_trunks_cdrs.residentialDeviceId_ is exported to _BillableCalls_ in _endpointType_ and _endpointId_ fields.

CDRs: transport residentialDeviceId to kam_trunks_cdrs

---

asterisk/agi/src/Dialplan/Headers.php
asterisk/agi/src/Dialplan/Retails.php
kamailio/trunks/config/kamailio.cfg

T.38 retail account outbound calls traverse Application Servers. In this traverse retailAccountId was lost.
This PR sets X-Info-RetailAccountId as KamUsers does for non-T.38 retail accounts.

Set retailAccountId for T.38 retail outbound calls

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

* 17937dfb7 - (HEAD -> kam-multiple-changes, origin/kam-multiple-changes, bleeding) kam: grab and store X-Call-Id if present 80 seconds ago ccruz
* e98d52faf - kam: skip mediarelay only when necessary 16 minutes ago ccruz
* a0da83b3b - kamusers: set To equal to R-URI in DDI_IN feature 4 hours ago ccruz
* 507410bea - kamusers: not consider friend value starting with + as internal 4 hours ago ccruz
4 unrelated Kamailio minor changes:
- Not consider friend value starting with + as internal so that it gets transformed properly.
- Set To username equal to R-URI username in DDI_IN feature.
- Avoid media relay skip for T.38 retail calls.
- Grab and store X-Call-Id if present.
- Make cidhash calculation logic equal between both proxies.

kam: multiple minor changes

---

kamailio/users/config/kamailio.cfg

Call waiting feature limits received simultaneous calls.
Currently, it only counts received calls.
After this commit, it will count both generated and received calls. It will
continue blocking just received calls when configured limit is reached.

kamusers: count outgoing calls in call waiting feature

---

asterisk/agi/composer.lock
library/Ivoz/Cgr/Domain/Service/CgratesReloadNotificator.php
library/Ivoz/Cgr/Domain/Service/TpAccountAction/CreateByCompany.php
library/Ivoz/Cgr/Domain/Service/TpDestination/UpdatedTpDestinationNotificator.php
library/Ivoz/Provider/Domain/Service/Company/CompanyLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/Company/SendCgratesUpdateRequest.php
library/composer.lock
library/spec/Ivoz/Provider/Domain/Service/Company/SendCgratesUpdateRequestSpec.php
microservices/balances/composer.lock
microservices/recordings/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
microservices/workers/src/Worker/Cgrates.php
schema/app/DoctrineMigrations/Version20200109172609.php
schema/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock

_tp_action_triggers_ was introduced in #1166 with a row per brand with 1000000 default threshold. This threshold was overridden using cgrates API with wanted value per Client.
This runtime threshold are lost when CGRateS tariff plans are reloaded for some accounts (those with no BalanceMap).
This PR changes _tp_action_triggers_ so that is has one entry per client with wanted threshold.
**Pending:**

Solve maxDailyUsage threshold override

---

library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping/TpCdr.TpCdrAbstract.orm.yml
schema/app/DoctrineMigrations/Version20200113155612.php

Add an index into tp_cdrs.answer_time so that it can be rotated

schema: added index into tp_cdrs.answer_time

---

web/rest/brand/app/config/api/raw/kam.yml
web/rest/brand/features/kam/usersCdr/getUsersCdrs.feature
web/rest/brand/features/kam/usersCdr/postUsersCdrs.feature
web/rest/brand/features/kam/usersCdr/putUsersCdrs.feature
web/rest/brand/features/kam/usersCdr/removeUsersCdrs.feature
web/rest/brand/tests/DataAccessControl/Kam/UsersAddressTest.php
web/rest/brand/tests/DataAccessControl/Kam/UsersCdrTest.php

Allow GET operations only on users cdr

Restrict user cdrs api methods

---

library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrAbstract.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrInterface.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrAbstract.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrInterface.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksCdr.TrunksCdrAbstract.orm.yml
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.yml
library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallAbstract.php
library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.yml
schema/app/DoctrineMigrations/Version20200113080213.php

Removing on cascade billable calls and trunks/users cdrs when a company/brand is deleted may cause high database load. Remove them asynchronously instead.

No cascade delete on calls

---

library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallRepository.php
library/Ivoz/Provider/Domain/Model/Invoice/Invoice.php
library/Ivoz/Provider/Domain/Model/Invoice/InvoiceInterface.php
library/Ivoz/Provider/Domain/Service/Invoice/AutoRateCalls.php
library/Ivoz/Provider/Domain/Service/Invoice/CheckValidity.php
library/Ivoz/Provider/Domain/Service/Invoice/Generator.php
library/Ivoz/Provider/Domain/Service/Invoice/SendGenerateOrder.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php
library/spec/Ivoz/Provider/Domain/Service/Invoice/CheckValiditySpec.php
library/spec/Ivoz/Provider/Domain/Service/Invoice/SendGenerateOrderSpec.php
schema/tests/Provider/BillableCall/BillableCallRepositoryTest.php
schema/tests/Provider/Invoice/InvoiceLifeCycleTest.php

Unify criteria between invoice validation and generation steps 
Move BillableCall where conditions into the repository
Prevent invoice validity checks to be run on every change

Unified billable call repo criteria

---

microservices/workers/src/Worker/Rates.php

Restores logic implemented in 3027797 and deleted in 0120f85

microservices: recover disableDestination logic

---

web/rest/brand/app/config/api/raw/kam.yml

Set /api/brand/users_cdrs as deprecated

rest: added deprecation warning on /api/brand/users_cdrs

---

library/composer.lock
schema/app/AppKernel.php
schema/app/config/services.yml
schema/composer.lock

Updated irontec/ivoz-dev-tools to v2.4 and registered MigrationsBundle so that migrations use LoggableMigration by default

Customized doctrine:migrations:diff

---

kamailio/trunks/config/kamailio.cfg
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php

7c8b3ef introduced parsed handling in cfg for special numbers.
This PR forces 0 as default value directly in kamailio.cfg. Without this, NULL was inserted for inbound calls, causing not being parsed by the cdr-mixer.
Changes introduced in 58cb8d204 are no longer needed.

kamtrunks: 0 as default value for trunksCdr.parsed

---

library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByFriend.php
schema/app/DoctrineMigrations/Version20200127120901.php

Directmedia in friends call may cause no audio issues if SIP endpoint on the other side does not handle media liberation correctly.
This PR disables direcmedia for every friend to prevent these problems.

Friends disable directmedia

---

library/Ivoz/Provider/Domain/Model/Invoice/Invoice.php
library/Ivoz/Provider/Domain/Model/Invoice/InvoiceInterface.php
library/Ivoz/Provider/Domain/Service/Invoice/SetInvoiceNumber.php
library/spec/Ivoz/Provider/Domain/Service/Invoice/SetInvoiceNumberSpec.php
microservices/workers/src/Worker/Invoices.php

Do not set it on workers as they run in parallel and causes unique key (brand, number) issues

core: invoice number sequence error prevention

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

3 minor fixes here:
- KamTrunks dropped calls if X-Call-Id was missing. This is not done anymore, as has no effect in call establishment.
- KamTrunks parsed X-Info-Special header for fax route detection. Retails calls can also contain this header now (since T.38 passthrough was added).
- KamUsers IS_INTERNAL detected wrong internal numbers in some call bouncing scenarios due to XAVP inheritance. This PR empties XAVPs to avoid this situation.

Kam: minor fixes

---

debian/ivozprovider-profile-common.postinst
debian/ivozprovider-schema.postinst
doc/dev/en/storage.md

Two changes in postinstall scripts:
- Apply doctrine migrations without quietness.
- Do not execute recursive chmod on storage.

pkg: changes on postinstall scripts

---

library/Ivoz/Cgr/Domain/Service/TpDestination/CreatedByDestination.php
library/Ivoz/Cgr/Domain/Service/TpDestinationRate/UpdatedByDestinationRate.php
library/Ivoz/Cgr/Domain/Service/TpRate/UpdatedByDestinationRate.php
library/Ivoz/Kam/Domain/Service/TrunksAddress/UpdateByDdiProviderAddress.php
library/Ivoz/Kam/Domain/Service/TrunksLcrGateway/UpdateByCarrierServer.php
library/spec/Ivoz/Cgr/Domain/Service/TpDestination/CreatedByDestinationSpec.php
library/spec/Ivoz/Cgr/Domain/Service/TpDestinationRate/UpdatedByDestinationRateSpec.php
library/spec/Ivoz/Cgr/Domain/Service/TpRate/UpdatedByDestinationRateSpec.php
library/spec/Ivoz/Kam/Domain/Service/TrunksLcrGateway/UpdateByCarrierServerSpec.php

Replace entity direct setters on services by dtos

Do not use entity setter on services

---

asterisk/agi/composer.lock
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.yml
library/composer-packages/irontec/ivoz-provider-bundle/ProviderBundle.php
library/composer.json
library/composer.lock
microservices/balances/composer.lock
microservices/recordings/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/app/config/config.yml
schema/composer.lock
web/rest/brand/app/config/security.yml
web/rest/brand/composer.lock
web/rest/client/app/config/api/raw/kam.yml
web/rest/client/app/config/security.yml
web/rest/client/composer.lock
web/rest/platform/app/config/security.yml
web/rest/platform/composer.lock

Removed symfony deprecation warnings below: 
- Silent handling of duplicate mapping keys in YAML is deprecated since Symfony 3.2 and will throw \Symfony\Component\Yaml\Exception\ParseException in 4.0
- Bundle inheritance is deprecated since Symfony 3.4 and will be removed in 4.0
- The stub.prophet service is private
- User Deprecated: Auto-registration of the command

core: removed duplicated settings

---

web/admin/application/library/IvozProvider/Klear/Filter/CompanyServices.php

d877740 introduced a logic to hide non-vpbx services to vpbx clients. This logic was broken.
This PR aims to fix it.

web/admin: fix vpbx service selector filter

---

kamailio/trunks/config/kamailio.cfg

Gateways selected by stopper routes should not be inactivated to avoid this route from being skipped in next calls.

kamtrunks: do not inactivate stopper route carriers

---

web/admin/application/configs/klear/model/Companies.yaml
web/admin/application/configs/klear/model/ResidentialClients.yaml
web/admin/application/languages/ca_ES/ca_ES.po
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/languages/it_IT/it_IT.po

Fix labels so that "DTMFs" turns into "Both SIP INFO + DTMFs"

On-demand record DTMFs supports both SIP INFO and DTMFs

---

doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends/index.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends/internal_friends.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends/remote_friends.rst
kamailio/users/config/kamailio.cfg
library/Ivoz/Provider/Domain/Model/Friend/Friend.php
schema/DoctrineMigrations/Version20200220142749.php
web/admin/application/configs/klear/FriendsList.yaml
web/admin/application/library/IvozProvider/Klear/Options/OptionsCustomizer.php

Regexps linked to Friends let IvozProvider know who is in the other side. This is not necessary for intervpbx friends, as that other side is another IvozProvider client.
This PR adds the logic to make intervpbx regexps not necessary.

Friends intervpbx need no regexp

---

asterisk/agi/config/services.yml
asterisk/agi/src/Agi/Action/HuntGroupAction.php
asterisk/agi/src/Agi/Action/HuntGroupCallAction.php
asterisk/agi/src/Agi/Action/HuntGroupStatusAction.php
asterisk/agi/src/Dialplan/HuntGroupMember.php
asterisk/agi/src/Dialplan/HuntGroups.php
asterisk/agi/src/MicroKernel.php
asterisk/config/dialplan/default.conf
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/hunt_groups.rst
library/DataFixtures/ORM/ProviderHuntGroupsRelUser.php
library/Ivoz/Provider/Domain/Model/HuntGroupsRelUser/HuntGroupsRelUser.php
library/Ivoz/Provider/Domain/Model/HuntGroupsRelUser/HuntGroupsRelUserAbstract.php
library/Ivoz/Provider/Domain/Model/HuntGroupsRelUser/HuntGroupsRelUserDto.php
library/Ivoz/Provider/Domain/Model/HuntGroupsRelUser/HuntGroupsRelUserDtoAbstract.php
library/Ivoz/Provider/Domain/Model/HuntGroupsRelUser/HuntGroupsRelUserInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/HuntGroupsRelUser.HuntGroupsRelUserAbstract.orm.yml
library/spec/Ivoz/Provider/Domain/Model/HuntGroupsRelUser/HuntGroupsRelUserSpec.php
schema/DoctrineMigrations/Version20200220113025.php
web/admin/application/configs/klear/HuntGroupsList.yaml
web/admin/application/configs/klear/HuntGroupsRelUsersList.yaml
web/admin/application/configs/klear/model/HuntGroupsRelUsers.yaml
web/admin/application/languages/ca_ES/ca_ES.po
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/languages/it_IT/it_IT.po
web/admin/application/library/IvozProvider/Klear/Filter/HuntGroupsRelUsers.php
web/rest/client/features/provider/huntGroupsRelUser/getHuntGroupsRelUser.feature
web/rest/client/features/provider/huntGroupsRelUser/postHuntGroupsRelUser.feature
web/rest/client/features/provider/huntGroupsRelUser/putHuntGroupsRelUser.feature

This PR adds support for external numbers in all HuntGroups types.
Instead of dialing huntgroup endpoints, a new dialplan context has been created to handle each huntgroup entry individually, now routed like the other entities based on its route type field.
This implies that calls from Huntgroups to Users are now handled in the same way Extension to Users calls are handled. Same applies for external numbers.

Huntgroup external numbers

---

doc/sphinx/administration_portal/brand/billing/current_day_usages.rst
web/admin/application/configs/klear/model/Companies.yaml
web/admin/application/library/IvozProvider/Klear/Ghost/Companies.php

MaxDailyUsage has a runtime value (obtained asking to CGRateS) and a database value (Companies.maxDailyUsage) that should be equal.
_Current Day Usage_ shows runtime value. This PR shows this value in red if database value is different.

web/admin: show red if runtime MaxDailyUsage is not equal to database value

---

asterisk/agi/src/Agi/Action/ExternalFaxCallAction.php
asterisk/agi/src/Dialplan/Friends.php
asterisk/agi/src/Dialplan/Headers.php
asterisk/agi/src/Dialplan/Users.php
kamailio/trunks/config/kamailio.cfg
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrAbstract.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrDtoAbstract.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrInterface.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksCdr.TrunksCdrAbstract.orm.yml
library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallAbstract.php
library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallInterface.php
library/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateByTrunksCdr.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.yml
schema/DoctrineMigrations/Version20200221112255.php

Propagate to _kam_trunks_cdrs_:
- userId
- friendId
- faxId
**Just for outgoing calls**.
Propagate this new fields for new external outgoing call to:
- BillableCalls.endpointType:
- User
- Friend
- Fax
- BillableCalls.endpointId
**IMPORTANT NOTE**: Just for **outgoing** external calls. In inbound calls KamTrunks does not know who is going to answer the call.

Propagate client side endpoint to trunks cdrs for outbound calls

---

web/rest/brand/config/api/raw/provider.yml
web/rest/brand/features/provider/callCsvReport/putCallCsvReport.feature
web/rest/brand/tests/DataAccessControl/Provider/CallCsvReportTest.php
web/rest/client/config/api/raw/provider.yml
web/rest/client/features/provider/callCsvReport/putCallCsvReport.feature
web/rest/client/tests/DataAccessControl/Provider/CallCsvReportTest.php

Remove PUT operation on CallCsvReports from client API.

Dont allow updates on call csv reports

---

kamailio/users/config/kamailio.cfg

- [] Small bug fix
Increase KamUsers TCP max connections from 2048 (default value) to 8192.

kamusers: increase TCP max conns

---

library/DataFixtures/FixtureHelperTrait.php
library/DataFixtures/ORM/ProviderCallCsvReport.php
library/DataFixtures/ORM/ProviderDestinationRateGroup.php
library/DataFixtures/ORM/ProviderFaxesInOut.php
library/Ivoz/Provider/Domain/Model/InvoiceTemplate/InvoiceTemplate.php
library/Ivoz/Provider/Domain/Model/InvoiceTemplate/InvoiceTemplateDto.php
library/Ivoz/Provider/Domain/Model/NotificationTemplate/NotificationTemplate.php
library/Ivoz/Provider/Domain/Model/SpecialNumber/SpecialNumber.php
library/Ivoz/Provider/Domain/Model/SpecialNumber/SpecialNumberDto.php
web/rest/brand/features/provider/invoiceTemplate/getInvoiceTemplate.feature
web/rest/brand/features/provider/invoiceTemplate/postInvoiceTemplate.feature
web/rest/brand/features/provider/invoiceTemplate/putInvoiceTemplate.feature
web/rest/brand/features/provider/specialNumber/getSpecialNumber.feature
web/rest/brand/features/provider/specialNumber/postSpecialNumber.feature
web/rest/brand/features/provider/specialNumber/putSpecialNumber.feature

Fixed security checks so that a global record is not turned into a brand one on:
- SpecialNumber
- NotificationTemplate
- InvoiceTemplate

Brand API: forbidden global record updates

---

asterisk/agi/composer.lock
library/composer.json
library/composer.lock
microservices/balances/composer.lock
microservices/recordings/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/composer.lock
web/rest/brand/composer.lock
web/rest/brand/config/api_platform.yml
web/rest/brand/features/provider/country/getCountry.feature
web/rest/brand/features/provider/timezone/getTimezone.feature
web/rest/client/composer.lock
web/rest/client/config/api_platform.yml
web/rest/client/features/provider/country/getCountry.feature
web/rest/client/features/provider/ratingPlanGroup/getPrices.feature
web/rest/client/features/provider/timezone/getTimezone.feature
web/rest/platform/composer.lock
web/rest/platform/config/api_platform.yml
web/rest/platform/features/pagination.feature
web/rest/platform/features/provider/billableCalls/getBillableCalls.feature
web/rest/platform/features/provider/country/getCountry.feature
web/rest/platform/features/provider/timezone/getTimezone.feature

Optimized memory usage on unpaginated API requests. Current memory usage on BillableCalls:
- CSV
- 500 result => 11.84 mb
- 5k => 43.42 mb
- 10k => 77.93 mb
- Unpaginated (60k) => 30.66 mb (35.15 mb before this PR)
- JSON
- 500 result => 12.16 mb
- 5k => 40.04 mb
- 10k => 71.09 mb
- Unpaginated (60k) => 27.96 mb (75.57 mb before this PR)
Maximun items per page have been increased from 500 to 5k on client API and from 500 to 10k on brand and platform APIs.
updated ivoz dependencies:
- https://github.com/irontec/ivoz-api/commits/2.4.2
- https://github.com/irontec/ivoz-api-bundle/commits/3.2.1
- https://github.com/irontec/ivoz-core/commits/2.3.7

Improved API memory usage

---

asterisk/agi/composer.json
asterisk/agi/composer.lock
library/composer-packages/irontec/ivoz-provider-bundle/composer.json
library/composer.lock
microservices/balances/composer.json
microservices/balances/composer.lock
microservices/recordings/composer.json
microservices/recordings/composer.lock
microservices/scheduler/composer.json
microservices/scheduler/composer.lock
microservices/workers/composer.json
microservices/workers/composer.lock
schema/composer.json
schema/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.json
web/rest/platform/composer.lock

symfony/symfony composer dependecy was removed in https://github.com/irontec/ivozprovider/commit/8a7c3fbcf7a6800cb2fa3b5e97954dc7fea374f9 but there were still some references in composer.lock files.
That was making improsible to add new apps to the project

Fixed dependencies

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

This PR saves into Redis dialog status realtime information.
Both proxies generate events related to dialog state machine explained [in RFC 4235](https://tools.ietf.org/html/rfc4235#section-3.7.1)
KamUsers has a special event to handle caller updates via 200 (in call diversions) or within dialog UPDATE/INVITE request (for call transfers).

kamailio: save realtime information in Redis

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

- Get companyName and brandName before using its values.
- No functional change as those fields are not used in KamUsers.
- Set ownerName for wholesale calls.
- Fixes empty _Owner_ column for wholesale realtime section.
- Fix empty _Party_ column for inbound calls in client realtime section.
- Show user extension in _Owner_ column for vPBX realtime section.

kam: fix empty Party in client realtime

---

kamailio/trunks/config/kamailio.cfg
library/Ivoz/Provider/Domain/Service/BillableCall/UpdateByTpCdr.php

Bounced calls are external outgoing calls to existing numbers in DDIs table. They are not delivered to any carrier, but carrier selection is made as if they were to make sure that an outgoing routing exist to place these calls.
Apart from that, even though carrier was not reached:
- _carrierId_ was set to selected carrier.
- Carrier balance was decremented.
- Call cost was calculated using that carrier's active pricing plan.
This PR changes this behaviour. From now on:
- _carrierId_ will be NULL for these calls (both in _kam_trunks_cdrs_ and _BillableCalls_ tables).
- No carrier balance will be decremented.
- Call cost will be set to 0.
This way:
- CDRs of specific carrier won't include bounced calls, as they are not delivered to any carrier.
- Call cost will be 0, as no price will be …

Bounced outgoing calls: zero cost and no carrierId

---

kamailio/users/config/kamailio.cfg

Improve wholesale detection to skip unwanted logic and handle possible misleading scenarios (e.g. non-wholesale clients using an IP address assigned to wholesale client).
In such cases, wholesale has precedence:
- Non-INVITE requests from that source address will be rejected.
- Calls will be handled as wholesale calls.

kamusers: improve wholesale logic

---

asterisk/agi/src/Agi/Action/UserCallAction.php

When users are called from HuntGroups, CallForwardSettings may be enabled or disabled based on HuntGroup configuration.
For this last case, the noAnswer timeout was being configured in the final call to the user, even if allowCallForwards are disabled.
This PR fixes that problem by removing call timeout when CallForwards are not allowed.

agis: ignore user call timeout when call forwards are disabled

---

asterisk/agi/src/Agi/Action/CallForwardAction.php
asterisk/agi/src/Dialplan/Users.php
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdr.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrAbstract.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrInterface.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksCdr.TrunksCdrAbstract.orm.yml
library/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateByTrunksCdr.php
schema/DoctrineMigrations/Version20200513164526.php

- Avoid undesired Diversion related requests in KamUsers.
- Diversion headers with no PAI/RPID are dropped.
- Ensure _X-Info-DdiId_ is correctly set in retail calls.
- Drop outbound non-wholesale calls with no _X-Info-DdiId_ header.
- _BillableCalls.caller_ is now set using _kam_trunks_cdrs.ddiId_ for outbound calls (instead of  _kam_trunks_cdrs.diversion_).
- This way it is always a DDI belonging to a client (except for wholesale clients).
- Fix AGI userId/residentialDeviceId bug for web call-forwards.
- Calls to your extension will never add a Diversion header (even if your terminal has a call forward).
- Calling to your forwarded extension will be equal to calling to call forward target.

Diversion related minor improvements

---

library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvScheduler.php
library/Ivoz/Provider/Domain/Model/Invoice/Invoice.php
library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceScheduler.php

Long errors messages were breaking entity updates

core: truncate entity error messages

---

asterisk/agi/src/Agi/Action/UserCallAction.php
asterisk/config/dialplan/default.conf

This PR updates UserCallAction to use a different context when call forwards are disabled. This prevents reaching UserStatus AGI when Dial is not answered.

agis: do not enter UserStatus when Call forwards are disabled

---

doc/sphinx/administration_portal/brand/providers/carriers.rst
library/Ivoz/Kam/Domain/Service/TrunksClientInterface.php
library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php
web/admin/application/configs/klear/CarrierServersList.yaml
web/admin/application/configs/klear/CarriersList.yaml
web/admin/application/configs/klear/model/CarrierServers.yaml
web/admin/application/configs/klear/model/Carriers.yaml
web/admin/application/library/IvozProvider/Klear/Ghost/CarrierServerStatus.php

Non-responding carrier servers are inactivated until they respond to OPTIONS ping request.
This PR adds this information to web portal:
- CarrierServers: green/red icon.
- Carriers: icon is green if every carrier server of given carrier are active, red if they are all inactive and yellow if just some of then are inactive.
This PR needs _lcr.dump_gws_ command being patched to retrieve just one gateway (see irontec/kamailio@e19074d7cc2da074ba123e9d28969d3d978f78ee)

web/admin: show carrier and carrier server status icon

---

debian/ivozprovider.postinst
doc/sphinx/administration_portal/brand/calls/call_csv_schedulers.rst
doc/sphinx/administration_portal/client/vpbx/calls/call_csv_schedulers.rst
doc/sphinx/administration_portal/platform/external_calls.rst
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Since #1305 outbound external calls have userId and friendId set in BillableCalls. But external inbound calls didn't, as KamTrunks does not know who is going to answer the call.
This PR uses Kamailio DMQ to send that information from KamUsers to KamTrunks for **vPBX external inbound calls**. userId and friendId will be set to **first interlocutor id**.
Inbound calls to DDIs routed to virtual fax will have _faxId_ set accordingly too.

kam: userId/friendId/faxId for inbound calls

---

doc/sphinx/security_and_maintenance/security/antiflooding.rst
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

- #1326 introduced antiflood banned address new section. This PR populates this section with KamTrunks antiflood blocked address.
- No antiflood for within-dialog requests.

kam: antiflood improvements

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Using these functions with vars:
- is_present_hf($var(header))
- remove_hf($var(header)
Causes warning messages like this:
WARNING: <core> [core/mem/q_malloc.c:476]: qm_free(): WARNING: free(0) called from core: core/action.c: do_action(1126)
This PR avoids using them to prevent those warning messages.
There should be no logic change.

kam: avoid empty pointer free warning log

---

doc/sphinx/administration_portal/platform/antiflood_trusted_ips.rst
doc/sphinx/security_and_maintenance/security/antiflooding.rst
kamailio/trunks/config/kamailio.cfg

With latest change done via d11177e4ad0ae711bbc3e318d2ec127864dbfaaf antiflood in trunks is excluded for:
- IvozProvider internal elements  (it has always been)
- DdiProviderAddresses (it has always been)
- Carrier (only applied for within dialog requets, that are excluded now)
This means that only applies for invalid sources that will be rejected with 403 Forbidden in GET_TRANSFORMATIONS_IN: 
https://github.com/irontec/ivozprovider/blob/b62e94fbf68e5b70f4e22bdd6c0620bb9a0ec45e/kamailio/trunks/config/kamailio.cfg#L1081
This PR removes antiflood mechanism for KamTrunks and adds a simple logic in its place that rejects with 403 Forbidden any inbound initial request from a source IP no in kam_trunks_address (checked with _allow_source_address()_ that makes no underlying query).
As side …

trunks: disable antiflooding mechanism

---

kamailio/users/config/kamailio.cfg

- $dlg_var(companyId) is $null in STATIC_LOCATION route for unsolicited NOTIFY MWI.
- This causes db_mysql module error and $var(static_location) being set to 0.
- This error is harmless except for terminals and residential devices with no direct
connectivity, but misroutes NOTIFY for residential devices with directConnectivity
This commit removes $dlgvar(companyId) from where condition as all name+domain
combinations are unique in kam_users, fixing this misrouting.

kamusers: fix unsolicited NOTIFY MWI for residential devices with directConnectivity  

---

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/DestinationDoctrineRepository.php
microservices/workers/src/Worker/Rates.php
schema/DoctrineMigrations/Version20200608091055.php
web/admin/application/controllers/ImportDestinationRatesCustomFileController.php

- Italian and Catalan values were empty on Destinations table. Fixed importer
- Fixed encoding related issues as well (for instance Ñ character was breaking the importer)

Set missing multilang destination values

---

doc/sphinx/security_and_maintenance/security/antibruteforce.rst
doc/sphinx/security_and_maintenance/security/index.rst
kamailio/users/config/kamailio.cfg

This commit bans sources that fail in SIP auth for 100 times:
-  Ban expires after 12 hours and counter is reset to 80 (for faster re-ban after expiry).
- Source is defined as fromUsername@fromDomain::proto:source_ip:source_port combo.
This PR prevents brute-force-attacks from IP addresses excluded from antiflood mechanism.

kamusers: anti brute-force attack mechanism

---

doc/sphinx/administration_portal/brand/views/ipfilter_blocked_addresses.rst
kamailio/users/config/kamailio.cfg

Requests rejected by IP filter mechanism were not banned at all. This PR banned invalid IP address for 5 minutes instead of per request.
If address is granted adding to any client or to trusted list, its will be allowed immediately.

kamusers: ban ipfilter addresses for 5 minutes

---

microservices/realtime/src/Services/AbstractWsServer.php

Redis listeners may continue to work after server shutdown in some circumstances

microservices: forced realtime exit after shutdown

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
profiles/proxy/etc/mysql/conf.d/kamailio.cnf

_sqlops_ module is (sometimes?) connecting MySQL using _latin1_swedish_ci_ to get Company names for realtime service, causing errors like these:
```jansson [jansson_funcs.c:160]: janssonmod_set(): value to add is not a string - "Company"```
and empty fields in realtime section.
These PR forces new [kamailio] my.cnf group usage, that sets utf8 and seems to work.

kam: fix jansson error that cause realtime empty fields

---

microservices/realtime/src/Services/AbstractWsServer.php
microservices/realtime/src/Services/WsServer.php

Do not shutdown on redis master down/switch

realtime: reload service on redis down instead of restarting it

---

library/Ivoz/Provider/Domain/Service/TransformationRule/GenerateInRules.php
schema/DoctrineMigrations/Version20200625094153.php

This PR is a partial regression from #1197 removing the Transformation Rules created in default Country Transformation Rule Sets and the Rules generator.
These rules allow dialing numbers in E.164 without plus format in Country rule sets that can lead to undesired behaviors if there are National numbers that start with the Country Code. An example of this is any Italian mobile starting with 39 that is also the Italy Country Code.
Before: Dialing 397000111 was transformed to +397000111 assuming the initial 39 was Italy CC
After: Dialing 397000111 will be transformed to +39397000111 without E.164 without plus rule 
Thanks @nitefood for reporting and debugging this.

Transfomations e164 regression

---

web/admin/application/configs/klear/CalendarsList.yaml
web/admin/application/configs/klear/CallACLList.yaml
web/admin/application/configs/klear/CompaniesList.yaml
web/admin/application/configs/klear/CompanyServicesList.yaml
web/admin/application/configs/klear/ConditionalRoutesList.yaml
web/admin/application/configs/klear/ConferenceRoomsList.yaml
web/admin/application/configs/klear/ExtensionsList.yaml
web/admin/application/configs/klear/ExternalCallFiltersList.yaml
web/admin/application/configs/klear/ExternalCallFiltersResidentialList.yaml
web/admin/application/configs/klear/FriendsList.yaml
web/admin/application/configs/klear/HuntGroupsList.yaml
web/admin/application/configs/klear/IvrList.yaml
web/admin/application/configs/klear/LocutionsList.yaml
web/admin/application/configs/klear/MatchListsList.yaml
web/admin/application/configs/klear/MusicOnHoldList.yaml
web/admin/application/configs/klear/OutgoingDDIRulesList.yaml
web/admin/application/configs/klear/PickUpGroupsList.yaml
web/admin/application/configs/klear/QueuesList.yaml
web/admin/application/configs/klear/ResidentialDevicesList.yaml
web/admin/application/configs/klear/RetailAccountsList.yaml
web/admin/application/configs/klear/RetailDdisList.yaml
web/admin/application/configs/klear/RouteLocksList.yaml
web/admin/application/configs/klear/SchedulesList.yaml
web/admin/application/configs/klear/TerminalsList.yaml
web/admin/application/configs/klear/UsersList.yaml
web/admin/e2e/tests/features/1-platform/05-proxyTrunks.feature

HIde new/edit/delete buttons on company type specific list screens

Improved webadmin emulation checks

---

doc/sphinx/administration_portal/brand/views/ipfilter_blocked_addresses.rst
kamailio/users/config/kamailio.cfg

Revert #1421 changes.
Maintainers of a given platform can register a phone in a client to make some tests. If that client has IP filter enabled, mantainer's IP can be banned. This IP may be used by maintainer in its own client.

Revert ban ip filter addresses

---

library/Ivoz/Provider/Domain/Service/CallCsvReport/EmailSender.php

Fixes a regression introduced by commit [9542131711a99b45f315d0bbd1687849d8afdd27](https://github.com/irontec/ivozprovider/commit/9542131711a99b45f315d0bbd1687849d8afdd27) that caused the Body Type to be ignored for Call CSV scheduled reports. HTML emails would go out with a 'text/plain' header that caused email clients to render it as plaintext instead of HTML (tested with Thunderbird v68.10.0).
Thanks @Kaian for the excellent support!

core: corrected bodyType parsing in CSV scheduler emails

---

library/DataFixtures/ORM/ProviderCarrier.php
library/Ivoz/Cgr/Infrastructure/Cgrates/Service/CarrierBalanceService.php
library/Ivoz/Cgr/Infrastructure/Cgrates/Service/CompanyBalanceService.php
library/Ivoz/Provider/Domain/Model/Carrier/CarrierRepository.php
library/Ivoz/Provider/Domain/Service/Carrier/SyncBalances.php
library/Ivoz/Provider/Domain/Service/Company/SyncBalances.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CarrierDoctrineRepository.php
library/spec/Ivoz/Provider/Domain/Service/Carrier/SyncBalancesSpec.php
schema/tests/Provider/Carrier/CarrierRepositoryTest.php
web/admin/application/library/IvozProvider/Klear/Ghost/Carriers.php
web/admin/application/library/IvozProvider/Klear/Ghost/Companies.php
web/rest/brand/features/provider/carrier/getCarrier.feature

- sync balances microservice was not saving correct balance values in Carriers.balance
- sync balances microservice was logging error messages for carriers with calculateCost disabled
- sync balances microservice was saving 0 balances when CGRateS returned null (or empty) balancemaps.
- As a side effect, balance ghosts have been adapted to show 0 for empty balancemaps.

microservices: fix sync balances

---

asterisk/agi/composer.lock
library/composer.lock
microservices/balances/composer.lock
microservices/realtime/composer.lock
microservices/recordings/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock

- Updating symfony/polyfill-php70 (v1.17.0 => v1.17.1):  Checking out 471b096aed
- Updating symfony/polyfill-ctype (v1.17.0 => v1.17.1):  Checking out 2edd75b8b3
- Updating symfony/polyfill-mbstring (v1.17.0 => v1.17.1):  Checking out 7110338d81
- Updating symfony/polyfill-util (v1.17.0 => v1.17.1):  Checking out 6dd644eda4
- Updating symfony/polyfill-php56 (v1.17.0 => v1.17.1):  Checking out a25861bb3c
- Updating symfony/polyfill-intl-icu (v1.17.0 => v1.17.1):  Checking out 7b5e03aeb8
- Updating symfony/polyfill-apcu (v1.17.0 => v1.17.1):  Checking out a96dc28442
- Updating symfony/polyfill-intl-idn (v1.17.0 => v1.17.1):  Checking out a57f816150
- Updating friendsofphp/php-cs-fixer (v2.16.3 => v2.16.4):  Checking out 1023c34581
- Updating symfony/polyfill-iconv (v1.17.0 => v1.17.1): …

core: updated composer dependencies

---

microservices/balances/config/services.yml

It's already imported in cofig file through "@ProviderBundle/Resources/config/config.yml"

microservices: fixed duplicated resource import

---

debian/ivozprovider-profile-common.postinst

This is a regression from 2bf572708ab27dac3bb682ef3859f743330e9807 where storage permissions was changed to 777 after every upgrade. This causes some problems if the storage is distributed (DBRD, GlusterFS, and so on) and there are lots of files.
This PR revert the change only changing the root storage directory, so web interface can create required folders to upload images or logos.
I still see some permissions problem in other cases. For example FaxFiles can be created from asterisk on incoming faxes and from the web interface for outgoing faxes. If the folders in storage are created during incoming faxes, outgoing ones that share storage path will fail to upload.

pkg: fix storage permissions on fresh install

---

kamailio/users/config/kamailio.cfg
schema/DoctrineMigrations/Version20200710151403.php

_kam_users_ view is not a good option in high rates escenarios.
This PR removes this view and changes KamUsers config file to obtain information from regular tables.
No functional change.

kamusers: drop kam_users view

---

doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends/internal_friends.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends/remote_friends.rst
kamailio/users/config/kamailio.cfg
library/Ivoz/Provider/Domain/Model/Friend/FriendAbstract.php
library/Ivoz/Provider/Domain/Model/Friend/FriendDtoAbstract.php
library/Ivoz/Provider/Domain/Model/Friend/FriendInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Friend.FriendAbstract.orm.yml
schema/DoctrineMigrations/Version20200716075035.php
web/admin/application/configs/klear/FriendsList.yaml
web/admin/application/configs/klear/model/Friends.yaml
web/admin/application/languages/ca_ES/ca_ES.po
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/languages/it_IT/it_IT.po

When sending requests to a friend or receiving requests from a friend caller and callee headers are inspected looking for numbers that must be transformed using Friend's numeric transformation.
Until now, internal numbers were not transformed:
- Numbers in Extension section.
- Numbers matching Friend's regexps.
This PR makes this configurable, so that you can modify numbers even if they seem internal.
This PR enables adding prefixes to local extensions or dialing 801 but calling to SOMEPREFIX801 that were not possible because internal numbers didn't traverse numeric transformation logic.

friends: new always transform numbers option

---

asterisk/agi/src/Agi/Action/ServiceAction.php

Call Forward Settings services assume the caller is a ResidentialAgent and uses its ID as ResidentialDeviceId in order to check, delete or add new Call Forward Settings.
If for some reason a User calls these services, the UserId will be used as ResidentialDeviceId, causing unexpected behaviors.
This PR adds a check to ensure the Agent's company is a ResidentialClient (so Agent can only be a ResidentialDevice).

agis: ensure CFW services are only used by Residential clients

---

doc/sphinx/administration_portal/brand/calls/call_csv_schedulers.rst
doc/sphinx/administration_portal/client/residential/calls/call_csv_schedulers.rst
doc/sphinx/administration_portal/client/vpbx/calls/call_csv_schedulers.rst
library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvScheduler.php
library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerDto.php
library/Ivoz/Provider/Domain/Service/InvoiceScheduler/NextExecutionResolverTrait.php
library/spec/Ivoz/Provider/Domain/Service/InvoiceScheduler/NextExecutionResolverSpec.php
web/admin/application/configs/klear/CallCsvSchedulersBrandList.yaml
web/admin/application/configs/klear/CallCsvSchedulersList.yaml
web/admin/application/configs/klear/model/CallCsvSchedulers.yaml
web/admin/application/library/IvozProvider/Klear/Filter/BrandCompanies.php

Allow inbound call CSV schedulers to be filtered by user/friend/fax

core: allow new call CSV scheduler filters

---

kamailio/users/config/kamailio.cfg

KamTrunks fixes wrong R-URI in within dialog requests with a logic added a lot of time ago. This PR copies this logic to KamUsers.

kamusers: copy fix contact logic from trunks

---

kamailio/users/config/kamailio.cfg

Several WebRTC/websockets changes:
- add rtcp-mux options to WSS dialogs
- SRTP without DTLS no longer supported in WebRTC
Non-functional changes:
- local proto is equal to remote proto
-  less logs for wss dialogs

kamusers: several websockets fixes

---

web/admin/application/configs/klear/model/Friends.yaml
web/admin/application/configs/klear/model/ResidentialDevices.yaml
web/admin/application/configs/klear/model/Terminals.yaml

Trimming select fields causes problems in VisualFilters scenarios:
- Hidden select field with trim.
- As it is hidden, it is set to null.
- null turns into '' after being trimmed.

web/admin: no trim for select fields

---

web/admin/application/configs/klear/model/ExternalCallFilters.yaml
web/admin/application/configs/klear/model/ExternalCallFiltersResidential.yaml
web/admin/application/library/IvozProvider/Klear/Filter/CompanyOrBrand.php

Brand level matchlists couldn't be selected in client external call filters.

web/admin: allow using brand level matchlists

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

No intended functional change.
- KamUsers will always call rtpengine except in known_dlgs:
- Intervpbx bounced call second processing
- Retail/wholesale call to retail DDI second processing
- KamTrunks will always call rtpengine except:
- calls from kamusers
- calls from carriers to retail DDIs
- second processing of bounced calls

kam: skip media-relay logic rewritten

---

doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends/remote_friends.rst
kamailio/users/config/kamailio.cfg
library/Ivoz/Provider/Domain/Model/Friend/Friend.php
library/Ivoz/Provider/Domain/Model/Friend/FriendAbstract.php
library/Ivoz/Provider/Domain/Model/Friend/FriendDtoAbstract.php
library/Ivoz/Provider/Domain/Model/Friend/FriendInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Friend.FriendAbstract.orm.yml
schema/DoctrineMigrations/Version20201005171626.php
web/admin/application/configs/klear/FriendsList.yaml
web/admin/application/configs/klear/model/Friends.yaml

non-intervpbx friends now have a new field: **From User**.
If non-empty, its value will be included as username of From header in INVITE initial requests from IvozProvider. If empty, its value will be equal to source in PAI header (as it is now).

Add From User in remote Friends

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

- KamUsers will always call rtpengine.
- KamTrunks will always call rtpengine.
- Both proxies will add "call-id=trunks|users-inbound|outbound-$ci" flag to avoid rtpengine collisions in bouncing scenarios.
These changes:
- Solve No NAT retail/wholesale calling to behind NAT retail DDI no audio.
- Solve some recording issues in skip scenarios.
- In KamUsers, guarantees each UAC sends RTP to media-relay linked to its client.
- In KamTrunks, guarantees RTP traverses media-relays linked to each client.

kam: remove skip media-relay logic

---

asterisk/agi/src/Agi/Wrapper.php
asterisk/agi/src/Dialplan/HuntGroupMember.php

This PR adds fake ringing in ringall huntgroups containing at least one external number.
This solves multiple early-media not being connected to caller, leading to no ringing tone in such scenarios.

agi: fake ringing for external ringall huntgroups

---

kamailio/users/config/kamailio.cfg

SAVE_CONTACT and FIX_RURI logic was broken under these circumstances:
- retail/wholesale calling to retail DDI.
- call was bounced to in trunks.
- dialog was handled twice in users.
- two dialog structures (one inbound, one outbound).
Accessing to dlg_vars in within-dialog requests always returns first dialog structure value (e.g. $dlg_var(direction) always outbound).
This causes R-URI being mangled incorrectly when callee hangs up (as saved contact from the other side was retrieved). This lead to BYE (and all within-dlg) misrouting.
This commit changes implementation so that no dlg_var is used.

kamusers: fix R-URI without dlg_vars

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
microservices/recordings/src/Recording/Encoder.php

- start_recording() and stop_recording() need callid= flag.
- recordings microservice needs to be updated with new recording file name.

kam: adapt recordings to new rtpengine callid flag

---

kamailio/trunks/config/kamailio.cfg

Since https://github.com/irontec/cgrates/pull/3 Kamailio gets company from URL param instead of parsing http body.

kamtrunks: End company calls from urlparam

---

kamailio/trunks/config/kamailio.cfg

A carrier may be used both in stopper rule and in non-stopper one.
With previous logic, non stopper rule may inactivate a carrier that is stopper
in another rule. As inactivated gateways are not taken into account in new calls,
stopper rule may be skipped.
This commit avoids inactivating a carrier that is stopper in any rule.

kamtrunks: do not inactivate stopper gateways

---

library/Ivoz/Provider/Domain/Service/Invoice/CreateByScheduler.php
library/Ivoz/Provider/Domain/Service/InvoiceScheduler/SetExecutionError.php
library/Ivoz/Provider/Domain/Service/InvoiceScheduler/UpdateLastExecutionDate.php

Error messages were not being persisted in database

core: persist invoice scheduler errors properly

---

doc/sphinx/administration_portal/client/residential/residential_devices.rst
doc/sphinx/administration_portal/client/retail/retail_accounts.rst
kamailio/users/config/kamailio.cfg

Diversion related logic in AGIs (for vpbx/residential) is different from
Kamusers logic (for retail/wholesale).
This commit drops any Diversion header with an invalid number so that AGIs only
receive valid Diversion headers.

kamusers: drop invalid Diversion

---

doc/sphinx/administration_portal/platform/antiflood_banned_ips.rst
doc/sphinx/security_and_maintenance/security/antibruteforce.rst
doc/sphinx/security_and_maintenance/security/antiflooding.rst
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

This PR increases threshold from 15 request in 2-second-interval to 100 requests in same time interval.
**KAMUSERS**
- no source IP exceptions
Antiflood will take into account:
- failing requests during endpoint identification and authentication phase
- initial call establishments of legitimate UACs
**KAMTRUNKS**
- This partially reverts commit cbbea39.
- Antiflood will only count initial requests from non-DDIproviders.
This PR makes unnecessary to add client IP ranges to skip Antiflood after lights-out events.

kam: changes in antiflooding mechanism

---

library/Ivoz/Provider/Domain/Model/Carrier/Carrier.php
library/Ivoz/Provider/Domain/Model/Company/Company.php
library/Ivoz/Provider/Infrastructure/Domain/Service/Carrier/SendTrunksLcrReloadRequest.php

Prevents lots of unnecessary lcr.reload commands
Database and CGRateS precision difference caused balance change logic for equal balances.
Prevents lots of unnecessary lcr.reload commands and changelog entries.

core: avoid detecting balance changes for equal values

---

library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOut.php

Replace any non numeric valur on faxesInOut destination

core: ensure numeric only fax dst

---

debian/ivozprovider-profile-proxy.postinst
debian/ivozprovider-profile-proxy.templates

Make rtpengine ports configurable via debconf.

pkg: make rtpengine ports configurable via debconf

---

asterisk/config/sorcery.conf

Re-enable asterisk realtime PJSIP cache.
Solves asterisk booting problems in environments with hundreds of endpoints.

asterisk: enable realtime pjsip cache

---

library/Ivoz/Provider/Domain/Service/Invoice/Generator.php
library/composer.json
library/composer.lock
microservices/workers/composer.json
microservices/workers/composer.lock
profiles/portal/etc/supervisor/conf.d/ivozprovider.conf
schema/DoctrineMigrations/Version20210114122624.php
web/admin/templates/basic.txt
web/admin/templates/detailed.txt
web/admin/templates/header.txt

Updated wkhtmltopdf library version in order to avoid some segmentation fault errors. PDF font sizes are smaller in the latest version so CSS styles have been changed.

Updated pdf generator

---

web/admin/application/configs/klear/model/BillableCalls.yaml
web/admin/application/controllers/KlearCustomBillableCallsController.php

Allow lists to be filtered by null / not null on numeric field
Requires klear matrix to be updated (https://github.com/irontec/klearMatrix/commit/2d77e67fdf6e49244796068e49e8bb9b313204de)

Allow null/not null search on price and cost

---

web/admin/templates/provisioning/SnomD375/generic.cfg
web/admin/templates/provisioning/SnomD717/generic.cfg
web/admin/templates/provisioning/SnomD735/generic.cfg
web/admin/templates/provisioning/SnomD785/generic.cfg

Add support for certificate chains for Snom provisioning certificates. With this change, a <certificate> section is added to provisioning for each certificate added into snom.crt

provisioning: add support for certificate chains

---

library/Ivoz/Kam/Domain/Service/TrunksLcrRuleTarget/TrunksLcrRuleTargetFactory.php
schema/tests/Provider/CarrierServer/CarrierServerLifeCycleTest.php

If weight is zero in LcrRuleTarget Kamailio lcr module reload will fail.

core: avoid 0 weight LcrRuleTarget

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Print 3 log messages on dialog end in both proxies:
- inbound mos value: RTP flow from external elements (UAC/carrier) to IvozProvider.
- outbound mos value: RTP flow from IvozProvider to external elements (UAC/carrier).
- global mos value: inbound RTP flow + outbound RTP flow.
Just print 3 log messages per dialog in both proxies, no database storage or further calculations yet.

kam: print quality log messages on dialog end

---

library/Ivoz/Provider/Domain/Model/Company/CompanyAbstract.php
library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php
library/Ivoz/Provider/Domain/Model/Ddi/Ddi.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiAbstract.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiInterface.php
library/Ivoz/Provider/Domain/Model/Terminal/Terminal.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Ddi.DdiAbstract.orm.yml
library/spec/Ivoz/Provider/Domain/Model/Company/CompanySpec.php
schema/DoctrineMigrations/Version20210218095214.php
web/admin/application/configs/klear/model/Terminals.yaml

- allow nullable terminal model in web portal selector.
- Not nullable company countryId
- Nullable DDI countryId (it'll inherit it from company if null)
- Avoid '' terminal name.

Reviewed nullable fields

---

library/composer.lock

API: Use 422 Unprocessable Entity http response code when the payload includes a non existing foreign key

Improved api response codes

---

web/admin/application/configs/klear/klear.yaml

Record counts on large tables, such as external calls, slows down dashboard loading time significantly. Turn it off.
Requires klear to be updated:
- https://github.com/irontec/klearMatrix/commit/b718d8de1043d8c2acfdcaff227168cd7151c543
- https://github.com/irontec/klear/commit/df7044ed5e2a965cd813286a8c281b07fd3cf58d

web/admin: skip record count on large tables in the dashboard

---

asterisk/config/sorcery.conf

Cache was enabled in f97079556 to make Asterisk boot faster in environments with
lots of endpoints. But it breaks unsolicited NOTIFY for mwi, so this commits
disables cache again.

asterisk: re-disable realtime pjsip cache

---

kamailio/users/config/kamailio.cfg

- _Trying_ state only applies for caller parties.
- As soon as _dlg_manage()_ is called for vpbx initial INVITEs from UACs, a PUBLISH with _Trying_ state is sent to every active watcher.
- If finally this request is not sent (rejected by antiflood, etc.), no PUBLISH is generated with _terminated_ state.
- BLF lights remain red for 3 hours (dialog max lifetime).
This PR:
- Fixes call rejections done after _dlg_manage()_:
- Antiflood moved upwards.
- Doble '*' check removed.
- Removes expired presentity entries every 10 seconds (instead of 100 seconds).
This PR together with https://github.com/irontec/kamailio/pull/3 mitigates any future Trying lock from 3 hours to 30 seconds (20 seconds of _Trying_ state lifetime + 10 seconds of expired presentity cleanup).

kamusers: mitigate BLF locking in Trying state

---

microservices/recordings/src/Recording/Encoder.php

A race condition existis if the recording timer starts at the same time
a call has been answered and its recording has just been created.
The resulting file will have 0 bytes and the garbage handler of recordings
service will remove the file.
This PR adds a new condition to ignore recent created files
to give the chance to recording daemon to add data.

recordings: avoid race ignoring too recent recorded files

---

asterisk/agi/src/Dialplan/FaxDial.php
asterisk/config/dialplan/faxes.conf
library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOut.php

- [] Fixes an existing issue (Fixes #XXXX) 
Following commits fixes some scenarios that was not being validated:
a) Sending a file other than a PDF caused conversion errors not being handled
b) Sending a Fax to a destionation that does not answer keeps the faxfile in pending status forever
c) Sending a Fax to a only letters destination keeps the faxfile in pending status forever
Above error should be fixed in this PR commits

Several Fax validations improved

---

web/user/app/languages/locale-en.json

Fix English translation for call type: both.

i18n: Update locale-en.json to fix translation for "both"

---

library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallRepository.php
library/Ivoz/Provider/Domain/Service/BillableCallHistoric/ImportFromBillableCalls.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php
microservices/scheduler/src/BillableCallHistoricController.php
schema/tests/Provider/BillableCall/BillableCallRepositoryTest.php

Higher id's don't guarantee higher startTime, removed time based discrimination

core: fixed billable call rotator

---

asterisk/agi/src/Agi/Action/ExternalNumberAction.php
asterisk/agi/src/Agi/Action/FriendCallAction.php
asterisk/agi/src/Agi/Action/ResidentialCallAction.php
asterisk/agi/src/Agi/Action/UserCallAction.php

Set max call duration to 3 hours like already configured in Kamailio Proxies:
https://github.com/irontec/ivozprovider/blob/361284c5fa6edd9bddb5ac3f68f07076b88334ca/kamailio/users/config/kamailio.cfg#L60-L61

agis: set max call duration to 3 hours

---

library/Ivoz/Provider/Domain/Service/Invoice/Generator.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BillableCallDoctrineRepository.php
microservices/workers/src/Worker/Invoices.php

Long queries don't play well with percona cluster

core: set invoice id by iterating chunks in order to avoid lock timeouts

---

doc/sphinx/administration_portal/brand/providers/carriers.rst
doc/sphinx/administration_portal/brand/providers/ddi_providers.rst
doc/sphinx/administration_portal/platform/infrastructure/media_relay_sets.rst
kamailio/trunks/config/kamailio.cfg
library/Ivoz/Provider/Domain/Model/Carrier/CarrierAbstract.php
library/Ivoz/Provider/Domain/Model/Carrier/CarrierDtoAbstract.php
library/Ivoz/Provider/Domain/Model/Carrier/CarrierInterface.php
library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderAbstract.php
library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderDtoAbstract.php
library/Ivoz/Provider/Domain/Model/DdiProvider/DdiProviderInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Carrier.CarrierAbstract.orm.yml
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/DdiProvider.DdiProviderAbstract.orm.yml
schema/DoctrineMigrations/Version20210607104602.php
web/admin/application/configs/klear/CarriersList.yaml
web/admin/application/configs/klear/DdiProvidersList.yaml
web/admin/application/configs/klear/model/Carriers.yaml
web/admin/application/configs/klear/model/DdiProviders.yaml

Media-relays can be grouped into sets and assigned to clients. It was not possible to choose one set when talking to a specific carrier/ddiprovider because in some scenarios kamusers/kamtrunks media-relay was skipped.
This skip logic is gone, so it is possible to choose one media-relay set per client (in kamUsers) and another media-relay set per carrier/ddiprovider (in KamTrunks).
This PR adds missing pieces to achieve this.
To make this change backward compatible, carriers/ddiprovider may use (and would use by default) client's mediarelay set.

kam: add carrier/ddiprovider mediarelayset relationship

---

kamailio/trunks/config/kamailio.cfg

Before overriding lowest-id-first-matching ddiProvider with ddiProvider linked
to matching DDI, make sure this ddiProvider matches source IP, local socket and
callee_in transformation too.
If so, override $dlg_var(ddiProviderId) and related dlg_vars (tr_* and mediaRelaySetsId).

kamtrunks: fix ddiProvider detection logic

---

doc/sphinx/administration_portal/brand/routing/outgoing_routings.rst
kamailio/trunks/config/kamailio.cfg
library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRouting.php
library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingDto.php
web/admin/application/configs/klear/model/OutgoingRouting.yaml

Until this PR, blocking OutgoingRoutes had a forced 0 priority value. This made impossible setups like these:
- Allow All clients to call Emergency numbers (prio 1).
- Block remaining call for specific client X (blocking prio 2).
This PR tries to make it possible.

kamtrunks: blocking route no prio 0

---

asterisk/agi/config/services.yml
asterisk/agi/src/Agi/Action/RetailCallAction.php
asterisk/agi/src/Agi/Action/RouterAction.php
asterisk/agi/src/Dialplan/Retails.php
asterisk/config/dialplan/default.conf
doc/sphinx/administration_portal/client/retail/retail_accounts.rst
kamailio/users/config/kamailio.cfg
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByRetailAccount.php
library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSetting.php
library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingAbstract.php
library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingDtoAbstract.php
library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSettingInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallForwardSetting.CallForwardSettingAbstract.orm.yml
schema/DoctrineMigrations/Version20210708134307.php
web/admin/application/configs/klear/CallForwardSettingsList.yaml
web/admin/application/configs/klear/model/CallForwardSettings.yaml
web/admin/application/library/IvozProvider/Klear/Filter/RetailAccounts.php
web/admin/application/library/IvozProvider/Klear/Filter/TargetTypes.php
web/admin/application/library/IvozProvider/Klear/Ghost/RouteTarget.php
web/rest/client/features/provider/callForwardSetting/postCallForwardSetting.feature
web/rest/client/features/provider/callForwardSetting/putCallForwardSetting.feature

Retail account call-forward can only be routed to external numbers.
This PR makes it possible to call-forward to another retail account in the same retail client.

Add retail to retail call-forward

---

kamailio/trunks/config/kamailio.cfg

Once Terminated state was reached, logic avoided going back to Trying for next selected gateway. This PR fixes realtime in gateway failover scenarios.
Prior to this PR, only first attempt was listed in god/brand realtime section. If it failed, call disappeared nevertheless it was routing through other gateway.

kamtrunks: fix realtime for GW failover

---

web/admin/application/configs/klear/CallForwardSettingsList.yaml
web/admin/application/configs/klear/ConditionalRoutesConditionsList.yaml
web/admin/application/configs/klear/ConditionalRoutesList.yaml
web/admin/application/configs/klear/DdisList.yaml
web/admin/application/configs/klear/ExtensionsList.yaml
web/admin/application/configs/klear/ExternalCallFiltersList.yaml
web/admin/application/configs/klear/FaxesList.yaml
web/admin/application/configs/klear/HuntGroupsList.yaml
web/admin/application/configs/klear/HuntGroupsRelUsersList.yaml
web/admin/application/configs/klear/IvrEntriesList.yaml
web/admin/application/configs/klear/IvrList.yaml
web/admin/application/configs/klear/MatchListPatternsList.yaml
web/admin/application/configs/klear/QueuesList.yaml
web/admin/application/configs/klear/RetailDdisList.yaml

Replace afganistan by client country as default country number value in edit screen
requires: https://github.com/irontec/klearMatrix/commit/e35a093e242fbdda34b8d7dabf3fe06904144cb8

Set default country value in edit screens

---

library/Ivoz/Provider/Domain/Service/CallForwardSetting/CheckUniqueness.php
library/spec/Ivoz/Provider/Domain/Service/CallForwardSetting/CheckUniquenessSpec.php

Doctrine was throwing an error when a ddi was selected:
"Cannot match on Ivoz\Provider\Domain\Model\CallForwardSetting\CallForwardSetting::ddi with a non-object value. Matching objects by id is not compatible with matching on an in-memory collection, which compares objects by reference. (0) # /opt/irontec/ivozprovider/library/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/PersisterException.php"

core: fixed CFW creation issues

---

web/admin/application/configs/klear/FriendsList.yaml
web/rest/brand/config/api/raw/provider.yml
web/rest/brand/features/provider/friend/postFriend.feature
web/rest/brand/features/provider/friend/putFriend.feature
web/rest/brand/features/provider/friend/removeFriend.feature
web/rest/brand/tests/DataAccessControl/Provider/FriendTest.php

Allow brand admins to managed friends from API
Remove inter company field from clients admin page (read only field until now)

Friend inter company

---

library/Ivoz/Cgr/Domain/Model/TpDestination/TpDestinationRepository.php
library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/TpDestinationDoctrineRepository.php
microservices/workers/src/Worker/Rates.php

Two improvements:
- Do not sync tp_destinations <-> Destination if no affected rows.
- When sync is needed, sync only inside current brand.

microservices: make CSV import faster

---

library/Ivoz/Provider/Domain/Service/Invoice/Generator.php
schema/DoctrineMigrations/Version20191226104551.php
web/admin/templates/basic.txt
web/admin/templates/detailed.txt

Use two decimals instead of four in invoice tax amount and simplify default template resume table

Invoice decimal precision

---

asterisk/agi/src/Agi/Action/ServiceAction.php
doc/sphinx/administration_portal/brand/settings/generic_services.rst

Residential devices can add and remove call forward settings
using services codes.
When adding a new call forward setting to destination '*'
the created cfw target will be voicemail instead of number.

agi: add support to residential cfw to voicemail

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

- After crash/restart, BYEs of active calls are correctly forwarded.
- But, realtime service is not updated when they hang up (as BYE is not recognized as coming from
a known dialog).
- This causes that 'Active calls' section show these calls until they expire (3 hours later).
This commit searches call-ids of this kind of BYEs and, if found in redis, send Terminated event to redis.
BYE of unknown dialogs will be counted by antiflood.

kam: publish to redis BYEs of unknown dialogs

---

asterisk/agi/composer.lock
debian/control
library/Ivoz/Kam/Domain/Service/TrunksClientInterface.php
library/Ivoz/Kam/Infrastructure/Gearman/TrunksClient.php
library/composer.lock
microservices/balances/composer.lock
microservices/realtime/composer.lock
microservices/realtime/src/Services/AbstractWsServer.php
microservices/realtime/src/Services/WsServer.php
microservices/recordings/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/composer.lock
tests/docker/Dockerfile
web/rest/brand/composer.lock
web/rest/brand/features/my/activeCalls/getActiveCalls.feature
web/rest/brand/src/Controller/My/ActiveCallsAction.php
web/rest/client/composer.lock
web/rest/client/features/my/activeCalls/getActiveCalls.feature
web/rest/client/src/Controller/My/ActiveCallsAction.php
web/rest/platform/composer.lock
web/rest/platform/features/my/activeCalls/getActiveCalls.feature

Resolve Active calls through redis so that kamailio reloads do not show zero active calls

Api active calls from redis

---

doc/sphinx/administration_portal/brand/clients/index.rst
doc/sphinx/administration_portal/brand/clients/operators.rst
doc/sphinx/api_rest/multilevel.rst
doc/sphinx/api_rest/use_case.rst
web/rest/brand/config/api/resources.yml
web/rest/brand/src/Controller/Auth/TokenExchangeAction.php
web/rest/client/config/api/resources.yml
web/rest/client/src/Controller/Auth/TokenExchangeAction.php

Allow to impersonate just by entity id as an alternative to administrator username in /token_exchange API endpoint

Easier internal token exchange

---

profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf
profiles/portal/etc/apache2/sites-available/030-ivozprovider-prov.conf

Use logger to send logs to rsyslog/journald instead of files in /var/log/apache2
This allows more control over the created log files.

portals: redirect apache2 logs to journald

---

asterisk/config/dialplan/default.conf
asterisk/config/extensions.conf

Like kamailio configuration, limit the call duration to 3 hours.
This avoids infinite duration channels in case of missed or not properly routed BYE requests.

as: set max call duration to 3 hours

---

web/admin/application/configs/klear/RetailAccountsList.yaml
web/rest/client/config/api/raw/provider.yml
web/rest/client/features/provider/retailAccount/putRetailAccount.feature

Retail accounts must be editable by retail admins (everything but name)

Retail account access fix

---

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/TerminalModel.TerminalModelAbstract.orm.yml
schema/DoctrineMigrations/Version20220207084804.php
schema/tests/Provider/TerminalModel/TerminalModelLifeCycleTest.php
web/rest/platform/features/provider/terminalModel/postTerminalModel.feature

This change make genericUrlPattern unique to avoid any missconfigurations in terminal provisioning.
If there are genericUrlPatterns duplicated in database, this schema change may fail and human interaction will be required to fix the data before reapplying the migration.

schema: add unique constraint to TerminalModel genericUrlPattern field

---

library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.yml
schema/DoctrineMigrations/Version20220207102413.php

Add db index on kam_user_cdrs.start_time so that it can be rotated easily

kam_user_cdrs start_time index

---

library/DataFixtures/ORM/KamTrunksCdr.php
library/Ivoz/Cgr/Infrastructure/Cgrates/Service/RerateCallService.php
library/Ivoz/Kam/Domain/Model/TrunksCdr/TrunksCdrRepository.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksCdrDoctrineRepository.php
schema/tests/Kam/TrunksCdr/TrunksCdrRepositoryTest.php

Reset orphan cgrids before rerating ir order to avoid potential cgrates issues

Improved rerating

---

kamailio/trunks/config/kamailio.cfg

Avoids a GW being inactivated if 408 event raised (or response received) after any other response (e.g. 100-408 sequence)

kamtrunks: avoid inactivating gw if any reply received

---

doc/sphinx/administration_portal/client/residential/residential_devices.rst
doc/sphinx/administration_portal/client/retail/retail_accounts.rst
doc/sphinx/administration_portal/client/vpbx/routing_endpoints/friends/remote_friends.rst
kamailio/users/config/kamailio.cfg

- Prevalence order in incoming requests: PAI > PPI > RPID > From
- IvozProvider will always use PAI when it needs to add an identity header.

kamusers: add P-Preferred-Identity support

---

kamailio/trunks/config/kamailio.cfg

Bounced calls may cause gw inactivation if bounced call causes t_branch_timeout event. In this situation, gateway of external carrier that would be chosen if call was not bounced may be inactivated.
This PR fixes this weird behaviour.

kamtrunks: skip gw inactivation on bounced calls

---

cgrates/config/cgrates.json
debian/ivozprovider-profile-common.config
debian/ivozprovider-profile-data.postinst
debian/ivozprovider-profile-data.templates
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/parameters.yml
library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/parameters.yml.dist
microservices/realtime/config/services.yaml
profiles/data/etc/bind/db.ivozprovider.local

New local dns entry for redis sentinel.
This allows spliting redis and mysql in differents hosts.

New local dns entry cache.ivozprovider.local

---

library/Ivoz/Provider/Application/Service/User/SyncFromCsv.php
library/Ivoz/Provider/Domain/Model/Ddi/Ddi.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiInterface.php

If users mass import has just created a DDI, assign it's user to it's route type

core: assign ddi route type in users mass import

---

profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf
profiles/portal/etc/apache2/sites-available/060-ivozprovider-api.conf

Enable H2 protocol on apache and removed php settings that conflic with php-fpm

Enable HTTP/2 protocol

---

doc/sphinx/administration_portal/client/vpbx/routing_tools/external_call_filters.rst
library/DataFixtures/ORM/ProviderExternalCallFilter.php
library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilter.php
library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilterAbstract.php
library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilterDtoAbstract.php
library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilterInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ExternalCallFilter.ExternalCallFilterAbstract.orm.xml
schema/DoctrineMigrations/Version20220324084602.php
web/client/src/entities/ExternalCallFilter/ExternalCallFilter.tsx
web/client/src/entities/ExternalCallFilter/ExternalCallFilterProperties.tsx
web/client/src/entities/ExternalCallFilter/Form.tsx
web/rest/client/features/provider/externalCallFilter/postExternalCallFilter.feature
web/rest/client/features/provider/externalCallFilter/putExternalCallFilter.feature
web/rest/client/features/provider/externalCallFilterBlackList/getExternalCallFilterBlackList.feature
web/rest/client/features/provider/externalCallFilterBlackList/postExternalCallFilterBlackList.feature
web/rest/client/features/provider/externalCallFilterRelCalendar/getExternalCallFilterRelCalendar.feature
web/rest/client/features/provider/externalCallFilterRelCalendar/postExternalCallFilterRelCalendar.feature
web/rest/client/features/provider/externalCallFilterRelSchedule/getExternalCallFilterRelSchedule.feature
web/rest/client/features/provider/externalCallFilterRelSchedule/postExternalCallFilterRelSchedule.feature
web/rest/client/features/provider/externalCallFilterWhiteList/getExternalCallFilterWhiteList.feature
web/rest/client/features/provider/externalCallFilterWhiteList/postExternalCallFilterWhiteList.feature

Add a new toggle field to External Call Filters calendar section to enable or disable holiday logics.
This is like #1740 for Calendars instead of Schedules

External call filters: make calendar filtering optional

---

library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilterAbstract.php
library/Ivoz/Provider/Domain/Model/ExternalCallFilter/ExternalCallFilterDtoAbstract.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/ExternalCallFilter.ExternalCallFilterAbstract.orm.xml
schema/DoctrineMigrations/Version20220328144016.php
web/client/src/entities/ExternalCallFilter/ExternalCallFilter.tsx

Set External Call Filters toggles for Holidays & Calenders disabled by default
Related with #1750 and #1740

Set External Call Filters toggles for Holidays & Calenders disabled by default

---

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/TerminalDoctrineRepository.php

When no terminal is excluded, the query generated has syntax errors.
This can be easly reproduced by creating a new company with no terminals, the user creation screen won't load Terminal field.

core: fix unassigned terminals repository query

---

library/Ivoz/Provider/Domain/Model/AdministratorRelPublicEntity/AdministratorRelPublicEntityRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/AdministratorRelPublicEntityDoctrineRepository.php
library/composer.lock
microservices/realtime/composer.lock
schema/composer.json
schema/composer.lock
schema/symfony.lock
schema/tests/Provider/AdministratorRelPublicEntity/AdministratorRelPublicEntityRepositoryTest.php
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/client/config/api/raw/provider.yml
web/rest/client/config/api/resources.yml
web/rest/client/config/routes.yaml
web/rest/client/features/my/activeCalls/getActiveCalls.feature
web/rest/client/features/my/profile/getProfile.feature
web/rest/client/phpstan-baseline.neon
web/rest/client/src/Controller/My/ProfileAction.php
web/rest/client/src/Model/Profile.php
web/rest/client/src/Model/ProfileAcl.php
web/rest/client/src/Service/Behat/FeatureContext.php
web/rest/platform/composer.lock
web/rest/user/composer.lock

Expose /my/profile endpoint in client API in order to allow admins to know their ACLs and admin type.
API dependencies has been updated:
- Upgrading irontec/ivoz-api (4.7 => 4.7.1)
- Upgrading irontec/ivoz-api-bundle (4.4 => 4.4.2)

Provider 183 web client acls

---

debian/ivozprovider-web-rest.postinst

Replace swagger export path web/swagger.json for Platform/Brand/Client REST API with correct path public/swagger.json
The current export path for swagger.json is incorrect and so the task fails at post-install, resulting in no swagger API docs - also visible at https://irontec.github.io/

Fix Swagger gen path at install

---

web/admin/application/configs/klear/model/ExternalCallFilters.yaml

Set External Call Filters toggles for Holidays & Calenders disabled by default
Implementation of #1752 for web/admin component

web/admin: Call Filters toggles for Holidays & Calendars disabled by default 

---

web/admin/application/configs/klear/RouteLocksList.yaml
web/admin/application/configs/klear/model/RouteLocks.yaml

This is part of the implementation of #1759 for web/admin component

web/admin: create route locks open by default

---

kamailio/users/config/kamailio.cfg

Using the E.164 number in this comparisson caused errors
in variable converssion to integer. Using DDI id should
also work here to check if the query has returned an
alternative DDI.

kamusers: fix fallback DDI selection validation

---

microservices/realtime/spec/Services/RegistrationChannelResolverSpec.php
microservices/realtime/src/Services/RegistrationChannelResolver.php

Looks like using executeStatements creates unbuffered queries
that triggers errors on new connections after the first one.

realtime: fix mysql reconnection check query

---

library/Ivoz/Provider/Domain/Model/CallForwardSetting/CallForwardSetting.php

Properly validate Retail account call forward settings to avoid data inconsistency.
CfwRetailAccountId is mandatory for retail route types
Also CallFilterType must be forced to 'both' (other filters types doesn't even show the CFW in web admin)

core: properly validate Retail Account Call forward settings

---

kamailio/trunks/config/kamailio.cfg

RTPengine sessions need to be freed when no reply is received from AS or GW (remaining failure cases sessions are freed in onreply_route).
Before this PR, unreachable gateways may cause rtpengine port exhaustion.

kamtrunks: call rtpengine_delete on branch timeout with no reply

---

library/DataFixtures/ORM/KamUsersLocation.php
library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallDto.php
web/rest/brand/features/provider/residentialDevice/getResidentialDeviceStatus.feature
web/rest/client/features/provider/residentialDevices/getResidentialDeviceStatus.feature

Fixed devices/status API responses. It was showing only the first status row
Upport from #1689 for halliday

Api device status error

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

kamcmd-proxyusers cfg.set config maintenance_mode 1
kamcmd-proxytrunks cfg.set config maintenance_mode 1
- Exit Kamailio when no active calls
kamcmd-proxyusers cfg.set config maintenance_mode 2
kamcmd-proxytrunks cfg.set config maintenance_mode 2
- Rejects any request not belonging to any existing dialog (reject new calls)
- Wait until active calls end
- Exit Kamailio when no active calls
kamcmd-proxyusers cfg.set config maintenance_mode 3
kamcmd-proxytrunks cfg.set config maintenance_mode 3
- Rejects any request not belonging to any existing dialog (reject new calls)
- Ends all active calls (generating CDRs)
- Exit Kamailio
May be useful for graceful restarts.
This is an upport from #1667 for halliday

kam: new maintenance mode

---

web/admin/application/library/IvozProvider/Klear/Filter/OutgoingRoutingMode.php
web/admin/application/library/IvozProvider/Klear/Ghost/OutgoingRouting.php

Update Outgoing Routing ghost fields to replace obsolete constants from class with auto-generated from interface.

web/admin: replace OutgointRouting routing mode constants

---

library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallAbstract.php
library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallDtoAbstract.php
library/Ivoz/Provider/Domain/Model/BillableCall/BillableCallInterface.php
library/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateByTrunksCdr.php
library/Ivoz/Provider/Domain/Service/BillableCall/UpdateByTpCdr.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/BillableCall.BillableCallAbstract.orm.xml
library/spec/Ivoz/Provider/Domain/Service/BillableCall/CreateOrUpdateByTrunksCdrSpec.php
schema/DoctrineMigrations/Version20220603083243.php

BillableCalls.direction should not be nullable and it also has a default value.

schema: make BillableCalls direction field not nullable

---

kamailio/trunks/config/kamailio.cfg
library/Ivoz/Kam/Domain/Service/TrunksUacreg/CreatedByDdiProviderRegistration.php
schema/DoctrineMigrations/Version20220624114352.php
schema/tests/Provider/DdiProviderRegistration/DdiProviderRegistrationLifeCycleTest.php

Use contact_addr uacreg database field instead of kamailio.cfg logic.
No functional change.

kamtrunks: use contact_addr uacreg field

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Use rtimer module instead of timer
timer module causes problems (see https://lists.kamailio.org/pipermail/sr-dev/2021-October/064151.html)

kam: use rtimer instead of timer

---

kamailio/trunks/config/kamailio.cfg

Routing logic may add same carrierServer more than once (due to LCR).
This makes no sense as if a carrierServer fails for a call it will also fail for the same call some failover later.
This PR modifies gateways AVP so that a carrier server is included only once (the first time).

kamtrunks: remove duplicates from gws final avp

---

kamailio/trunks/config/kamailio.cfg

If AS returns a negative response, no failover needs to be done in failure, forward that response downstream.
Bounced calls are calls to DDIs handled inside the platform, so no real carrier is involved. Failover logic in failure_route needs to be skipped.

kamtrunks: avoid gw failover on bounced calls

---

doc/sphinx/administration_portal/brand/invoicing/invoice_schedulers.rst
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoice/FixedCostsRelInvoice.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceScheduler.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerAbstract.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerDto.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerDtoAbstract.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/FixedCostsRelInvoiceScheduler.FixedCostsRelInvoiceSchedulerAbstract.orm.yml
schema/DoctrineMigrations/Version20220701103822.php
web/admin/application/configs/klear/FixedCostsRelInvoiceSchedulersList.yaml
web/admin/application/configs/klear/model/FixedCostsRelInvoiceSchedulers.yaml
web/rest/brand/features/provider/fixedCostsRelInvoiceScheduler/getFixedCostsRelInvoiceScheduler.feature
web/rest/brand/features/provider/fixedCostsRelInvoiceScheduler/postFixedCostsRelInvoiceScheduler.feature

Add dynamic fixed costs in scheduled invoices. Quantity of this fixed costs are calculated on invoice generation.
This PR adds fixed costs by client _maxCalls_ value.
- "Max calls" value is retrieved from client configuration at scheduled invoice "Next execution".
- Regenerating the invoice later would not modify assigned value.

Dynamic fixed costs by client maxCalls in scheduled invoices

---

library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOut.php
library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOutAbstract.php
library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOutDtoAbstract.php
library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOutInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/FaxesInOut.FaxesInOutAbstract.orm.xml
schema/DoctrineMigrations/Version20220707125449.php
web/rest/client/config/api/raw/provider.yml

Because of recent model changes we've lost the hability to make required entity methods nullable (it's checked during fromDto execution). Fix FaxesInOut so that callDate is not requested

Fix unable to create faxes in out without call date

---

doc/sphinx/administration_portal/brand/invoicing/invoice_schedulers.rst
library/Ivoz/Provider/Domain/Model/Ddi/DdiRepository.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoice/FixedCostsRelInvoice.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoice/FixedCostsRelInvoiceInterface.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceScheduler.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerAbstract.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerDto.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerDtoAbstract.php
library/Ivoz/Provider/Domain/Model/FixedCostsRelInvoiceScheduler/FixedCostsRelInvoiceSchedulerInterface.php
library/Ivoz/Provider/Domain/Service/FixedCostsRelInvoice/CreateByScheduler.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/DdiDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/FixedCostsRelInvoiceScheduler.FixedCostsRelInvoiceSchedulerAbstract.orm.xml
library/phpstan-baseline.neon
library/psalm-baseline.xml
schema/initial.sql
schema/tests/Provider/BrandService/BrandServiceRepositoryTest.php
schema/tests/Provider/Ddi/DdiRepositoryTest.php
web/admin/application/configs/klear/FixedCostsRelInvoiceSchedulersList.yaml
web/admin/application/configs/klear/conf.d/ddisMatchHelp.yaml
web/admin/application/configs/klear/model/FixedCostsRelInvoiceSchedulers.yaml
web/admin/application/languages/ca_ES/ca_ES.po
web/admin/application/languages/en_US/en_US.po
web/admin/application/languages/es_ES/es_ES.po
web/admin/application/languages/it_IT/it_IT.po
web/admin/application/library/IvozProvider/Klear/Ghost/FixedCostsRelInvoiceSchedulers.php
web/rest/brand/features/provider/fixedCostsRelInvoiceScheduler/getFixedCostsRelInvoiceScheduler.feature
web/rest/brand/features/provider/fixedCostsRelInvoiceScheduler/postFixedCostsRelInvoiceScheduler.feature

Add DDI criteria in dynamic fixed costs added in https://github.com/irontec/ivozprovider/pull/1847
You may choose the country you want and only DDIs of that country will be taken into account.
This is an upport from 1849

Dynamic fixed costs by client DDI in scheduled invoices

---

web/admin/application/configs/klear/ResidentialDevicesList.yaml
web/rest/client/config/api/raw/provider.yml
web/rest/client/features/provider/residentialDevices/putResidentialDevice.feature

Residential devices must be editable by residential admins (everything but name)
This PR is an upport for #1745

Residential devices must be editable by residential admins

---

library/Ivoz/Provider/Application/Service/ResidentialDevice/ResidentialDeviceDtoAssembler.php
library/Ivoz/Provider/Domain/Model/ResidentialDevice/ResidentialDeviceDto.php
library/psalm.xml
web/client/src/entities/ResidentialDevice/Form.tsx
web/client/src/entities/ResidentialDevice/ResidentialDevice.tsx
web/client/src/entities/ResidentialDevice/ResidentialDeviceProperties.tsx
web/client/src/entities/ResidentialDevice/foreignKeyGetter.tsx
web/rest/brand/features/provider/residentialDevice/getResidentialDevice.feature
web/rest/brand/features/provider/residentialDevice/getResidentialDeviceStatus.feature
web/rest/client/features/provider/residentialDevices/getResidentialDevice.feature
web/rest/client/features/provider/residentialDevices/getResidentialDeviceStatus.feature
web/rest/client/features/provider/residentialDevices/putResidentialDevice.feature
web/rest/client/features/provider/voicemail/postVoicemail.feature

Removed API endpoints that are not supposed to be acccesed by client admin and fixed residential device list screen

Fix residential devices on new client portal

---

web/admin/application/configs/klear/VoicemailsList.yaml
web/portal/client/src/entities/Voicemail/Form.tsx
web/portal/client/src/entities/Voicemail/Voicemail.tsx

This field doesn't make sense for Residential clients, because there is no way to upload Locutions for this client type.

Remove Locution field from Residential Device voicemails

---

web/admin/application/configs/klear/DdisList.yaml
web/admin/application/configs/klear/RetailAccountsList.yaml

It was throwing error 500: `Configuration for selected option [exportBillableCallsToCsv_command, type: commands] not found`

web/admin: fixed Retail Accounts > DDI > External calls screen

---

web/admin/application/library/IvozProvider/Klear/Ghost/RegisterStatus.php

When a DDI Provider registration witn non random username is created, the status field ghost queries proxytrunks to check registration status. This raises an exception if no information is found that renders the screen unusable.
This PR aims to fix that problem.

web/admin: fix DDI PRovider Registation status check

---

web/admin/application/library/IvozProvider/Klear/Ghost/RegisterStatus.php

When a DDI Provider registration witn non random username is created, the status field ghost queries proxytrunks to check registration status. This raises an exception if no information is found that renders the screen unusable.
This PR aims to fix that problem.

web/admin: fix initial DDI PRovider Registation status check

---

web/portal/user/src/entities/UsersCdr/UsersCdr.tsx

This PR modifies UsersCdr entity ordering startTime property in an ascendent order (most recent calls first).

web/user: Ordered asc by startTime call in UsersCdr.

---

kamailio/users/config/kamailio.cfg

Call-forward from retail accounts are sent through Asterisk. If the retail account has media encryption enabled, INVITE to AS was sent with RTP/SAVP transport, causing 488 failure.
This PR fixes this situation.

kamusers: no savp when talking to as

---

kamailio/users/config/kamailio.cfg

- Increase presence _clean_period_ from 15 to 100 seconds.
- Do not generate PUBLISH if no active watcher.
- Do not admit SUBSCRIBE to non-existent users.
About _clean_period_ change:
clean_period was set to 15 instead of default 100 value in f6addae35 (PR #1570)
to have BLF light off asap in case of rejected call establishments.
To avoid extensive database usage, this value goes back to its default value of 100.
With this change, BLF light will be off a bit later (not 3 hours as the Kamailio
patch persists, but neither 30 seconds... new intermediate reasonable value: 2-3 minutes)
It is a valid value because this reject call establishment are quite rare and database
access is expensive.
About not generating PUBLISH if no active watcher found:
Drawback: the first watcher of a given …

Kamusers: minimize presence database usage

---

library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersLocationAttr.UsersLocationAttr.orm.xml
schema/DoctrineMigrations/Version20220929101012.php

Change kam_users_location_attrs id to bigint to avoid easily reaching max value.
This table has lots of inserts and deletes so auto increment id raises quite fast.

schema: change kam_users_location_attrs id to bigint

---

library/Ivoz/Provider/Domain/Model/CompanyRelRoutingTag/CompanyRelRoutingTag.php
library/Ivoz/Provider/Domain/Model/CompanyRelRoutingTag/CompanyRelRoutingTagInterface.php
library/Ivoz/Provider/Domain/Service/CompanyRelRoutingTag/CheckCompanyType.php
library/Ivoz/Provider/Domain/Service/CompanyRelRoutingTag/CompanyRelRoutingTagLifecycleServiceCollection.php
library/phpstan-baseline.neon

Fixes a Company type validation done when a Routing tag is assigned to a company.
This check can not be done in the setter or sanitize of the rel entity because company field is not yet assigned.

core: convert routing tag company type validation into a service

---

debian/ivozprovider-profile-proxy.postinst
library/DataFixtures/ORM/KamRtpengine.php
schema/DoctrineMigrations/Version20221007090801.php
web/admin/application/configs/klear/model/KamRtpengine.yaml
web/rest/platform/features/kam/rtpengine/getRtpengine.feature
web/rest/platform/features/kam/rtpengine/postRtpengine.feature

By default in ivozprovider, rtpengine uses 13000 to 19000 for media ports. Moving the control port from 22223 to 2223 allows increasing this range when required.

Change rtpengine control port to 2223

---

kamailio/users/config/kamailio.cfg

URL decode replaces + in $rU with a whitespace and causes invalid URI.
This PR avoids this wrong decode.

kamusers: fix URL-decode $rU

---

asterisk/agi/src/Agi/ChannelInfo.php

When a user calls to a HuntGroup where some of the users have Call Forward configured, the call origin information was being lost due to wrong variable inheritance.

Fix call forward presentation in Hunt Groups users' Call Forwards

---

kamailio/trunks/config/kamailio.cfg

Some carriers use username params in URIs of within-dialog requests. Example:
```
From: <sip:XXXYYYZZZ;phone-context=+34@A.B.C.D;user=phone>;correlation-id=56752665;tag=l9quzgg4-267aw
```
These params makes SQL-injection fail, so this mechanism will be skipped for within-dialog requests.

kamtrunks: skip sql-injector detector for within-dialog reqs

---

library/Ivoz/Cgr/Domain/Model/TpCdr/TpCdr.php
library/Ivoz/Cgr/Domain/Model/TpCdr/TpCdrAbstract.php
library/Ivoz/Cgr/Domain/Model/TpCdr/TpCdrDtoAbstract.php
library/Ivoz/Cgr/Domain/Model/TpCdr/TpCdrInterface.php
library/Ivoz/Kam/Domain/Model/UsersLocationAttr/UsersLocationAttr.php
library/Ivoz/Kam/Domain/Model/UsersLocationAttr/UsersLocationAttrDtoAbstract.php
library/Ivoz/Kam/Domain/Model/UsersLocationAttr/UsersLocationAttrInterface.php
library/Ivoz/Kam/Domain/Model/UsersLocationAttr/UsersLocationAttrTrait.php
library/composer.lock
schema/composer.lock

Doctrine casts bigint db fields to string but we hint them as integer which causes runtime issues
More info: https://github.com/irontec/ivozprovider/pull/new/PROVIDER-566-errores-de-conversion-tp-cdr-get-usage

Fix bigint issues

---

microservices/provision/templates/provisioning/SPA502G/generic.cfg
microservices/provision/templates/provisioning/SPA504G/generic.cfg
microservices/provision/templates/provisioning/SPA509G/generic.cfg
microservices/provision/templates/provisioning/SPA514G/generic.cfg
microservices/provision/templates/provisioning/SPA525G2/generic.cfg
web/admin/templates/provisioning/SPA502G/generic.cfg
web/admin/templates/provisioning/SPA504G/generic.cfg
web/admin/templates/provisioning/SPA509G/generic.cfg
web/admin/templates/provisioning/SPA514G/generic.cfg
web/admin/templates/provisioning/SPA525G2/generic.cfg

This changes fix a typo in generic config provision files.

Modified SPA50*.cfg for firmwareVersion variable typo.

---

library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php

This error happens when retrieving LcrGatewayInfo and the object composition changes between versions 5.1 and 5.4 of Kamailio.

Fixed object error in TrunksClient.

---

library/Ivoz/Provider/Domain/Model/Terminal/TerminalRepository.php
library/Ivoz/Provider/Domain/Model/User/UserRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BrandDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/TerminalDoctrineRepository.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/UserDoctrineRepository.php
library/psalm-baseline.xml
microservices/provision/config/routes.yaml
microservices/provision/config/services.yaml
microservices/provision/psalm.xml
microservices/provision/src/Controller/ProvisionController.php
microservices/provision/src/Services/Provision.php
microservices/provision/src/Services/ProvisionGeneric.php
microservices/provision/src/Services/ProvisionSpecific.php
microservices/provision/src/Services/TemplateRenderer.php
schema/tests/Provider/Terminal/TerminalRepositoryTest.php

This issue modifies the existent provision microservice to perform a provisioning process for specific provision templates of different terminal manufacturers and their corresponding models.

Serve specific provision templates

---

library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php
library/phpstan-baseline.neon

This PR prevents this exception when accessing Carriers section using Klear web portal:
`
klear[1550304]: Exception captured [500]: Ivoz\Kam\Infrastructure\Kamailio\TrunksClient::getLcrGatewayInfo(): Return value must be of type array, stdClass returned (0) # /opt/irontec/ivozprovider/library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php (141)
`

core: return array as defined in function header

---

kamailio/users/config/kamailio.cfg
kamailio/users/config/pushservers.cfg.in

Upport #1971.
Cherry-pick and additional commit to use rtimer instead of timer (preferred module in 5.6).

kamusers: skip IP filter for push servers

---

doc/sphinx/administration_portal/brand/clients/residential.rst
doc/sphinx/administration_portal/brand/clients/retail.rst
doc/sphinx/administration_portal/brand/clients/virtual_pbx.rst
doc/sphinx/administration_portal/brand/clients/wholesale.rst
doc/sphinx/administration_portal/brand/providers/carriers.rst
kamailio/trunks/config/kamailio.cfg
library/Ivoz/Provider/Domain/Model/Company/CompanyAbstract.php
library/Ivoz/Provider/Domain/Model/Company/CompanyInterface.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.xml
schema/DoctrineMigrations/Version20230124171627.php
web/admin/application/configs/klear/model/Companies.yaml
web/admin/application/configs/klear/model/ResidentialClients.yaml
web/admin/application/configs/klear/model/RetailClients.yaml
web/admin/application/configs/klear/model/WholesaleClients.yaml
web/portal/brand/src/entities/Company/Company.tsx

In Artemis _externallyRated_ setting was related to Carriers. In Halliday, _externallyRated_ is going to be related to Companies.
This way, calls from a given company may or may not be rated, no matter which carrier is used to place calls.
This is a **breaking change** for platforms using a mix of _externallyRated_ carriers and non-_externallyRated_ ones for a given company. This was quite weird, as a call from a client A to a destination B may have rating details (price and cost) depending on the carrier used to place that specific call at that specific moment:
- If used carrier was marked as _externallyRated_: no rating details were calculated.
- Otherwise, rating details were calculated.
This was even more misleading as clients may call to to destinations not included in their pricing …

Make externallyRated a company setting

---

kamailio/trunks/config/kamailio.cfg

route(RTPENGINE) route needs dlg_var(mediaRelaySetId) to be set in order to assign proper media-relay to each call depending on which carrier/ddiprovider is involved.
With previous logic, it was used before being assigned, so it failed.
Besides, on _failure_route_ was not invoked again (to choose proper media-relay of eventual failover carrier).
This commit tries to fix this initial RTPENGINE call, calling it after mediaRelaySetId is set.
It also re-invokes RTPENGINE route so that calls through failover carriers use proper media-relay too.

kamtrunks: fix carrier/ddiprovider mediarelay selection

---

library/Ivoz/Provider/Domain/Model/Carrier/CarrierDto.php
library/Ivoz/Provider/Domain/Model/Carrier/CarrierStatus.php
library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerDto.php
library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerStatus.php
web/rest/brand/config/api/raw/provider.yml
web/rest/brand/features/provider/carrierServer/getCarrierServer.feature
web/rest/brand/features/provider/carrierServer/getCarrierServerStatus.feature

This fix adds attribute definitions to help ivoz-api be able to expose them as documentation Models.

Status definitions in api are not correct

---

kamailio/users/config/kamailio.cfg

Create different media-session for different branches of the same call (due to parallel-forking enabled UAC). This way, each of them can be configured independently.
This PR fixes this known situations as no audio in calls where a branch replies 183 with SDP but the call is answered by a different branch.

kamusers: handle parallel-forking media-sessions properly

---

library/DataFixtures/ORM/ProviderVoicemail.php
web/rest/client/config/api/raw/provider.yml
web/rest/client/features/provider/voicemail/postVoicemail.feature
web/rest/client/features/provider/voicemail/removeVoicemail.feature

Current API ACLs allows deletion of Voicemails associated to Users and Residential Devices. This PR fixes that to only permit generic voicemails removal.

Fix Voicemail rest API delete ACLs

---

web/portal/brand/src/App.tsx
web/portal/client/src/App.tsx
web/portal/platform/src/App.tsx
web/portal/user/src/App.tsx
web/rest/brand/public/index.php
web/rest/client/public/index.php
web/rest/platform/public/index.php
web/rest/user/public/index.php

- Keep klear session on new portal login
- Allow to have a tab in platform portal and another one in client/brand/user without losing the first token

Session & Login conflicts

---

Jenkinsfile
library/bin/test-psalm-update-baseline
library/psalm-baseline.xml
microservices/balances/psalm-baseline.xml
microservices/provision/psalm-baseline.xml
microservices/provision/psalm.xml
web/rest/user/psalm-baseline.xml

Unline PHPStan, Psalm does not check its baseline for exceptions that no longer apply, so this PR adds a test to the pipeline that regenerates Psalm baselines and ensures all existing exceptions still apply.

Add psalm baseline test to Jenkins pipeline

---

microservices/workers/psalm-baseline.xml
microservices/workers/src/Worker/KamRpc.php

When redis fails on blPop it's returning false value instead of expected array. Handle this scenario in a better way.

Enhanced redis blpop errors

---

library/Ivoz/Provider/Domain/Model/MatchList/MatchListDto.php
web/portal/client/src/entities/MatchList/MatchList.tsx
web/portal/client/src/entities/MatchList/MatchListProperties.tsx
web/rest/brand/features/provider/matchList/putMatchList.feature
web/rest/client/config/api/raw/provider.yml
web/rest/client/features/provider/callAclRelMatchList/getCallAclRelMatchList.feature
web/rest/client/features/provider/callAclRelMatchList/postCallAclRelMatchList.feature
web/rest/client/features/provider/conditionalRoutesConditionsRelMatchlist/getConditionalRoutesConditionsRelMatchlist.feature
web/rest/client/features/provider/conditionalRoutesConditionsRelMatchlist/postConditionalRoutesConditionsRelMatchlist.feature
web/rest/client/features/provider/externalCallFilterBlackList/getExternalCallFilterBlackList.feature
web/rest/client/features/provider/externalCallFilterBlackList/postExternalCallFilterBlackList.feature
web/rest/client/features/provider/externalCallFilterWhiteList/getExternalCallFilterWhiteList.feature
web/rest/client/features/provider/externalCallFilterWhiteList/postExternalCallFilterWhiteList.feature
web/rest/client/features/provider/matchList/getMatchList.feature
web/rest/client/features/provider/matchList/postMatchList.feature
web/rest/client/features/provider/matchList/putMatchList.feature
web/rest/client/features/provider/outgoingDdiRulesPattern/getOutgoingDdiRulesPattern.feature
web/rest/client/features/provider/outgoingDdiRulesPattern/postOutgoingDdiRulesPattern.feature

MatchLists are used in brand (aka generic matchlists) and client portals.
Brand MatchLists have brandId with value and companyId set to NULL.
Client MatchLists have brandId set to NULL and companyId with value.
Brand Administrators can only work (read/write/delete) with their own Brand MatchLists.
Client Administrators can read Brand MatchLists, but can only work (read/write/delete) with their own Client MatchLists.
Same logic applies to its child entity MatchListPattern, although not implemented here.

Review MatchLists rest API ACLS

---

web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/notificationTemplate/postNotificationTemplate.feature
web/rest/platform/features/provider/notificationTemplate/putNotificationTemplate.feature
web/rest/platform/features/provider/notificationTemplate/removeNotificationTemplate.feature

Only read Notification Templates entity.

Remove default notification templates crud from rest platform

---

profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf

Replace token values in logs with [MASKED] 
```
- - [10/Feb/2023:13:36:38 +0100] "GET /client/?target=1&token=[MASKED] HTTP/2.0" 200 926 "https://1.1.1.1/brand/vPbx" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
- - [10/Feb/2023:13:36:38 +0100] "GET /client/assets/index.5265c558.css HTTP/2.0" 200 649 "https://1.1.1.1/client/?target=1&token=[MASKED] "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
- - [10/Feb/2023:13:36:38 +0100] "GET /client/assets/index.226e74ea.js HTTP/2.0" 200 390956 "https://1.1.1.1/client/?target=1&token=[MASKED] "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
- - [10/Feb/2023:13:36:39 +0100] "POST …
```

portals: hide token params from apache logs

---

tests/docker/Dockerfile
tests/docker/bin/prepare-and-run

Improve prepare times by caching node_modules in Docker image

Add yarn cache in testing Docker image

---

web/portal/client/src/entities/PickUpGroup/Form.tsx
web/portal/client/src/entities/PickUpGroup/PickUpGroup.tsx

UserIds was not defined as array of FKs

Fixed pick up group form issues

---

kamailio/users/config/kamailio.cfg

Before this PR UACs were supposed to reach KamUsers as first hop (no middle-proxy, no Record-Route in requests).
This PR adapts KamUsers to received proxied UAC, both of them behind NAT. On these escenarios Record-Route inserted by middle-proxy has a non-reachable address, so it needs to be handled.
No functional change if no proxied UACs.

kamusers: handle proxied behind NAT UAC

---

web/portal/platform/src/entities/Brand/Brand.tsx

It was showing ids instead of string values

Fixed features resolution in brand lists

---

web/portal/platform/src/entities/Brand/Brand.tsx
web/portal/platform/src/entities/Brand/ForeignKeyResolver.tsx

It was showing the id instead of a string value

Fixed brand.proxyTrunks foreign key resolver

---

library/Ivoz/Provider/Domain/Model/Brand/BrandDtoAbstract.php
library/Ivoz/Provider/Domain/Model/Brand/Invoice.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Brand.Invoice.orm.xml
schema/DoctrineMigrations/Version20230301093113.php

Default empty value for brand invoicing fields

Brand invoicing issues

---

debian/ivozprovider-profile-common.preinst

Some setups that use cloudinit or other provisioners, resolv.conf file is a symlink to /run/ so its contents doesn't persist to reboots. This PR breaks the symlink before setting the local DNS configuration.

pkg: remove resolv.conf symlink before setting local DNS resolution

---

asterisk/agi/src/Agi/Action/IvrAction.php

Remove duplicated success locution when an ivr entry matches and have custom entry locution

Fix duplicated IVR Entry success locution

---

web/portal/platform/src/entities/MediaRelaySet/MediaRelaySet.tsx
web/rest/platform/config/api/raw/provider.yml
web/rest/platform/features/provider/domain/getDomains.feature

Removed elements from domain list if domain attributes matches  *.local

Portal platform domain list cannot show user ivozprovider local nor proxy trunks ivozprovider local

---

library/Ivoz/Provider/Domain/Model/RatingPlan/RatingPlanDto.php
library/psalm-baseline.xml

Portal brand destination rate when fix fails when timing is always

Portal brand destination rate when timing is always it fails

---

kamailio/users/config/kamailio.cfg

Asterisk send out-of-dialog NOTIFY requests with MWI related info. Leave them traverse KamUsers.
This was accidentally removed in eb054231f28c4e51aeb52ae6cdf5a8bce9bc7daf inside #1742

kamusers: allow unsolicited notify from asterisk for mwi

---

web/admin/application/configs/klear/ResidentialClientsList.yaml

Fix `Call to undefined method Ivoz\Provider\Domain\Model\Company\CompanyDto::setPostalAddress() (0) # /opt/irontec/klear/modules/klearMatrix/controllers/helpers/Column2Model.php` error on residential client creation

web/admin: fixed residential client forced values

---

library/Ivoz/Ast/Domain/Service/PsIdentify/UpdateByFriend.php
library/Ivoz/Ast/Domain/Service/PsIdentify/UpdateByResidentialDevice.php
library/Ivoz/Ast/Domain/Service/PsIdentify/UpdateByRetailAccount.php
library/Ivoz/Ast/Domain/Service/PsIdentify/UpdateByTerminal.php
schema/tests/Provider/Friend/FriendLifeCycleTest.php
schema/tests/Provider/ResidentialDevice/ResidentialDeviceLifeCycleTest.php
schema/tests/Provider/RetailAccount/RetailAccountLifeCycleTest.php
schema/tests/Provider/Terminal/TerminalLifeCycleTest.php

PsIdentify entities must be updated when its owner entity (Terminal, Friend, Residential Device or Retail Account) changes. Otherwise, some data like endpoint name is not properly synced.

Update PsIdentify when owner entity changes

---

web/portal/platform/src/router/EntityMap.ts

It was showing both god and brand portals

Filter platform web portals properly

---

library/Ivoz/Provider/Domain/Model/Administrator/Administrator.php
library/Ivoz/Provider/Domain/Model/Administrator/AdministratorInterface.php
library/Ivoz/Provider/Domain/Model/Administrator/AdministratorRepository.php
library/Ivoz/Provider/Infrastructure/Api/Timezone/UserTimezoneInjector.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/AdministratorDoctrineRepository.php
schema/tests/Provider/Administrator/AdministratorRepositoryTest.php

Use original admin timezone instead

Ignore internal admin timezones in UserTimezoneInjector

---

web/portal/platform/src/entities/BillableCall/BillableCall.tsx
web/portal/platform/src/entities/BillableCall/ForeignKeyResolver.tsx
web/portal/platform/src/entities/Ddi/Ddi.tsx
web/portal/platform/src/entities/DdiProvider/DdiProvider.tsx

Fixed path literal in DDi entity from platform portal, and exposed its collection in the API.

Portal platform not found snackbar when inital load at list

---

asterisk/agi/composer.lock
library/Ivoz/Provider/Domain/Model/Administrator/Administrator.php
library/Ivoz/Provider/Infrastructure/Api/Jwt/JWTCreatedListener.php
library/composer-packages/irontec/ivoz-provider-bundle/Resources/config/services/infraestructure/rest.yml
library/composer-packages/irontec/ivoz-provider-bundle/composer.json
library/composer.lock
microservices/balances/composer.lock
microservices/provision/composer.lock
microservices/realtime/composer.lock
microservices/recordings/composer.lock
microservices/scheduler/composer.lock
microservices/workers/composer.lock
schema/composer.lock
web/rest/brand/composer.lock
web/rest/client/composer.lock
web/rest/platform/composer.lock
web/rest/user/composer.lock

Persist admin impersonation chain in the commandlog

Impersonate admin chain in commandlog

---

web/portal/package.json
web/portal/platform/src/entities/TerminalModel/Form.tsx
web/portal/yarn.lock

Added width and empty content to specific and generic templates
Added width and empty content to specific and generic templates

Added width and empty content to specific and generic templates

---

web/portal/brand/src/entities/MatchListPattern/Field/MatchValue.tsx

Added condition to work with regexp type in custom match value component.
Added condition to work with regexp type in custom match value component.

Added condition to be able to work with regexp type

---

library/Ivoz/Provider/Application/Service/HolidayDate/SyncFromCsv.php
library/Ivoz/Provider/Domain/Service/HolidayDate/HolidayDateFactory.php
web/rest/client/config/api/resources.yml
web/rest/client/config/routes.yaml
web/rest/client/features/provider/holidayDate/postHolidayDateMassImport.feature
web/rest/client/src/Controller/Provider/PostHolidaysMassImportAction.php
web/rest/client/src/Model/HolidaysMassImport.php

Feature that includes the option for upload a csv file and create holiday Dates for a given calendar
From now, loaded file for holiday dates importation, the elements must be quoted and separated by a comma.
`"Christmas eve","2018-12-24"
"New year's day","2019-01-01"
"New year's day new","2020-01-01"`

Back web client import holidays

---

profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf

This was broken when we added /classic path support. Before this commit the doc was available at /classic/doc, not it can also be accessed in /doc

portal: add apache /doc alias for documentation

---

profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf

Allow blob as media-src in Content-Security-Policy so that web audio player does not complain about security rules

Fixed audio players

---

web/rest/client/CHANGELOG.md

Updated API changelog for v3.4
`/my/active_calls/realtime_filter` endpoints have been ignored as they are considered internal

v3.4 API changelog

---

kamailio/users/config/kamailio.cfg

nat_uac_test(18) is always true for responses due to Via tests (thanks @manwe :)
Use NAT flags instead calling nat_uac_test(18) inside RTPENGINE route, that is also used in responses.
RTPENGINE was called inside NATMANAGE route. Now it is called afterwards, to ensure that NAT flags are correctly set for both initial and within-dialog requests and responses.

kamusers: avoid nat_uac_test(18) for responses

---

kamailio/users/config/kamailio.cfg
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrAbstract.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrDtoAbstract.php
library/Ivoz/Kam/Domain/Model/UsersCdr/UsersCdrInterface.php
library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.xml
schema/DoctrineMigrations/Version20231124114023.php

kam_users_cdrs will store non-established calls (failed calls, missed calls). This PR adds a new field responseCode that will be non-200 for these calls.
Upcoming PRs will show these calls on both vpbx client portal and user portal.

Store user-side missed calls

---

web/portal/brand/.eslintrc.js
web/portal/brand/src/components/ActiveCalls/ActiveCalls.helpers.tsx
web/portal/brand/src/components/ActiveCalls/ActiveCalls.styles.tsx
web/portal/brand/src/components/ActiveCalls/ActiveCalls.tsx
web/portal/brand/src/components/ActiveCalls/FilterComponent.tsx
web/portal/brand/src/components/ActiveCalls/hooks/useCriteriaChangeListener.tsx
web/portal/brand/src/components/ActiveCalls/hooks/useRealtimeCalls.tsx
web/portal/brand/src/components/ActiveCalls/hooks/useWsClient.ts
web/portal/brand/src/components/ActiveCalls/types.ts
web/portal/brand/src/entities/ActiveCalls/ActiveCalls.tsx
web/portal/brand/src/entities/ActiveCalls/ActiveCallsProperties.tsx
web/portal/brand/src/translations/ca.json
web/portal/brand/src/translations/en.json
web/portal/brand/src/translations/es.json
web/portal/brand/src/translations/it.json
web/portal/package.json
web/portal/yarn.lock

Brand portal active calls filters

---

library/DataFixtures/ORM/ProviderBrand.php
library/Ivoz/Provider/Domain/Model/Brand/Brand.php
library/spec/Ivoz/Provider/Domain/Model/Brand/BrandSpec.php
web/portal/platform/src/entities/Brand/Brand.tsx

Require Brand.domainUsers if residential or retail features are enabled.

Required SIP domain

---

kamailio/users/config/kamailio.cfg

KamUsers generated errors (e.g. 486 due to maxcalls) get responseCode null ($rs is null in dialog:failed event route) and cdr fails as it cannot be null.
This PR adds 500 default response code for KamUsers generated errors.

kamusers: 500 as default responseCode for internal errors

---

library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrAbstract.php
library/Ivoz/Provider/Domain/Model/UsersCdr/UsersCdrInterface.php
library/Ivoz/Provider/Domain/Service/UsersCdr/MigrateFromKamUsersCdr.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/UsersCdr.UsersCdrAbstract.orm.xml
schema/DoctrineMigrations/Version20240126093233.php
web/portal/client/src/entities/UsersCdr/UsersCdr.tsx

Add "error" in UserCdr.disposition enum values

UserCdr disposition "error" value

---

library/Ivoz/Kam/Domain/Service/TrunksUacreg/CreatedByDdiProviderRegistration.php
schema/tests/Provider/DdiProviderRegistration/DdiProviderRegistrationLifeCycleTest.php

After #2491 kam_trunks_uacreg entries should use advertised address of DDIProvider socket (if any).

core: set uacreg contact to advertised address (if any)

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Use from-domain if diversion-domain is empty, to avoid a new Diversion header with empty domain.

kam: avoid empty Diversion domain

---

library/DataFixtures/ORM/ProviderAdministrator.php
library/Ivoz/Provider/Domain/Model/Administrator/Administrator.php
library/Ivoz/Provider/Infrastructure/Api/Timezone/UserTimezoneInjector.php
library/spec/Ivoz/Provider/Domain/Model/Administrator/AdministratorSpec.php
schema/DoctrineMigrations/Version20240202081754.php
web/portal/brand/src/components/Login.tsx
web/portal/brand/src/entities/Administrator/Action/Impersonate.tsx
web/portal/brand/src/entities/Administrator/Action/index.ts
web/portal/brand/src/entities/Administrator/Administrator.tsx
web/portal/brand/src/router/AppRoutesGuard.tsx
web/portal/brand/src/router/EntityMap.ts
web/portal/client/src/components/Login.tsx
web/portal/client/src/router/AppRoutesGuard.tsx
web/portal/package.json
web/portal/platform/src/entities/Administrator/Action/Impersonate.tsx
web/portal/platform/src/entities/Administrator/Action/index.ts
web/portal/platform/src/entities/Administrator/Administrator.tsx
web/portal/platform/src/router/EntityMap.ts
web/portal/yarn.lock
web/rest/brand/features/exchangeTimezones.feature
web/rest/brand/src/Service/Behat/FeatureContext.php

From now on internal admins will inherit timezone from their parent admin (the first one that is not internal in the impersonation chain). On the other hand, "real admin" impersonation will keep it's timezone.

Enhanced tz conversion on API impersonation

---

schema/DoctrineMigrations/Version20231218161807.php

Don't assume language ids are 1, 2, 3 and 4 (like in the initial.sql dump)

Fix Language ids of Access Credentials notification migration

---

kamailio/users/config/kamailio.cfg

X-Info-Endpoint header is used in Asterisk to identify calling peer. This header is added by KamUsers and was added wrong for retail call forwards.
This PR fixes this minor bug.

kamusers: fix X-Info-Endpoint for retail call-forward

---

asterisk/agi/composer.json
asterisk/agi/composer.lock
asterisk/agi/config/services.yaml
asterisk/agi/symfony.lock
library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOut.php
library/Ivoz/Provider/Domain/Model/FaxesInOut/FaxesInOutDto.php
library/Ivoz/Provider/Domain/Service/FaxesInOut/FaxesInOutLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/FaxesInOut/SendFaxFile.php
library/phpstan-baseline.neon
library/psalm-baseline.xml
web/rest/client/features/provider/faxesInOut/postFaxesInOut.feature

This PR includes a group of fixes to make Faxes work again:
- File uploaded through API was not being stored in storage path
- Faxes configured to send emails was not working
- PDF to TIF conversion was using a library not included as dependency
- Send request was being sent before the entity was totally saved in database

Fix errors while sending faxes through rest API  

---

microservices/realtime/pkg/services/redis_helper.go

TTL of keys stored with SETEX can not be overwritten by another SETEX with a different TTL. This was causing all keys to be stored only during 2 minutes (initial TTL when a call wasn't been answered).
The easiest approach here is to create keys with 3 hours TTL (the one intended to be used when a call was answered) instead of mixing two different types of TTL based on call status.

Set all realtime keys TTL to 3 hours

---

cgrates/scripts/cgrates-reload
debian/ivozprovider-profile-proxy.postinst

When this script is run with `-b all` flag, it makes a database query that must be run in data.ivozprovider.local with credentials

Fix cgrates-reload database access for all brands reloading

---

kamailio/users/config/kamailio.cfg

In version 4 presence is handled in AS nodes. Prior versions handled presence in Kamailio users proxy.
_Event: as-feature-event_ SUBSCRIBEs are rejected by Asterisk and causes UACs to retry a lot. After a while, legitimate UACs get banned by PIKE.
This PR drops this kind of unsupported SUBSCRIBE messages to avoid this pike ban.

kamusers: drop as-feature-event to avoid pike

---

microservices/provision/templates/provisioning/SnomD375/generic.cfg
microservices/provision/templates/provisioning/SnomD717/generic.cfg
microservices/provision/templates/provisioning/SnomD735/generic.cfg
microservices/provision/templates/provisioning/SnomD785/generic.cfg

This function is not longer allowed to be called in provisioning templates, so if you specify a provisioning site certificate in generic provisioning, paste the whole certificate content in the template.

Remove file_get_contents from generic SNOM templates

---

kamailio/users/config/kamailio.cfg

Recover route[PRESENCE] to avoid presence requests traverse INVITE-only logics.
No functional change, just avoid some error logs.

kamusers: avoid presence requests in invite logics

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

No failover is needed when AS replies 404.

kamusers+kamtrunks: avoid AS failover on 404

---

kamailio/users/config/kamailio.cfg

Presence initial requests should be record_routed.
This bug was introduced in https://github.com/irontec/ivozprovider/pull/2561/commits/cd6afb566535da55ec86217b8e9fea41ecee054c

kamusers: record-route initial presence requests

---

profiles/portal/etc/supervisor/conf.d/asterisk-dialplan.conf
profiles/portal/etc/supervisor/conf.d/asterisk-hints.conf
profiles/portal/etc/supervisor/conf.d/kamrpc-daemon.conf
profiles/portal/etc/supervisor/conf.d/kamrpc-delayed-daemon.conf

Use default startsecs to detect when a worker is not running

Use default startsecs for supervisord workers

---

kamailio/users/config/kamailio.cfg

Refer-to header may be too long for a 128 varchar.
This PR saves into $dlg_var(referee) just the URI in Refer-to.

kamusers: save Refer-to URI in dlg_var(referee)

---

schema/DoctrineMigrations/Version20240315103713.php
web/portal/client/src/entities/CallAclRelMatchList/CallAclRelMatchList.tsx
web/portal/client/src/entities/HolidayDateRange/HolidayDateRange.tsx
web/rest/client/config/api/raw/provider.yml

Fixed bug in add holiday ranges access control.
Access control for was not enforced for client Holiday Date Ranges if logged with a restricted administrator.

Unable to calculate acls in client portal

---

library/composer.json

Include Ivoz namespace in library autoload
This was causing errors in terminal provisioning generated templates

Fixed library composer autoload rules

---

profiles/portal/etc/apache2/conf-available/realtime.conf

This value is 300 seconds by default and causes Active Calls section timeouts when no call is displayed.

Increase websocket idle timeout to 3600 seconds

---

kamailio/users/config/kamailio.cfg

Cisco phones send in-dialog SUBSCRIBEs with wrong R-URI. This PR fixes R-URI so that it can be correctly routed to application server.

kamusers: save external element Contact for Cisco phones

---

kamailio/users/config/kamailio.cfg

Behind NAT UACs routing their requests through a intermediate external SIP proxy are not being handled correctly (only SUBSCRIBEs). Prior to version 4 presence messaged where handled in Kamailio, but since version 4 they are routed to application server.
This PR avoids Contact handling for non-first-hop SUBSCRIBE requests so that they are routed properly (equal to remaining non-first-hop requests).

kamusers: fix behind nat proxied SUBSCRIBEs

---

web/portal/brand/src/router/EntityMap.ts

The "Route Labels" section does not have to be displayed in the brand portal without retail/wholesale features

Hide "Route Labels" if brand has not retail or wholesale features

---

kamailio/users/config/kamailio.cfg

Discard in KamUsers SUBSCRIBE requests no non-existing hints.
This way Asterisk is not bothered.

kamusers: discard SUBSCRIBEs to non existing hints

---

kamailio/users/config/kamailio.cfg

Reject SUBSCRIBE with Expires lower than 1800.
Reject with "423 Intervel Too Brief" with "Min-Expires: 1800" header.

kamusers: force min subscription expires to 1800

---

asterisk/config/pjsip.conf

Disable initial MWI notification during asterisk startup, otherwise it can become a problem on environments with lots of endpoints.

asterisk: disable initial unsolicited MWI notification

---

asterisk/config/dialplan/default.conf
kamailio/trunks/config/kamailio.cfg

Now it is not compulsory to assign a DDI to a company, it can be left unassigned.
This PR adds logic to send inbound external calls to these DDIs to Asterisk to play a locution to calling party.

kamtrunks: unassigned DDIs handling

---

kamailio/trunks/config/kamailio.cfg

Reject calls to retail DDI linked to no retail account.
Prior to this PR, KamTrunks assumed retail DDIs were always linked to a retail account, but new version makes it possible to have DDIs linked to a retail client but not to a retail account.

kamtrunks: reject calls to retail DDI linked to no retail account

---

kamailio/users/config/kamailio.cfg

Do not forward within dialog SUBSCRIBE to a wrong AS, reply 500 instead to force new SUBSCRIBE dialog (that will be routed to right AS).
This PR prevents problems with changes in AS dispatch list, that may lead to calls being handled in a different AS to SUBSCRIBE dialogs.

kamusers: avoid routing within dialog SUBSCRIBE to wrong AS

---

library/composer.json
library/composer.lock
schema/composer.lock
schema/config/bundles.php
schema/config/services.yaml

So that migrations come with LoggableMigrations by default
Updates ivoz-dev-tools to include https://github.com/irontec/ivoz-dev-tools/commit/9a9f237a4645f9d5878a2df1e3a6c12464c4b71f

Get Migration bundle back

---

schema/DoctrineMigrations/Version20220317124540.php

This migration updated ast_ps_endpoints table with the appropiate
hint_extension and subscribe_context values, but it was only
considering terminals with user and extension assigned.
This is ok for hint_extension but subscribe_context must be updated
in all endpoints, no matter if there is user or not using that
terminal.

Fix endpoints hints migration

---

kamailio/users/config/kamailio.cfg

Discard with "489 Bad Event" all SUBSCRIBE messages except "Event: dialog"

kamusers: SUBSCRIBE Event dialog only

---

kamailio/users/config/kamailio.cfg

usrloc/tm xavp_contact modparam allows storing additional attributes per contact. Prior to this PR, we use them to store registration socket and protocol.
This PR adds logic to get the same info (socket and protocol) without using contact attributes. The reason behind this is to avoid inserts into this table per registration (and lots of selects).

kamusers: stop using attributes per contact (ulattrs)

---

kamailio/users/config/kamailio.cfg

Logic in 2d32c9b39 did not work for AoRs with a single contact address, causing wrong media-relay interface selection and no audio scenarios. This PR fixes this.

kamusers: fix media-relay interface for AoRs with just one contact

---

asterisk/config/sorcery.conf

Decrease asterisk sorcery cache lifetime from 1800 secs to 120

asterisk: decrease sorcery cache lifetime to 120 secs

---

kamailio/users/config/kamailio.cfg

Static location friends, retail accounts and residential devices now have a new field ruri_domain. This PR uses this new field to route requests properly.
3 kind of static location routing from now on:
- **ruri_domain + ip/port**: ip/port will act as outbound-proxy and R-URI domain will be used in R-URI header domain.
- **ruri_domain without ip/port**: no outbound-proxy, ruri_domain used in R-URI will be used to route the request.
- **ip/port without ruri_domain**: behaviour prior to this PR. ip/port will be set in R-URI.

kamusers: use new ruri_domain for static location (retail, residential and friends)

---

debian/systemd/fastagi@.service

Limit fastagi service duration to 300 seconds

---

web/portal/platform/src/entities/BannedAddress/BannedAddress.tsx
web/rest/platform/config/api/raw/provider.yml

Fixed default order in banned addresses listing from portal plataform
The order is desc by lastBannedTime

Fixed banned addresses order in platform

---

kamailio/users/config/kamailio.cfg

Change [timer_procs usrloc modparam](https://kamailio.org/docs/modules/5.7.x/modules/usrloc.html#usrloc.p.timer_procs) so that usrloc has 4 timer processes for its inserts.

kamusers: 4 timer processes for usrloc

---

library/Ivoz/Provider/Domain/Service/Friend/AvoidUpdateCompany.php
library/Ivoz/Provider/Domain/Service/Friend/FriendLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/ResidentialDevice/AvoidUpdateCompany.php
library/Ivoz/Provider/Domain/Service/ResidentialDevice/ResidentialDeviceLifecycleServiceCollection.php
library/Ivoz/Provider/Domain/Service/RetailAccount/AvoidUpdateCompany.php
library/Ivoz/Provider/Domain/Service/RetailAccount/RetailAccountLifecycleServiceCollection.php
library/spec/Ivoz/Provider/Domain/Service/Friend/AvoidUpdateCompanySpec.php
library/spec/Ivoz/Provider/Domain/Service/ResidentialDevice/AvoidUpdateCompanySpec.php
library/spec/Ivoz/Provider/Domain/Service/RetailAccount/AvoidUpdateCompanySpec.php
web/portal/brand/src/entities/ResidentialDevice/Form.tsx
web/portal/brand/src/entities/RetailAccount/Form.tsx
web/rest/brand/features/provider/friend/putFriend.feature
web/rest/brand/features/provider/residentialDevice/putResidentialDevice.feature
web/rest/brand/features/provider/retailAccount/putRetailAccount.feature

Modified back and front to make client readonly on Friends, RetailAccounts and ResidentialDevices edition

Readonly client on brand retail residential and friend

---

kamailio/users/config/kamailio.cfg

Use Friend/RetailAccount/ResidentialDevice proxyUsersId field added in #2671 to force proper socket in calls towards these objects.

kamusers: force selected socket for direct connectivity objects

---

web/portal/brand/src/entities/DdiProviderRegistration/DdiProviderRegistration.tsx

Fixes issue with breadcrumb: a numeric Id was shown instead of the name

Fixed label on breadcrumbs

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Fast media liberation is a mechanism that drops UPDATE/reINVITE until initial transaction is acknowledged with an ACK.
This PR:
- Removes this mechanism in KamTrunks as no media-liberation is done in carrier calls.
- Removes this mechanism in KamUsers when no SDP is present.

kamailio: changes in fast media liberation delayer

---

microservices/recordings/src/Service/Encoder.php

Before this change, Call-Id header value was used for the temporal mp3 file of recordings. This value can contain characters that breaks the avconv command (like '/') so, we could encode this value or just replace it for another one. This is a temporal file that will be deleted by FSO core logic, so the easiest was to change its value to hashid, a partial md5 of Call-Id.

microservices/recordings: use hashid for temporal MP3 filename

---

debian/ivozprovider-web-rest.postinst

Keys generation script is being invoked before changing to rest/platform directory, so the creation was failing.

Fix initial generation of JWT keys

---

asterisk/agi/src/Dialplan/Trunks.php

On Demand recording feature code was not being set poperly on user channel during external incoming calls due to a missing channel variable.

Fix on-demand recording code on incoming calls

---

profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf

Fixed Content-Security-Policy allowing load of images with src starting with blob:

Fix Content-Security-Policy for img blob

---

.gitignore
kamailio/.gitignore
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
profiles/proxy/etc/kamailio/autoconf

Standalone installations sharing a unique IP address where broken as long as 5060 port for proxytrunks was hardcoded in some points of logic.
This PR avoids this hardcoding and fixes standalone mono-IP environments using 7060 in proxytrunks.

kamailio: avoid hardcoded SIP ports

---

library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByUserDeleted.php
library/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByUserTerminalUnassignment.php
library/Ivoz/Provider/Domain/Service/User/UserLifecycleServiceCollection.php
library/spec/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByUserDeletedSpec.php
library/spec/Ivoz/Ast/Domain/Service/PsEndpoint/UpdateByUserTerminalUnassignmentSpec.php

PsEndpoint asterisk table is populated from Terminals, but some  fields are taken from the user (like extension, pickupgroups, etc).
When User changes its terminal or it's deleted, these fields were not being updated.
This PR should fix that setting those fields to null

Update PsEndpoints when User changes its Terminal or is deleted

---

asterisk/config/pjsip.conf.in
debian/ivozprovider.postinst

Change how endpoints are intified by asterisk. Request from kamailio proxyusers have an X-Info-Endpoint header, while requrest from kamailio proxytrunks will be identified by IP address.

asterisk: fix wrong endpoint identify in single IP standalone installs

---

asterisk/agi/src/Agi/Action/HuntGroupCallAction.php
asterisk/agi/src/Dialplan/Trunks.php
asterisk/agi/src/Dialplan/Users.php

To enable builtin automixmon features, Dial application require xX flags (most probably only x is required) and also setting the DTMF code including * in "FEATUREMAP(automixmon)" variable.
This PR add the missing options to Dial used by simple HuntGroups and fixes the code not having the * prefix proprely defined in feature map variable.

agis: fix on demand record code on simple huntgroups

---

library/Ivoz/Provider/Domain/Model/Voicemail/Voicemail.php
web/portal/client/src/entities/Voicemail/Voicemail.tsx
web/portal/client/src/translations/ca.json
web/portal/client/src/translations/en.json
web/portal/client/src/translations/es.json
web/portal/client/src/translations/it.json

Add validation to the email field

---

web/portal/brand/src/entities/Carrier/Carrier.tsx
web/portal/brand/src/entities/Carrier/Form.tsx
web/portal/brand/src/entities/Carrier/hooks/useDefaultProxyTrunk.tsx
web/portal/brand/src/entities/DdiProvider/DdiProvider.tsx
web/portal/brand/src/entities/DdiProvider/Form.tsx
web/portal/brand/src/entities/DdiProvider/hooks/useDefaultProxyTrunk.tsx

Added logic for automatically selecting proxyTrunk in Carrier and DdiProvider when there's only one option available.

Selected single proxyTrunk choice

---

library/Ivoz/Provider/Application/Service/WebPortal/GetLogoPath.php

Fixed webPortal logo load when requested logName contains character not valid in an URL

Fixed webPortal logo load

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

SIP callid header should be long and random enough to be globally unique over time. However, some poor SIP implementators generate too short callid (e.g. numeric 5 digits callids).
This PR lengthen the callid saved in CDR fields whenever original callid is shorter than 20 characters, adding some random content.

kamailio: avoid short callid collisions

---

asterisk/config/res_config_odbc.conf

This PR introduces a change in how data is retrieved from ODBC to fix the members dial order in Linear Queues.
Before this change, members were called ordered by interface (actually extension in ivozprovider), rather than creation time as documented.

asterisk: add odbc configuration to override default results order

---

library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerAbstract.php
library/Ivoz/Provider/Domain/Model/CallCsvScheduler/CallCsvSchedulerDtoAbstract.php
library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/CallCsvScheduler.CallCsvSchedulerAbstract.orm.xml
schema/DoctrineMigrations/Version20241114091020.php

Added default empty value for email in CallCsvScheduler

Default empty email in CallCsvScheduler

---

web/portal/brand/cypress/fixtures/apiSpec.json
web/portal/client/cypress/fixtures/apiSpec.json

Updated brand and client apiSpec

---

debian/ivozprovider-profile-as.links
debian/ivozprovider-profile-as.postinst
doc/dev/AcceptedCommitTagsList.txt
extra/simple-cdd/profiles/ivozprovider.downloads

- Add zstd to extra explict Debian download packages 
- Fix ivozprovider-profile-as not installing because it required user confirmation to overwrite odbcinst.ini

Fix ISO image Debian dependencies

---

microservices/recordings/bin/prepare-test-db
microservices/recordings/bin/test-recordings
microservices/recordings/composer.json
microservices/recordings/composer.lock
microservices/recordings/config/bundles.php
microservices/recordings/config/packages/test/doctrine.yaml
microservices/recordings/config/services.yaml
microservices/recordings/phpstan-baseline.neon
microservices/recordings/phpunit.xml.dist
microservices/recordings/psalm-baseline.xml
microservices/recordings/src/Model/Mp3FileInfo.php
microservices/recordings/src/Model/RawRecordingInfo.php
microservices/recordings/src/Service/Encoder.php
microservices/recordings/src/Service/FileUnlinker.php
microservices/recordings/src/Service/RawRecordingInfoFactory.php
microservices/recordings/src/Service/RawRecordingProcessor.php
microservices/recordings/src/Service/RawRecordingsGetter.php
microservices/recordings/symfony.lock
microservices/recordings/tests/Service/EncoderTest.php
microservices/recordings/tests/bootstrap.php

Refactorize and test microservice/recordings

---

ChangeLog
README.md
asterisk/config/pjsip.conf.in
doc/sphinx/conf.py
kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg
web/rest/brand/CHANGELOG.md
web/rest/client/CHANGELOG.md
web/rest/platform/CHANGELOG.md
web/rest/user/CHANGELOG.md

Updated documentation with most relevant changes in 4.3.0 release.
> [!WARNING]  
> The Format of Rest APIs Changelog has changed a bit since new changelogs are generated using GPTs
> [!NOTE]  
> This PR will be updated with new changes introduced in not yet merged Pull Requests

Update ChangeLog for 4.3.0 release

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Asterisk does not reply to within dialog INFOs (except DTMFs). With this PR, these INFO will be answered in proxies.

kamailio: do not forward within-dlg INFO to AS-es (except DTMFs)

---

library/Ivoz/Provider/Application/Service/User/SyncFromCsv.php
library/Ivoz/Provider/Domain/Model/Ddi/Ddi.php
library/Ivoz/Provider/Domain/Model/Ddi/DdiInterface.php
web/rest/brand/features/provider/user/postUser.feature
web/rest/brand/features/provider/user/postUserMassImport.feature

Fix users import ddi

---

library/Ivoz/Provider/Domain/Service/Terminal/Provision/ProvisionSpecific.php

Specific provisioning pattern matching is making a comparison based on the request's last segment, comparing the specificUrl in the Terminal Model with the request sent by the terminal. This comparison was being done by removing the extension (e.g., .cfg) from the terminal model's specificUrl, but not from the terminal's request. This was preventing the terminal from being found by its MAC address.

microservice/provision: fix specific provisoning mac comparisson

---

library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CallCsvSchedulerDoctrineRepository.php

Modified logic should only apply for client created CallCsvSchedulers. Its goal is to avoid duplicate names.
Before this fix a collision between brand generated CallCsvSchedulers and client generated ones happened. With this fix, each level can have same names without causing any trouble.

[PROVIDER-2218] core: fix hasUniqueName (only for client CallCsvSchedulers)

---

library/bin/test-phpstan
library/bin/test-phpstan-update-baseline

Before this change, test-phpstan-update-baseline stops on the first application that haves no errors in the baseline file (because having no error is considered an error when --generate-baseline flag is used). Configured phpstan version has no --allow-empty-baseline flag, so we workaround the scripts to check exit codes and generated files to properly check all symfony applications.

[PROVIDER-2256] Update test-phpstan-update-baseline to avoid premature exit

---

schema/DoctrineMigrations/Version20250602085035.php

This migration prevents errors when moving voicemail recording files within the filesystem (e.g., when a message is moved to the 'Old' directory after being listened to).

[PROVIDER-2278] Migrated existing realtime voicemails messages recordings

---

kamailio/trunks/config/kamailio.cfg

Use internal socket for bounced calls, instead of carrier external socket.
This PR fixes one-way-audio in bounced calls depending on networking of given environment.

[PROVIDER-2296] kamtrunks: fix socket for bounced calls

---

kamailio/trunks/config/kamailio.cfg
kamailio/users/config/kamailio.cfg

Avoid large while loops in hint validation search, dividing the logic in 2 independent queries.
`max_while_loop` has been increased from 250 to 2500 too.

[PROVIDER-2307] kam: avoid while loops in hint validation search

---

asterisk/config/sorcery.conf

Updated cache settings for endpoint and aor in sorcery.conf to increase object lifetime.

[PROVIDER-2336] Fix asterisk sorcery configuration to avoid memory leaks
